### ISSUE TITLE
Update illustrations and screenshots on www.mozilla.org for MR1 

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10184]
## Description

MR1 will introduce an updated UI for Firefox including a new style for tabs. This means we will need to update various screenshots and illustrations across mozilla.org

---

#### Tasks
- [x]  Identify pages that will be affected
- [x]  Identify and catalog which assets on those pages need to be updated.
- [x]  Submit list of assets needed to creative team
- [x]  Receive updated assets from creative team
- [x]  create PR to update Bedrock
- [x]  changes go live on day of MR1

**Comment by slightlyoffbeat** [comment]
I'll take on the ownership of all tasks before handing off to a dev

**Comment by slightlyoffbeat** [comment]
We will have P1 assets from creative by Friday, May 21. 

Here is the document I created that audits assets and assigns priorities:

https://docs.google.com/spreadsheets/d/1Fsx_b-Vs0GOyLi_MoTBK_ZUdoNWsN2L76EUjX2l1aa8/edit?usp=sharing
