### ISSUE TITLE
[Epic] evolve static getpocket.com pages

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10211]
## Description
We are in the process of migrating the marketing pocket pages to the `externalpages/pocket` directory within bedrock. 

With the pages in bedrock we can leverage the existing l10n and asset pipelines, and any changes will be much easier with jinja templates.

#### Front-end tasks
- [x] Incorporate JS from pocket repo (if needed)
- [x] #10783
- [x] #11171  ([relevant JS](https://github.com/mozmeao/pocket-marketing-pages/tree/master/content/marketing-assets/js))

**Migrate the following pages:**
- [x] [about](https://www.getpocket.com/en/about)
- [x] [add](https://www.getpocket.com/en/add)
- [x] #10749 
- [x] #10750
- [x] #10755
- [x] #10751
- [ ] #10756 - **Blocked**
- [x] #10757
- [x] #10758
- [x] #10752
- [x] #10759
- [x] #10753
- [x] #10760
- [ ] #10761 - **Blocked**
- [x] #10762
- [x] #10754
- [x] #10764
- [x] #10763
- [x] #10767

#### Sub-epics
- [x] https://github.com/mozilla/bedrock/issues/11403

#### Backend tasks
- [x] Ensure the supported locales match with the supported Pocket locales
- [x] Add appropriate FTL files for localized content
- [x] Ensure the FTL file path is included in the `l10n/configs/vendor.toml` file
- [x] Update documentation to include information about the externalpages app
- [x] Write some tests for the backend
- [ ] Consider a middleware to catch/log any redirects coming from bedrock for external pages (these will break the URL for the end user)

**Comment by reemhamz** [comment]
Doc detailing our next steps and action plan:
https://docs.google.com/document/d/1gqSpl2K6EpZOfzOZeMni0cC-9KM-HjnwGmK9--QjgLw/edit

**Comment by slightlyoffbeat** [comment]
@slightlyoffbeat lets get access to the pocket repo to get the pre-compiled styles

**Comment by slightlyoffbeat** [comment]
2 pages to solve for:

- Pocket hits signup page
- Pocket hits confirmation page

@slightlyoffbeat to talk to Tina.

**Comment by maureenlholland** [comment]
Question for analytics: do we need to migrate the snowplow script over for these pages as well?
(right now there's a mozilla cookie helper script that has no use without snowplow: https://github.com/mozilla/bedrock/issues/11123)

**Comment by pmac** [comment]
Yes I believe we do need snowplow still.

**Comment by slightlyoffbeat** [comment]
Yes, snowplow should be considered a requirement.

**Comment by stevejalim** [comment]
@reemhamz @slightlyoffbeat Naive question: is the pocket index/root page being ported, too, please?

**Comment by slightlyoffbeat** [comment]
Yes, the logged-out homepage is being ported.
