### ISSUE TITLE
[Epic] Switch to a more modern front-end build tool

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#10310]
## Description

This is an epic to track updating bedrock's front-end build tool. Our current solution (Gulp) is not so actively maintained as it once was, and our existing build script is somewhat complicated and can manifest in some hard to fix bugs (such as https://github.com/mozilla/bedrock/issues/9700). This can sometimes slow dev work.

Things we use said build tool for:

- Sass / CSS pre & post processing.
- JS pre processing.
- JS/CSS bundling & minification.
- Static file / image copying (`/media` -> `/static`).
- Source-map production in dev mode.
- File watching in dev mode.
- Local web server in dev mode.

From prior discussions there has been some interest in trying out both [Webpack](https://webpack.js.org/) and [Parcel](https://parceljs.org/) (are there any other tools or combinations worth testing?). 

I propose we try and get a build of each tool deploying to a demo server (from trying out webpack we found this unearthed a lot of considerations). We can then hopefully make an informed decision on which one we want to go for.

---

#### Success Criteria
- [x] Evaluation of available build tools.
- [x] Build of Webpack sucessfully deploying to demo.
- [ ] ~Build of Parcel sucessfully deploying to demo.~
- [x] Stop bundling JS to legacy IE browsers.
- [x] Migration to chosen build tool.
- [x] Documentation.

**Comment by alexgibson** [comment]
I rebased my old webpack branch and opened a [draft PR here](https://github.com/mozilla/bedrock/pull/10314) so folks can take a look. It still needs some more work to make it mergable, but it at least builds to demo for now.

Let's take a look at Parcel also.

**Comment by alexgibson** [comment]
I've spent some time looking at [Parcel](https://parceljs.org/), and whilst it's certainly possible to pass it multiple entrypoints to create the large number of CSS/JS bundles we need - one thing it doesn't seem to do (afaict), is support [dynamic entrypoints](https://webpack.js.org/configuration/entry-context/#dynamic-entry). This makes it difficult to support passing in an external source such as `static-bundles.json` where we could then iterate through it. Instead, we'd need to re-architect how we're defining bundles, so that every asset had an individual entrypoint that Parcel can then use. This is definitely do-able, but it would be a big change, and might be hard to land given all the changes and work happening all the time.

Parcel also has a [packager](https://parceljs.org/packagers.html), but from what I can it can only run after assets have been processed, and a bundle tree has been created.

It's also worth noting that Parcel v1 is deprecated, and [Parcel 2](https://v2.parceljs.org/) is now the main version being worked on. This is still in beta however, and I found that some of the documentation was still lacking to really dig in much further.

**Comment by alexgibson** [comment]
Given the large refactor it would require (see above), I'm not sure if it's worth the effort of making a Parcel branch that can deploy all the way to demo - unless we were confident that we wanted to go with it over webpack.

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/10192

**Comment by alexgibson** [comment]
I've spent some time looking at [rollup.js](https://rollupjs.org/guide/en/) as a bundling option. I think this would be great for smaller projects, but it would likely need to be used in conjunction with another tool to help build other static asset types. For bedrock it would also require a pretty big change in how we define entrypoints for our JS (similar to Parcel), so for now I think Webpack still seems like it might be the most suitable option given the size of the project.
