### ISSUE TITLE
Sunset research.mozilla.org

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10556]
## Description

research.mozilla.org is mostly focused on Emerging Technologies and a research program that no longer exists.

Instead of updating this site, my recommendation that we take it down. We can leave the site on wpengine if there is desire to bring it back in the future.

#### Tasks
- [ ] Check Google Analytics to identify remaining traffic sources.
- [ ] Search mozilla.org and compile a list of anywhere we link to this domain. Remove those links or find alternatives.
- [ ] Find appropriate domain to redirect to.
---

Dave Camp, Selena, Ekr, and Ellen have asked to be in the loop for timeline.

**Comment by slightlyoffbeat** [comment]
I'd be good to remove all of those links instead of replacing for now. In the future, we can explore ways to resurface information around our efforts and contributions for things like servo and rust.

As far as forwarding, my current recommendation is simply to redirect all research.mozilla.org links to mozilla.org

**Comment by slightlyoffbeat** [comment]
@reemhamz yes, lets go ahead and remove those links.

Craig can confirm, but It looks like we can simply remove for now and not worry about replacing

**Comment by slightlyoffbeat** [comment]
As for the site itself. I'm proposing the following after an internal conversation with stakeholders:

1. make the publication page the primary/homepage of research.mozilla.org
2. unpublish all the other pages.
3. set up a few redirects for the pages that will be depublished (although I believe Wordpress handles this automatically)
