### ISSUE TITLE
Sunset labs.mozilla.org

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10557]
### Description

labs.mozilla.org is mostly focused on Emerging Technologies initiatives and outdated information. Although Mozilla will always be working on new ideas and technologies, this site no longer has an owner and my recommendation is to sunset.

#### Tasks

- [ ] SEO insights and recommendations (URLs to forward, flags, etc)
- [ ] Search mozilla.org and compile a list of anywhere we link to this domain. Remove those links or find alternatives.
- [ ] Shut down labs.mozilla.org

**Comment by slightlyoffbeat** [comment]
Hubs links: redirect to https://hubs.mozilla.com/

Firefox Reality: https://blog.mozilla.org/en/mozilla/news/update-on-firefox-reality/

Common Voice: https://commonvoice.mozilla.org/

Spoke: https://hubs.mozilla.com/spoke

Webthings: https://webthings.io/ (should we also forward https://iot.mozilla.org/?)

XR Viewer: N/A or (https://apps.apple.com/us/app/webxr-viewer/id1295998056)

Listen: N/A


General Redirect for everything else: ?? Possibly blog.mozilla.org

**Comment by a-kyne** [comment]
I think we should redirect iot.mozilla.org to https://hacks.mozilla.org/2020/12/flying-the-nest-webthings-gateway-1-0/; it explains the change.

Agreed that XR Viewer should go to the app listing (unless there are plans to take the app down in the near future).

No redirect for anything else. If it doesn't have a useful replacement, then it should 404. There is no SEO benefit to mass redirects (they're identified and treated as "soft 404s").

**Comment by maureenlholland** [comment]
@slightlyoffbeat bumping this on your radar

**Comment by janbrasna** [comment]
This can be closed now. There's no content on labs.m.o and all mozorg links now redirect to future.m.o instead.
