### ISSUE TITLE
Epic: Improve reslilence and monitoring of DB updates

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#10627]
Following on from the SQS/Contentful work for #10544 we want to improve the observability of our data-updating tasks

##### Success criteria
- [ ] Each step of the DB update script should log to Sentry if it fails - https://github.com/mozilla/bedrock/issues/10813
- [ ] Each step of the DB update script should not block the others from running, and we trigger a snitch on success, so we can confirm they are _all_ running, even if they don't change DB state - https://github.com/mozilla/bedrock/issues/10814
- [ ] Update /healthz-cron/ to show the latest ContentfulEntry timestamp, so we know when content was last actually ingested - https://github.com/mozilla/bedrock/issues/10815

**Comment by alexgibson** [comment]
@stevejalim is this something you're still working on?
