### ISSUE TITLE
(epic) VPN Moments Page for Q4 2021

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#10702]
## Description

We will have 3 moments pages in Q4 2021 for VPN.

Brief: https://docs.google.com/document/d/1kRv98xE20exYqlNtuZUWjH4baaKz07AePLEM8fqE324/edit?usp=sharing

### Dates

11/15: FR/EN/DE. Use existing pages (firefox/welcome/10/ & firefox/welcome/9)
11/29: all regions. Shopping focused
12/15: all regions. Message TBD

### Design & Copy
11/15: use existing pages
11/29 & 12/15: TBD

---

#### Success Criteria
- [x] Make sure /firefox/welcome/10 & /firefox/welcome/9 are still good to go
- [x] Submit trigger criteria for 11/15
- [x] Develop page for 11/29 moments page
- [x] submit trigger criteria for 11/29 moments page
- [x] ensure 11/29 page is localized
- [x] Develop page for 12/15 moments page
- [x] Submit trigger criteria for 12/15 moments page
- [x] ensure 12/15 page is localized
