### ISSUE TITLE
Epic: Improve health checks

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#10810]
## Description

We had a degradation of service due to a bug we hadn't spotted on dev or stage, so we should try to improve automatic alerting and checking of the platform each time we roll out a release (to dev, stage or prod)

---

#### Issues to come - bullet points for now

- [ ] Add a check to healthz-cron that ensures key pages (TBC which) return a HTTP 200 
  - [ ] Add a check to healthz-cron that ensures key Contentful pages (TBC which) are definitely be rendered (eg by checking template name to ensure it's the contentful-powered page being rendered, not a fallback)
  - [ ] Add Sentry logging so that if we fallback from a Contentful page to a hard-coded one, we're immediately told which
- [ ] Create a base set of evergreen key pages (TBC which but at least m.o homepage) which can be served as fallback if Contenful fails
- [ ] add a DMS to the Contentful Sync (already ticketed as #10627)
- [X] Update documentation about changing fields in the Django layer, which was a root cause of a failure. Done -> https://github.com/mozilla/bedrock/pull/10809

**Comment by alexgibson** [comment]
@stevejalim is this something we're still working on?

**Comment by stevejalim** [comment]
It's still in the backlog, but less pressing given we're using Contentful for less/at a plateau for now.

To move this on, it looks like we need some extra info:

1) What are our key contentful pages that we want to trigger an alert for?
2) Do we have those base set of evergreen pages (eg homepage) we can use as fallback?

**Comment by stevejalim** [comment]
Closing this as we're moving away from Contentful. We may want to revisit if we want to keep Wagtail-based pages in our health checks, but that's a separate piece of work
