### ISSUE TITLE
Epic: Python 3.9 upgrade

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11054]
## Description

We are currently running a mixture of Python 3.7 and 3.8 in production, and it make sense to both standardise across the ecosystem and also upgrade to 3.9 well before 3.7 reaches end-of-life. (3.7 hits EOL in June 2023, 3.9 is maintained until October 2025 - https://devguide.python.org/#status-of-python-branches)

(We could look to 3.10 instead but at the time of writing, it wasn't clear whether every single dependency we use supports 3.10 just yet)

Upgrading 3.7 to 3.9 should not be hard, but we _should_ expect to upgrade and possibly remove some libraries as part of this.

One risk we have is if a particular codebase lacks enough test coverage, we'll have to invest more time in manual testing.

---

#### Issues
- [x] #11057 (pre-req)
- [x] #11051
- [x] https://github.com/mozmeao/basket/issues/788
- [x] https://github.com/mozilla/nucleus/issues/622
- [x] more to come for other projects
