### ISSUE TITLE
Python dependency-management standardisation

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11056]
## Description

At the moment, our projects use different tools to manage Python dependencies - `pip` and `pip-tools`, plus we use hashes to ensure we're getting what we expect. It all _works_ but, it would be useful to settle on an approach that is:
* easy to use
* efficient
* secure (verifies packages)
* compatible with `dependabot`
* consistently used across all of Mozmeao
* appropriately documented so everyone knows exactly how to update dependencies

---

#### Issues
- [x] https://github.com/mozilla/bedrock/issues/11055
- [x] Apply to Bedrock - issue to come
- [x] Apply to Basket - issue to come
- [ ] Apply to Snippets - issue to come
- [x] Apply to Nucleus - issue to come
- [ ] Apply to [many] others - issue to come

**Comment by stevejalim** [comment]
The summary doc that led us (me?) to pick `pip-compile-multi` is at https://docs.google.com/document/d/1dk8NLxSyVdvU3m2udjU-VCUsuC33hT3wZ46-ZZ6m8NM/edit#heading=h.oq9kby8rxip3 - it essentially let us keep separate dependency files and a familiar setup, as switching workflow didn't pay enough dividends. Hopefully.

**Comment by stevejalim** [comment]
This is basically done. We might tune between pip-tools and pip-compile multi a bit more but all active projects have the same overall behaviour and same `make` commands
