### ISSUE TITLE
WNP 96 en (epic)

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11070]
## Description

For What's New Page 96 (english) we will promote 2 things:

Firefox Mobile (90% traffic)
Mozilla Rally (10% traffic)

---

Mozilla Rally

[Design](https://www.figma.com/file/CZvzHgU9NQMQUm34lomIl5/Firefox-WNP?node-id=1391%3A39478)
[Copy (needs legal approval)](https://docs.google.com/document/d/1G-srYSNDKdC3zJVPMNFscF5dCbGdN0jJmtlO4Ok-AXo/edit?usp=sharing)

---

### Firefox Mobile

[Brief](https://docs.google.com/document/d/1rNpvv4nlwiJUoOFUuLUOPVfYUUU_mH4H9pGTILIUv9Y/edit?usp=sharing)

Copy (TBD)
Design (TBD)

## Testing:

If time permits, i would like to test 3 different download methods: Email, Text, and QR Code.

If we have the time and capability to test all three, then we can do 30% traffic for each variation (with final 10% going to Mozilla Rally)

## CTA

TBD. I have reached out to receive fresh adjust links for this WNP.

#### Success Criteria

- [ ] Attribution through new adjust links
- [ ] Rally Page coded
- [ ] 10% traffic sent to Rally
- [ ] Mobile page coded
- [ ] rest of en traffic sent to Mobile page.
- [ ] (if testing) QR code method is control with 30% of traffic. Email is V1 & text is V2
