### ISSUE TITLE
Test new service for powering text-to-download.

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11119]
## Description

We removed our text-to-download capabilities a while back because our solution was costly, complicated, and not worth maintaining. 

Lets test integrating a new service. I recommend starting with Twilio, but open to ideas and options.

---

#### Tasks
- [ ] Scope work and determine if this test is worth doing.
- [ ] Research Twilio and alternatives. Choose one to test.
- [ ] Build MVP.
- [ ] Set up traffic cop to test text-to-download against our existing solutions for email-to-download & qr-to-download.

If we determine this is worth the effort, we can add additional tasks for getting a contract with a new provider, and rolling out to the rest of the site.

**Comment by craigcook** [comment]
Some added details after discussion:

1. We're moving forward with a test of Twilio.
2. We'll run a traffic cop test on /firefox/browsers/mobile/android/
3. Three variants: QR, Email, and SMS, with a 33/33/33 split.
4. English only, US only.
5. We'll need custom Adjust links with experiment params for attribution.
6. We'll plan to run the experiment for two weeks.

**Comment by slightlyoffbeat** [comment]
Lets use this for the adjust link:

https://app.adjust.com/kwd7bhf

campaign = sendtodownload
adgroup = android (or ios)
creative = QR, text2download, email2download

I'm realizing as I type this that we can't use custom attribution for email2download without getting a new email list set up. I'll chat with the activations team. Perhaps we can get enough data by just monitoring the attribution results for the duration of the test.

**Comment by slightlyoffbeat** [comment]
I spoke activations, and they are going to create a unique email so that we can have true attribution for email-to-download. I'll update when we have a basket ID for that.

**Comment by slightlyoffbeat** [comment]
@robhudson lets go with:

Download the Firefox mobile browser for automatic protection on all your devices. [link]

**Comment by slightlyoffbeat** [comment]
@craigcook @robhudson Lets keep using this issue to track work against an Android test. I'd like to set up the exact same experiment with the same parameters, but test it against the Android audience.

Can you help me figure out what is needed, apart from new Adjust links?

**Comment by craigcook** [comment]
New Adjust URLs for Android:

QR to download: https://app.adjust.com/s801luk
email to download: https://app.adjust.com/4t56430
text to download: https://app.adjust.com/48k9twc

**Comment by slightlyoffbeat** [comment]
@slightlyoffbeat to check in on status of this.

**Comment by stevejalim** [comment]
@robhudson Can we close this now?

**Comment by alexgibson** [comment]
@slightlyoffbeat is there a summary we could share about how this experiment performed? What was the winner for going forward?

**Comment by slightlyoffbeat** [comment]
@alexgibson just a note that this note is received. I have a spreadsheet with numbers that I'll work into something that can be shared out.
