### ISSUE TITLE
Multi-newsletter signup

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11120]
## Description

The newsletter signup that is on various pages on mozilla.org only signs up users for the mozilla foundation newsletter. In 30 days, it signs up ~25-30k users. There is an opportunity to also surface our Firefox newsletter.

The ask is to have an updated version of our email signup that has an option to sign up for the Firefox newsletter in addition to the mozilla foundation newsletter when they input their email address and submit. This is also an opportunity to refresh our visuals and copy (if needed).

[Brief](https://docs.google.com/document/d/1VD6pLOnO8t_3lvAFXBeiQNoL9vMYN0UEPgkXHaQ5K6A/edit?usp=sharing)

Languages: See brief.

---

#### Tasks
- [x] Update design to accommodate multiple newsletters (reach out to Elise for UX). See additional design requests in brief.
- [x] Refresh copy (to be provided by studio team)
- [ ] code updated signup form
- [ ] Roll out to homepage, /mission, /about/manifesto
- [ ] Roll out to /newsletter and /newsletter/firefox

#### Requirements:
- Be transparent. Opt out is fine, we just need to make sure its clear

#### Consideration & Questions:
- fr/de homepage has newsletters signups for firefox instead of Mozilla. Can we roll this out to those languages as well? Is the mozilla newsletter ready for those languages?

**Comment by slightlyoffbeat** [comment]
![Love the Web](https://user-images.githubusercontent.com/2030656/150037866-fbeda0b3-fc60-41fe-9177-03a16e115098.png)

Here is the design from Elise. This has a thumbs up from the email team as well. I reached out to studio team to see if they would like to use this as an opportunity to update copy.

With design direction, this is ready for work to begin.

**Comment by slightlyoffbeat** [comment]
lets consider updating /newsletter and /newsletter/firefox
