### ISSUE TITLE
[Epic] VPN Affiliate

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11212]
## Description

We will soon have the ability to have affiliate links for VPN. This requires changes/additions to Mozilla.org. 

When a user arrives to the VPN landing page from an affiliate link, we will show this user a message. This message allows users to either opt in or out of our ability to affiliate attribution.

Tasks include:

- [x] Determine behavior of banner (blocking, non-blocking, opt-in, opt out, toaster, modal, etc)
- [x] Copy for banner
- [x] Design for banner
- [x] Implement attribution API flow.
- [x] Implement cookie banner & opt-out mechanism.
- [x] Add entire flow behind a feature switch.
- [x] Unit / behavioral tests.
- [x] Update `fxa-product-button.js` to support overwriting flow params.
- [x] Add GA events for banner views / clicks.
- [x] Add production API endpoint.
- [x] Banner strings added to Pontoon for L10n.
- [x] Defined list of countries and/or languages to limit attribution to.
- [x] Documentation

**Comment by slightlyoffbeat** [comment]
I wrote to legal to ask for guidance on copy for the banner. I will take what is provided, and send to studio team for user-facing copy.

**Comment by slightlyoffbeat** [comment]
Here are the options that I can think of for banner/modal behavior:
1. there is a banner somewhere that requires users to opt in. This is not recommended because there is a high likely-hood that most people will ignore the banner and we will get a minimal amount of opt-ins.
2. There is a banner somewhere that requires users to opt out. We would need to design this in a way that makes it obvious and clear for users who wish to chose this option
3. a blocking modal. This modal would display and would only be dismissed when a user chooses either "opt in" or "opt out"

**Comment by slightlyoffbeat** [comment]
@alexgibson @pmac for visibility. Any options I'm missing?

@alexgibson could you add technical tasks to the checklist?

**Comment by alexgibson** [comment]
Reference docs:

- Microservice API endpoint: https://github.com/mozilla-services/cjms/tree/v0.2#aic---affiliate-identifier-cookie
- Architecture flow diagram: https://www.figma.com/file/6jnLCLzclBN0uyS4nJp57d/Affiliate-Marketing-(CJ)-Architecture-%2F-Flow?node-id=0%3A1

Dev server for the microservice should be available by the end of Monday 28 Feb.

**Comment by alexgibson** [comment]
@slightlyoffbeat I added some techincal tasks to the list here, thanks.

As soon as we have a dev server to post data to, I should be able to start workjing on the flow for this (even if we don't yet have the banner figured out).

**Comment by birdsarah** [comment]
Small update:
- I don't anticipate the dev server will be up until mid-end day Tuesday US time, so you're probably stuck till Wed @alexgibson.
- I'll update this issue with a more canonical version of the docs, once we get the PR merged. The latest version is here: https://github.com/mozilla-services/cjms/tree/affiliate_identifier_cookie_endpoint#aic---affiliate-identifier-cookie with some notes about potential error states - mostly 500s and a 404.

**Comment by slightlyoffbeat** [comment]
Thanks @alexgibson. An update from our weekly affiliate meeting:

We decided to move ahead with the option to have a banner that allows users to opt out. A user is opted in unless they click a button on the banner to opt out.

This approach is approved by legal and all stakeholders.

I created a brief to get design & copy from the studio. My expectation is that it will be a very simple banner at the top of the page with copy + button/s.

**Comment by birdsarah** [comment]
You should be unblocked: https://dev.cjms.nonprod.cloudops.mozgcp.net/aic

**Comment by birdsarah** [comment]
> If that assumption is correct, then when someone does click to "opt-out", are there any new / extra flow steps required to remove their data? 

To make the "opt-out" work, you will need to trigger a new call to the fxa metrics API to get a new flow_id. By doing that and NOT sending it to the cjms endpoint then cjms will have no knowledge of the new flow_id and so will be out of the cjms flow.

You could clean out the cookie or whatever you want to do on your end. But from a preventing join perspective the only necessary step is to get a new flow_id and put it on the subscribe buttons.

**Comment by alexgibson** [comment]
@birdsarah I'm hitting a CORS error when trying to POST to the CJMS endpoint locally. Can you please see if we can add the following allowed origins to both the dev and prod server? Thanks:

Dev:

- http://localhost:8000/
- https://www-dev.allizom.org/
- https://www-demo1.allizom.org/
- https://www-demo2allizom.org/
- https://www-demo3.allizom.org/
- https://www-demo4.allizom.org/
- https://www-demo5.allizom.org/

Prod:

- https://www.allizom.org/
- https://www.mozilla.org/

**Comment by birdsarah** [comment]
I have pushed a fix and been able to verify it locally against https://dev.cjms.nonprod.cloudops.mozgcp.net/aic.

In case you need a reference, the specifics are [here](https://github.com/mozilla-services/cjms/pull/25/files#diff-6563b1dfe926fb2b1f81bebadb71e69b481323f62b3badd5c87a3e30cd278f79R48-R78).

**Comment by alexgibson** [comment]
@birdsarah here's my WIP branch up on demo. This is still in a state of flux, but I have the main API flow working for both `POST` and `PUT` and setting the affiliate marketing cookie.

https://www-demo1.allizom.org/en-US/products/vpn/?cjevent=09d8676b716a11ec831e01500a18050e

Note: I haven't started on the cookie banner or opt-out mechanism yet, this is next on my list.

**Comment by alexgibson** [comment]
Some open questions I'm not sure on the answer to:

- Do we need to handle this flow for multiple VPN pages, or only the main VPN landing page? (all pages is possible, but gets more complex since only the main page contains actual subscrition buttons with flow params).
- If we store a marketing cookie value for a visitor but they don't subscribe, and instead return later on directly (not via a CJ link), do we need to do anything? The flow diagram suggests no, but thought I should double check.
- If someone opts-out of affiliate attribution via the banner, how long should we set the cookie for? 1 day, 1 week?
- Is there anything we need to add to our website [privacy policy](https://www.mozilla.org/en-US/privacy/websites/) before this goes live?

**Comment by slightlyoffbeat** [comment]
Checked with legal: no privacy policy changes needed. We already have a section that covers this.

**Comment by slightlyoffbeat** [comment]
Unless we receive additional guidance, i'd say we set the cookie for 4 weeks.

**Comment by slightlyoffbeat** [comment]
Homepage only (english, french & german)

**Comment by slightlyoffbeat** [comment]
@alexgibson I like the idea of using an existing component and not inventing or reinventing anything. Normally this would be a quick question to UX but we don't have a UX resource currently. I put this option in front of the studio team and will have an answer by end of week.

**Comment by alexgibson** [comment]
> Homepage only (english, french & german)

Thanks, I'll limit the flow to `en`, `de`, `fr`.

**Comment by alexgibson** [comment]
@birdsarah @slightlyoffbeat another open question:

If someone revisits the page later (without a CJ event param in the URL), but already has a marketing cookie set because they didn't opt-out originally, then do we want to show the banner to them again on their repeat visit?

**Comment by slightlyoffbeat** [comment]
I'll be interested in what @birdsarah says, but I'd say we show the banner.

@alexgibson also, we have a thumbs up to just use the notification component. Copy will come next week.

**Comment by birdsarah** [comment]
Good question. I don't know. Lets discuss at next affiliate meeting.

**Comment by alexgibson** [comment]
@slightlyoffbeat any update on status of the strings for the banner?

**Comment by alexgibson** [comment]
Final copy on cookie banner is now in place:

![image](https://user-images.githubusercontent.com/400117/159967875-65ee94bd-a2de-4e57-b457-e00c4556ced3.png)

Demo: https://www-demo1.allizom.org/en-US/products/vpn/?cjevent=09d8676b716a11ec831e01500a18050e
