### ISSUE TITLE
[Epic] WNP 98 (EU VPN)

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#11210]
## Description

Launching **March 8** (strings need to be in Pontoon by **March 1st**).

[Launch plan](https://docs.google.com/document/d/1emFAlQB1U9KY--tYGHK3NUvZfTnQZnbcFnTZOwt7Kvg/edit?usp=sharing) (Mozilla access only)

- [x] Page design and content - re-used from previous WNP. Localized. @slightlyoffbeat will provide
- [x] Localized into three locales (see launch plan).
- [x] Geo target these pages to new countries (see launch plan).
- [ ] Copy needs to be in Pontoon by **March 1st**.

Also depends on:

- [ ] https://github.com/mozilla/bedrock/issues/11213

**Comment by slightlyoffbeat** [comment]
copy document: https://docs.google.com/document/d/1tfDXrMxnebgJ6-6eBQS_2WSoy0AxMRi1D73uDBOMNp0/edit?usp=sharing

**Comment by alexgibson** [comment]
Demo:

- https://www-demo1.allizom.org/en-US/firefox/98.0/whatsnew/?geo=se
- https://www-demo1.allizom.org/en-US/firefox/98.0/whatsnew/?geo=fi
