### ISSUE TITLE
Epic: Pocket + Bedrock + l10n

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11403]
## Description

What is the overall outcome we aim to achieve? 

* Multilingual Pocket pages, served by Bedrock, with content coming purely from Smartling

Link to pitch, brief, or background documents.

* This [summary doc](https://docs.google.com/document/d/1C9I_ydjvZxhWman92TtHtEf2xDrNYn4W9v2Gg9iNr3U/edit#heading=h.ugqmpl58v1kc) includes latest requiremetns 

---

#### Issues
- Site splitting:
  - [x] https://github.com/mozilla/bedrock/issues/11426
  - [x] https://github.com/mozilla/bedrock/issues/11510
  - [x] Work out hostnames for pocket ingress in dev, stage, test, prod
  - [x] https://github.com/mozilla/bedrock/issues/11509

- Code/content fixups
  - [x] https://github.com/mozilla/bedrock/issues/11508
  - [x] https://github.com/mozilla/bedrock/issues/11542
  - [x] Move Pocket legal pages to github.com/mozilla/legal-docs

- Fluent support
  - [x] https://github.com/mozilla/bedrock/issues/11519
  - [x] https://github.com/mozilla/bedrock/issues/11619
  - [x] https://github.com/mozilla/bedrock/issues/11674

- l10n content 
  - [x] Amendments from L10N team feedback to https://github.com/mozilla-l10n/pocket-www-l10n/pull/6 
  - [x] Confirm plan for international Spanish locale use and line up locales https://github.com/mozilla/bedrock/pull/11743
  - [x] https://github.com/mozilla/bedrock/issues/11738
  - [x] Remove stale files from pocket-www-l10n before Smartling work starts - see [here](https://github.com/mozilla-l10n/pocket-www-l10n/pull/6#discussion_r894009365) https://github.com/mozilla-l10n/pocket-www-l10n/pull/7
 
- l10n pipeline support
  - [x] @stevejalim set up new `www-pocket-l10n` repo in `mozilla-l10n`
  - [x] https://github.com/mozilla/bedrock/issues/11521
  - [x] Update https://github.com/mozilla-l10n/mozl10n-linter to include new pocket l10n repo -> https://github.com/mozilla-l10n/mozl10n-linter/pull/13

- Deployment work
  - [X] Decide on how static asset URLs will be referenced from Pocket mode
  - [x] Plan CDN cut-over
  - [x] Re-check CSP rules on prod instance, before domain switchover
  - [x] Execute CDN cut-over

- Spin-off tickets, non-blocking
  - [x] https://github.com/mozilla/bedrock/issues/11543
  - [ ] https://github.com/mozilla/bedrock/issues/11544
  - [x] https://github.com/mozilla/bedrock/issues/11641 -> split to other ticket

**Comment by stevejalim** [comment]
Cross-linking to #10211
