### ISSUE TITLE
Mark up Pocket pages with Fluent syntax

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11519]
## Description

The Pocket pages ported into bedrock only contain English text, inline in the HTML templates.

We need to change this to be marked up ready for translation with Fluent.

---

#### Success Criteria
- [x] bedrock has a clear directory structure for pocket-related fluent files, in the same pattern as main bedrock l10n files but _not_ in the same child directory
- [x] All pages marked up for Fluent (please stick your name beside one if you start it, then link to the PR as we work through them)
  - [x] about.html - @stevejalim - https://github.com/mozilla/bedrock/pull/11541

  Once the one above ☝️ is merged, that will unblock doing these:

  - [x] #11565 - @nathan-barrett 
  - [x] #11620 
  - [x] [ios.html](https://github.com/mozilla/bedrock/pull/11579)
  - [x] [chrome.html](https://github.com/mozilla/bedrock/pull/11579) 
  - [x] [safari.html](https://github.com/mozilla/bedrock/pull/11579)
  - [x] [opera.html](https://github.com/mozilla/bedrock/pull/11579)
  - [x] [edge.html](https://github.com/mozilla/bedrock/pull/11579)
  - [x] [welcome.html](https://github.com/mozilla/bedrock/pull/11579)
  - [x] #11598
  - [x] #11621 
  - [x] pocket-and-firefox.html #11638
  - [x] get-inspired.html #11638
  - [x] jobs.html - #11643
  - [x] privacy.html - #11643
  - [x] tos.html - #11643
  - [x] #11623 
  - [x] 404 and 500 pages - need to be created and marked up - see https://github.com/mozilla/bedrock/issues/11542
  - [x] Homepage - still to be ported into Bedrock - see https://github.com/mozilla/bedrock/issues/11513

**Comment by nathan-barrett** [comment]
@stevejalim once that initial PR is merged I can start cranking on these other pages

**Comment by stevejalim** [comment]
@nathan-barrett Unblocked, sir! 😄 Thanks!

**Comment by nathan-barrett** [comment]
Talked with Dan - looks like tos.html and privacy.html will not be using fluent (due to the legal nature of the text)

**Comment by stevejalim** [comment]
Nice one, everyone!
