### ISSUE TITLE
Add l10n pipeline for Pocket Fluent translations

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11521]
## Description

Pocket translations will happen in parallel to Mozorg ones, but in the same pattern.

---

#### Tasks
- [x] Prepare bedrock repo for pocket-l10n integration - set up directories for outbound fluent strings
- [x] Understand the `mozmeao` fluent repo for Mozorg, incl CI
- [x] Understand the `mozilla-l10n` fluent repo for Mozorg, incl CI 
- [x] Update settings and/or env vars suitable for use in Pocket mode in relevant scripts/commands triggered in CI
- [x] Update language activation logic for Pocket mode to just return all prod locales   
- [x] Add Pocket-specific logic to https://github.com/mozilla/bedrock/blob/main/.gitlab-ci.yml#L35-L47 so that Mozorg mode and Pocket mode trigger the appropriate l10n repo PRs
