### ISSUE TITLE
Bedrock demos on GCP infra

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#11641]
## Description

This work focuses on standing up five demo servers/apps/sites for Mozorg and two for Pocket. 
We will be doing this using GCP, leveraging Cloud Run (ie, a serverless approach), Cloud Build and related GCP backing services.

We have a viable workflow that a proof of concept shows can let us continue to push to a branch and end up with a deployed demo site (as we used to do on Heroku). This ticket outlines the approach and also the remaining ops work to get it into everyday use.

---- 

## Summary of the viable PoC workflow

Cloud Build's features are key to the work here (but we also leverage Cloud Run, Artifact Registry and Secrets Manager).

Cloud Build supports triggers, including those which monitor branches on code repos.

We use two triggers in Cloud Build: one to stand up Mozorg demos and a very similar one for Pocket demos. The triggers look for pushes up to `mozilla/bedrock`, and specifically to branches named from `mozorg-demo-1` to `mozorg-demo-5` or `pocket-demo-1` and `pocket-demo-2` (only). 

Cloud Build then runs a Docker build of our regular Bedrock container, using a Mozorg- or Pocket-specific Cloud Build config, which is chosen based on the branch name that triggered the build.

The relevant config makes Cloud Build:
* build a container based off the HEAD of the branch that triggered it
* upload the resulting container to a demo-specific repository in GCP Artifact Registry
* invoke GCP Cloud Run to run the container as a Service, with a `SITE_MODE` of either `Mozorg` or `Pocket` -- again selecting the appropriate Service configuration based on the branch that triggered the build. 

IMPORTANT NOTE:
_The branch names that we push to are crucial to the worfklow_ – they are used to name the resulting Containers in Artifact Registry and also the Cloud Run services that use those containers, which in turn will have friendly domains mapped to them. **It's important we only use the following branch names if we want everything to work:**

* mozorg-demo-1
* mozorg-demo-2
* mozorg-demo-3
* mozorg-demo-4
* mozorg-demo-5
* pocket-demo-1
* pocket-demo-1

(In theory you could push to pocket-demo-9 and it would trigger a build, but you may not end up with a nice hostname pointed a that running Service)

### How do env vars and secrets work?

* Secrets are stored in GCP Secrets and referenced in the configuration for the demo Cloud Run Service. They are never public
* Public-appropriate env vars, meanwhile, live in the bedrock repo, in an appropriately named YAML file (see `gcp/bedrock-demos/cloudrun/mozorg-demo.env.yaml` and `gcp/bedrock-demos/cloudrun/pocket-demo.env.yaml`). These files can be edited or added to at will on any feature branch being developed, and can be checked to the repo in because these demo env var files are not used at all in our real Kubernetes production infrastructure. Yes, there is a small risk of a merge conflict if multiple developers are updating demo env vars, but these can be resolved manually before merge.

### How do domains work?

Cloud Run allows us to consistently map a domain to a Service, and we'll set up the following domain-to-service mappings:

* www-demo1.allizom.org -> mozorg-demo-1
* www-demo2.allizom.org -> mozorg-demo-2
* www-demo3.allizom.org -> mozorg-demo-3
* www-demo4.allizom.org -> mozorg-demo-4
* www-demo5.allizom.org -> mozorg-demo-5
* www-demo1.tekcopteg.com -> pocket-demo-1
* www-demo2.tekcopteg.com -> pocket-demo-2

## Things to set up in GCP

All of this should happen in us-central1/Iowa (low-carbon data center; we already have presence in the same region)

Right now, this is all artisnal clickops, which is far from ideal. If we're happy with the approach, I am happy to turn as much of this as possible into configuration files, but from my explorations it seems like one can't dump out a current config into a file for all the things we're using. (I will keep looking, though)

#### Project:

  - [ ] Create a GCP project - eg `bedrock-demo-sites`

#### Create a Service Account with the roles:
 - [ ] Cloud Run Admin 
 - [ ] Service Account User  
 - [ ] the Secret Manager Secrets Accessor
 - [ ] Logs Writer role
 - [ ] Artifact Registry Writer 

#### Grant project access to the following services/APIs:

  - [ ] Artifact Registry
  - [ ] Cloud Build
  - [ ] Cloud Run
  - [ ] Secret Manager  

#### Create GCP objects:

  - [ ] In Artifact Registry, create a repo called `bedrock-demo`

  - In Secrets Manager, create the following secrets:
     - [ ] bedrock-demos-core-BASKET_API_KEY - get value from Heroku Demos settings or Basket itself or @stevejalim 
     - [ ] bedrock-demos-core-FXA_ENDPOINT - get value from Heroku Demos settings or @stevejalim  
     - [ ] bedrock-demos-core-SECRET_KEY - can be a new random string
     - [ ] bedrock-demos-core-VPN_ENDPOINT - get value from Heroku Demos settings or @stevejalim 

    (If we can do these as a single YAML/JSON file, that'd be neater, but will likely then need code changes)
    
  - In Cloud Build set up Mozorg support   
    - [ ] A trigger called `mozorg-demo-trigger`
    - [ ] ...which is run based on changes to a branch 
    - [ ] ...on `mozilla/bedrock`
    - [ ] matching the regex `^mozorg-demo-\d$`
    - [ ] In Advanced Settings, reads a Cloud Build configuration file
    - [ ] ...from the repository... at the path `gcp/bedrock-demos/cloudbuild/mozorg-demo.yaml`
    - [ ] Assign the service account you made above to this trigger
    (Note you wil need to link Cloud Build to Bedrock on Github and you will need to be an Admin on `mozilla/bedrock` to make the link)

  - And also Pocket support
    - [ ] A trigger called `pocket-demo-trigger`
    - [ ] ...which is run based on changes to a branch 
    - [ ] ...on `mozilla/bedrock`
    - [ ] matching the regex `^pocket-demo-\d$`
    - [ ] In Advanced Settings, reads a Cloud Build configuration file
    - [ ] ...from the repository... at the path `gcp/bedrock-demos/cloudbuild/pocket-demo.yaml`
    - [ ] Assign the service account you made above to this trigger

#### Initial deployment, ahead of domain names

   - [ ] ~Grant access for the service account used by Cloud Run to the Secrets: - the service account used must be granted the 'Secret Manager Secret Accessor'  role. Discovering the service account may not be possible until the step below is done once and fails - in which case the relevant Cloud Build job can be restarted after the role is added without needing to push up code again, I think~ No longer needed now we're using a dedicated service account, above

  - [ ] Test build and deploy works: Make a trivial edit to the `demos-on-cloud-run` branch (or `main` if it's been merged) and force push it to trigger the Cloud Build triggers for each demo env, which will spin up all seven demo apps.

  Assuming your origin for `mozilla/bedrock` is called `mozilla`:
      
  ```
  git push -f mozilla demos-on-cloud-run:mozorg-demo-1
  git push -f mozilla demos-on-cloud-run:mozorg-demo-2
  git push -f mozilla demos-on-cloud-run:mozorg-demo-3
  git push -f mozilla demos-on-cloud-run:mozorg-demo-4
  git push -f mozilla demos-on-cloud-run:mozorg-demo-5
  git push -f mozilla demos-on-cloud-run:pocket-demo-1
  git push -f mozilla demos-on-cloud-run:pocket-demo-2
  ```

- [ ] In Google Cloud Run dash (https://console.cloud.google.com/run), confirm all seven services are now running

- [ ] In the Cloud Run dash, use the Manage Custom Domains link to set up the above domain mappings.

#### Bonus things that'd be good to sort

- [ ] Auto-delete stale containers, unless they are free to store.

----

# Success Criteria

- [X] Code can be pushed to a demo server and it is deployed in an appropriate mode (Mozorg or Pocket) 
- [X] It's possible for developers to add/amend env vars easily
- [X] Mozorg changesets can be explored on a demo server
- [X] Pocket changesets can be explored on a demo server
- [x] GCP setup is replicable from code, not from a clickops checklist. Ideally it's done via Terraform
- [x] Documentation is updated, incl how to deploy Mozorg or Pocket modes, hostnames to use and an explanation about how to update env vars for demos

**Comment by pmac** [comment]
> * Because the demo servers could be used for Mozorg or Pocket, we will use the generic `moz.works` domain, following the hostname pattern `bedrock-demo-{1,5}.gcp.moz.works`

This is fine to have as well, but I'm sure there will also be a desire to keep our current `www-demoX.allizom.org`. I see no issue with that.

**Comment by bkochendorfer** [comment]
Looks good to me. I hope we can get the gcp cloud run stuff into terraform instead of ClickOps once we are ready https://github.com/mozmeao/infra-services/tree/main/gcp

**Comment by stevejalim** [comment]
@bkochendorfer Happy to put it in terraform if you're cool with revieiwng and trying it

**Comment by stevejalim** [comment]
Update: just brushing up my Terraform. Also, I should make this run with a v limited service account (even within my throwaway sandbox), so will sort that, too

**Comment by stevejalim** [comment]
The main work here is done. There are some follow-ups to do with improving the developer experience, but they live in their own tickets. Closing!
