### ISSUE TITLE
Contentful Clean-up

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#11823]
We want to de-clutter Contentful-related content and prioritize remaining issues

CONTENTFUL WEB APP
- [ ] Remove test content entries from Master Contentful environment (these should be tested in sandbox environments going forward)
- [x] [Update to new Compose content model](https://github.com/mozilla/bedrock/issues/11810)

BEDROCK API
- [ ] No more TODO in comments (or at least, all todos are linked to issues so we don't lose track of them)

OPEN ISSUES
If still relevant and not already there, maybe add to [marketing-platform project board](https://github.com/mozilla/bedrock/projects/30)?

Workflow
- [x] https://github.com/mozilla/bedrock/issues/9467
- [x] https://github.com/mozilla/bedrock/issues/9469
- [x] https://github.com/mozilla/bedrock/issues/9472
- [ ] https://github.com/mozilla/bedrock/issues/9901
- [ ] https://github.com/mozilla/bedrock/issues/9988
- [x] https://github.com/mozilla/bedrock/issues/9993
- [x] https://github.com/mozilla/bedrock/issues/9994
- [ ] https://github.com/mozilla/bedrock/issues/9996
- [x] https://github.com/mozilla/bedrock/issues/9997

Enhancements
- [ ] https://github.com/mozilla/bedrock/issues/10678
- [ ] https://github.com/mozilla/bedrock/issues/10742
- [x] https://github.com/mozilla/bedrock/issues/10743
- [x] https://github.com/mozilla/bedrock/issues/10773
- [ ] https://github.com/mozilla/bedrock/issues/10785
- [ ] https://github.com/mozilla/bedrock/issues/10898
- [ ] https://github.com/mozilla/bedrock/issues/10899
- [ ] https://github.com/mozilla/bedrock/issues/10443
- [ ] https://github.com/mozilla/bedrock/issues/9992
- [ ] https://github.com/mozilla/bedrock/issues/12027

Bugs [mostly related to homepage, should be fixed with split-based homepage update coming soon]
- [ ] https://github.com/mozilla/bedrock/issues/10667
- [x] https://github.com/mozilla/bedrock/issues/10668
- [x] https://github.com/mozilla/bedrock/issues/10677
- [ ] https://github.com/mozilla/bedrock/issues/10765

Design system checklist
- [ ] https://github.com/mozilla/bedrock/issues/10127
remaining unchecked
- rich text image support
- high/low res image solutions for split, hero, cards, and rich text
- include CSS as needed for nested components (i.e. youtube videos in cards)
- include JS as needed for nested components (i.e. youtube videos in cards)
- figure out section/background wrappers
- add split support inside rich text areas
- filter improvements: download button shouldn't be wrapped in p tags, safe guard against dev/staging links
- CTA button for Monitor, tracking params
- CTA app store links for Firefox mobile and Pocket
- **l10n:** translated feature pages, DE homepage
- **analytics:** identify CTAs by position on page
- include Pocket feed on homepage
- add all Protocol icons to media library
- add all product OG images to media library
- docs for Contentful available components in Protocol
- center logo or wordmark when text is centered
- **picto:** request icon without aspect ratio
- **section heading:** zap support
- **card layout:** "ragged" image aspect ratios
- **multi-column:** centered text option

**Comment by maureenlholland** [comment]
Going forward, I'd put the top 2 priorities as:
1. l10n integration (Smartling)
2. Ship-it Workflow (order of operations when updates happen across Contentful API and bedrock code, while editors might be changing content in Contentful master environment)

**Comment by maureenlholland** [comment]
@stephaniehobson I tried to round up our outstanding Contentful issues for re-evaluation. Take a look when you have time to see if there are any we can close or should prioritize (i.e. responsive images)

**Comment by maureenlholland** [comment]
closing in favor of more specific issues and updated label organization ([see Contentful labelled issues](https://github.com/mozilla/bedrock/issues?q=is%3Aopen+is%3Aissue+label%3AContentful))
