### ISSUE TITLE
[Epic] Refresh Pocket Marketing page images 

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#12290]
## Description

Some Pocket Marketing Pages contain some images which need updating

* Homepage image is currently localised only for `en` and `de` - TBC whether we should localise further
* The platform-specific images on the following pages are all stale and would benefit from a check and refresh in terms of logo and UI
  - [ ] https://getpocket.com/chrome 
  - [ ] https://getpocket.com/opera
  - [ ] https://getpocket.com/safari
  - [ ] https://getpocket.com/edge  

---

#### Success Criteria
- [ ] Site images are up to date/current

**Comment by maureenlholland** [comment]
Whoever we contact for creative help here could also assist with https://github.com/mozilla/bedrock/issues/11699

**Comment by Ayush-Kori** [comment]
Hello, Can I take up this issue to update images??

**Comment by stevejalim** [comment]
Sorry @Ayush-Kori - this one needs liaison internally with the studio team to produce the new images

**Comment by maureenlholland** [comment]
https://github.com/mozilla/bedrock/issues/12324 can also be included here
