### ISSUE TITLE
Epic: Custom Asana integrations

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#12642]
## Description

In order to boost the value of Asana for our team and reduce the legwork in maintaining both Github and Asana tickets, we would like to have some integrations established to automate certain tasks.

We'll start simply and extend as we go.

---

#### Requirements
- [x] https://github.com/mozilla/bedrock/issues/12643  (similar to how [this integration](https://asana.com/apps/github) associates pull requests).
- [x] Easily extensible framework so we can add extra behaviour
- [ ] If a demo gets added to an issue, that could be something interesting to pull in.
