### ISSUE TITLE
Epic: Migrate CI infra for Bedrock

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#12948]
## Description

In order to simplify our CI processes, we've decided to move from GitLab to GH Actions.

---

#### Issues
- [x] https://github.com/mozilla/bedrock/issues/12820
- [x] https://github.com/mozilla/bedrock/issues/12984
- [x] https://github.com/mozilla/bedrock/issues/12481
- [x] https://github.com/mozilla/bedrock/issues/13029
- [x] https://github.com/mozilla/bedrock/issues/12480
- [x] https://github.com/mozilla/bedrock/issues/12947
- [x] www-admin / content cards - https://github.com/mozmeao/www-admin/pull/103
- [x] www-experiment-media - https://github.com/mozmeao/www-experiment-media/pull/1
- [x] https://github.com/mozilla/bedrock/issues/12946
- [x] https://github.com/mozilla/bedrock/issues/12950
- [x] https://github.com/mozilla/bedrock/issues/12949
