### ISSUE TITLE
Epic: Add support for GA4

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#13238]
## Description

Google is turning off UA/GA3 data collection in July for most users. WMO ([www.mozilla.org](http://www.mozilla.org/)) needs to migrate to a new system.

```[tasklist]
### Tasks
- [ ] https://github.com/mozilla/bedrock/issues/13683
- [x] https://github.com/mozilla/bedrock/pull/13416
- [x] https://github.com/mozilla/bedrock/pull/13356
- [x] https://github.com/mozilla/bedrock/pull/13012
- [ ] https://github.com/mozilla/bedrock/issues/13943
- [ ] https://github.com/mozilla/bedrock/pull/13914
- [ ] https://github.com/mozilla/bedrock/issues/13942
- [ ] https://github.com/mozilla/bedrock/pull/13926
- [ ] https://github.com/mozilla/bedrock/issues/13919
- [x] https://github.com/mozilla/bedrock/pull/13913
- [ ] https://github.com/mozilla/bedrock/issues/13685
- [ ] https://github.com/mozilla/bedrock/issues/13948
- [ ] https://github.com/mozilla/bedrock/issues/12801
- [ ] https://github.com/mozilla/bedrock/issues/13904
- [ ] https://github.com/mozilla/bedrock/issues/13895
- [ ] https://github.com/mozilla/bedrock/pull/13898
- [ ] https://github.com/mozilla/bedrock/issues/14072
```

**Comment by stephaniehobson** [comment]
I'm moving outstanding tasks to https://github.com/mozilla/bedrock/issues/14749 and marking this as complete.
