### ISSUE TITLE
Epic: Update Glean.js to test new features and improvements

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#13431]
## Description

This is an epic to track updating bedrock's Glean.js implementation to test new client and platform improvements. The Glean.js team are implementing a set of standard default page load metrics (as well as other improvements), so that it's easier to standardize data and build automated dashboards in Looker. 

The breakdown of work in this epic involves migrating bedrock to use these new features so that we can test them, provide feedback, and take advantage of the new tooling.

```[tasklist]
### Action items
- [x] Update Glean JS to to take advantage of synchronous pings
- [x] Migrate from current custom ping schema to native event pings
- [x] Send pings using `sendBeacon` uploader
- [x] Migrate to standardized page load event and default metrics
- [x] Enable automatic event monitoring dashboard creation in Looker
- [x] Proxy pings via the CDN for improved baseline metrics
- [x] Create temporary dashboard in Redash
```

Individual issues will be referenced below:

---

#### Issues / pull requests
- [x] https://github.com/mozilla/bedrock/pull/13430
- [x] https://github.com/mozilla/bedrock/issues/13481
- [x] https://github.com/mozilla/bedrock/issues/13493
- [x] https://github.com/mozilla/bedrock/pull/13532
- [x] https://github.com/mozilla/bedrock/pull/13573
- [x] https://github.com/mozilla/bedrock/issues/13581
- [x] https://github.com/mozilla/bedrock/issues/13583
- [x] https://github.com/mozilla/bedrock/issues/13592
- [x] https://github.com/mozilla/bedrock/issues/13593
- [x] https://github.com/mozilla/bedrock/issues/13639
- [x] https://github.com/mozilla/bedrock/issues/13652
- [x] https://github.com/mozilla/bedrock/issues/13675
- [x] https://github.com/mozilla/bedrock/pull/13730
- [x] https://github.com/mozilla/bedrock/pull/13789
- [x] https://github.com/mozilla/bedrock/pull/13812
- [x] https://github.com/mozilla/bedrock/issues/13876
- [x] https://github.com/mozilla/bedrock/pull/13899
- [x] https://github.com/mozilla/bedrock/pull/13986
- [ ] https://github.com/mozilla/bedrock/pull/13988
- [x] https://github.com/mozilla/bedrock/pull/14006
