### ISSUE TITLE
Parity check with relay.firefox.com

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#13432]
```[tasklist]
### Tasks
- [x] Add sign in button
- [ ] Update image in page header on landing & premium
- [ ] Convert reviews into carousel of reviews
- [x] Remove Get VPN button
- [x] Add "per month" after pricing in matrix
- [x] Add price to VPN column in matrix
- [x] Update hero blurb on premium page.
```

**Comment by stephaniehobson** [comment]
The Relay migration to bedrock is paused.
