### ISSUE TITLE
Epic: Data consent updates and privacy improvements

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#14213]
## Description

Individual tasks are still being fleshed out and will be added to this list later, but I'm creating this epic for now just to help keep track of the list as it grows.

```[tasklist]
### Tasks
- [ ] Add explicit opt-in for data collection in EU/EAA countries only on specific URLs.
- [ ] Omit non-essential cookies and analytics on URLs in EU/EAA countries where opt-in is not requested.
- [ ] Add global data preferences page and link in main footer.
- [ ] Implement Global Privacy Control (GPC) as an additional opt-out signal to Do Not Track (DNT).
- [ ] https://github.com/mozilla/bedrock/issues/14494
- [ ] https://github.com/mozilla/bedrock/issues/14488
- [ ] https://github.com/mozilla/bedrock/issues/14482
- [ ] https://github.com/mozilla/bedrock/issues/11698
- [ ] https://github.com/mozilla/bedrock/pull/14208
- [ ] https://github.com/mozilla/bedrock/issues/14172
- [ ] https://github.com/mozilla/bedrock/issues/14201
- [ ] https://github.com/mozilla/bedrock/issues/14120
- [ ] https://github.com/mozilla/bedrock/issues/14086
```
