### ISSUE TITLE
Refresh Epic: Site Cleanup

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14229]
## Description

We did a [site audit](https://docs.google.com/spreadsheets/d/1fuzDBBmxct-9BB_wa_x5XDK__UYil7OYBPE6Cufn0vQ/edit#gid=0) (Mozilla only link) and identified some pages and widgets that can be removed or updated to reduce the maintenance burden. This epic is to group individual issues that came out of that site audit and the discussions that followed in the weeks after.

```[tasklist]
### Tasks
- [ ] https://github.com/mozilla/bedrock/issues/15008
- [ ] https://github.com/mozilla/bedrock/issues/15007
- [ ] https://github.com/mozilla/bedrock/issues/13878
- [ ] https://github.com/mozilla/bedrock/issues/14230
- [ ] https://github.com/mozilla/bedrock/issues/14142
- [ ] https://github.com/mozilla/bedrock/issues/14141
- [ ] https://github.com/mozilla/bedrock/issues/14231
- [ ] https://github.com/mozilla/bedrock/issues/14244
- [ ] https://github.com/mozilla/bedrock/issues/14243
- [ ] https://github.com/mozilla/bedrock/issues/14245
- [ ] https://github.com/mozilla/bedrock/issues/14246
- [ ] https://github.com/mozilla/bedrock/issues/14247
- [ ] https://github.com/mozilla/bedrock/issues/14251
- [ ] https://github.com/mozilla/bedrock/issues/14248
- [ ] https://github.com/mozilla/bedrock/issues/14249
- [ ] https://github.com/mozilla/bedrock/issues/14252
- [ ] https://github.com/mozilla/bedrock/issues/14543
- [ ] https://github.com/mozilla/bedrock/issues/14550
```

**Comment by janbrasna** [comment]
@stephaniehobson Do you have a rough idea about the remaining tasks that block completing this epic? The `contribute.json` has been sorted out, so only two are left:
1. `try-picture-in-picture` is meant to remove #13680 and redirect it to its feature page? (I've seen PiP being brought up again in WNPs, but they usually showcase new content and link the features page anyway…)
2. `locales` could mean the l10n obsolete cleanup reminder that's now in place, or perhaps something else? (more performant firefox/all for some locales? accept-header-specific or more precisely language agnostic firefox/new+download experience? or perhaps getting rid of home-old for the "slower" translations?)

**Comment by stephaniehobson** [comment]
@janbrasna I've formalized the two remaining ones in issues #15007 and #15008. Let me know if you have any more questions :)

**Comment by janbrasna** [comment]
@stephaniehobson Yeah I should have noticed it was the actual _paths_  that were tracked in the tasks;) so thanks for the nudge. No questions, just good to close it out, as the sole remaining issue is not an easy cleanup as it may look, and has a few intertwined issues partly blocking it — so better to leave that one separately.
