### ISSUE TITLE
Refresh Epic: Product List Page

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14220]
## Description

As we move away from the "Firefox" family of products and towards a "Mozilla" family of products. In response to this some re-organization of our list pages makes sense.

```[tasklist]
### Tasks
- [ ] https://github.com/mozilla/bedrock/issues/14221
- [ ] https://github.com/mozilla/bedrock/issues/14222
- [ ] https://github.com/mozilla/bedrock/issues/14290
- [ ] https://github.com/mozilla/bedrock/issues/14455
- [ ] https://github.com/mozilla/bedrock/issues/14457
- [ ] https://github.com/mozilla/bedrock/issues/14456
- [ ] Add Fakespot to homepage products
- [ ] Add Fakespot to navication menu
```

**Comment by stephaniehobson** [comment]
@janbrasna the navigation menus are a little more politically tricky to change but you make a good point that it doesn't match the page anymore. I'll ask around internally and see if we think we can change this without forming a committee 😝

**Comment by stephaniehobson** [comment]
@janbrasna https://github.com/mozilla/bedrock/issues/14458 is yours if you want it :)
