### ISSUE TITLE
EPIC: Wagtail in Bedrock

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#14225]
# Proof of concept of Wagtail as an additional app within Bedrock, for CMS-managed content

## Scratch todo list
(Scrappy but working in the open is like that sometimes)

- [X] Wagtail in installed apps and URLs
- [X] Lock away the wagtail admin unless there's an env var set
  - [ ] Add tests -- awkward to test

- [X] custom template shenanigans
  - [X] Add tests

- [ ] Sort out middleware
  - [X] Can we update the middleware if there is a WAGTAIL_ENABLE_ADMIN?
    - [ ] Should we? or should we just load it all the time?

  - [ ] test it with and without the WAGTAIL_ENABLE_ADMIN set

- [X] Loading media from images
- [X] Test storage bucket

- [X] Add base page type that doesn't cache password-protected pages

- [ ] Add in wagtail-localize so we get locale-based URLs in from Day 0
  - [X] keep on with the tutorial
  - [X] Fix double locale redirect
  - [X] Fix page chooser locale error

- [X] Add fluent l10n_render into page.serve and page.serve_preview

- [X] Add BedrockCMSBasePage

- [ ] Add GeneralContentPage with a note about what it's used for
  - [ ] Get it working in a couple of locales to be sure the Fluent stuff can be picked up

- [ ] **Locale support**
  - [X] get published page viewing working correctly
    - [ ] Surrounding fluent strings too?
      - [ ] SUPPORT ACTIVE LOCALES FOR A WAGTAIL-HELD TEMPLATE
    - [ ] Add tests

  - [X] Get page previewing working correctly - why is it losing the locale?
    - [X] Spin up test project to see what admin prevoew behaviour should be
    - [ ] Add tests

  - [ ] Deal with locale upcasing/downcasing
    - [ ] ensure that original behaviour still works fine!!
    - [ ] Add tests
    - [ ] Explore this: Why codes this give us the CMS root page <http://localhost:8000/es-mx/> but <http://localhost:8000/es-MX/> gets the proper es-MX homepage?

- [ ] SessionMiddleware sets cookies which in turn breaks the CDN with Vary: Cookie
  - [ ] Handle this with custom middleware from Birdbox

- [ ] JINJA TEMPLATE HANDLING

    > Wagtail lets us have Snippets, which are blocks of content that behave like pages, but are not routed via URLs like regular pages instead you have something like {% snippet ff_download_button  %} and that slots in the HTML you need (edited) we could MAYBE write a custom snippet renderer that takes a Jinja2 template and spits out the HTML, so the Wagtail page that uses the snippet can still be in DTL

- [X] Add StructuralPage
  - [ ] add tests for StructuralPage

  - [ ] See if userbar still works ok else disable it
  - [ ] See about url routing for /en-US/

- [ ] chat about making URL structures in the CMS fit seamlessly with pages handled by traditional Django views. I have a plan for this (StructuralPages) and happy to share and get feedback on it

- [ ] Redo leadership pages
- [ ] Redo VPNRC pages

- [ ] test out more locales

- [X] CSP for wagtail admin
  - [X] exclude as per Birdbox
  - [/] OR add `connect-src` <https://releases.wagtail.org>

- [ ] ADD SSO, but only on certain domains

- [ ] do we need to worry about rate limiting?

- [ ] routing

- [ ] Look for these, else write them:
  - [ ] sqlite to postgres tool
  - [ ] postgres to sqlite tool

---

- [ ] Check behaviour when fed mixed-case locales
- [ ] Check redirects all work

## To discuss

---
- [ ] Interleaving CMS managed pages with straightforward Django views - process needs to be firmed up

- [ ] Can we make Wagtail run entirely statelessly when not in editing mode? We don't want the session table to be written to on the web pods if they're all using sqlite.

---

## Deferred

- [ ] Sitemap feed/generation

- [ ] Can we render pages using the password protection without the session middleware?
  - [ ] IF NOT, DISABLE THIS FEATURE

- [ ] Check if we need to subclass and adjust `django.middleware.locale.LocaleMiddleware` so that it doesn't mess with things. Can check for `page` in a context, or a snippet?

====

# Tests related to using Wagtail within parts of mozorg

import sys
from http import HTTPStatus
from importlib import reload

from django.conf import settings
from django.test import override_settings

import pytest

def reload_urlconf(urlconf=None):
    # Hat-tip to David, 12 years on! <https://codeinthehole.com/tips/how-to-reload-djangos-url-config/>
    if urlconf is None:
        urlconf = settings.ROOT_URLCONF
    if urlconf in sys.modules:
        reload(sys.modules[urlconf])

@pytest.mark.django_db
@pytest.mark.parametrize("enable_admin", (True, False))
def test_wagtail_admin_only_available_if_settings_allow_it(client, enable_admin):
    with override_settings(
        WAGTAIL_ENABLE_ADMIN=enable_admin,
    ):
        reload_urlconf()

        resp = client.get("/cms-admin/", follow=False)

        if enable_admin is True:
            assert resp.status_code == HTTPStatus.FOUND
        else:
            assert resp.status_code == HTTPStatus.NOT_FOUND
