### ISSUE TITLE
Update headshot on leadership page

### ISSUE THREAD

**Issue by enavajas** [mozilla/bedrock#14506]
Hello. We have received a request to replace the headshot for Laura Chambers' on [the leadership page. ](https://www.mozilla.org/en-US/about/leadership/)

They would like it to be formatted like Lindsey's where it has the option to download the images in a zip file, [see here](https://www.mozilla.org/en-US/about/leadership/#lindsey-obrien) [and the screenshot] <img width="1239" alt="Screenshot 2024-04-29 at 11 15 51 AM" src="https://github.com/mozilla/bedrock/assets/134577516/54e1c895-3bd6-4a19-bb91-7e7370ab4a55">

The image that should be used as the new headshot is: 
![LC headshot white background](https://github.com/mozilla/bedrock/assets/134577516/ea337459-ba6a-4f04-ab3a-f31c265fc9e4) (please let me know if the quality is not high enough). 

The two images that should be included in the zip file are in [this](https://drive.google.com/drive/folders/1L_bcbi5RDQL-bysyT3xHW_S97cqRFnKs?usp=sharing) folder. 

Thank you!

```[tasklist]
### Tasks
- [x] Update Laura's headshot on the leadership page with the new one (white background)
- [x] Add the two photos from the google drive folder into a zip file that can be shared
- [x] Add a link to the zip file on Laura's bio page (as seen in Lindsey's page shared above)
- [x] Eat a snack
```
