### ISSUE TITLE
Add tooling to give local developers an easy way to get appropriate CMS/Bedrock data to work with

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#14659]
### Problem
As an FE you need a local copy of what's on Dev or Stage or Prod. Up until now, you could just download a copy of the sqlite DB that we use in production. However, now we have a change in our DB (centralised DB vs multiple sqlite copies) and we also have CMS-uploaded images that live in a cloud bucket specific to dev/stage/test/prod (rather than all images living in the `mozilla/bedrock` codebase because they are hard-coded). 

We could just hack in something that lets a local build reference the cloud-hosted images, but then if a developer wants to upload an image locally as they develop a new page, we don't want them uploading that (potentially dummy) image to, say, the prod bucket. 

### Proposed solution

Eve is a developer working on Bedrock who needs a copy of local data

* She goes to a page in the Bedrock documentation that shows where (in a cloud bucket or git repo) to find a recent copy of a sqlite DB that she can use with bedrock locally.
  * This sqlite file is produced daily and uploaded into the same bedrock database bucket that we currently use.
* Eve downloads the file 
* Eve uses a new script/command that copies it from the download path (which she provides) into the right place as `path/to/bedrock/data/bedrock.db` and it also backs up the sqlite DB version she had before.
* The script also offers the option to sync down any images from a cloud bucket that don't already exist locally. (We can bake the names of the cloud buckets into the command because they're ultimately public and Eve can picks one of them.)

```[tasklist]
### Tasks
- [x] Image file downloads + documentation
- [x] Update `make preflight` to have a --retain-db flag + documentation
- [x] Document how to download from different environments
```
