### ISSUE TITLE
Epic: Remove GA3/UA

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14749]
## Description

Google is turning off UA/GA3 data collection in July. We need to avoid errors this will create and remove all associated code.

### GTM tasks

- [x] https://github.com/mozilla/bedrock/issues/13951
- [x] https://github.com/mozilla/bedrock/issues/14054
- [x] https://github.com/mozilla/bedrock/issues/14940
- [x] https://github.com/mozilla/bedrock/issues/14750
- [x] https://github.com/mozilla/bedrock/issues/15259

### Bedrock tasks

- [ ] https://github.com/mozilla/bedrock/issues/14079
- [ ] https://github.com/mozilla/bedrock/issues/14902
- [x] https://github.com/mozilla/bedrock/issues/12694
- [ ] https://github.com/mozilla/bedrock/issues/15267
- [x] https://github.com/mozilla/bedrock/issues/14901
- [x] https://github.com/mozilla/bedrock/issues/10733
- [x] https://github.com/mozilla/bedrock/issues/10054
- [x] https://github.com/mozilla/bedrock/issues/14062
- [x] https://github.com/mozilla/bedrock/issues/14406
- [x] https://github.com/mozilla/bedrock/issues/14055

**Comment by stephaniehobson** [comment]
Leftover stuff is nice to have.
