### ISSUE TITLE
Refresh Epic: MVP

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14826]
It's time to start putting pen to paper (finger to keyboard?) on applying the new brand elements to the website. 

Start your switch names with `M24-` so we can tell it's refresh related.

Major Chuncks:

- [x] https://github.com/mozilla/bedrock/issues/14892
- [x] https://github.com/mozilla/bedrock/issues/14893
- [x] https://github.com/mozilla/bedrock/issues/14827
- [x] https://github.com/mozilla/bedrock/issues/14830
- [x] https://github.com/mozilla/bedrock/issues/15073
- [x] https://github.com/mozilla/bedrock/issues/15088
- [x] https://github.com/mozilla/bedrock/issues/15095

Follow up changes:

- [x] https://github.com/mozilla/bedrock/issues/15120
- [x] https://github.com/mozilla/bedrock/issues/15089
- [x] https://github.com/mozilla/bedrock/issues/15129
- [x] https://github.com/mozilla/bedrock/issues/15128

**Comment by enavajas** [comment]
@stephaniehobson hi. nav and footer should be on hold because it is currently still on round 1. But, homepage and about page are ok to begin with using placeholder images, placeholder copy, and lorem ipsum.

**Comment by stephaniehobson** [comment]
@enavajas I have the go-ahead from Dan to start with the existing content in the header and footer - have you heard differently?

**Comment by enavajas** [comment]
> @enavajas I have the go-ahead from Dan to start with the existing content in the header and footer - have you heard differently?
> 
> That will let us get a jump-start on the code before the content is finished.

Hi, I wrote that comment based on my conversation with Dan and Shing in Seattle on Wednesday, and is still accurate AFAIK.

**Comment by stephaniehobson** [comment]
Still to do:

- [ ] hover and focus states should take a more unified approach
- [ ] Protocol hover and focus states are still bleeding through our overrides.
