### ISSUE TITLE
Remove Google Ads campaign tracking parameters from within- or between-site navigation

### ISSUE THREAD

**Issue by a-kyne** [mozilla/bedrock#14838]
## Description
WMO and other Mozilla websites use ad tracking parameters for links both within and between Mozilla sites.

Google Ads campaign tracking parameters ("UTM tags", or "Urchin Tracking Module tags") identify the origin of referrals that come from _external sites_. They are _unnecessary_ for tracking activity within our own websites because we can use web analytics to measure clicks on any link without changing the URL. 

These tracking parameters are often stripped by ad blockers and so they only offer _biased data_. 
Firefox also includes "Copy Link Without Site Tracking" in the contextual menu to enable users to strip tracking parameters; this suggests that we think there is something wrong with using them, and may make our own URLs look untrustworthy.

**SEO: Duplicate Content**
Google cannot distinguish between URLs that contain tracking parameters and URLs that contain content parameters (which are necessary). Thus, every version of a URL that is different from the canonical URL has to be crawled, indexed, and then processed to identify and remove the duplicate copies of the same page. If a URL with tracking parameters is used consistently enough within a website, Google will overwrite the stated canonical value of the URL in favor of the one with tracking parameters. (We have observed instances of this happening with Pocket navigational URLs, for example).

**Analytics Data Quality**
Links that use UTM parameters for reasons other than campaign tracking muddy the data that Google Analytics can collect. For example, if we cannot rely on UTM parameters to be valid for website analytics, we cannot use features such as data-driven attribution. It would be better if systems like RTAMO used differently named parameters, instead of using Google campaign tracking.

---

#### Success Criteria
- [ ] No internal WMO links contain tracking parameters 
- [ ] No links to other Mozilla sites contain tracking parameters that are used for purposes other than website analytics
- [ ] Links that must be tracked are configured for event collection
