### ISSUE TITLE
Refresh Epic: Homepage

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#14892]
~[Details are in this Figma file.](https://www.figma.com/design/mYHdNFy9RyswvKRWzEK6wH/%F0%9F%9A%A7-MVP-mozilla.org-updates?node-id=0-1&t=ntGdhSogMey0VErw-0)~ [Details are in this Figma file](https://www.figma.com/design/LrsDRGILM9Xyp7AEB7vTFO/MVP-Update-%7C-Fall-2024-%7C-Mozilla.org?node-id=28-106023&t=5t2116YNVc7Jl6uQ-1)

Still to do:

- #15303
- #15304
- #15309
- #15305
- #15307
- #15306
- #15308
  - Products: Use lighter grey on product list hover state
  - Address font weight of section CTAs
  - Change AI section to black and add transition
  - Check greys match new colour pallet
- #15399

_Note: the expanded product sections are not part of the homepage MVP_

**Comment by amiii123malviya** [comment]
Hello,

I hope you are doing well,
Is this issue still active??
I would like to work on this.

Best regards

**Comment by stephaniehobson** [comment]
Please look at Good First Bug and Help Wanted tags to find a place to contribute. the https://github.com/mozilla/bedrock/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Bug%22+label%3A%22Help+wanted+%F0%9F%91%8B%22

This issue is large and has a short timeline so it's not a good one for a contributor to pick up. Thanks for your interest!

**Comment by amiii123malviya** [comment]
Hello @stephaniehobson ,

Thankyou for your time and I will look forward to Good First Bugs for contribution.

Best Regards

**Comment by stephaniehobson** [comment]
Still to do:

- [ ] Donate: update component to match "exploration 2"
- [ ] Donate: update component to have a pixel transition on the bottom
- [ ] Products: Use lighter grey on product list hover state
- [ ] Check greys match new colour pallet
- [ ] add updated copy
