### ISSUE TITLE
Refresh: CSS base bundle clean up

### ISSUE THREAD

**Issue by wen-2018** [mozilla/bedrock#15120]
## Description

Currently, the `m24` base bundle doesn't include existing component styles. We should update it to include common styles in `protocol-mozilla`, but with imports of the new nav / footer, home and new styles instead of the old ones, avoiding serving redundant styles to users when the brand refresh switch is on:

```
{% if switch('m24-base') and LANG.startswith('en-') %}
  {{ css_bundle('m24-base') }}
{% else %}
  {{ css_bundle('protocol-mozilla') }}
{% endif %}
```

---

```[tasklist]
### Tasks
- [x] remove old navigation styles from the new navigation and its stylesheet (fixed in https://github.com/mozilla/bedrock/pull/15222)
- [ ] add new nav and footer styles to the new base CSS bundle
- [ ] remove old nav and footer styles from the new base CSS bundle
- [ ] import styles of components that are used on all pages using the existing designs to the new base CSS bundle
```
