### ISSUE TITLE
Back-end pocket-mode removal

### ISSUE THREAD

**Issue by robhudson** [mozilla/bedrock#15124]
```[tasklist]
### Tasks
- [ ] Infra switch off
- [ ] Backend code removal
- [ ] Remove Cloud Build triggers for the pocket demo servers - @stevejalim can advise/support
```

**Comment by robhudson** [comment]
#14596
