### ISSUE TITLE
Wagtail <-> L10N workflow improvements

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#15348]
## Description

We have a core workflow operational with Smartling thanks to https://github.com/mozilla/wagtail-localize-smartling but there are some additional things we need to do (mostly within Bedrock, not `wagtail-localize-smartling`) to improve the workflow.

### Tasks
- [ ] https://github.com/mozilla/bedrock/issues/15349
- [ ] https://github.com/mozilla/bedrock/issues/15347
- [ ] https://github.com/mozilla/wagtail-localize-smartling/issues/34
- [ ] Track the [`wagtail-localize` issue with auto-translation of subtrees failing](https://github.com/wagtail/wagtail-localize/issues/773), to completion
- [ ] Track the [`wagtail-localize` issue about the translation UI misbehaving](https://github.com/wagtail/wagtail-localize/issues/833) to completion
- [ ] https://github.com/mozilla/bedrock/issues/15702
- [ ] https://github.com/mozilla/wagtail-localize-smartling/issues/44
