### ISSUE TITLE
Refresh: Pre-launch checklist

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#15416]
Launch blocking: 

- [x] Pages have appropriate titles and descriptions
- [x] All links have analytics
- [x] All links have correct `href` & utms
- [x] All images are optimized
- [x] All images have a height and width defined (stop page from reflowing as images load)
- [x] Heading order is correct
- [x] No issues detected by a11y checkers
- [x] Images lazy-load when appropriate
- [x] Test all interactions on an actual touch screen mobile device

--

Nice to have:

- [x] Look for performance improvements
- [x] RTL support

**Comment by janbrasna** [comment]
I've noticed a few tiny bits that may (or may not) need some tweaking after being carried over to the M24 style:

Long headings are even bigger now, escaping the expected space (e.g. in `de`, `pt`, `ru`, `nl` etc.)
- https://www-demo4.allizom.org/de/firefox/enterprise/
> ![Screen Shot 2024-11-05 at 03 13 16](https://github.com/user-attachments/assets/4d438ff9-7dda-41af-b074-727511ac0882)

The dark purple background for some in-product pages is black now:
- https://www-demo4.allizom.org/en-US/firefox/nightly/firstrun/
- https://www-demo4.allizom.org/en-CA/firefox/86.0a2/whatsnew/

Some images include the moz://a wordmark:
- https://www-demo4.allizom.org/en-US/careers/ (footer)
- https://www-demo4.allizom.org/en-US/careers/locations/
  `careers/footer-remote.png` and `careers/locations/mozilla-remote.png`

There are some bits of the old system:
- https://www-demo4.allizom.org/en-US/contribute/
1. "Our Mission" heading resembles the old wordmark styling _(this is also heavily used in sei/impact)_
2. "Learn about Mozilla" section uses favicon as its image, that may need updating from "m" to flag icon?

**Comment by janbrasna** [comment]
Also there are some languages that have trouble fitting into the grid elsewhere now with the type size changes:

- https://www-demo4.allizom.org/el/firefox/browsers/mobile/ios/

> <img width="862" alt="Screenshot 2024-12-04 at 0 52 18" src="https://github.com/user-attachments/assets/af05f617-74b2-40e7-8f64-e2abb12c417f">
