### ISSUE TITLE
Epic: Improve demo servers

### ISSUE THREAD

**Issue by stevejalim** [mozilla/bedrock#15578]
## Description

The Bedrock Demo servers/services on GCP Cloud Run need some improvements

---

#### Issues, ordered by priority
- [x] #15577
- [x] https://github.com/mozilla/bedrock/issues/15604
- [x] https://github.com/mozilla/bedrock/issues/12303
- [x] https://github.com/mozilla/bedrock/issues/9800
- [x] https://github.com/mozilla/bedrock/issues/11960

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/WT-291)
┆Priority: P2
┆Sprint: Backlog

**Comment by stevejalim** [comment]
Done for Bedrock and for Springfield
