### ISSUE TITLE
CasperJS Functional Tests Tracker

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/bedrock#3089]
Below is a list of all (well most) of the pages that make up mozilla.org

The intention here is to keep track of all of the pages and mark those that already have functional tests, [written using Casperjs](http://bedrock.readthedocs.org/en/latest/testing.html#writing-casperjs-tests), and those still in need of functional tests.

##Mozilla

- [x] https://www.mozilla.org/en-US/
- [x] https://www.mozilla.org/en-US/about/
- [x] https://www.mozilla.org/en-US/mission/
- [x] https://www.mozilla.org/en-US/newsletter/
- [x] https://www.mozilla.org/en-US/contact/spaces/
- [x] https://www.mozilla.org/en-US/about/history/
- [x] https://www.mozilla.org/en-US/plugincheck/
- [x] https://www.mozilla.org/en-US/styleguide/

##Community

- [x] https://www.mozilla.org/en-US/contribute/
- [x] https://www.mozilla.org/en-US/contribute/friends/
- [x] https://www.mozilla.org/en-US/contribute/events/
- [x] https://www.mozilla.org/en-US/contribute/stories/
- [x] https://www.mozilla.org/en-US/contribute/stories/faye/
- [x] https://www.mozilla.org/en-US/contribute/signup/

##Firefox OS

- [x] https://www.mozilla.org/en-US/firefox/os/2.0/
- [x] https://www.mozilla.org/en-US/firefox/os/devices/
- [x] https://www.mozilla.org/en-US/firefox/os/devices/tv/
- [x] https://www.mozilla.org/en-US/firefox/os/faq/

##Firefox

- [x] https://www.mozilla.org/en-US/firefox/tiles/
- [x] https://www.mozilla.org/en-US/firefox/partners/
- [x] https://www.mozilla.org/en-US/firefox/products/
- [x] https://www.mozilla.org/en-US/firefox/personal/
- [x] https://www.mozilla.org/en-US/firefox/new/
- [x] https://www.mozilla.org/en-US/firefox/android/
- [x] https://www.mozilla.org/en-US/firefox/sync/
- [x] https://www.mozilla.org/en-US/firefox/hello/
- [x] https://www.mozilla.org/en-US/firefox/dnt/
- [x] https://www.mozilla.org/en-US/firefox/developer/
- [ ] https://www.mozilla.org/en-US/firefox/desktop/
- [ ] https://www.mozilla.org/en-US/firefox/desktop/trust/
- [ ] https://www.mozilla.org/en-US/firefox/desktop/customize/
- [ ] https://www.mozilla.org/en-US/firefox/desktop/fast/

##Persona

- [ ] https://www.mozilla.org/en-US/persona/
- [ ] https://www.mozilla.org/en-US/persona/about/
- [ ] https://www.mozilla.org/en-US/persona/terms-of-service/

##Governance

- [ ] https://www.mozilla.org/en-US/about/governance/
- [ ] https://www.mozilla.org/en-US/about/governance/roles/
- [ ] https://www.mozilla.org/en-US/about/governance/policies/
- [ ] https://www.mozilla.org/en-US/about/governance/organizations/
- [ ] https://www.mozilla.org/en-US/about/leadership/
- [ ] https://www.mozilla.org/en-US/about/partnerships/
- [ ] https://www.mozilla.org/en-US/about/forums/

##Privacy

- [ ] https://www.mozilla.org/en-US/privacy/
- [ ] https://www.mozilla.org/en-US/privacy/firefox/
- [ ] https://www.mozilla.org/en-US/privacy/websites/
- [ ] https://www.mozilla.org/en-US/privacy/firefox/
- [ ] https://www.mozilla.org/en-US/privacy/firefox-os/
- [ ] https://www.mozilla.org/en-US/privacy/firefox-cloud/
- [ ] https://www.mozilla.org/en-US/privacy/firefox-hello/
- [ ] https://www.mozilla.org/en-US/persona/privacy-policy/

##Legal

- [ ] https://www.mozilla.org/en-US/about/legal/
- [ ] https://www.mozilla.org/en-US/about/legal/terms/mozilla/
- [ ] https://www.mozilla.org/en-US/about/legal/terms/services/
- [ ] https://www.mozilla.org/en-US/about/legal/terms/firefox-hello/
- [ ] https://www.mozilla.org/en-US/about/legal/terms/firefox/
- [ ] https://www.mozilla.org/en-US/about/legal/terms/thunderbird/
- [ ] https://www.mozilla.org/en-US/about/legal/fraud-report/

##Foundation

- [ ] https://www.mozilla.org/en-US/foundation/licensing/
- [ ] https://www.mozilla.org/en-US/foundation/trademarks/policy/

##Thunderbird

- [ ] https://www.mozilla.org/en-US/thunderbird/
- [ ] https://www.mozilla.org/en-US/thunderbird/features/
- [ ] https://www.mozilla.org/en-US/thunderbird/organizations/

## Components

- [x] Family Navigation

**Comment by schalkneethling** [comment]
One question I have on the above is whether we need to test *all* of the individual pages under `/styleguide/` or, whether we will just do some basic sanity checks across the most complex or representative of these. @alexgibson ?

**Comment by alexgibson** [comment]
> One question I have on the above is whether we need to test all of the individual pages under /styleguide/ or, whether we will just do some basic sanity checks across the most complex or representative of these. @alexgibson ?

The style guide pages are pretty basic - I think just one test suite for general things like the index page loads ok, nav is present etc should be enough. I think we probably want to avoid being overly specific if pages are very basic.

**Comment by alexgibson** [comment]
Closing this since we're no longer using CasperJS.
