### ISSUE TITLE
JS Unit Tests Tracker 

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/bedrock#3110]
# This is a WIP so expect lots of edits for a while

The following JS files still require unit tests:
## Base
- [ ] media/js/base/mozilla-accordion-gatrack.js
- [ ] media/js/base/mozilla-input-placeholder.js
- [ ] media/js/base/mozilla-modal.js
- [ ] media/js/base/mozilla-share-cta.js
- [ ] media/js/base/mozilla-video-poster.js
- [ ] media/js/base/mozilla-video-tools.js
- [ ] media/js/base/nav-main-resp.js
- [ ] media/js/base/nav-main.js
- [ ] media/js/base/svg-animation-check.js

**Comment by alexgibson** [comment]
Should we update this list to match what we covered in #3109?

**Comment by schalkneethling** [comment]
:+1:

**Comment by alexgibson** [comment]
@schalkneethling - I think writing unit tests for our common JS libraries and helpers in `base` makes good sense, but looking at the rest of this list I think most of it will be covered by functional tests soon. In a perfect world every JS file would be unit tested in some way, but realistically I can't see us rewriting everything here to make it so. I would like to propose updating this to cover our reusable code base, thoughts?

**Comment by schalkneethling** [comment]
You make a lot a sense :+1:

**Comment by alexgibson** [comment]
Closing out old issues
