### ISSUE TITLE
Transparency report updates

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5747]
https://www.mozilla.org/en-US/about/policy/transparency/

- [x] #1 - Create new transparency report for July-December 2017 with content [here](https://www.mozilla.org/en-US/about/policy/transparency/jan-jun-2017/)
- [x] #2 - Corresponding to #1: In https://www.mozilla.org/en-US/about/policy/transparency/ - Change text on button to “July-December 2017 Report”
- [x] #3 - add new Question to [FAQ](https://www.mozilla.org/en-US/about/policy/transparency/#faq ) according to spec [here](https://docs.google.com/document/d/1eXoZbq2apake2e2onL5YHbchu_7zpCb5bks6yoD7S6I/edit)

**Comment by stephaniehobson** [comment]
We were asked to revert this and wait until July 3 to launch.

**Comment by alexgibson** [comment]
This is up on demo https://bedrock-demo-agibson.oregon-b.moz.works/en-US/about/policy/transparency/jul-dec-2017/

**Comment by jgmize** [comment]
https://www.mozilla.org/en-US/about/policy/transparency/ now has errors since https://github.com/mozilla/bedrock/pull/5848 went into production:

NoReverseMatch: Reverse for 'mozorg.about.policy.transparency.jul-dec-2017' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

**Comment by jgmize** [comment]
the errors appear to be the result of the switch `transparency-report-030618` being unset or false: https://github.com/mozilla/bedrock/pull/5848/files#diff-71245d0bee3444a747f3251f25fc59a4R317
