### ISSUE TITLE
Nav / IA project status tracking card

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5960]
This card is used to monitor the overall project status of implementing a new Navigation based on a revised Information Architecture for www.mozilla.org

[The Nav / IA project board](https://github.com/mozilla/bedrock/projects/8)

Success Criteria:
- [ ] Must go live with update to the footer
- [ ] Must go out as a test, behind a switch for easy shut off
- [ ] Monitoring plan is in place at launch of test

**Comment by michaelmccombie** [comment]
Dependent on https://github.com/mozilla/protocol/issues/182

**Comment by thejeffreytaylor** [comment]
Dropping documentation links in here: 

[Nav demo](https://demo2--mozilla-protocol.netlify.com/demos/navigation.html)

[IA/Nav Outline (using existing content](https://docs.google.com/document/d/1cHrYCrS93TEvCEkL0bd3gf4mCtPbM-xNtGe6GDndPYc/edit?usp=sharing))

[Round 1 IA/Nav Outline](https://demo2--mozilla-protocol.netlify.com/demos/navigation.html) that included pages that need to be built (needs a revision, as we stopped revising on this doc - pining @djst as this could provide a partial roadmap for future durable team work on pages and taxonomy)

[User Testing Notes ](https://docs.google.com/spreadsheets/d/1J1ZA0D5tfA4e8haNAVvQXcMxinOGR8qsmMCDYTCmMCA/edit?usp=sharing)(currently in progress, should be completed by EOD 7 August)

**Comment by thejeffreytaylor** [comment]
Adding [WIP IA/Nav KPI sheet.](https://docs.google.com/document/d/1w3BMTkYJrSwBDOzyP5-NBxRdZ9_l7U7FsX8Nzc3JgvE/edit?usp=sharing)

**Comment by thejeffreytaylor** [comment]
Adding [WIP KPIs for the redesign](https://docs.google.com/document/d/1w3BMTkYJrSwBDOzyP5-NBxRdZ9_l7U7FsX8Nzc3JgvE/edit?usp=sharing)

**Comment by ejregithub** [comment]
@michaelmccombie to deliver icon updates today

**Comment by ejregithub** [comment]
@djst to send out demo branch for feedback on nav.

**Comment by ejregithub** [comment]
Blocked by footer update #6104

**Comment by alexgibson** [comment]
@ejregithub I don't think the nav work necessarily needs to be blocked by the footer. It's behind a switch, so we can review, merge any time independently of the footer.

**Comment by djst** [comment]
Let's push this out, then?

**Comment by ejregithub** [comment]
@alexgibson - if it doesn't great. I was led to believe it did.  Let's confirm with the team during stand-up to be sure there are no objections.

**Comment by alexgibson** [comment]
No, what I mean is there's nothing blocking us from finishing the nav and merging it. The footer is a separate piece of work. But both should be in place before we flip the switch to start the test.

Either way, I don't see why this card needs to be blocked.

**Comment by ejregithub** [comment]
Agreed. I've noted the dependency(in Success Criteria) on the footer for go live of the test.

**Comment by alexgibson** [comment]
The nav is live. We still need to update the footer, but that's being tracked in https://github.com/mozilla/bedrock/issues/6104
