### ISSUE TITLE
About page project status tracking card

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#5961]
This card is used to monitor the overall project status of implementing updates to the About page on www.mozilla.org 

[The About project board](https://github.com/mozilla/bedrock/projects/7)

### Assets
[City Illustration Gifs](https://mozilla.box.com/s/k8bm62z3g31wvdko69fld5crovnr7b4r)

### Mock-ups
[Sketch File](https://share.goabstract.com/25d3bf4b-7df6-48eb-8dda-b2efa0d501b7)

### Copy
[Copy Deck](https://docs.google.com/document/d/18jVD7utz_5NeJpbQf5koBayqvaBXlhcAtTRS0lSSK64/edit)

**Comment by michaelmccombie** [comment]
Here is a link to the city assets (animated gifs) that James created.
https://mozilla.box.com/s/k8bm62z3g31wvdko69fld5crovnr7b4r

**Comment by stephaniehobson** [comment]
@michaelmccombie I do not have access to box and have been told as a developer I do not need it and will not be given an account. Could you put the assets somewhere else please?

**Comment by michaelmccombie** [comment]
@stephaniehobson sorry about that, I didn't realize that Box access wasn't available for the developers on our team. Here is a zip folder with those assets:
[city-illustrations.zip](https://github.com/mozilla/bedrock/files/2247041/city-illustrations.zip)

**Comment by stephaniehobson** [comment]
Here's the copy deck: https://docs.google.com/document/d/18jVD7utz_5NeJpbQf5koBayqvaBXlhcAtTRS0lSSK64/edit

**Comment by stephaniehobson** [comment]
@dzingeek Is the `About Page` branch in Abstract the right place to be looking for designs?

**Comment by dzingeek** [comment]
@stephaniehobson link to sketch file in abstract below. note: @mrkwvr (mark) is working on the hero graphic

https://share.goabstract.com/f0ee2ac8-06bc-44c2-962b-1edfdec97313

Also, box is still good for assets. @michaelmccombie you need to make sure that the files are shareable to anyone who has the link. Box defaults to private.

**Comment by michaelmccombie** [comment]
Thanks, Jennifer. @stephaniehobson this Box link should work now:

**Comment by stephaniehobson** [comment]
Thanks, I have what I need now :)

**Comment by stephaniehobson** [comment]
@ejregithub I see that we're not planning to localize this new page. The current about page is one of the most translated pages on the site. Will we localize this page in the long run? Is there a requirement to keep the old content around and serve it to other locales?

**Comment by ejregithub** [comment]
@stephaniehobson - the only reason not to localize now is that more iterations to the page are expected (there are 10 more users stories in the backlog of the [project](https://github.com/mozilla/bedrock/projects/7)  ).  We do need to keep serving up the current content for other locales.  I do think, and we need @djst 's input on this, if we don't continue on those stories and iterate within a reasonable span of time (perhaps a month?) we should then tag it for l10n.

**Comment by stephaniehobson** [comment]
I've completed all the coding I can do with what I have.

Waiting on:
- Approval of the Protocol addition: https://github.com/mozilla/protocol/pull/197
- The hero image.

**Comment by ejregithub** [comment]
@mrkwvr - please add/link to the hero image for the About page here when you have it.

**Comment by stephaniehobson** [comment]
I have the hero image from Mark.

**Comment by stephaniehobson** [comment]
I submitted https://github.com/mozilla/bedrock/pull/5973

The site is on demo here: https://bedrock-demo-about.oregon-b.moz.works/en-US/about/

⚠️ 2 small lines of text are missing pending mozilla/protocol#197 I believe it is ready for review without these :)

**Comment by thejeffreytaylor** [comment]
@dzingeek and I are reviewing this today, 6 August, and will have feedback ready when @stephaniehobson returns from holiday tomorrow.

**Comment by dzingeek** [comment]
@stephaniehobson edits and tweaks below. reach out w/any questions.

**Our Mission Section**
- [ ] - CTA should go to https://www.mozilla.org/en-US/mission/
- [ ] - space between the cards in “our mission in action” section feel tight. If it doesn’t already it should match the spacing of the cards on the homepage. https://screenshots.firefox.com/n7ZtMOPJsBpin203/bedrock-demo-about.oregon-b.moz.works
- [ ] - Add space (about 120px) to bottom of “our mission..” section and top of the corporate section https://screenshots.firefox.com/GTjw2YyhnKRquiux/bedrock-demo-about.oregon-b.moz.works

**Foundation Section**
- [ ] - Add space (about 120px) to bottom of foundation section and top of manifesto section https://screenshots.firefox.com/z8SalnLzkXfCAwDK/bedrock-demo-about.oregon-b.moz.works

**A Global Space Section**
- [ ] - Copy should be centered https://screenshots.firefox.com/WT2B1Cn3A8k2fGmh/bedrock-demo-about.oregon-b.moz.works
- [ ] - Link “offices all over the world” (also use are default text link style) to https://www.mozilla.org/en-US/contact/spaces/
- [ ] - Headline should be the same size as “The Mozilla Manifesto” size https://screenshots.firefox.com/IDLAjwFOrqEXz5wH/bedrock-demo-about.oregon-b.moz.works

- [ ] - Each “card” should link to those locations
- San Fran = https://www.mozilla.org/en-US/contact/spaces/san-francisco/
- Berlin = https://www.mozilla.org/en-US/contact/spaces/berlin/
- Taipei = https://www.mozilla.org/en-US/contact/spaces/taipei/
- Toronto = https://www.mozilla.org/en-US/contact/spaces/toronto/

- [ ] - Add space (about 120px) between the bottom of the “global view” section and the top of the “Work and help” cards https://screenshots.firefox.com/KjcmZfiyQUleMYPc/bedrock-demo-about.oregon-b.moz.works

**Work at Moz and Help Section**
- [ ] - Add space (about 100px) below cards and above Mozilla newsletter sign up section


_Link to latest copy deck just for reference. No changes other than what is mentioned above. 
https://docs.google.com/document/d/18jVD7utz_5NeJpbQf5koBayqvaBXlhcAtTRS0lSSK64/edit?usp=sharing_

**Comment by stephaniehobson** [comment]
Blocked on a replacement image for the Firefox OS image for "Get Involved."

Also, do we have a high quality image for the IRL image? What's in the Sketch file is not high enough quality for high res.

**Comment by stephaniehobson** [comment]
Got a replacement IRL image.

**Comment by dzingeek** [comment]
@stephaniehobson let's just keep the image as is for the get involved section (ios blue shirt guy).

**Comment by ejregithub** [comment]
@stephaniehobson - when you can, please update the page on demo.  I suspect @djst will be shopping this to stakeholders on Monday/Tuesday

**Comment by stephaniehobson** [comment]
The most recent version of the code is on the demo site. https://bedrock-demo-about.oregon-b.moz.works/en-US/about/
