### ISSUE TITLE
Lean Data - Content

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6095]
Content size =  1 days

[Copy doc](https://docs.google.com/document/d/1NBKCDZt8PJjPXP1yHNOozKx7ChUMYfAMIreTNpURH0g/edit?usp=sharing)

**Tasks**
- [x] [Landing Page Content]
- [x] [Stay Lean Content]
- [x] [Build Security Content]
- [x] [Engage Users Content]
- [x] Resources Content

**Comment by thejeffreytaylor** [comment]
I did the thing and the other thing. @michaelmccombie has been briefed on [what's going on with the doc](https://docs.google.com/document/d/1NUI2aBMxfVExCzBO7lbMzzimiNPY0ui17O0e5n0S1Io/edit?usp=sharing), and where we need some guidance from Mika.

**Comment by dzingeek** [comment]
The doc Jeffrey did was a bit confusing as all pages were in one doc. I broke those pages up into 4 docs (links in tasks). 

We still need content from Mika on the Resources page.

@ejregithub please see above comment and we should get Natalie in on this copy, Mark and I are worried about the length of some things. Then we will need Mika to review all copy docs.

**Comment by dzingeek** [comment]
Natalie is going to re-work the copy and have something to us wed/thurs this week.

**Comment by dzingeek** [comment]
Still waiting on updated copy. Not sure how much it will impact design or ux, hopefully not much.

**Comment by dzingeek** [comment]
[latest copy doc ](https://docs.google.com/document/d/1NBKCDZt8PJjPXP1yHNOozKx7ChUMYfAMIreTNpURH0g/edit?usp=sharing)

**Comment by dzingeek** [comment]
Link for Toolkit CTA
https://docs.google.com/document/d/1TJafYmeFT3LIQe6YPLEHWwh37PGbK2RunntDIaN2lL8/edit?usp=sharing
