### ISSUE TITLE
Lean Data - UI

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6097]
UI/Design size =  3 days

**Tasks**
- [x] Visual Design for Landing Page
- [x] Visual Design for other pages (template)
- [x] Design Review : Creative
- [x] Design Review  : Dev.
- [ ] Design Review : Stakeholder
- [ ] Packages Assets
- [ ] Dev Handoff

**Comment by dzingeek** [comment]
@mrkwvr copy decks have been broken out. we are still waiting on the last one resources, but that should not impact you. 

See github issue for copy deck links.
https://github.com/mozilla/bedrock/issues/6095

**Comment by dzingeek** [comment]
Mark and I are working on the design but we are still waiting on updated copy, which could impact what we have so far.
