### ISSUE TITLE
Lean Data - Dev

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6099]
Dev size =  5 days

**Tasks**
- [x] Code main page
- [x] Code template
- [x] Code content in template for page 1of4
- [x] Code content in template for page 2of4
- [x] Code content in template for page 3of4
- [x] Code content in template for page 4of4
- [ ] Review : Creative
- [ ] Review : Stakeholder
- [ ] Code : Stakeholder

**Comment by dzingeek** [comment]
[sketch file ](https://share.goabstract.com/f52097fc-127a-4c68-b62c-40fadbbf651f)

@craigcook 
Just a quick note, small tweaks are still happening with this file..mostly just around the images. Will get those assets to you shortly.

**Comment by dzingeek** [comment]
[Copy doc](https://docs.google.com/document/d/1NBKCDZt8PJjPXP1yHNOozKx7ChUMYfAMIreTNpURH0g/edit?usp=sharing)

**Comment by dzingeek** [comment]
@craigcook here are the assets for the lean data pages. 
[lean-data-assets.zip](https://github.com/mozilla/bedrock/files/2429813/lean-data-assets.zip)

_Note: will have small the small illustrations for v2 next week._

**Comment by dzingeek** [comment]
here are updated transparent hero images
[lean-data-hero-assets.zip](https://github.com/mozilla/bedrock/files/2429911/lean-data-hero-assets.zip)

**Comment by craigcook** [comment]
On demo https://bedrock-demo-craigcook.oregon-b.moz.works/about/policy/lean-data/

**Comment by dzingeek** [comment]
Here is the link for the Toolkit CTA
https://docs.google.com/document/d/1TJafYmeFT3LIQe6YPLEHWwh37PGbK2RunntDIaN2lL8/edit?usp=sharing

**Comment by dzingeek** [comment]
Please add Contact Us (call out compact component) to the secondary pages. See screenshot for reference. 

![screen shot 2018-10-01 at 1 32 45 pm](https://user-images.githubusercontent.com/3740746/46314342-1cd46480-c57f-11e8-9095-0de38b319538.png)

**Comment by alexgibson** [comment]
This looks like it was merged, but the issue was never closed.
