### ISSUE TITLE
[10/16] WNP 63

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6156]
Latest updates to the /whatsnew page for the 63 release

[Master Project Doc](https://docs.google.com/document/d/1UAPeYEApfyzaAOk7OmYEvcJwM8_wVl-VKHlnhF-aecc/edit)

**Success Criteria:**
- [x] Page is live 10/16 the Tuesday prior to product release 
- [x] Copy is in PR for l10n on Wednesday Sept 19th 

**Tasks:**
- [x] Data Collection
- [x] Flow documentations + exploration for new proposed flow
- [x] Copy - Natalie
- [x] Design - Mark
- [x] Team QA of design - Jennifer
- [x] Stakeholder QA of design - Eric
- [x] Code - Alex
- [x] Team QA of coded page on demo
- [x] Stakeholder QA of coded page on demo - Eric

[Pull request](https://github.com/mozilla/bedrock/pull/6195)

**Comment by dzingeek** [comment]
Here is a link to the data that Raphael and Alex gathered. 
https://docs.google.com/spreadsheets/d/1tn9Uml8UUIKctVR0NcVV9flLJ2ZYVU3qFYC72zz5iyA/edit?usp=sharing

**Comment by dzingeek** [comment]
**Current Flow**
![whatsnew63_userflow_current](https://user-images.githubusercontent.com/3740746/45382812-445a9180-b5be-11e8-80aa-a2406dece10b.png)

**Comment by dzingeek** [comment]
**Approved (08.11.18) New Flow** 
![whatsnew63_userflow_proposed_opt1](https://user-images.githubusercontent.com/3740746/45382832-5b00e880-b5be-11e8-962f-bb7fd26d3d19.png)

**Comment by ejregithub** [comment]
[WNP 63-NL_091718.pdf](https://github.com/mozilla/bedrock/files/2390033/WNP.63-NL_091718.pdf)

**Comment by ejregithub** [comment]
Noting that stakeholder (Michele Warther) QA of the WNP 63 page on demo is complete and approved.  I just spoke with her and she confirmed (10/10)

**Comment by ejregithub** [comment]
@alexgibson - please coordinate code review with another developer so we can launch this page on Wed the 17th (so Softvision can QA test). It can go sooner if it's ready.

**Comment by ejregithub** [comment]
@alexgibson - Analytics Pros is going to QA the page and reply here.  They're aware of the time constraints for launch on 10/23.

**Comment by alexgibson** [comment]
@ejregithub the ask is to have this in production for 10/16. I don't think we can wait any longer for AP here, so we may need to revisit if there are any GA changes needed.

**Comment by rbwinters** [comment]
@alexgibson the spec link has been added in the project tracker (google sheet). Once implemented, let us know and we can do a quick QA. Thanks!

**Comment by alexgibson** [comment]
All this work is now complete, and AP have signed off QA for the page. Closing this epic, and retiring the sub-board.
