### ISSUE TITLE
WNP 63 - UX

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6157]
**Resources**
[Master Product Doc](https://docs.google.com/document/d/1UAPeYEApfyzaAOk7OmYEvcJwM8_wVl-VKHlnhF-aecc/edit)

**Todos**
- [x] create flow diagram
- [x] get signoff from dev team
- [x] get signoff from stakeholders

**Comment by dzingeek** [comment]
**Current Flow: All Conditions:
![whatsnew63_userflow_current](https://user-images.githubusercontent.com/3740746/45382812-445a9180-b5be-11e8-80aa-a2406dece10b.png)

**Comment by dzingeek** [comment]
**Approved (08.11.18) New Flow** 
![whatsnew63_userflow_proposed_opt1](https://user-images.githubusercontent.com/3740746/45382832-5b00e880-b5be-11e8-962f-bb7fd26d3d19.png)

**Comment by alexgibson** [comment]
@dzingeek can we expect any new Protocol components to be required for this page? We need to thik about creating cards for that work if so. Happy to discuss in person to identify if anything is needed here.

**Comment by alexgibson** [comment]
Can this issue now be moved to the done column?

**Comment by dzingeek** [comment]
I say yes, will move over now.
