### ISSUE TITLE
WNP 63 - UI

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6158]
**Resources**
- [(copy doc)](https://github.com/mozilla/bedrock/issues/6159)
- [flow diagram](https://github.com/mozilla/bedrock/issues/6157#issuecomment-420459794)

**Todos**
- [x] visual design for fxa not signed in condition.  
       - "snippet" style section that highlights account login + sign up
       - focus on privacy messaging
- [x] visual design for fxa signed in condition. 
       - same as above minus "snippet"
- [x] design review (creative + keep devs in the loop)
- [x] identify any new Protocol components
- [x] stakeholder review
- [x] package assets for devs

**Comment by alexgibson** [comment]
@dzingeek @mrkwvr can we expect any new Protocol components to be required for this page? We need to thik about creating cards for that work if so. Happy to discuss in person to identify if anything is needed here.

**Comment by alexgibson** [comment]
Ok, there may already be components we have in bedrock which haven't been back ported to Protocol yet, like the FxA email form. I think we should at least track that work and make sure we create issues for whatever might need doing (even if it doesn't block the work for 63). Thanks

**Comment by alexgibson** [comment]
@mrkwvr Is there a due date when we can expect design to be ready for?

**Comment by dzingeek** [comment]
@alexgibson Since Mark is in training today and tomorrow I will be working on this. Trying to get this approved by tomorrow. I would say we are pretty close so you can start, I will get you assets as soon as it's approved. 

Also, let's sync up on it tomorrow morning, I have a quick question.

**Comment by dzingeek** [comment]
The design was approved by Michele in the slack channel at 10:48 am on 09.26.17

**Comment by dzingeek** [comment]
@alexgibson 
[wnp 63 sketch file](https://share.goabstract.com/b1b28993-132c-41a0-8a49-f915128bcf38)
[wnp 63 assets.zip](https://github.com/mozilla/bedrock/files/2421504/wnp.63.assets.zip)

**A few things to note:**
- Built-In Tracking... **Learn More** link should go to about:preferences#privacy
- Secure Syncing...**Learn More** link should go to https://www.mozilla.org/en-US/firefox/accounts/features/
- Sketch file should have examples of breakpoints, these are just for reference.
