### ISSUE TITLE
Dev: Pocket Landing Pg > Update Images

### ISSUE THREAD

**Issue by dzingeek** [mozilla/bedrock#6234]
Found some issues with the images and the illustrator asked us to update them. 

[pocket-updated-imgs.zip](https://github.com/mozilla/bedrock/files/2435102/pocket-updated-imgs.zip)

**Todos:**
Upadate all images on page
- [ ] Update Hero Img 
- [ ] Update Reading Img
- [ ] Update Save Img
- [ ] Update Discover Img
- [ ] Update Mobile Img

**Comment by dzingeek** [comment]
After looking into the correct image sizes I noticed we were missing some high res images, so I also included those. Please update all images.

**Comment by alexgibson** [comment]
Oops, I didn't notice this was already assigned to @craigcook as It was still in the ready column. I'm gonna re-assign as this was only a small task.
