### ISSUE TITLE
Copy Change Per Legal Request: Remove the word "Truly" from "Truly Private Browsing.."

### ISSUE THREAD

**Issue by dzingeek** [mozilla/bedrock#6299]
Legal would like us to remove the word 'Truly' from 'Truly Private Browsing..." on any page it appears. They specifically called out /new and /new variations. 

**Tasks**
- [ ] Research where this change needs to take place
- [ ] Scope this change...assuming it will need to be localized as well
- [ ] Check /firefox/campaign for this string.
- [ ] Change copy to...
       "Private Browsing with Tracking Protection"
- [ ] Check /firefox/campaign for this string.
- [ ] Tag for L10n

**Comment by dzingeek** [comment]
Image for reference
![screenshot_2018-10-15 download the fastest firefox ever](https://user-images.githubusercontent.com/3740746/46983367-078a2a80-d095-11e8-9301-bfebb9a9cfc2.png)

**Comment by craigcook** [comment]
I can only find this phrase on three pages:

[/firefox/templates/firefox/new/base.html](https://github.com/mozilla/bedrock/blob/db1c75bf8e2ecde4dd679e865c664919ac1c938a/bedrock/firefox/templates/firefox/new/base.html#L91)
[/firefox/templates/firefox/recommended.html](https://github.com/mozilla/bedrock/blob/db1c75bf8e2ecde4dd679e865c664919ac1c938a/bedrock/firefox/templates/firefox/recommended.html#L62)
[/firefox/templates/firefox/new/yandex/base.html](https://github.com/mozilla/bedrock/blob/db1c75bf8e2ecde4dd679e865c664919ac1c938a/bedrock/firefox/templates/firefox/new/yandex/base.html#L90)

**Comment by stephaniehobson** [comment]
@ejregithub Looks like this fell through the cracks, but it's a legal thing. We should get it back on the radar.
