### ISSUE TITLE
Accounts Benefits Page

### ISSUE THREAD

**Issue by bensternthal** [mozilla/bedrock#6339]
| Estimates |  |
| ------------- | ------------- | 
| TL | 5|
| PM | 12|
| ENG | 60|
| SEO | 0|
| ANA | 8|
| DES | 60|
| COPY | 40|

Description, good enough that reading the card 1 month from now, you still know what it means.

---

#### :yellow_heart: Success Criteria :yellow_heart:

- [x] We've determined which page it replaces/kills
- [x] The other page (non-winner) is redirected here
- [x] A user understands what product services work w. an account
- [x] Launch to en-US
- [x] Page must be localizable at launch
- [x] Visuals (not animated)
- [x] Visuals that explain benefits clearly to English and non-English speaking users
- [ ] Build in Protocol w. new components added
- [ ] Protocol code/design review
- [ ] Conditional CTA based on audience - download or signup/in
- [ ] User understands what an account is
- [ ] Maintainable addition and removal of benefits
- [ ] Design and coded page must be approved by the team and the Approver
- [ ] Analytics QA
- [ ] Legal Approval
- [ ] Increased proportion of traffic to the page
- [ ] a user understands why an account is beneficial
- [ ] Uses Raphael's SEO keyword recommendations
- [x] Links out to each product/services
- [ ] Animation similar to the device sync animation on the old sync page)
- [x] Animations / visuals do not include text

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] What will trigger updates?

#### Tasks
- [ ] UX - @dzingeek 
- [ ] Write copy - @clay-chaffin 
- [ ] Design (create design) - @mrkwvr 
- [ ] Code - @amychurchwell 
- [ ] QA testing of design (the team)
- [ ] QA testing of design (Approver)
- [ ] QA testing of coded page on demo (the team)
- [ ] QA testing by Analytics
- [ ] QA testing of coded page on demo (Approver)

**Comment by ejregithub** [comment]
Blocked by lack of info/data/research in https://github.com/mozilla/bedrock/issues/6344

**Comment by amychurchwell** [comment]
#6345 -- **final URL**: /firefox/benefits

Redirects - https://github.com/mozilla/bedrock/issues/6345#issuecomment-435737625

**Comment by dzingeek** [comment]
Latest designs can be found here. 

[Desktop View: FxA CTA (Full Design)](https://mozilla.box.com/s/1kkfvxw2dq5xps82m3j7hpyt3lpakjng)
[Mobile View: FxA CTA (Full Design)](https://mozilla.box.com/s/ox68mk22m69exbfb0s9eeck47eey6qad)
[Desktop View:  Fx Download CTA](https://mozilla.box.com/s/chbkxhy484lnhd8vwkk891dgq1vwzd35)
[Desktop View:  Fx Mobile App Download CTA](https://mozilla.box.com/s/5shj1ibryozgunkbt8no37uiyry2lhu3)
[Mobile View: Fx Mobile App Download CTA](https://mozilla.box.com/s/5zoo18xmlemtdbw6mzap73ycmz3wfnek)

**Comment by dzingeek** [comment]
Design Assets
[_fxa assets.zip](https://github.com/mozilla/bedrock/files/2573477/_fxa.assets.zip)

**Comment by ejregithub** [comment]
@amychurchwell - here's the QA review - 
[Mozilla_ FxA Page QA 11.28.2019 (1).pdf](https://github.com/mozilla/bedrock/files/2630903/Mozilla_.FxA.Page.QA.11.28.2019.1.pdf)
