### ISSUE TITLE
Remove jQuery as a dependency from Protocol base template

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6504]
All Protocol components use vanilla JS and have zero dependencies, but jQuery is still bundled in the Protocol base template due to legacy scripts in bedrock.

It would be great to eliminate jQuery from these dependencies, so we can lighten the overall JS payload across the site. We could do this by porting the following files to vanilla JS (or by removing them entirely):

- [x] `js/base/mozilla-utils.js`
- [x] `js/base/mozilla-image-helper.js` (I don't think this is being actively used on any Protocol pages)
- [x] `js/base/nav-main-resp.js` (can be removed once we localize the new navigation)
- [x] `js/base/base-page-init.js`
- [x] `js/base/core-datalayer.js`
- [ ] `js/base/core-datalayer-init.js`
- [x] `js/base/search-params.js`
- [ ] `js/base/stub-attribution.js`

Note: we may still want to keep a version of jQuery around to serve to [legacy IE](https://github.com/mozilla/bedrock/blob/master/bedrock/base/templates/base-pebbles.html#L178-L180), but that should be fine as it's in a conditional comment.

**Comment by stephaniehobson** [comment]
Could I do this? I've been wanting a chance to really focus on JS.

**Comment by alexgibson** [comment]
Go for it 👍

**Comment by stephaniehobson** [comment]
@agibson What is our minimum viable browser support for these files?

**Comment by alexgibson** [comment]
Most of the dependencies in this issue were resolved, however a couple still remain. Digging deeper, there are still more pieces of legacy code that aren't covered here. I'm going to close this issue and open new issues for the remaining places.
