### ISSUE TITLE
Translate /vi/, /vi/firefox/ and /vi/firefox/new/

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#6579]
We lost the translations of the core pages in Vietnamese during the quantum launch and this caused a 35% fx-desktop-download decline of non-fx-users in Vietnam YoY. 

As around 75% of all downloads in Vietnam are from organic search, we should translate the core pages /vi/, /vi/firefox/ and /vi/firefox/new/ to regain rankings, traffic and eventually downloads. FOr search its necessary that all three pages exist, otherwise it would have been maybe enough to translate just /new/.

[Opportunity in numbers.](https://docs.google.com/document/d/1LHdx9SagQjvX9xB8CWwz-HfJi611uOK97mWq26d4yuA/edit?usp=sharing)

Maybe just a couple of strings are missing, maybe we need a complete translation. We should reach out to the community but even if they will not find time for this, we should look for a agency, as the numbers in the doc above indicate that this is a opportunity worth even paying for.

### To-Do

- [ ] check status of existing translations with community

- [ ] translate /vi/

- [ ] translate /vi/firefox/

- [ ] translate /vi/firefox/new/

**Comment by gueroJeff** [comment]
We'll follow up with the Vietnamese community (currently consists of one localizer) and raise the priority level for these in Pontoon. Unfortunately, the moz.org l10n infrastructure prevents us from being able to send this content out to a vendor (the .lang format alone locks us out).

Is Vietnamese the only locale that has experience fx-desktop-download decline? Are you in the process of auditing that for all locales?

**Comment by gueroJeff** [comment]
@peiying2 is looking into what happened here. It looks like the community has translated the content and /vi/ is live in production. Still looking into what we're missing for /firefox/ and /firefox/new/

**Comment by peiying2** [comment]
They have been quite busy catching up the pending tasks: https://pontoon.mozilla.org/vi/mozillaorg/. Sort by latest activities, you will see what they have completed just this week. I have just made a production push.

**Comment by stephaniehobson** [comment]
🇻🇳 ❤️

**Comment by ejregithub** [comment]
Sorry (voice texted that last email): RaPHael.

**Comment by rraue** [comment]
Seems like all three pages are live. Thank you so much everyone and especially the community. And it seems to work:
<img width="812" alt="screen shot 2018-12-17 at 16 21 45" src="https://user-images.githubusercontent.com/36700618/50097046-4bc2b400-0219-11e9-8eb7-5a12e500b6f5.png">
Conversion rate is up 10% on /vi/firefox/new/ compared to /firefox/cahnnel/desktop/. Only three days to compare, but that looks very promising. Overall conversion rate went up by 20% and organic fx-desktop downloads even 21% up.

**Comment by gueroJeff** [comment]
Thanks Raphael. I think there's value in evaluating each locale and taking
data on the opportunity cost of not having these pages localized. Any data
that helps us draw a line between localization and ROI (and this seems like
a pretty clear-cut line) would be helpful.

**Comment by rraue** [comment]
@gueroJeff And answering your question, the only other locale with problems like that is /my/ but there its not such an issue as English is offical language in my knowledge and conversion rates on /en-US/firefox/new/ from malaysia confirm that.

**Comment by gueroJeff** [comment]
I'm a bit surprised to hear that. Arabic is a good example of where there's
a lot of opportunity but the community often let's pages like this go to
en-US for months at a time.

**Comment by rraue** [comment]
We haven't changed these three pages in a while. But to be fair I checked only locales existed before based on decline, I might want to reverse this and do it by country in GA and see which non english countries have the most traffic/downloads on /en-US/.

**Comment by ejregithub** [comment]
@rraue - please confirm that we can close this issue.

**Comment by peiying2** [comment]
https://pontoon.mozilla.org/vi/mozillaorg/ - the team has completed all the pages in the last few weeks.
