### ISSUE TITLE
DE version of en-US www homepage

### ISSUE THREAD

**Issue by djst** [mozilla/bedrock#6585]
| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | 3 days |
| SEO | |
| ANA | |
| DES | |
| COPY | |

Description: We need the equivalent of the en-US homepage for German, meaning, the same template, same ability to curate "cards" linking to German blog posts.

From a dev point of view, this is likely fairly straightforward since we'll be reusing the en-US templates with some new configurations.

From a design point of view, we're reusing the design as is. Only changes might be the lack of a Pocket feed, but that should be minimal design work.

From a copy point of view, l10n should come from the Marketing team, meaning, Clay won't need to be engaged here. 

From a SEO point of view, there may be work to identify appropriate keywords, tags etc. 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of success criteria. Use a checklist!
- [ ] This is an example of success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of risk. Use a checklist!
- [ ] This is an example of risk.

#### Tasks
- [ ]

[Master project doc](https://docs.google.com/document/d/10wvOenVYQM7CpZIaVU5y_5TqpIz3stC093D5DM4EfHI/edit#)
- Includes link brief, seven sheets, decision log, meeting notes, etc
------

**Comment by ejregithub** [comment]
Contexting session is booked for Monday Jan 28th

**Comment by alexgibson** [comment]
Blocked on content

**Comment by alexgibson** [comment]
@ejregithub what was the due date for delivering this content? I seem to remember the team thought they could deliver it last Friday (since they wanted it live within a week). Can you check what the status is here? Thanks

**Comment by ejregithub** [comment]
@alexgibson - see here (it’s the 2/6/2019 Edition) in [Airtable](https://airtable.com/shrsePL6DurBLe9mg/tblgNmPLbDjXxeViI/viwYLv28cjNOdZMm0?date=2018-06-16&mode=month)

And here is the sheet with all the content: ([content is in tab 1 + banners are in tab 2](https://docs.google.com/spreadsheets/d/1gLv1pfj7TIuGXZyPnzi3iwdG0heYVpID1HWe4wrLT3c/edit?ts=5c5c56da#gid=1177271466))

**Comment by alexgibson** [comment]
Great, picking this one up today 👍

**Comment by alexgibson** [comment]
WIP of this is now up on demo: https://bedrock-demo-agibson.oregon-b.moz.works/de/

We're still missing some translations:

**Untranslated strings:**
* Page title `Internet for people, not profit`
* Page description `Mozilla is the not-for-profit behind the lightning fast Firefox browser. We put people over profit to give everyone more power online.`
* Manifesto banner link text `Learn more about us`.
* Bottom download CTA (non-FF users)
    * Title `Supporting a healthy internet is easy.`
    * Description: `Get started by browsing with Firefox powered by Mozilla.`
* Bottom Firefox Accounts CTA (FF-users)
    * Title: `The account that protects you rather than profits off you.`

**Missing strings:**
* Technology banner link copy
* Newsletter title, subtitle and button copy

**Comment by alexgibson** [comment]
Blocking this on missing strings.

**Comment by alexgibson** [comment]
We now have all required copy, so removing the blocker.

**Comment by alexgibson** [comment]
We're still blocked on some final imagery.
