### ISSUE TITLE
Stocktake of active experiments

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6669]
Below is a list (in no particular order) of all experiments in the bedrock code base. Some have been running for a long time, and we've never made a decision on them or followed up. Others may not have enough data yet to be conclusive, and some are inactive and probably just need clean up.

- [x] 1. Feature page A/B test without main header (Issue #6155). The code exists in bedrock but I can't see the switch enabled in production. Was this experiment ever run?
- [x] 2. Pre-download experiment rerun (Issue #6456). We've finished the rerun of this experiment for English locales, but the experiment is still running for Germany and France.
- [x] 3. Firstrun copy experiment ([bug 1451051](https://bugzilla.mozilla.org/show_bug.cgi?id=1451051)). This is an old page, and the experimet is inactive. Not sure if we ever followed up on it, but the code and templates can likely all be removed.
- [x] 4. SEM browser compare experiment for Chrome (Issue #5952). Experiment is active in production and has been running for a long time.
- [x] 5. SEM browser compare experiment for Edge (Issue #5951). Experiment is active in production and has been running for a long time.
- [x] 6. SEM browser compare experiment for Opera (Issue #6130). Experiment is active in production and has been running for a long time.
- [x] 7. SEM browser compare experiment for Internet Explorer (Issue #6466). Same as above, but has been running for less time. 
- [x] 8. We're also actively serving a Facebook video chat funnelcake to users who visit /firefox/ from a FB referrer (#6206). This has been running for a long time. Given that users cannot easily update their funnelcake build via the regular FF update channel, is serving a long running funnelcake like this benefiting aDAU, or harming it?
- [x] 9. Experiment to add FxA CTA to /new (Issue #6173). Active in production and has been running for a long time.
- [x] 10. Yandex experiment on /ru/firefox/new/ (Issue #6300). This is still running, and nobody knows quite what to do with it, or if it's something we want to continue doing long term.

I think that's it, but I'll add more if / when I come across them.

**Comment by alexgibson** [comment]
10. We're also actively serving a Facebook video chat funnelcake to users who visit `/firefox/` from a FB referrer (https://github.com/mozilla/bedrock/issues/6206). This has been running for a long time. Given that users cannot easily update their a funnelcake via the regular FF update channel, is serving a long running funnelcake like this benefiting aDAU in the long run, or harming it?

**Comment by hoosteeno** [comment]
> 1. Feature page A/B test without main header (Issue #6155). The code exists in bedrock but I can't see the switch enabled in production. Was this experiment ever run?

I don't think it was ever run; if it was, it was not documented. I've added it to the experiments backlog.  Consider it triaged.

**Comment by hoosteeno** [comment]
@alexgibson can you tell whether the experiment #6173 implements the form-view code recommended in https://github.com/mozilla/bedrock/pull/6396#issuecomment-435228076? It's much trickier to assess if it does not.

**Comment by hoosteeno** [comment]
> 8. Experiment to add FxA CTA to /new (Issue #6173). Active in production and has been running for a long time.

Analysis is done. Recommendation is to remove. See https://github.com/mozilla/bedrock/issues/6689.

**Comment by hoosteeno** [comment]
> 3. Firstrun copy experiment (bug 1451051). This is an old page, and the experimet is inactive. Not sure if we ever followed up on it, but the code and templates can likely all be removed.

Yes:
https://github.com/mozilla/bedrock/issues/6705

**Comment by hoosteeno** [comment]
>  4. SEM browser compare experiment for Chrome (Issue #5952). Experiment is active in production and has been running for a long time.
> 5. SEM browser compare experiment for Edge (Issue #5951). Experiment is active in production and has been running for a long time.
> 6. SEM browser compare experiment for Opera (Issue #6130). Experiment is active in production and has been running for a long time.
> 7. SEM browser compare experiment for Internet Explorer (Issue #6466). Same as above, but has been running for less time.
> 8. We're also actively serving a Facebook video chat funnelcake to users who visit /firefox/ from a FB referrer (#6206). This has been running for a long time. Given that users cannot easily update their funnelcake build via the regular FF update channel, is serving a long running funnelcake like this benefiting aDAU, or harming it?

I believe these are all New ADAU experiments. I emailed that team asking them to help wrap them up.

**Comment by hoosteeno** [comment]
> Yandex experiment on /ru/firefox/new/ (Issue #6300). This is still running, and nobody knows quite what to do with it, or if it's something we want to continue doing long term.

Emailed that team to ask about it.

**Comment by hoosteeno** [comment]
Added to issues to backlog to stop Yandex experiment and SEM landing page experiments. All have a winner that we should leave in place.

**Comment by craigcook** [comment]
> 8. We're also actively serving a Facebook video chat funnelcake to users who visit /firefox/ from a FB referrer (#6206). This has been running for a long time. Given that users cannot easily update their funnelcake build via the regular FF update channel, is serving a long running funnelcake like this benefiting aDAU, or harming it?

According to Nick Thomas via Slack, funnelcake users do receive updates through the regular channel, so this should do no harm: "What we do is that the funnelcake134 build will request updates on release-cck-mozilla134 channel, and if nothing is found there the update server will automatically try release instead. So we have the option of giving them something different, but hardly ever do and they’re treated like all the other endusers."

**Comment by alexgibson** [comment]
Thanks @ejregithub - PRs below for both locales, with appropriate DNM dates for each:

https://github.com/mozmeao/www-config/pull/201
https://github.com/mozmeao/www-config/pull/202

**Comment by alexgibson** [comment]
The pre-download experiment is now turned off for DE.

**Comment by alexgibson** [comment]
Both pre-download experiment have now ended. I'm going to close this issue, and open a PR to remove the experiment code. Thanks all!
