### ISSUE TITLE
Launch new SEO page "Incognito browser"

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6712]
| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | 2 |
| ENG | ? |
| SEO | ? |
| ANA | |
| DES | |
| COPY | |

Description: using the template established for SEO pages from the NA Desktop team, create the new page 'Incognito browser'

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is live before end of January 2019

#### Tasks
- [ ]  Assign the URL /technology/incognito-browser/
- [ ] Use the copy found in [this doc](https://docs.google.com/document/d/1cyHpu6mB2_-Dy1j9Gazw4OqTGymQ6gQTxL-Ys75rokE/edit) (includes meta data at the bottom)

Native Sketch file can be found here (in Abstract): https://share.goabstract.com/75a5ee3e-51e2-415f-8950-3ae3e70200ef

Look for the `Incognito Landing Page" layer.

**Comment by ejregithub** [comment]
Block on meta data

**Comment by ejregithub** [comment]
@alexgibson - QA review came up with the request to:  In the cookies section, please cut (remove) “Cookies basically function as tiny online spies for ad companies.” from the end of the second paragraph. Otherwise good to go for launch.
