### ISSUE TITLE
Revert to accordion on Fx Privacy Notice page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6713]
| Estimates |  |
| ------------- | ------------- | 
| PM | .5 |
| ENG | 2 |

Description:
Near the end of last year, the accordions/expanders on the Firefox Privacy Notice were removed. It's important that we put them back.

GDPR created an requirement that Privacy Notices be very short and understandable. But it also allows us to create a "layered" privacy policy. The first layer is the headlines. The second layer (under the accordions) has more explanation. Since legal creates and maintains this page to manage our legal risk, it's important to us to have control over how it looks.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] When a user lands on the page, they see only the headlines, and then can expand them for more information.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of risk. Use a checklist!
- [ ] This is an example of risk.

#### Tasks
- [ ] Revert the page to the previous accordion design (not the content, just the accordion)
- [ ] Restore or otherwise place anchors

**Comment by ejregithub** [comment]
Comment from Mika: Some of the anchors seem to have gotten lost.  since someone has to go in and put the accordian back, can they make sure each section has an anchor? This is important because we have a lot of web content that points to a specific part of the FxA privacy notice (like the section on Sync, or the section on Content Recommendations, etc.).

**Comment by alexgibson** [comment]
I've opened a PR that reverts removal of the accordion. Some notes from testing this old code:

"Whilst restoring this code I realised it was never very accessible. The ARIA support isn't great, and the individual sections are not expandable via keyboard 😩. There seems to be some urgency in restoring this that I don't fully understand (from a legal point of view), but if we are to support this accordion as a feature long term, then we should at least file bugs and make sure our privacy content is accessible to everyone."

Also note re: anchors. The content for this page is controlled by the legal team over in https://github.com/mozilla/legal-docs/. If anchors have been removed, it will likely be from content there, and not something in bedrock (we just consume the markdown and convert it to HTML).

**Comment by alexgibson** [comment]
Ok, I've spent some time fixing the accessibility issues on this accordion. Longer term, we should port this page to use the new standard [Details molecule](https://protocol.mozilla.org/patterns/molecules/details.html) in Protocol. What we have now is a stop-gap until we can prioritise that work.
