### ISSUE TITLE
Update copy on Licensing Page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6714]
| Estimates |  |
| ------------- | ------------- | 
| PM | .5 |
| ENG | ? |

Description:  Update copy on https://www.mozilla.org/en-US/foundation/licensing/ 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Page is placed on demo server for Legal review prior to go live
- [ ] Page content is updated and live

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of risk. Use a checklist!
- [ ] This is an example of risk.

#### Tasks
- [ ]  Update, swapping out this content:

"Mozilla website content (i.e. text and pictures, not look and feel) is generally licensed under Creative Commons Attribution Share-Alike (CC-SA) licenses. User-generated content, such as comments on our blog posts, are also generally made available under CC-SA, but different Mozilla websites (such as addons.mozilla.org) may allow users to choose other licenses for content that they upload to our sites."

To be this instead (without the quotes):

"The text of Mozilla websites is generally licensed under a Creative Commons Attribution (CC BY) or Attribution-ShareAlike (CC BY-SA) license, as indicated. Also, certain Mozilla websites (such as addons.mozilla.org) may allow users to choose Creative Commons licenses for content that they upload to our sites."

**Comment by ejregithub** [comment]
@amychurchwell  - please note the requirement to have the page on demo for Legal signoff prior to go live.

**Comment by amychurchwell** [comment]
@ejregithub the copy under the 'website content' section has been updated on demo -- https://bedrock-demo-achurchwell.oregon-b.moz.works/en-US/foundation/licensing/

**Comment by ejregithub** [comment]
Thanks @amychurchwell - I sent the URL to Mika and Michael in email and will post their response(s) here.

**Comment by ejregithub** [comment]
@amychurchwell - we are approved to go live by legal (Michael Feldman)
