### ISSUE TITLE
Update leadership page, new CFO

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#6737]
| Estimates |  |
| ------------- | ------------- |
| PM | 1 hour |
| ENG | 2 hours |

Description: We've [just announced our new CFO, Roxi Wen](https://blog.mozilla.org/blog/2019/01/22/welcome-roxi-wen-our-incoming-chief-financial-officer/), so we'll need to add her to the leadership page, also removing Kenton Chow as interim CFO.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Roxi's info/headshot image is added and live on the leadership page within 48 hours (business days) of receipt ([bio and headshot are in the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1525759))
- [ ] Kenton Chow is removed from the leadership page

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of risk. Use a checklist!
- [ ] This is an example of risk.

#### Tasks
- [ ] Add Roxi's info/image
- [ ] Remove Kenton's info/image

**Comment by hoosteeno** [comment]
Can you add me to the bug?

Is this really in the current sprint? She doesn't start for a while.

**Comment by ejregithub** [comment]
@craigcook  - this is good to go, needs to be live on the morning of, not before, Roxi's start day which is Thursday Feb 14th. [See the bug for required bio and image.](https://bugzilla.mozilla.org/show_bug.cgi?id=1525759)
