### ISSUE TITLE
'SEO page' performance metrics

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6746]
| Estimates |  |
| ------------- | ------------- | 
| TL | ? |
| PM | 1/2 day |
| ENG | NA |
| SEO | ? |
| ANA | ? |
| DES | NA |
| COPY | NA |

Description: We have a set of pages on Mozilla.org who's main purpose is to drive SERP ranking and, in turn, download & install conversions. We need to understand each page's performance to determine if further analysis is warranted to propose iterations for improvement.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] 

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of risk. Use a checklist!
- [ ] This is an example of risk.

#### Tasks
- [x] Identify the set of pages on mozilla.org that should be included in this report
- [x] Draw data and provide analysis for SEO / page performance in SERP for each page
- [x] Pull GA data on conversions and install rate for each page

[Listing doc](https://docs.google.com/spreadsheets/d/1UPbSeU32x8AoeHaeEHCS4Dwp4OEAvdFIVKTBqkFgloo/edit#gid=0)

**Comment by ejregithub** [comment]
@rraue addressed the tasks here, inserting data into [this spreadsheet ](https://docs.google.com/spreadsheets/d/1UPbSeU32x8AoeHaeEHCS4Dwp4OEAvdFIVKTBqkFgloo/edit#gid=0)earlier today.
