### ISSUE TITLE
Remove Firefox Focus from /firefox/mobile/ page for specific countries

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6762]
| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |

Description:  We need to remove the Firefox Focus content (the top CTA and the 'see more' content at the bottom of the page) from /firefox/mobile/ page for specific countries (not locales)

India
Indonesia
Philippines
Thailand

- The current plan is to remove Focus from these markets on 1/31
- /firefox/mobile/ , the Focus content in it, results in ~150 user interactions (clicks) per week in these countries. Installs are ~50 per week.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Content is removed by date (TBD)

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of risk. Use a checklist!
- [ ] This is an example of risk.

#### Tasks
- [ ] Book contexting session to determine best course of action long term (Eric)
- [ ] Create a fallback state for when country cannot be detected.
- [ ] Remove the Firefox Focus content (the top CTA and the 'see more' content at the bottom of the page) from /firefox/mobile/ for these countries (NOT locales): 
India, Indonesia, Philippines, Thailand

**Comment by alexgibson** [comment]
I think we should discuss the context behind this request before settling on a technical implementation like this. Removing content based on physical location like this may be difficult and high effort. There could be several solutions to this, some of which may be simpler and less effort:

- Adding a disclaimer that Focus is not available in certain countries and hiding the app store links.
- Redesigning the `/mobile/` page, or splitting it into several pages (which we could then link to conditionally much easier).

**Comment by hoosteeno** [comment]
I'm just updating this card with some questions we need answers to.

* Why is this an urgent priority, considering the very small number of visitors currently impacted?
* If geo-based removal is very difficult, what about global removal (which is trivial)? Is there any reason we should keep promoting Focus on this page to _anyone_?
* How will we decommission Focus, and what does that imply for the website?
  * Will it happen country by country?
  * Do we need to have messaging or a "retirement" page to catch people coming for Focus?
  * Do we need to be promoting a different browser?
  * Should we plan to overhaul this entire section, and on what timeline?

**Comment by alexgibson** [comment]
> If geo-based removal is very difficult, what about global removal (which is trivial)?

Just to add some extra context here based on our discussion. It's not that removal based on geo would be super difficult per-say. It may be quite possible to do, but it would likely not be a great implementation and a hack at best. The page was never really designed or built to be incomplete like this. From a performance point of view, client side geo-location also has some real costs associated with it (as we saw with the Yandex page). Considering this is critical, above the fold content, we should weigh up the costs carefully.

**Comment by hoosteeno** [comment]
I talked with Loren and we agreed to icebox this request until/unless it becomes a problem. As things stand, the UX is probably better than any band-aid we could apply. Visitors to the page from these 4 countries who follow the CTA to the Focus App get a message: It's not available in their location. For us to provide a similar experience we'd have to jump through the hoops Alex mentions in https://github.com/mozilla/bedrock/issues/6762#issuecomment-460778929. Let's archive.

**Comment by alexgibson** [comment]
The updated /mobile page no longer features Focus, closing.
