### ISSUE TITLE
FxA CTA on /new: Build l10n rollout plan

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6763]
| Estimates |  |
| ------------- | ------------- |
| TL | 1 hour |
| PM |  |
| ENG | 1/2 day |
| SEO | |
| ANA | |
| DES | |
| COPY | |

We should release this feature in a source locale, and allow other locales to localize it on their own schedule.

We should ask l10n for help getting it localized in Tier 1 locales.

Locales where it is not 100% localized should fall back to the version of this page that is localized.

Locales where it is 100% localized should start seeing it when it is localized.

We should not worry about FxA support: They have 82 languages.

If this implies hard technical challenges, let's revisit.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] The plan is written
- [ ] The plan is reviewed by engineers

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] The plan implies hard technical challenges

#### Tasks
- [x] Write the plan

**Comment by hoosteeno** [comment]
@craigcook can you review the plan? It's above.

**Comment by ejregithub** [comment]
It's in the done column, so i'm closing this
