### ISSUE TITLE
FxA CTA on /new: Research: Find what languages are supported by accounts.firefox.com

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6769]
| Estimates |  |
| ------------- | ------------- |
| TL | 1 |
| PM |  |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

Description: Find out which languages (locales) are supported by accounts/firefox.com

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] We have a list
- [x] We use the list to inform l10n rollout plan

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of risk. Use a checklist!
- [ ] This is an example of risk.

#### Tasks
- [x] Talk to Accounts team about this
- [x] Push into l10n rollout plan

**Comment by ejregithub** [comment]
Hoosteeno to consult with Accounts team for response to this question and provide that listing here.

**Comment by hoosteeno** [comment]
Here are the supported languages:

https://github.com/mozilla/fxa-shared/blob/master/l10n/supportedLanguages.json

Here is Pontoon status:

https://pontoon.mozilla.org/projects/firefox-accounts/

**Comment by ejregithub** [comment]
Thanks @hoosteeno. Closing this issue.
