### ISSUE TITLE
FxA CTA on /new: Capture and analyze data

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6770]
| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | 2 days|
| ENG |5 days |
| SEO | |
| ANA |7 days |
| DES | |
| COPY | |

Description, good enough that reading the card 1 month from now, you still know what it means.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of success criteria. Use a checklist!
- [ ] This is an example of success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of risk. Use a checklist!
- [ ] This is an example of risk.

#### Tasks
- [ ] Make sure analytics is built into the page and QA 
- [ ] Provide analysis post launch
- [ ] Specify tracking parameters for all page states: amplitude and GA
- [ ] Implement Amplitude tracking on form views

**Comment by ejregithub** [comment]
@sghoseWI - please scope effort and assign hours up until a half day, then go by half day increments.

**Comment by sghoseWI** [comment]
Hi @ejregithub happy to help scope this -- but could you please provide some more context for what the specific ask for analysis/experimentation is?  Still unclear to me after looking through this Mana page: https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=81691802

**Comment by sghoseWI** [comment]
@ejregithub updated to my best estimation above (based on .  I haven't worked much with Amplitude much -- but I've been working with the devs for coordinating instrumentation on other experiments currently in queue. I'll reach out to Alex Davis so I can get more familiar on instrumentation process myself.

**Comment by hoosteeno** [comment]
@sghoseWI Can you link to the final work project here and close this?

**Comment by sghoseWI** [comment]
https://docs.google.com/document/d/1HKYoBiZ1uFXqgqGOEl1FXRTEeNoffJswy1_-cj5L6Pc/edit#

**Comment by ejregithub** [comment]
Closing.
