### ISSUE TITLE
Test that migration worked.

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#6773]
| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

We need to verify that a migration is not creating content bugs.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Test that sitemap is the same between migrated site and production
- [ ] Spot test that content is the same for locales on migrated site and production

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of risk. Use a checklist!
- [ ] This is an example of risk.

#### Tasks
- [ ]

**Comment by alexgibson** [comment]
I think this is covered by our migration scripts and review process with the L10n team.
