### ISSUE TITLE
Remove Test Pilot content on mozilla.org

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6776]
| Estimates |  |
| ------------- | ------------- | 
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

Description: Test pilot has ended and content (en-US and localized versions) for it needs to be removed from mozilla.org. 
---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of success criteria. Use a checklist!
- [ ] This is an example of success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of risk. Use a checklist!
- [ ] This is an example of risk.

#### Tasks
- [ ] Remove Test Pilot content from the following pages/sections:
- https://www.mozilla.org/en-US/firefox/channel/desktop/#help-out
- https://www.mozilla.org/en-US/firefox/features

**Comment by ejregithub** [comment]
@hoosteeno - flagging this one with you.
