### ISSUE TITLE
sla-page: Code and launch SLA page for Enterprise product

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6779]
https://docs.google.com/document/d/1Dj42ugxX4Uh5ihcPlNeSTmOQ2rSJk4cytvrPIAAojhs/edit#

## Description

Use designs from https://github.com/mozilla/bedrock/issues/6937 to build a new page at /firefox/enterprise/sla that contains [the SLA document](https://docs.google.com/document/d/1Dj42ugxX4Uh5ihcPlNeSTmOQ2rSJk4cytvrPIAAojhs/edit) in an appealing, on brand design that helps convince potential customers that this is a good service. A single page based on an existing template.

Depends on https://github.com/mozilla/bedrock/issues/6937.

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | 5 days |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page defaults to en-US when viewed by other locales

#### Tasks
- [ ] Take markdown from the product team and insert that into a page
- [ ] Code with this design file 
[Enterprise SLA.sketch.zip](https://github.com/mozilla/bedrock/files/2998063/Enterprise.SLA.sketch.zip)

**Comment by hoosteeno** [comment]
Depends on https://github.com/mozilla/bedrock/issues/6937

**Comment by ejregithub** [comment]
@amychurchwell  - And . . . we have stakeholder approval of design and may proceed with coding.

![Screen Shot 2019-03-22 at 4 13 04 PM](https://user-images.githubusercontent.com/20547886/54857601-837c4480-4cbd-11e9-9b86-e06156240620.png)

**Comment by hoosteeno** [comment]
@craigcook any update here? I know the stakeholders are eager to review.

**Comment by craigcook** [comment]
On demo: https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/enterprise/sla/

Still a bit more to tidy up but it's close to done, finally. Sorry for the delay.

**Comment by ejregithub** [comment]
blocked by PDF.  i pinged Tyler about in Slack

**Comment by hoosteeno** [comment]
@craigcook can you add status here?

**Comment by craigcook** [comment]
PR https://github.com/mozilla/bedrock/pull/7084 is ready for review, but still blocked by a PDF for a deployment guide that Mike Kaply and Tyler Ahn are providing. Once I have that file I just need to upload it to assets.mozilla.net and update the link in the page.

**Comment by hoosteeno** [comment]
@craigcook here's the PDF. [Firefox for Enterprise Browser Deployment Guide.pdf](https://github.com/mozilla/bedrock/files/3104092/Firefox.for.Enterprise.Browser.Deployment.Guide.pdf)
