### ISSUE TITLE
Redesign /all page to allow more installers

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6780]
## Description
The /firefox/all/ pages (there are several) are collectively responsible for > 2% of global downloads. They also serve as a significant SEO draw. But they are incomplete, and getting more incomplete over time. They also have old and overwhelming UI. We can improve them.

Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1493205

The Enterprise team and the product team are working together to release new installers for Firefox. Specifically,
* A 32-bit and a 64-bit MSI installer (i.e. 2 add'l installers). MSI is a Firefox installer that works on Windows and includes extra details about how Firefox should be configured. These are used by network administrators in large IT shops.
* An ARM64 installer. This is a Firefox installer that works in a particular hardware architecture that is popular on small, portable devices.

Right now those installers can only be found on [SUMO](https://support.mozilla.org/en-US/kb/deploy-firefox-msi-installers). SUMO is amazing, but it isn't optimized for download funnels. It's missing instrumentation; it's not suitable for marketing content. 

The number of distributed binaries under the Firefox brand is quite large, and growing. [Here's a list of the dimensions a UI could](https://docs.google.com/document/d/1MtqVFAfnDJOoR2X0OZ1yFDdSkfVUSCChgIOye8PklXk/edit) help users navigate.

https://www.mozilla.org/en-US/firefox/organizations/all/ (ESR)
https://www.mozilla.org/en-US/firefox/nightly/all/ (Nightly)
https://www.mozilla.org/en-US/firefox/developer/all/ (Dev Edition)
https://www.mozilla.org/en-US/firefox/beta/all/ (Beta)
https://www.mozilla.org/en-US/firefox/all/ (Release)

[Copy doc](https://docs.google.com/document/d/1phOeJaAiy5WlNSLiWKmlcMQiK5K22m1Fel8Uco3-7TE/edit)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page designs accommodate a growing number of installer types
- [ ] Page includes instrumentation allowing us to count sessions and downloads for each installer type
- [ ] Page includes all download options it currently has, plus new download options
- [ ] Page is launched in production and localizable

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] Product may not include feature X by release day Y. . .

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] Code the page using these assets supplied by team x

**Comment by hoosteeno** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1493205

**Comment by ejregithub** [comment]
- @hoosteeno - Package for external agency to produce

**Comment by claychaffin** [comment]
I've opened a DM on Slack with P_____  and @hoosteeno for guidance on (re)naming the Firefox Quantum browser on this page in light of master brand rollout and name exploration underway.

**Comment by claychaffin** [comment]
@hoosteeno @rraue  @mrkwvr  have an answer from P:  we're going with "Firefox browser" (not "Firefox Quantum") everywhere on this page, and in SEO. Thanks everyone.

**Comment by claychaffin** [comment]
Copy Deck: https://docs.google.com/document/d/1phOeJaAiy5WlNSLiWKmlcMQiK5K22m1Fel8Uco3-7TE/edit?usp=sharing

**Comment by claychaffin** [comment]
Redesign and copy are complete; coding is on hold for now and is captured in a separate issue: https://app.zenhub.com/workspaces/websites-team-59bd527821e82e515786ca73/issues/mozilla/bedrock/7076

**Comment by alexgibson** [comment]
This redesign has happened, and we're now adding the new MSI installers in https://github.com/mozilla/bedrock/issues/7209.
