### ISSUE TITLE
D&I 2019 - images

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6790]
| Estimates |  3.5 days and 1 hour total |
| ------------- | ------------- |
| TL | 1 hour |
| PM | 1/2 day |
| ENG | 3 days |
| DES | |

Description: D&I 2019 numbers are ready and need to be posted in a new blog. The job here is to create new images with the 2019 data

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of success criteria. Use a checklist!
- [ ] This is an example of success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of risk. Use a checklist!
- [ ] This is an example of risk.

#### Tasks
- [ ] Using the same designs created for the 2018 blog post, create new images with the 2019 data
[Data Source](https://mozilla.app.box.com/s/9wjudnp8qwmnu9903uj0sqfg0pi9iwoz)

**Comment by amychurchwell** [comment]
Repeat from earlier meeting-- but if these are charts that are used every year, we may consider using a JavaScript data visualization tool for the next one.

**Comment by craigcook** [comment]
Graph assets have been put in the google drive at https://drive.google.com/drive/u/1/folders/1a9PQH1sPogyprR_QEmh5xJMtuV53Mj56, pending review/approval from the D&I team.
