### ISSUE TITLE
Move from Jenkins to GitLab for CI/CD

### ISSUE THREAD

**Issue by pmac** [mozilla/bedrock#6794]
- [x] Setup CI for Bedrock in GitLab
- [x] Hook GitLab CI up to Github for build reporting
- [x] Configure build and deployment pipeline

See https://github.com/mozilla/kitsune/pull/3455 for a similar effort in Kitsune and [our infra docs](https://github.com/mozmeao/infra/blob/master/docs/gitlab_ci.md) for pipeline help.

**Comment by jgmize** [comment]
This was completed by https://github.com/mozilla/bedrock/pull/8222
