### ISSUE TITLE
WNP 67- Coding Design - Release date - 5/14

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6799]
[Master Project Document](https://docs.google.com/document/d/1_Jb3Z7RpVM-o5YKqOKDgW4v5CMdzSGIPTDa5GtYg-8A/edit)

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | 2 days |
| ENG | |
| ANA | TBD |
| DES | TBD |
| COPY | TBD |

Description: launch the whatsnew page one week before the Firefox 67 launch to promote FxA accounts (and possible other things).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Live and ready for QA (Soft Vision) on or before - 5/7

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] New copy string delivery in time to maximize l10n reach

#### Tasks
- [x] File bug requesting WNP w. Releng (Eric R)
- [x] Copy (Meghan)
- [x] Design (Carolyn)
- [ ] Code (Stephanie)
- [ ] Provide data reporting on CTA metrics (Saptarshi)

**Comment by amychurchwell** [comment]
@stephaniehobson :wave: Wanted to call out a newsletter bug Alex noticed (https://github.com/mozilla/bedrock/pull/7119) on WNP68 for beta & dev users that are already signed-in to a firefox account.

We may need to add `67` to this array, https://github.com/mozilla/bedrock/pull/7119/files

**Comment by stephaniehobson** [comment]
Thanks Amy! I had no idea but it looks like @craigcook did that when he added the strings. ⚡️
