### ISSUE TITLE
Remove sections from /firefox

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6806]
## Description

Update /firefox landing page based on user testing to remove low performing components.

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | 2 |
| SEO | |
| ANA | |
| DES | 3 |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Low performing elements have been removed
- [x] Remaining sections re-ordered

#### Tasks
- [x] Remove Whats New section and assets
- [x] Remove Features section and assets
- [x] Remove Smooth Browsing section and assets
- [x] Remove Mozilla section and assets

**Comment by stephaniehobson** [comment]
New order:

![firefox-desktop-v1](https://user-images.githubusercontent.com/854701/52511910-1736fd00-2bb7-11e9-99ce-157201bdf3dd.jpg)
