### ISSUE TITLE
Firefox 64-bit SEO page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6810]
## Description

Adapt the copy of this blog post https://blog.mozilla.org/firefox/firefox-64-default-64-bit-windows/ to become a landing page on Mozilla.org to see if the landing page converts better than the blog post.

[COPY ](https://docs.google.com/document/d/1GCY431SVMeeK8NirjAXgi0CQIndtYJPGeZKWr-sb__o/edit)

### Estimates

| Estimates |  |
| ------------- | ------------- |
| PM | 1 hour |
| ENG | 2 days |
| SEO | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### Tasks
- [ ] Use [this Sketch file/version in Abstract](https://app.goabstract.com/projects/1ce3a550-a647-11e8-9633-0bbf4af2c21f/branches/master/commits/2a30a004e9f7b8c5be59af2c8ab215ac7fd736da/files/5448B728-24A0-4F9A-9EBC-709E11BE476B/layers/F744312E-5D88-420B-B194-881AFC55660A?mode=design)
- [ ] Use this [copy](https://docs.google.com/document/d/1GCY431SVMeeK8NirjAXgi0CQIndtYJPGeZKWr-sb__o/edit)
- [x] @rraue identifies preferred URL for this page.  ( /firefox/windows-64-bit/ )

**Comment by ejregithub** [comment]
![image](https://user-images.githubusercontent.com/20547886/52576604-3dd27f00-2dd5-11e9-8f98-27d11df11728.png)

**Comment by amychurchwell** [comment]
Is there a preferred URL for this page?

**Comment by ejregithub** [comment]
@rraue - can you please provide the URL for this page?

**Comment by rraue** [comment]
/firefox/windows-64-bit/

**Comment by amychurchwell** [comment]
Demo is ready for review: https://bedrock-demo-achurchwell.oregon-b.moz.works/en-US/firefox/windows-64-bit/

**Comment by amychurchwell** [comment]
@hoosteeno Hi Justin, considering that Eric is out would you be able to put this demo link into the hands of stakeholders who need to approve? ⬆️

**Comment by hoosteeno** [comment]
Thanks Amy.

@rraue can you review/approve this?

**Comment by rraue** [comment]
One more thing: The last link to /firefox/all/ goes to the no-locale redirect, we should use the url() helper so it directly links to /locale/firefox/all
