### ISSUE TITLE
Why Firefox - SEO Page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6815]
## Description
SEO Page to drive SERP ranking entitled ""Why Firefox could be the best browser for you" 

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | 2 hours |
| ENG | |
| SEO | ? |
| ANA | |
| DES | |
| COPY | |

---

[Copy(https://docs.google.com/document/d/151gPy7rcGvd8Y9PCbtvFfFyLv066zi7F27DnGF5euYo/edit)

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Is approved by @rraue and Winston (page on demo server)
- [ ] Deployed at the URL specified by @rraue  - https://www.mozilla.org/firefox/best-browser/
- [ ] Strings are extracted for L10n
- [ ] Anika and Malcolm are notified when strings are available in Pontoon (@ejregithub)

#### Tasks
- [ ] Code the page using this file in [Abstract:](https://share.goabstract.com/3c00a324-3de4-4936-9997-6299a6133df8) noting that the layer the design lives on:
Revised Design layer > Choosing Browser Landing Page

**Comment by ejregithub** [comment]
![image](https://user-images.githubusercontent.com/20547886/54639184-ff6e5680-4a49-11e9-9795-e7a0ba48601a.png)

**Comment by ejregithub** [comment]
![image](https://user-images.githubusercontent.com/20547886/54731858-dd5dfc80-4b4d-11e9-8a06-a624068ea522.png)

**Comment by ejregithub** [comment]
@amychurchwell - apologies for the scope creep / lack of completeness in the tasks: The strings here do need to be extracted for L10n.

**Comment by amychurchwell** [comment]
Demo - https://bedrock-demo-achurchwell.oregon-b.moz.works/firefox/best-browser/

As mentioned, block quotes are currently a bit large because protocol will be updated directly instead of custom styles on top.

**Comment by ejregithub** [comment]
@amychurchwell - please ping me when the strings are extracted and available in Pontoon. We want to be sure Anika has first crack at them.

**Comment by amychurchwell** [comment]
@ejregithub strings have been extracted and [merged to l10n production repository](https://github.com/mozilla-l10n/bedrock-l10n/commits/master). I believe this means they are in Pontoon or will be soon.
