### ISSUE TITLE
Localize the new /about/ page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6828]
## Description

The newly designed [about page](https://www.mozilla.org/en-US/about/) has never been localized. With the launch of the new German home page, we'll be linking to `/de/about/` which is old branding. Unless we're not done experimenting on it yet, we should localize it so we can remove the old page.

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is exposed for translation.
- [ ] Template is behind a conditional l10n tag.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark
- [ ] Are there any reasons not to do this?

#### Tasks
- [ ] Prepare template/view for l10n.
- [ ] Ping l10n team for string extraction.

**Comment by peiying2** [comment]
One of the photos shows a person wearing t-shirts saying "Firefox OS LAUNCH TEAM". Should we change it?

**Comment by ejregithub** [comment]
@peiying2 - a known circumstance that has not yet been addressed due to time constraints/lack of a better image ready at hand.  Not a blocker for 110n though.

**Comment by alexgibson** [comment]
@peiying2 just checking in, is there anythign you need from us to get l10n started for this page?
