### ISSUE TITLE
Build SEM-specific default download experience

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6829]
## Description

Create a separate version of /new for paid funnel use

[Brief](https://docs.google.com/document/d/1Pm2xZTb337ZC-FbB89PoPL_8YHNfBq-0qhFiRg16YRo/edit#)
[Airtable listing](https://airtable.com/tbl1JN1aCB5UXpjvE/viwSPe2isp9ualv6O/recjJ3Bx5yWLV7U77)
[Context Doc](https://docs.google.com/document/d/1PucezGPizQFe2bZemAaISiig1bueFPvkEPhB8biLCEM/edit?usp=sharing)

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | 1 day |
| PM | 1/2 day |
| ENG | 2 & 1/2 days |
| SEO | 3 days |
---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Page is build wholly using Protocol components
- [x] Page comes as close to replicating existing /new as possible, within Protocol constraints (e.g. same images, background, and appx. same layout if possible)
- [x] Page lives at /firefox/campaign
- [x] Page uses a copy of existing /new .lang file which (requires conversation with l10n team)
- [x] Canonicalize the page to /new so this page is not indexed
- [x] Build for DE and en-GB locales

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] 

#### Tasks
- [x] Understand the l10n approach
- [x] Build the page(s)
- [x] Build the lang file(s)
- [x] Launch on demo
- [x] Ensure new page(s) respond to DE and en-GB requests

**Comment by alexgibson** [comment]
I have capacity to start this seeing as it's ready

**Comment by alexgibson** [comment]
This is now up on demo at : https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/campaign/

Note: the lang file has not been ported over yet, so en-US only for now.

**Comment by alexgibson** [comment]
PR to add the new lang file: https://github.com/mozilla-l10n/www.mozilla.org/pull/277

**Comment by alexgibson** [comment]
Ok, the new lang file is in place, this is ready for core review.
