### ISSUE TITLE
euexp02 Design Test on /new: More descriptive features/ "More content on /new"

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6830]
## Description

This project will create a page in which users can see the three feature areas that are currently "below the fold" and test that against the current /new page as the control.  We hypothesize that some people hitting this page are still on the fence and are interested in learning a bit more about Firefox before making a download decision. We believe users will be more likely to download when seeing content more directly, leading to an increase in installs and active days. 

~[Manapage](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=90737686) - euexp03 Design Test on /new: More descriptive features~

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Test is vetted and approved by Analytics (cohort sizes set for experiment, duration of experiment estimated)
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Depends on #6831

#### Tasks
- [x] Code the test page (dev)
- [x] Determine experiment parameters including target audience, cohort sizes and duration of test
- [x] Set up traffic cop to parameters provided by Analytics (dev)

[DE Copy](https://docs.google.com/document/d/1b--6mC2oQyaDmqvlllQkVust3IxKKdX6bX4TuQt_u9U/edit)
[EN Copy](https://docs.google.com/document/d/1n2ZZmFgy_5yYhxAuc8P36HDtYjFO0Mz8x3E12nmgUuo/edit?usp=sharing)
[Design assets in Abstract](https://share.goabstract.com/35b1fce8-8c72-4185-a215-7de33ac8d2e0)

**Comment by ejregithub** [comment]
![image](https://user-images.githubusercontent.com/20547886/52814462-11c33200-3051-11e9-8ebf-0563c111152f.png)

**Comment by ejregithub** [comment]
Link to file in Abstract:
Link to design file - https://share.goabstract.com/35b1fce8-8c72-4185-a215-7de33ac8d2e0

These designs live at the following path in the Sketch file:

Page:
- NA EXP 03

Layers:
- NA EXP 03 Shortform
- NA EXP 03 Longform

**Comment by alexgibson** [comment]
Ok, I spoke to Justin the designer and here's what needs doing:

The correct manapage for this experiment is: https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=90738680

The purpose of the experiment is to A/B test some longer form feature content against a control that is the short form content being worked on in https://github.com/mozilla/bedrock/issues/6831.

Therefore this experiment depends on https://github.com/mozilla/bedrock/issues/6831 before it can be rolled out.

That said, I can work on variation "C" independently, so I'll make a head start on that.

**Comment by alexgibson** [comment]
I'm not convinced the copy decks linked in the description here are the correct ones for this experiment. I'm looking for the long-form copy. For now, I'm going with whatever is in the Sketch files.

@ejregithub can you please try and find the correct copy decks?

**Comment by alexgibson** [comment]
Blocked on final copy

**Comment by alexgibson** [comment]
Final German copy https://docs.google.com/document/d/17P_5EwV9KDiYsxDlnEVlbWpoo6FwyM3rh3xKUUrTO9I/edit?usp=sharing

(Still waiting on English copy deck)

**Comment by alexgibson** [comment]
Update: copy is waiting on legal review / approval.

**Comment by ejregithub** [comment]
Alex - Legal (MFeldman) approved the en copy in [this doc ](https://docs.google.com/document/d/1n2ZZmFgy_5yYhxAuc8P36HDtYjFO0Mz8x3E12nmgUuo/edit). The en doc link has also been updated in the description of this issue.

**Comment by alexgibson** [comment]
@ejregithub the doc you link to is either incorrect or incomplete, ugh.

I've been given [this doc](https://docs.google.com/document/d/1yo4u3MayqTaNvp1kGGcWfmN7OfTrGGi2L6YEAZ_88gc/edit?usp=sharing) over Slack, which seems to be the correct copy for the page (although it does call it version "D" which is super confusing).

**Comment by alexgibson** [comment]
WIP is now up on demo:

- https://bedrock-demo-agibson.oregon-b.moz.works/en-GB/firefox/new/?v=a
- https://bedrock-demo-agibson.oregon-b.moz.works/en-GB/firefox/new/?v=b
- https://bedrock-demo-agibson.oregon-b.moz.works/en-GB/firefox/new/?v=c
- https://bedrock-demo-agibson.oregon-b.moz.works/de/firefox/new/?v=a
- https://bedrock-demo-agibson.oregon-b.moz.works/de/firefox/new/?v=b
- https://bedrock-demo-agibson.oregon-b.moz.works/de/firefox/new/?v=c

Each variant tracks the following information:

Stub attribution:

```
{ 
    utm_source: "www.mozilla.org", 
    utm_medium: "firefox-features", 
    utm_campaign: "firefox_new_page", 
    utm_content: "eu_exp02_[de|gb]_[a|b|c|d]" 
}
```

GA:

```
{ 
    "data-ex-name": "eu_exp02_[de|gb]", 
    "data-ex-variant": "v_[a|b|c|d]" 
}
```

For variation "c" we also track clicks on the features (despite them not being interactive in any way):

```
{
    'event': 'in-page-interaction',
    'eAction': 'feature click',
    'eLabel': [feature_name]
}

I need someone to verify if this all looks ok.

We also need a finalised test plan. Currently the mana page does not give any estimation as to the cohort sizes we should be suing.

**Comment by alexgibson** [comment]
@ejregithub we now need stakeholder approval of the demo URLs, and also the missing test information above ^

**Comment by alexgibson** [comment]
This experiment is also blocked on prioritisation, being that it needs to wait for the currently [headline experiment](https://github.com/mozilla/bedrock/issues/6851) to end.

**Comment by justinkropp** [comment]
@alexgibson Just a few tweaks if possible.

**The following tweaks should be applied to all designs, if possible:**

- [ ] 'h3' feature titles could use a bottom margin. `.75em` should be just fine.
- [ ] increase the max-width of the `.c-call-out-compact` just a bit so that the `c-call-out-container` text doesn't wrap?
- [ ] decrease the size of the mail icon in `newsletter-title` and vertically center both the icon and the h3

For reference:

<img width="787" alt="Screen Shot 2019-03-22 at 9 55 13 AM" src="https://user-images.githubusercontent.com/1461798/54828063-befd1b80-4c89-11e9-8041-26c72fbe8c99.png">


**The hero section should:**

- [ ] contain the updated browser image
- [ ] get rid of the wave background image `wave.6e6e5026bcc9.svg`

For reference:
![euxp02 DE Hero](https://user-images.githubusercontent.com/1461798/54826868-22397e80-4c87-11e9-89f6-1a02589e9059.png)

**Comment by gkabbz** [comment]
@alexgibson 

GA for variation c : Missing an event category - not sure if that's what event would be. It looks like, from the current events in GA, that the event category is usually set as where the interaction happened e.g. '/firefox/download/thanks/' Interactions or '/firefox/new/ Interactions' so we'd want to set it in a similar fashion here as well. The event action and event label look good to me.

@hoosteeno I'm not aware of where the data-ex-name and data-ex-variant show up in GA. Anybody able to shed some light for me.
{ 
    "data-ex-name": "eu_exp02_[de|gb]", 
    "data-ex-variant": "v_[a|b|c|d]" 
}

**Stub Attribution:** I think we should be consistent across experiments as to the standard utm parameters we put in the stub installer so it is easier for us to isolate and make sense of the activity a year from now when someone is doing year over year comparisons. e.g. In the how to install experiment we set the medium as download_button and here as firefox_features. My concern is a year from now, when looking at installs, someone could think these are legitimate traffic mediums that aren't repeating. So I'd suggest the following. @hoosteeno @sghoseWI @alexgibson I'm looking for feedback here if you agree with this approach. 

Thinking the utm source should always be set to 'mozilla.org', the medium to always be set as 'experiment', the campaign as the experiment name / description then the utm content can be similar to what you currently have with the experiment name and variant info. Thoughts? See sample below.

{ 
    utm_source: "www.mozilla.org", 
    utm_medium: "experiment", 
    utm_campaign: "descriptive_features_new_page", 
    utm_content: "eu_exp02_[de|gb]_[a|b|c|d]" 
}

**Comment by gkabbz** [comment]
@alexgibson sizing has been added to the mana for this experiment.  https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=90738680

**Comment by alexgibson** [comment]
>GA for variation c : Missing an event category - not sure if that's what event would be. It looks like, from the current events in GA, that the event category is usually set as where the interaction happened e.g. '/firefox/download/thanks/' Interactions or '/firefox/new/ Interactions' so we'd want to set it in a similar fashion here as well. The event action and event label look good to me.

@gkabbz I can't see any existing GA events where we specify an event category in code like this. My guess is this is something that's configured in GA itself, although I'm not sure where. You can see lots of other examples where we specify a custom event that follow the same properties as used here: https://github.com/mozilla/bedrock/search?q=eAction&unscoped_q=eAction

> I'm not aware of where the data-ex-name and data-ex-variant show up in GA. Anybody able to shed some light for me.
{
"data-ex-name": "eu_exp02_[de|gb]",
"data-ex-variant": "v_[a|b|c|d]"
}

Sorry I can't help here, but this is a [standard event format](https://bedrock.readthedocs.io/en/latest/analytics.html) we used for many experiments. Maybe @hoosteeno can point you in the right direction here.

> Thinking the utm source should always be set to 'mozilla.org', the medium to always be set as 'experiment', the campaign as the experiment name / description then the utm content can be similar to what you currently have with the experiment name and variant info. Thoughts? See sample below.

I'm happy to set these to any value we see fit, although I'll defer to @hoosteeno and @sghoseWI.

> @alexgibson sizing has been added to the mana for this experiment. https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=90738680

Updated, thank you.

**Comment by alexgibson** [comment]
@justinkropp thanks for these suggestions. I've updated as many as I can here, but only for variation "C". We shouldn't really make visual changes to the control experiences, else it may skew our data in some way. I couldn't update the browser image, as the version in the sketch file is not quite large enough. It needs to be 1400px wide at minimum in order to support a high-res version. If you have one, I'm happy to update it.

**Comment by hoosteeno** [comment]
> @hoosteeno I'm not aware of where the data-ex-name and data-ex-variant show up in GA. Anybody able to shed some light for me.
> {
> "data-ex-name": "eu_exp02_[de|gb]",
> "data-ex-variant": "v_[a|b|c|d]"
> }

These are [custom dimensions](https://support.google.com/analytics/answer/2709828?hl=en). You access them like any dimension. A custom report is handy for isolating them. You can manage them in the Admin section.

> {
> utm_source: "www.mozilla.org",
> utm_medium: "experiment",
> utm_campaign: "descriptive_features_new_page",
> utm_content: "eu_exp02_[de|gb]_[a|b|c|d]"
> }

These values look solid to me. r+. As usual, it's worth remembering that we have very particular logic for how we set these (when we set them):

> We don't write actual utm parameters on same-site links; we use JavaScript to pass contrived utm parameters to the stub installer when post-download measurement is necessary.

> If there is no utm_content param, then we can add it, with a value that includes the experiment identifier and the variation identifier as in `utm_content=eu_exp02_[de|gb]_[a|b|c|d]`

> If we add a utm_content param, we must ensure that utm_source, utm_medium and utm_content are also populated. If any are missing then we can fill them with default values, e.g. 
>  * `utm_source=www.mozilla.org`
>  * `utm_medium=experiment`
>  * `utm_campaign=description_of_experiment_eg_headlines_on_new`

> We should not overwrite utm parameters that exist.
