### ISSUE TITLE
Launch "SEO content on /new" in en-GB & DE

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6831]
## Description

We currently aren't ranking well for browser terms - we hypothesize that a longer-form page will have a higher chance of ranking for terms like "private browser", etc. We'll add them with this in hard coded templates for each locale.

[manapage](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=90737686)

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | 1/2 day |
| PM | 1/2 day |
| ENG | 4 | (add 2 if a/b/c test)
| SEO | 1 days |
| ANA | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Localized content /new appears for people requesting in those locales only
- [ ] Must be live end of sprint, target go live the first week of the sprint

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [x] The SEM page is completed first (Dependency)

#### Tasks
- [ ] Build hard coded templates for each page (2)
- [ ] Build hard coded long form templates for each test (long form page) (2)
- [ ] Set up TC for each locale (2 - DE, GB)
- [x] Get Copy - (from David's team)
[DE copy](https://docs.google.com/document/d/1b--6mC2oQyaDmqvlllQkVust3IxKKdX6bX4TuQt_u9U/edit#)
[en-GB copy](https://docs.google.com/document/d/1j4OTQkayYhdrcRWU3GtBExpMg7m_l4RAVhLaaaUPN1I/edit#)
- [x] Get Design (icons/images) (from David's team)
- [ ] To mitigate risk, put this behind a switch

**Comment by ejregithub** [comment]
@hoosteeno - please rescope this story.

**Comment by amychurchwell** [comment]
Adding blocked label until we get copy/design.

**Comment by rraue** [comment]
Sorry, just clicked the wrong button on our board
