### ISSUE TITLE
Decommission the old /firefox/accounts/ page

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#6837]
## Description

We launched the new Accounts benefits page a few months ago but have kept the legacy page while l10n has progressed on the new content. When we have sufficient locale coverage of the new page we should remove the old one.

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] New page is fully localized and active in all top tier locales.
- [ ] Any remaining locales that haven't yet translated the new page will redirect to the new page in English.
- [ ] The old lang file is removed

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Delete old `accounts.html` template, rename `accounts-2018.html` to `accounts.html` (but don't rename the `accounts-2018.lang` file).
- [ ] Update `urls.py` and `views.py` to use the single template.
- [ ] Delete any redundant assets (images, css, js) tied to the old template.
- [ ] Update any related tests.
- [ ] Remove the old lang file

**Comment by shane-tomlinson** [comment]
Is this the last place where FxA is iframed? It'd be *awesome* for us to be able to remove support for iframing.

**Comment by alexgibson** [comment]
> Is this the last place where FxA is iframed? It'd be _awesome_ for us to be able to remove support for iframing.

i think there's this page and also an old /firstrun. But I think that can also likely be removed now. If deprecation of that code is something that would help your team, then let's try and get this in our backlog 👍

**Comment by alexgibson** [comment]
Incidentally @shane-tomlinson, is introduction of the email-first form vs the old iframe on mozorg something that your team saw lead to an increase in FxA conversions? If so, that's something I'd love to read more about, if such data exists.

**Comment by shane-tomlinson** [comment]
> If so, that's something I'd love to read more about, if such data exists.

Let me get back you you, I have to summon @davismtl or @irrationalagent.

**Comment by irrationalagent** [comment]
@alexgibson you can see the results of the original test of the email-first flow [here](https://docs.google.com/document/d/1seUQEXOR-JGD6ff77iAP8lzDjW-BPengXugUzo-p2UQ/edit#heading=h.myd7simqfi45). 

That was some time ago. Apparently older versions of Firefox still use the iFrame, so it may be possible to do a side-by-side comparison with more contemporary data. But since clients on older versions tend to be a bit... weird I'm not sure how we would interpret the results there.

**Comment by stephaniehobson** [comment]
Backlog issue: #6149 (needs a new title)

**Comment by tomrittervg** [comment]
Hey @alexgibson can I follow up on this? It's possible the changes I landed in Bug 1539595 actually break FxA when it's iframed; but I'm not sure how to test since it returns an X Frame Options normally...

**Comment by alexgibson** [comment]
@tomrittervg the iframe was removed from this page some months ago. You should be safe 👍

**Comment by ejregithub** [comment]
Need to check L10n coverage on the newest version (accounts-2019) and confirm we have sufficient local coverage in that.

**Comment by alexgibson** [comment]
Bedrock PR: https://github.com/mozilla/bedrock/pull/7363
L10n PR: https://github.com/mozilla-l10n/www.mozilla.org/pull/309
