### ISSUE TITLE
EU Election Support: The /firefox/elections pages

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6849]
## Description

Description, good enough that reading the card 1 month from now, you still know what it means.

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | 1/2 day |
| PM | 1 day |
| ENG | 4 days |
| SEO | 1 hour |
| ANA | 1 day |
| DES | 1 day |
| COPY | ? |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] new templates at /firefox/elections for 3 alternate hreflangs: DE, FR, en-GB are live
- [ ] SEO - use title and description (reviewed by RRaue) for each template is in place
- [ ] CTA for FB container is included on each locale version
- [ ] page meta data requirements for Social sharing are included for each locale
- [ ] Launch on April 1
- [ ] Post election, retire the pages

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Will all the content really be the same across each locale template?

#### Tasks
- [ ] Research success/performance of the US Election page (we got good, more then 60, backlinks!)
- [ ] Eric to build out project schedule
- [ ] Create new templates at /firefox/elections for 3 alternate hreflangs: DE, FR, EN-GB
- [ ] SEO - meta title and description created/added to each template
- [ ] add CTA for FB container on each locale version
- [ ] Determine requirements and included page meta data  for Social sharing in each locale template
- [ ] Work AMO on analytics consideration
- [ ] Measure and report on session based metrics

**Comment by ejregithub** [comment]
Vince's initial pass as layout

![image](https://user-images.githubusercontent.com/20547886/53832937-459cc380-3f3c-11e9-8e4e-e28101a70963.png)

**Comment by ejregithub** [comment]
Vince will update the wireframe.

**Comment by vincejoyiv** [comment]
Updated wireframe attached below.

![image](https://user-images.githubusercontent.com/13005624/54141784-8f295a80-43e3-11e9-8e53-4bdd339d6cbc.png)

**Comment by hoosteeno** [comment]
This card will move off our sprint board and be picked up by NA Brand. cc @stephaniehobson.

**Comment by stephaniehobson** [comment]
Up on demo with placeholder content for some images: https://bedrock-demo-shobson.oregon-b.moz.works/en-US/firefox/election/
