### ISSUE TITLE
exp01 - Headline Test on /new: Replace the headline “The new Firefox”

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6851]
## Description

We know from past experience that a headline change can increase conversion rate on the /new page and that action-driven headlines that offer a benefit drive clicks. This experiment will test the hypothesis that if we replace the old headline and sub-head on the /new download page with benefits driven copy, we’ll increase the session-to-download install rate leading to an increase in active days generated by downloads because our user segmentation research demonstrates a large portion of our user base is interested in how the features of the product can improve their browsing experience.

[EN locales - Copy](https://docs.google.com/document/d/1NDXgfsCDMZpGSYOF12QO5-tD7OWVUU7GNOqNoNGkSgY/edit?usp=sharing)
[DE locale - Copy]
[Manapage for experiment parameters](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=90738380)

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | 2 days|
| PM | 1 day |
| ENG | 3 |
| SEO | 0 |
| ANA | ? |
| DES | 0 |
| COPY | 0 |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Experiment is launched and live across 5 locales in Sprint 3 (Mar 4-22)

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [x] Getting  'side-step' of stub attribution set up
- [ ] Not having the FR localization - BUT we can and should launch without it if it's not delivered in time

#### Tasks
- [ ] Code content for each of 4 variation in copy across each of the 5 locales (20 vars total)
- [x] Code Traffic Cop according to spec set up in [manapage](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=90738380)
- [x] set up 'side-step' of stub attribution - dependency on issue TBD  - 2 days to make this reusable

**Comment by alexgibson** [comment]
This is now up on demo with the following configuration:

- Experiment only runs on Windows (since measuring installs is a requirment) and with DNT disabled.
- Each cohort is configured at 25% of traffic:
  - `a`: // control
  - `b`: // privacy
  - `c`: // speed
  - `d`: // purpose
- Once a user lands on /new and meets the above criteria, one of the four variations of headline is displayed.
- Stub attribution data is then authenticated using the values below:

```javascript
{
    utm_source: 'www.mozilla.org',
    utm_medium: 'download_button',
    utm_campaign: 'firefox_new_page',
    utm_content: 'firefox_new_headline_experiment_[en|de]_v_' + variation
}
```

- An additional GA event is also then fired:

```javascript
window.dataLayer.push({
    'data-ex-name': 'firefox_new_headline_experiment_[en|de]',
    'data-ex-variant': 'v_' + variation
});
```

Demo URLs:

- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/
- https://bedrock-demo-agibson.oregon-b.moz.works/de/firefox/new/

**Comment by alexgibson** [comment]
@hoosteeno @ejregithub who's on-point to help verify analytics here?

**Comment by gkabbz** [comment]
@alexgibson UTM parameters look good to me since we are being consistent with the other experiment I looked at aka how to install. The only thing I would add is for utm_content: 'na_exp01_' + locale + '_' + variation'. I'd like to be able to isolate the different team's experiments later on so adding the na infront of the experiment so I can parse them later.

The only other question I have is around the traffic splits. They seem too high and aren't in line with what had been provided in the sizing. e.g. for NA the splits should be 2% for each of the variants with the rest of traffic going to control. Wondering where the splits here are from and where they came from? I wanna figure out where the communication is breaking down.

Here were the splits / sizing previously provided
en-US
Control - 94%, variants 1-3 - 2% each

en-CA
control - 55%, variants 15% each

en-GB
control - 46%, variants 18% each

**Comment by Kiiirby** [comment]
Thanks George!

@alexgibson Question about utm params: What happens to users who already have utm params when they arrive at /new? (for example, SEM traffic.) Are they automatically excluded from the experiment? If not, do they see the experimental pages but keep their existing utm params, and are therefore excluded from experiment reporting? Or do we "clobber" the existing params and replace them with the utm params designated for this experiment?

**Comment by alexgibson** [comment]
@Kiiirby we follow the logic here https://github.com/mozilla/bedrock/issues/6871

**Comment by Kiiirby** [comment]
Perfect that's exactly what I was looking for, thanks Alex!

**Comment by alexgibson** [comment]
Ok experiment is now configured like so:

### en-US

UTMs:

```
{
    utm_source: "www.mozilla.org", 
    utm_medium: "download_button", 
    utm_campaign: "firefox_new_page", 
    utm_content: "na_exp01_us_[1|2|3|4]"
}
```

GA:

```
    data-ex-name: "na_exp01_us"
    data-ex-variant: "v_[1|2|3|4]"
```

Cohorts:

```
{
    1: 94, 
    2: 2, 
    3: 2, 
    4: 2
}
```

### en-CA

UTMs:

```
{
    utm_source: "www.mozilla.org", 
    utm_medium: "download_button", 
    utm_campaign: "firefox_new_page", 
    utm_content: "na_exp01_ca_[1|2|3|4]"
}
```

GA:

```
    data-ex-name: "na_exp01_ca", 
    data-ex-variant: "v_[1|2|3|4]"
```

Cohorts:

```
{
    1: 55, 
    2: 15, 
    3: 15, 
    4: 15
}
```

### en-GB

UTMs:

```
{
    utm_source: "www.mozilla.org", 
    utm_medium: "download_button", 
    utm_campaign: "firefox_new_page", 
    utm_content: "na_exp01_gb_[1|2|3|4]"
}
```

GA:

```
     data-ex-name: "na_exp01_gb", 
    data-ex-variant: "v_[1|2|3|4]"
```

Cohorts:

```
{
    1: 46, 
    2: 18, 
    3: 18, 
    4: 18
}
```

### de

UTMs:

```
{
    utm_source: "www.mozilla.org", 
    utm_medium: "download_button", 
    utm_campaign: "firefox_new_page", 
    utm_content: "na_exp01_de_[1|2|3|4]"
}
```

GA:

```
    data-ex-name: "na_exp01_de", 
    data-ex-variant: "v_[1|2|3|4]"
```

Cohorts:

```
{
    1: 70, 
    2: 10, 
    3: 10, 
    4: 10
}
```

**Comment by alexgibson** [comment]
Ok, this experiment is now ready to go.

**Comment by alexgibson** [comment]
Noting here that en-US has been cut (for now) from the experiment list here, so that we don't conflict with another high priority experiment https://github.com/mozilla/bedrock/issues/6899
