### ISSUE TITLE
Build SEM-specific default download experience

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#6855]
## Description

Build a default download page for SEM traffic.

* [7 sheets here](https://docs.google.com/document/d/1PucezGPizQFe2bZemAaISiig1bueFPvkEPhB8biLCEM/edit)

### Estimates 
(How much time in hours (up to 2), then in 1/2 day increments it will take each role to complete the work required to meet the Success Criteria established for this issue).

| Estimates |  |
| ------------- | ------------- |
| TL = TeamLead | |
| PM = Program Manager | |
| Eng = Engineer | |
| SEO | |
| ANA = Analytics | |
| DES = Design | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Use existing strings from /new but create a new .lang file for the page
- [ ] Canonicalize the page to /new so this page is not indexed
- [ ] Build for DE and en-GB locales
- [ ] Exclude complex, Firefox-only features of the current /new page
- [ ] Launch the page at /firefox/campaign/

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] 

#### Tasks
- [ ] Understand the l10n approach
- [ ] Build the page(s)
- [ ] Build the lang file(s)
- [ ] Launch on demo
- [ ] Ensure new page(s) respond to DE and en-GB requests
