### ISSUE TITLE
Update front-end unit test dependencies

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6867]
## Description

Now that bedrock has updated to Gulp 4, we should also update our front-end unit test framework to use the latest dependencies:
                 
- `jasmine-core`                                 
- `karma`                              
- `karma-coverage`
- `karma-firefox-launcher`
- `karma-jasmine`     
- `sinon`

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Dependencies use the latest versions available on NPM.
- [x] Unit tests pass locally
- [x] Unit tests pass in CI

#### Tasks
- [x] Update dependencies.
- [x] Update unit tests where syntax changes may be required.
