### ISSUE TITLE
Update eslint to use @mozilla-protocol/eslint-config

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6868]
## Description

Now that bedrock has updated to Gulp 4, we should also update the version of ESLint that bedrock uses. This would also be a good time to switch to using the new [Protocol shared config](https://github.com/mozilla/eslint-config-protocol/).

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | 1 day |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Bedrock is using the latest version of ESLint.
- [ ] Bedrock config inerits from Protocol config.
- [ ] JS is free of linting errors.

#### Tasks
- [x] Update `gulp-eslint` dependency to the laterst NPM version.
- [x] Import new Protocol shared config.
- [x] Update any existing linting rules where necessary.
