### ISSUE TITLE
Update bedrock to the latest version of Stylelint.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6869]
## Description
Now that bedrock has updated to Gulp 4.0, we should also update our version of Stylelint.
---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Bedrock uses the latest version of Stylelint.
- [x] CSS assets are free of linting errors.

#### Tasks
- [x] Update `gulp-stylelint` to the latest version on NPM.
- [x] Update bedrock's stylelint rules where necessary.
- [x] Fix linting issues where necessary.
