### ISSUE TITLE
Update bedrock to latest version of gulp-less.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6870]
## Description

Now that bedrock has updated to Gulp 4, we should also update the version of `gulp-less` that we depend on. We should also update `gulp-clean-css` and `clean-css-cli` whilst we're at it.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Bedrock uses the latest version of Less.
- [x] All Less stylesheets compile without error.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Small risk of regession caused by processing CSS using a new major version.

#### Tasks
- [x] Update `gulp-less`.
- [x] Update `gulp-clean-css`.
- [x] Update `clean-css-cli`.

**Comment by alexgibson** [comment]
This issue is not yet complete, it's still waiting on code review.
