### ISSUE TITLE
Make "measuring installs" a repeatable, modular piece of code

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#6871]
(aka stub-attribution sidestep)

## Description

We're going to be measuring installs for some number of experiments in 2019, which requires us to change how we handle stub attribution code. [We've done that in a bespoke way](https://github.com/mozilla/bedrock/issues/6704#issuecomment-459357095). This makes it repeatable.

### Estimates 
(How much time in hours (up to 2), then in 1/2 day increments it will take each role to complete the work required to meet the Success Criteria established for this issue).

| Estimates |  |
| ------------- | ------------- |
| TL = TeamLead | |
| PM = Program Manager | |
| Eng = Engineer | 2 days |
| SEO | |
| ANA = Analytics | |
| DES = Design | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] We can measure install rate for people clicking on a particular download button
- [ ] We do not break any upstream utm parameters
    * If there is no utm_content param, then we can add it, with a value that includes the experiment identifier and the variation identifier as in `utm_content=download_thanks_install_experiment-v-{a|b|c|d}`
    * If we add a utm_content param, we must ensure that utm_source, utm_medium and utm_content are also populated. If any are missing then we can fill them with default values, e.g. `utm_source=www.mozilla.org`, `utm_medium=download_button{or other ui treatment}`, `utm_campaign=download_thanks_page{or other campaign}`.
    * We should not overwrite utm parameters that exist. 

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] Product may not include feature X by release day Y. . .

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] Code the page using these assets supplied by team x
