### ISSUE TITLE
Update SEO page for Ad Blocker

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6879]
## Description

The copy on this page is out of date since the developments released in 65. https://www.mozilla.org/en-US/firefox/features/adblocker/ 

Copy doc:
https://docs.google.com/document/d/1ZSvg6Qh9Rbqzu_7Mqo5CNEitAH7ryxNg5DyONmnJ6EA/edit

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | 3 | (string extraction)
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This page is updated so the DE team can localize it with the new content
- [ ] Meta data does not change
- [ ] Strings are extracted to Pontoon and tagged as optional for localizers
- [ ] Anika on the EU team is notified so she can add strings for the DE version in Pontoon

#### Tasks
- [ ] Code it with the provide copy
- [ ] As with the 64-bit SEO page, add a download button in the hero section
- [x] Confirm w. @rraue that this SEO page can be opened to all locales in Pontoon 
- [x] Verify that meta data does not need to change

**Comment by amychurchwell** [comment]
@ejregithub in the copy deck it says "[Insert Content Blocking menu]" --what is the content blocking menu? 
(Also is this copy final? It says "Headline Options:" at the top which makes me feel like it is a WIP.)

**Comment by ejregithub** [comment]
Hi Amy - I updated to the link to the copy doc that is now in our template, but I see the same things in the newer version - https://docs.google.com/document/d/1ZSvg6Qh9Rbqzu_7Mqo5CNEitAH7ryxNg5DyONmnJ6EA/edit

The headline should not be listed as an option (it's 'it'), i've reflected this in the copy.

Meanwhile, I've asked Chelsea to insert screenshots from the product to help us in deteriming what should be placed in the bracketed comments:

[Insert Content Blocking menu]
![Screen Shot 2019-04-11 at 4 09 10 PM](https://user-images.githubusercontent.com/20547886/55998695-3c59f180-5c74-11e9-836f-21577151d8d4.png)

[Insert full Content Blocking Menu with modes]
[Insert image of Custom Mode with all the options]
[Insert part of Custom Mode that shows Tracker options]
[Insert part of Custom Mode that shows Cookies options]
[Image of the Do Not Track option in Custom Mode]

**Comment by ejregithub** [comment]
@amychurchwell - Chelsea updated the copy doc with images for each of the sections in question.  Please review. Take better/higher res images as appropriate and don't hesitate to reach out with any questions.

**Comment by amychurchwell** [comment]
do any of the links in the copy doc need to have utm parameters?

**Comment by amychurchwell** [comment]
@ejregithub up on demo for stakeholder review: https://bedrock-demo-achurchwell.oregon-b.moz.works/en-US/firefox/features/adblocker/

**Comment by ejregithub** [comment]
@amychurchwell - Aleks noticed a missing 's' on tracker(s) in this sentence: 

"On Firefox, you can use Privacy or Content Blocking settings to get even more control over ad trackers that serve you the ads."
