### ISSUE TITLE
exp-predownload-newsletter-new: Designs for predownload newsletter signup CTA /new and/or /thanks pages

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6884]
## Description

Build an experiment to discover if any variation of a pre-download modal works well on the /new page. Suggest ~4 variations, see link below for ideas. Suggest answering questions like..
* Does more description of benefits change performance?
* Does it work as well on the /thanks page? Before or during download?

Reference:
- [Experiment Plan](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=90742108)
- Good ideas for variations #6562
- Original issue #5944 
- Relaunch #6456

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | 2 days |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Experiment produces data we can analyze to answer the question posed by the hypothesis
- [ ] Experiment produces recommendations for next steps

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] 

#### Tasks
- [ ] Variations are designed & vetted by engineering stakeholders
- [ ] Experiment is designed with precision about segments, timeline, variations, expectations
- [ ] Experiment is reviewed by accountable stakeholders
- [ ] Experiment is launched on /new

**Comment by alexgibson** [comment]
I spent some time this morning trying to some up with ideas for possible variations to test on /thanks/ 

Note: I'm no designer, these are just super quick edits I made in Dev Tools to serve as a starting point for discussion (and to hopefully generate more ideas from others).

**Idea 1** 

Improve conversions for the newsletter form that's already on the page.

![centered-newsletter](https://user-images.githubusercontent.com/400117/54126308-20f29100-43ff-11e9-98b4-c86e20d0929f.png)

- Download could still be triggered on page load just as it is now.
- Making the newsletter single column and centered on the page, bringing a little tighter to Firefox logo could make it convert better. 
- Uses current copy and form design that's already on the /thanks/ page, but we could also try improve & refine.

**Idea 2** 

In-page dual CTA's for "download & sign up", or "just download".

![dual-proposition](https://user-images.githubusercontent.com/400117/54126620-e0474780-43ff-11e9-9022-c7ab1a7eb338.png)

- Download would no longer be triggered on page load, requiring a second interaction instead.
- Uses current copy and form design that's already on the /thanks/ page, but we could also try improve & refine.

**Idea 3**

Offer a higher value proposition for entering an email address.

![firefox-minitor](https://user-images.githubusercontent.com/400117/54126813-52b82780-4400-11e9-9ae1-1509253d7018.png)

- Same as Idea 2, but instead we test the effectiveness of a higher value proposition for exchanging some personal data. In this example, signing up for Firefox Monitor instead of just an email newsletter.
- Note there is also an opt-in checkbox for signing up to a newsletter in the Firefox Monitor form.
- Firefox Monitor was the first example I thought of, but we could also try out other offers that are centered around the theme of privacy & security.

**Comment by hoosteeno** [comment]
Nice work, Alex! 

Several of these have the same effect as the modal, they just put the inquiry into an interstitial page. 
Do you feel like an interstitial is somehow better than a modal? 

@vincejoyiv Can you take these, and [Stephanie's earlier suggestions](https://github.com/mozilla/bedrock/issues/6562), and come up with a few you think we should test?

**Comment by alexgibson** [comment]
> Do you feel like an interstitial is somehow better than a modal?

To be honest, I struggled to find a suitable solution using a modal as a UI, since they can be nature be closed without explicitly choosing an option. They are also perceived as more obtrusive, especially when appearing automatically on page load. I'd love for us to find a solution that does not require a modal as a UI.

**Comment by michaelmccombie** [comment]
@hoosteeno I'm jumping in for Vince so he can work on some other stuff. I'll mock up some things based on the above and what Stephanie has in mind.

**Comment by claychaffin** [comment]
@alexgibson I love your Monitor approach -- offers the users good value. Wondering, is the opt-in essential? Concern is that many (most?) won't opt in, and if we honor that preference then in future emails we shouldn't pitch them anything but safety tips (and send breach alerts). We could ditch the opt-in and adjust the promise in the copy "Sign up to get breach alerts, safety tips and other helpful information from Firefox Monitor and Firefox."

**Comment by michaelmccombie** [comment]
Here's a link to the project in Abstract, still a WIP
https://share.goabstract.com/f881714a-a2c2-4db8-85e8-2f1b7d382cde

**Comment by hoosteeno** [comment]
@michaelmccombie what's the status of the project you link to above? I'm looking for some UX experiments that describe a user's flow through the funnel, with a newsletter CTA in the middle. I can see some nice interfaces in the Abstract you link to, but I need to see some connective tissue explaining what this is testing and how it differs from the current treatment on /firefox. Does this make sense?

**Comment by michaelmccombie** [comment]
I'm going to break this issue into several smaller issues to make it easier to track.
Here is the first proposal, I will update this thread as these new issues are created.
https://github.com/mozilla/bedrock/issues/6935

**Comment by michaelmccombie** [comment]
Here is the second proposal, adding the newsletter modal to /firefox/new
https://github.com/mozilla/bedrock/issues/6938

**Comment by hoosteeno** [comment]
> Here are the series of experiments broken into separate tickets. I'll be sure to add to this list as new experiments are proposed.

@michaelmccombie Thank you. I really appreciate that the 4 variations you've pitched represent *different moments in the journey*. This seems like the right thing for us to understand right now: Where is the most effective place to pitch this CTA?
