### ISSUE TITLE
Revive email CTA pre-download on /firefox/ for EN, DE and FR

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6886]
## Description

Restore content asking for email signup prior to download of Firefox, on the /firefox/ webpage, making this shown to 100% of:
- [x] All en locales
- [x] DE
- [x] FR

Reference:
- Original issue #5944 
- Relaunch #6456

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | 1 1/2 days |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Newsletter modal is shown for 100% of audience for en, de and fr locales.
- [x] Newsletter is shown only for desktop users.
- [x] Other locales can still download as normal.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Downloads will be impacted.
- [ ] Brand perception could be hurt.
- [ ] The current UX is poor, in that it does not make it obvious enough that signing up for the newsletter is optional.

#### Tasks
- [x] Refactor experiment code to be a more fully baked feature on the page.
- [x] Fix any UX problems we have scope to do in a very short timeframe?
- [ ] Write automated tests for the feature.

**Comment by alexgibson** [comment]
Work in progress is up on demo: 

- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/
- https://bedrock-demo-agibson.oregon-b.moz.works/de/firefox/
- https://bedrock-demo-agibson.oregon-b.moz.works/fr/firefox/

I still need to spend some time writing tests and tidying things up. Whilst that is happening, I wonder if there are any quick / simple improvements that we could make in a short amount of time before this goes out, focusing particularly around the "Continue Firefox Download" link perhaps?

Particularly interested in @vincejoyiv's thoughts here.

**Comment by alexgibson** [comment]
I also updated the success criteria, as well as the risks section above ^

**Comment by hoosteeno** [comment]
> Particularly interested in @vincejoyiv's thoughts here.

The team discussed in Slack. @craigcook produced a mockup that @vincejoyiv  gave the nod to. I'm attaching it. Let's launch this modified version of the modal to 100% of /firefox/ visitors in locales where we have localizations already (I think Tier 1, true?). Let's plan for this to be a part of the page for at least several weeks, if not longer.

![image](https://user-images.githubusercontent.com/94519/53942289-9c5ae800-4077-11e9-8cab-760fdfbaebd7.png)

**Comment by alexgibson** [comment]
> Let's launch this modified version of the modal to 100% of /firefox/ visitors in locales where we have localizations already (I think Tier 1, true?)

We have existing translations for English, French and German.

**Comment by alexgibson** [comment]
It occured to me that I can't write automated tests for this feature yet since it is behind a switch 😕

I'll file a followup issue to write tests once we're live and are confident that data looks ok.

**Comment by alexgibson** [comment]
Ok, design updates are in and up on demo, this is good for review.

**Comment by alexgibson** [comment]
@hoosteeno @sghoseWI One thing here that we could do with is some verification that we're tracking clicks on the right things still, now that this is being promoted to "not just an experiment".

Previously we we're firing custom GA events for the page variations, but obviously here we're now no longer doing that.

Key questions that could do with some validation:

- Are newsletter signups being counted correctly still.
- Do we need to track anything specific on the "Continue Firefox Download" link for it to count as a regular download event, or is landing on /thanks/ enough for this in itself?

Demo link: https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/

**Comment by hoosteeno** [comment]
Thank you Alex!

>     * Are newsletter signups being counted correctly still (should be a "yes" as nothing has changed here).

Let's take "no changes" as the answer here. If the form post is occurring, then any instrumentation questions are out of our hands right now.

>     * Is signing up for the newsletter and then being forwarded to /thanks/ enough to register as a regular download in GA?

Yes.

>     * Do we need to track anything specific on the "Continue Firefox Download" link for it to count as a regular download?

I think we should instrument an event on the "Continue Firefox Download" button. The count of "no thanks" is valuable info. But visiting /thanks will trigger a download increment.

>     * Will clicking the regular (green) download button prior to the modal opening count as a download event in GA? Do we need to do something to try and prevent this event from happening?

Only one download per session counts as a download in our reporting. We often see sessions clicking 2, 3, 6, 8 times. Those count as one download.

>     * In the experiment we only showed the modal on the primary download button. Should we now be doing this for every download button on the page? (I'm assuming yes).

Yes, please, excluding global nav if that helps reduce complexity.

> 
>     * I'm using the copy from variation B, which (i think) was the winner when compared to C. Is this OK?

Yes, variation B is the one to use.

**Comment by claychaffin** [comment]
@here I propose that for tomorrow we add the word "your" to our headline, as follows (quotation marks mine):
"Learn how to make your Firefox even faster, smarter and more secure."

**Comment by hoosteeno** [comment]
> @here I propose that for tomorrow we add the word "your" to our headline, as follows (quotation marks mine):
> "Learn how to make your Firefox even faster, smarter and more secure."

Solid suggestion. We're trying to launch in 5 locales (3 EN, but still) with no localization step, which means we can't change strings.

**Comment by alexgibson** [comment]
> I think we should instrument an event on the "Continue Firefox Download" button. The count of "no thanks" is valuable info. But visiting /thanks will trigger a download increment.

We already have data-attributes for GA on the continue download link, so hopefully this should be enough as is.

> I propose that for tomorrow we add the word "your" to our headline, as follows (quotation marks mine): "Learn how to make your Firefox even faster, smarter and more secure."

As Justin says, the text is localized so we can't change it without requiring new translations. I can change this for English only however, which is easy enough to do. I'll make sure we add it 👍

**Comment by claychaffin** [comment]
Thanks @alexgibson -- I'm glad you can change it for English

**Comment by vincejoyiv** [comment]
When a user does enter their email in the form, the modal content changes to a “thanks” message, which flashes for a half-second before automatically loading the /thanks page.

https://www.dropbox.com/s/r0su83403kodlmb/Screenshot%202019-03-08%2013.16.04.png?dl=0

What should this experience be?
- user has to click _another_ button to finish the download?
- why does this modal have an option to close? what happens if user clicks close button?
- does the user need to see this message? for legal reasons or otherwise?
- should we show a message that can't be read in the time it's on screen?

**Comment by hoosteeno** [comment]
I'd like your thoughts on the optimal experience, @vincejoyiv. IMO, a button saying "Download Firefox & Sign Up" should do both things. As a user choosing that option, I would prefer it to do both things.

**Comment by alexgibson** [comment]
@vincejoyiv @hoosteeno I've been thinking about what happens here and I think we can likely eliminate this flash of messaging entirely.

What would happen is:

- Person fills in the form and hits "Download Firefox & Sign Up".
- We show the (current) loading spinner whilst subscription data is sent.
- As soon as we get the success message, auto-close the immediately forward to /thanks/

I've pushed this to demo so you can test this out.

**Comment by vincejoyiv** [comment]
@alexgibson that looks 💯 to me. Thanks!

**Comment by hoosteeno** [comment]
Agree. Great work.

**Comment by hoosteeno** [comment]
In Lauren's absence, Michele is the stakeholder reviewing the treatment here. TLDR, we have a green light to launch and improve.

---

<img width="494" alt="Screen Shot 2019-03-11 at 3 08 14 PM" src="https://user-images.githubusercontent.com/94519/54158257-b4cc5900-440f-11e9-8809-f4fa8dd355e0.png">

**Comment by hoosteeno** [comment]
Usertesting on this modal is [here](https://docs.google.com/document/d/11g_tHnkO_xtDDYPiwrIi4YD3_0OllQxrwz8semiEkRk/edit#).
