### ISSUE TITLE
Graduate Global FxA CTA

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6887]
## Description

We previously ran this experiment and need to make it permanent in the locales in which it has been localized.

The original work - #6629 
The next rev with localizations - #6792

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| ANA | ? |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Global CTA is live in en, DE and FR
- [ ] Content (strings) are set to be localizable to all locales

#### Tasks
- [ ] Submit PR with strings tagged for L10n
- [ ] Reach out to Peiying with DE and FR content in request to extract strings - @ejregithub 
- [ ] Communicate to Accounts team (Alex Davis) that this is happening - @ejregithub 

Localized strings
EN | DE | FR
-- | -- | --
Get a Firefox Account | Firefox-Konto erstellen | Créez un compte Firefox
Check out the Benefits | Das sind deine Vorteile | Découvrez les avantages
