### ISSUE TITLE
Add download button to Win 64 landing page -- center of page in the header

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6892]
## Description

Including a download button in the header was omitted, overlooked in the original design. The ask here is to include the standard download button, no color change requests, in the middle of the hero section as shown in the attached image.

### Estimates

| Estimates |  |
| ------------- | ------------- |
| ENG | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Is live with GA in place
- [ ] Uses the standard button and string

#### Tasks
- [ ] Add download button on the page
- [ ] Instrument for GA data recording

**Comment by ejregithub** [comment]
![image](https://user-images.githubusercontent.com/20547886/53899343-d8963600-3fee-11e9-8438-518eacca68f9.png)

**Comment by amychurchwell** [comment]
Assuming that this stray download button is not a part of the mock-up? Continuing under that assumption.

<img width="925" alt="Screen Shot 2019-03-20 at 12 31 29 PM" src="https://user-images.githubusercontent.com/30483988/54713543-1aa19a80-4b0c-11e9-9722-e7a31da2de4c.png">
