### ISSUE TITLE
Migrate existing SEM download pages from /new to /campaign

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6894]
## Description
Now that `/firefox/campaign/` is live, we should migrate all existing SEM download page variations from `/firefox/new/` to `/firefox/campaign/`.

List of SEM download/campaign page variations:

- https://www.mozilla.org/en-US/firefox/new/?xv=betterbrowser
- https://www.mozilla.org/en-US/firefox/new/?xv=safari
- https://www.mozilla.org/en-US/firefox/new/?xv=edge
- https://www.mozilla.org/de/firefox/new/?xv=berlin
- https://www.mozilla.org/de/firefox/new/?xv=aus-gruenden
- https://www.mozilla.org/de/firefox/new/?xv=herz
- https://www.mozilla.org/de/firefox/new/?xv=geschwindigkeit
- https://www.mozilla.org/de/firefox/new/?xv=privatsphare
- https://www.mozilla.org/de/firefox/new/?xv=auf-deiner-seite

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | 1 day |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page variations are shown at `/firefox/campaign/?xv={% variation %}`

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] SEM team will need to update their ads to point to the new URL. This may take some coordination.

#### Tasks
- [ ] Update URLs/Views to show the correct templates.
- [ ] Update python unit tests for the new variations.
- [ ] Make /new/ versions available concurrently to /campaign URL versions so no SEM ad spends are lost.

**Comment by guyfitzpatrick** [comment]
@alexgibson those German links need to be updated to include /de i.e. https://www.mozilla.org/en-US/firefox/new/?xv=auf-deiner-seite to https://www.mozilla.org/de/firefox/new/?xv=auf-deiner-seite

**Comment by alexgibson** [comment]
@guyfitzpatrick thanks, I have updated this in the list above 👍

**Comment by guyfitzpatrick** [comment]
@alexgibson the following pages seem to have been replaced with /new:

https://www.mozilla.org/en-US/firefox/new/?xv=betterbrowser
https://www.mozilla.org/en-US/firefox/new/?xv=safari
https://www.mozilla.org/en-US/firefox/new/?xv=edge

**Comment by alexgibson** [comment]
@guyfitzpatrick thanks for alerting. I believe this is a bug introduced in https://github.com/mozilla/bedrock/issues/6899. I'll see what we can do to get it to resolved, but it may also mean waiting until that experiment is over.

This is a great exaple of why we need to simplify complexity on /new, by moving these campaign pages over to /campaign.

**Comment by alexgibson** [comment]
I filed a bug for above: https://github.com/mozilla/bedrock/issues/6974

**Comment by alexgibson** [comment]
@guyfitzpatrick I'm picking up this work today. My plan for migrating these URLs is as follows:

1. Make all the above URLs available at both `/new` and `/campaign`.
2. Once live, you can repoint your ads at the new `/campaign` URLs.
3. Once complete, I'll then remove the pages from `/new`.

Does this sound workable enough to you?

Thanks

**Comment by guyfitzpatrick** [comment]
Sounds good, thanks!

**Comment by alexgibson** [comment]
@guyfitzpatrick 

All the pages are now live in production:

- https://www.mozilla.org/en-US/firefox/campaign/?xv=betterbrowser
- https://www.mozilla.org/en-US/firefox/campaign/?xv=safari
- https://www.mozilla.org/en-US/firefox/campaign/?xv=edge
- https://www.mozilla.org/de/firefox/campaign/?xv=berlin
- https://www.mozilla.org/de/firefox/campaign/?xv=aus-gruenden
- https://www.mozilla.org/de/firefox/campaign/?xv=herz
- https://www.mozilla.org/de/firefox/campaign/?xv=geschwindigkeit
- https://www.mozilla.org/de/firefox/campaign/?xv=privatsphare
- https://www.mozilla.org/de/firefox/campaign/?xv=auf-deiner-seite

Can you please repoint the ads to these new URLs? Once that is done, please let me know and I will remove the old references from `/firefox/new/`. Many thanks.

**Comment by amychurchwell** [comment]
Closing this issue as primary task is complete. Opened issue for removal of the old references from `/firefox/new/` -- https://github.com/mozilla/bedrock/issues/7046
