### ISSUE TITLE
Experiment: Dry market test for new Desktop pitches

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6899]
## Description

Executive request to test a couple desktop product pitches on /new with a dry market test. 

* Experiment Plan: https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=90741743

[Master Project Doc](https://docs.google.com/document/d/1Yb5Rc_uO_Yk6PJbqvP5W-5KfsN7sk3FwjYnyeq2eOG4/edit#)

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL |2 days|
| PM | |
| ENG | 2 days  |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Experiment with 3 variations (including control) is in market for a week with the parameters specified in experiment plan
- [ ] Data gathered from experiment answers the question posed by the hypothesis

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Establish RASCI
- [ ] Write copy for UTP variation
- [ ] Write copy for Bundle variation
- [ ] Share copy with working team; get approved
- [ ] Put copy into mockups, probably devtools screenshots
- [ ] Share mockups with working team, exec stakeholders
- [ ] Build mockups in code
- [ ] Build TrafficCop experiment
- [ ] Launch
- [ ] Analyze & present analysis

**Comment by ejregithub** [comment]
Blocked on content from PMM/Porfirio
