### ISSUE TITLE
Add Firefox Send to the /firefox/accounts/ page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#6914]
## Description

Firefox Send (https://send.firefox.com/) has now launched and adds a real incentive for signing up and using a Firefox Account (send files up to 2.5gb if you're signed-in). It is also not dependent on using Firefox and works with any browser. 

We should add Send as a feature to the /accounts/ page as a benefit.

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Design and copy delivered by the end of the sprint (ends 4/12)
- [ ] Is tagged for L10n

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Identify Celeste as A in RASCI, Michele likely as C
- [ ] Clay to write Copy
- [ ] Websites to create Design (Mark)

**Comment by hoosteeno** [comment]
Whoever picks this up, please see https://github.com/mozilla/bedrock/issues/6953.

**Comment by mrkwvr** [comment]
> Do we have design and copy for this yet?

no not yet, Clay and I will be working on those

**Comment by claychaffin** [comment]
Hi All, I'm *blocked* on _accurate_ Send copy until we get a messaging brief. I've asked Celeste/Lauren for it in FxA - benefits channel.

**Comment by claychaffin** [comment]
https://github.com/mozilla/bedrock/issues/6914
Hi All,  I'm *blocked* on _accurate_ Send copy until we get a messaging brief. I've asked Celeste/Lauren for it in FxA - benefits channel.

**Comment by hoosteeno** [comment]
This is ready for design and copy review. Copy and image in attached screenshot comes from WNP66.

![Screen Shot 2019-04-12 at 5 18 04 PM](https://user-images.githubusercontent.com/94519/56070746-f3bf3880-5d46-11e9-8396-91bfba2b3f38.png)

**Comment by hoosteeno** [comment]
@claychaffin @mrkwvr Can you take a look? [Full screenshot for context here](https://user-images.githubusercontent.com/94519/56070849-9ecff200-5d47-11e9-8073-cbadc28f584f.png).

**Comment by claychaffin** [comment]
Hey @Justin Crawford <hoosteeno@mozilla.com>, legal forbids "secret agent"
so I'm looking for a replacement. Otherwise, I like this copy. Thanks.

**Comment by mrkwvr** [comment]
@hoosteeno I didn't realize we already had an illustration and copy for this. This is the illustration I created for the page if we want to use that. I think either one works
![Screen Shot 2019-04-15 at 10 29 30 AM](https://user-images.githubusercontent.com/29285941/56143098-e89a2180-5f6d-11e9-9721-40a351e41f97.png)

**Comment by claychaffin** [comment]
Here is the final copy. Thanks for your patience.
https://docs.google.com/document/d/1rmelaXbYKQ3FiDLhNIT1VItF5TQ8_fEh2ngQGAFx1-4/edit?usp=sharing
