### ISSUE TITLE
Experiment: Accessibility improvements to /download/thanks

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/bedrock#6935]
## Description

This is a proposal for a handful of visual improvements that will make the page easier to read, brings more attention to the CTA, and prepares us for the new branding. 

**1. Center the content**
The current design has all of the content justified to the left, with nothing to the right of that content. Centering the content will bring balance to the page and adds a visual difference that will hopefully catch users attention when they land on this page.

**2. Place the content on a white panel**
This accomplishes several things: 
- Increases legibility by changing the text color to black and placing it on a white background
- Calls attention to itself by creating a visual separation from the background.
- Allows us to use a blue button instead of a white one
- Makes it easy to change the background image.

**3. Use a blue sign up button**
Blue buttons perform better than black/white buttons.

**4. Plans for future branding**
The blue wave is scheduled to disappear in the near future. With this design we can swap that blue wave for any image of any color without having to worry about the content that is placed in the panel.

**5. Remove the Mozilla logo**
The logo already exists in the footer of the page and there is another experiment which proposes placing the site navigation on this page (https://github.com/mozilla/bedrock/issues/6261) so the logo will reappear if that test is successful. The newsletter is Firefox branded so removing the Mozilla logo makes the page feel like it is coming from that singular voice (Firefox).

### Current /thanks
![image](https://user-images.githubusercontent.com/5924575/54626875-574b9400-4a2f-11e9-8a71-1e94f1213fc8.png)

### Proposed /thanks
![image](https://user-images.githubusercontent.com/5924575/54628416-bd85e600-4a32-11e9-8213-d916db7baf4a.png)

### Note
This is the first in a series of experiments. See also:
#6938 - Experiment: Newsletter modal on /new
#6939 - Experiment: Newsletter page on pre-download on /new
#6944 - Experiment: Newsletter CTA on /firefox/new

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | 1 Day |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Newsletter sign ups either remain consistent or improve.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Simultaneous experiments on the page or in this flow could skew results.

#### Tasks
- [x] Design a mock-up
- [ ] Build the page
- [ ] Launch the page

**Comment by hoosteeno** [comment]
Cool!

The 'Current /thanks' treatment appears post-download. Is that true of the 'Proposed /thanks', too?

**Comment by michaelmccombie** [comment]
Yes, I just realized I forgot to include the "Your download will..." message at the top of the page so I updated the image to add that back in.

This specific treatment is for users who download Firefox directly from /new so it is a post-download experience.

**Comment by hoosteeno** [comment]
So if we were to write a hypothesis about this in the framework of [the experiment we're discussing](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=90742108), would it sound something like this?

"A post-download treatment can perform as well as a pre-download treatment if it has a more compelling design."

**Comment by michaelmccombie** [comment]
I think that would be the wrong hypothesis for this particular experiment. 

Our control in the hypothesis should be the current page/ experience and we should measure ourselves against that metric. If this experiment proves to be successful than we can move up the baseline on the pre-download experiment from "needs to outperform X number of sign-ups" to "needs to outperform Y number of sign-ups".

So I would run this test first and write a hypothesis like this:
"A more compelling and accessible design should increase the performance of the current post-download experience."

Then run a pre-download test with a hypothesis like this:
"A pre-download treatment can perform better than the newly implement post-download experiment"

**Comment by alexgibson** [comment]
@michaelmccombie Hi, can you please link to a sketch file for this mockup? I've found all the other variations, but this one does not seem to be included in that same file. Thanks!

**Comment by alexgibson** [comment]
Oh, please disregard @michaelmccombie I've found it 👍

**Comment by alexgibson** [comment]
Centered newsletter post-download on /thanks/ page:
This user flow is now up on demo:

- https://www-demo1.allizom.org/en-US/firefox/new/?xv=pre-dl&v=b

![image](https://user-images.githubusercontent.com/400117/55236875-ce034100-5228-11e9-8097-ee69905c4200.png)

![image](https://user-images.githubusercontent.com/400117/55236912-dce9f380-5228-11e9-8855-33c82f8a875a.png)

![image](https://user-images.githubusercontent.com/400117/55236947-f1c68700-5228-11e9-8b92-fe95c56e6c87.png)

**Comment by rraue** [comment]
I have no SEO concerns about this implementation.

**Comment by alexgibson** [comment]
This experiment is in the wild and will be finishing shortly. Closing this issue out.
