### ISSUE TITLE
Experiment: Newsletter modal on /new

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/bedrock#6938]
## Description

Clicking on the "download" button will open up a modal prompting a user to either download Firefox or sign up for a newsletter and download simultaneously. This iteration will also add an alternative /thanks page for those who select the newsletter option. 

**Newsletter Modal**
![image](https://user-images.githubusercontent.com/5924575/54637835-d0a2b100-4a46-11e9-92b8-20392b10f3b7.png)

**/thanks (if a user selects the "newsletter" option**
![image](https://user-images.githubusercontent.com/5924575/54637916-06479a00-4a47-11e9-8c7e-7e59bcf1ef87.png)

**/thanks (if a user selects the "continue with download" option)**
![image](https://user-images.githubusercontent.com/5924575/54637934-0f386b80-4a47-11e9-8374-8914058cc6f4.png)

### Note
This is the second in a series of experiments. See also:
#6935 - Experiment: Accessibility improvements on /thanks
#6939 - Experiment: Newsletter page on pre-download on /new
#6944 - Experiment: Newsletter CTA on /firefox/new

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | 1 hour |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] The newsletter modal doesn't decrease downloads beyond an acceptable limit

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] The newsletter modal decreases downloads
- [ ] Negative comments on social media sites impacting brand perception

#### Tasks
- [ ] Design a mock-up
- [ ] Build out the modal/page
- [ ] Launch the experiment

**Comment by alexgibson** [comment]
This user flow is now up on demo (use a non-FF browser to see the modal):

- https://www-demo1.allizom.org/en-US/firefox/new/?xv=pre-dl&v=c

Page load:
![image](https://user-images.githubusercontent.com/400117/55237280-b9737880-5229-11e9-94b9-05b3949bf397.png)

Click download:
![image](https://user-images.githubusercontent.com/400117/55237296-c2fce080-5229-11e9-9127-cc53f6375c52.png)

Newsletter success:
![image](https://user-images.githubusercontent.com/400117/55237417-0c4d3000-522a-11e9-8b85-bd181eb70b2c.png)

Newsletter no thanks:
![image](https://user-images.githubusercontent.com/400117/55237440-18d18880-522a-11e9-9e9d-b469710e603b.png)

**Comment by rraue** [comment]
I have no SEO concerns about this implementation.

**Comment by alexgibson** [comment]
This experiment is in the wild and will be finishing shortly. Closing this issue out.
