### ISSUE TITLE
Experiment: Newsletter CTA on /firefox/new

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/bedrock#6944]
## Description

This proposal takes the content in the newsletter modal and adds it to the /new page. This would remove one of the steps it takes to download Firefox and sign up for the newsletter

**Current Design**
![image](https://user-images.githubusercontent.com/5924575/54648133-4e27ea80-4a62-11e9-93fb-a761e1132196.png)

**Proposed Update**
![image](https://user-images.githubusercontent.com/5924575/54648110-39e3ed80-4a62-11e9-828c-df5fac147050.png)

Note
This is the forth in a series of experiments. See also:
#6935 - Experiment: Accessibility improvements on /thanks
#6938 - Experiment: Newsletter modal on /new 
#6939 - Experiment: Newsletter page on pre-download on /new

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | 1 day |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Improves the download / sign up rate

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Reduces the download rate below an acceptable level

#### Tasks
- [ ] Design the mock-up
- [ ] Build the page
- [ ] Launch the page

**Comment by alexgibson** [comment]
This user flow is now up on demo:

- https://www-demo1.allizom.org/en-US/firefox/new/?xv=pre-dl&v=e

Page load:
![image](https://user-images.githubusercontent.com/400117/55238342-2f78df00-522c-11e9-9930-ecd5a8c6f8e6.png)

Newsletter success (initiates download)
![image](https://user-images.githubusercontent.com/400117/55238367-43244580-522c-11e9-8424-852a8dc81e96.png)

Newsletter no thanks (initiates download)
![image](https://user-images.githubusercontent.com/400117/55238392-546d5200-522c-11e9-832e-385b1a78ed64.png)

**Comment by hoosteeno** [comment]
I really appreciate how this variation fits in with the other variations in this experiment, exploring all the places we could make this kind of CTA. I'm afraid it may trigger the same SEO risk we previously saw with our FxA-on-/new work. @rraue...
* Are you concerned about SEO impacts from having this experiment run in a single locale, for e.g. 2% of visitors, for a week?
* Would you be concerned about SEO impacts if some version of this pre-download CTA went out as a new default on /new?

**Comment by rraue** [comment]
@hoosteeno 

- I am not concerned about the experiment, let's run it, even if the crawler runs into it, it does change the semantic perception but not as much as the fxa modal.

- Yes I am concerned as this page has so little content right now, that these sentences could change the perception. The concern will be less with the new feature content. More content on /new/ lowers the weight, even if its pretty prominent.

**Comment by claychaffin** [comment]
I chatted with JRouse. and here’s what we propose:
1) Keep the copy the same in all four variations to ensure we are testing the user’s experience. (Going with one version of copy for all was your request as well, as time is short.).
Please note: currently the copy in one of our variations (embedded form on /new) differs from the control copy.  Conform this copy as well, unless there's a reason not to that we're unaware of.
2) Test to identify the best performing user experience
3) Create copy variations for the winning user experience.
Separately, Jennifer and Natalie are running a rogue qualitative copy test. Jennifer will share results soon. If it did well, we should consider using it as one copy variation. Please see below**
5) Test to identify the best performing copy
6) Celebrate the winner!

![Screen Shot 2019-04-04 at 3 19 18 PM](https://user-images.githubusercontent.com/45859665/55594446-7ff0b080-56f4-11e9-8e1f-26703e021b9c.png)

**Comment by alexgibson** [comment]
@claychaffin 

> Please note: currently the copy in one of our variations (embedded form on /new) differs from the others - is this because we wish to keep "The New Firefox. Fast for good." in one variation? If not, I suggest we use the same copy we use in the other variations.

That's my guess here yes, but I'm slightly unclear on what you propose we use for copy instead here. Wouldn't using the same copy mean we lose the call-to-action to download Firefox that's seen in all other variations? It would be super helpful if you could provide some copy here that you think may work better.

![image](https://user-images.githubusercontent.com/400117/55613456-a52c0000-5782-11e9-9fcd-eb4a43c00227.png)

Just so I'm clear, you're not proposing we use this copy seen in the screenshot in this experiment. Is that right?

**Comment by claychaffin** [comment]
@hoosteeno Hi Justin:  
1) I propose that we test experience with our variations (not copy or design).
2) Do you want to use the live /firefox page modal copy as our control? Or do we not need a control since we're establishing a baseline in a new channel? And thus, we can just go with whatever new copy we think best?
3) re: Embedded Newsletter CTA on/new (#6944)
I reco not testing this variation. There's no meaningful way to add the same newsletter CTA copy used in the other variations while keeping "The New Firefox. Fast for good." in place.
Thanks.

**Comment by alexgibson** [comment]
Based on @claychaffin's copy recommendations, I'm a little lost as to what needs doing to move this epxeriment forward. I'm also a little confused as to why we wouldn't want to test the embedded email form, which feels like an important alternative UX to testing the modal. Maybe I don't quite understand why the copy needs to be identical for all variations for this experiment to still be informative?

**Comment by hoosteeno** [comment]
Clay is calling out a risk: When we run treatments that include multiple variables, we can't know which variable (copy? stage of the journey? background color?) was responsible for any observed differences in measurement. 

This is a valid concern. One mitigation is to get rid of treatments with variables we can't control, as Clay advises. Another mitigation is to be very clear in our analysis that any observed differences relate to the complete treatment, and not to some specific variable in the treatment.

I prefer the latter. In this experiment, we are trying to understand whether we have any better options than a treatment many of us find problematic. We're putting our best treatments forward. If we discover that we do (or don't) have a better option to the treatment currently in /firefox, that will be an important learning. One of the 4 options we want to test is in #6944. 

Let's run all 4, and let's be clear in our analysis that any observed differences relate to entire treatments.

**Comment by alexgibson** [comment]
< I prefer the latter. In this experiment, we are trying to understand whether we have any better options than a treatment many of us find problematic. We're putting our best treatments forward. If we discover that we do (or don't) have a better option to the treatment currently in /firefox, that will be an important learning. One of the 4 options we want to test is in #6944.

I think I have to agree here. If we were testing in which place a specific piece of copy worked best, then keeping things uniform across all variations would be something we'd want to adhere. But what we're trying to do is work out which UX flow (some pretty radically different) is the most effective, so keeping copy identical throughout 4 the flows may not really be practical taking the full funnel into account imho.

> Let's run all 4, and let's be clear in our analysis that any observed differences relate to entire treatments.

Ok, I'm going to take this as there are no changes to the copy required, and everything we have right now is what we may eventually want to move forward with post-experiment.

**Comment by hoosteeno** [comment]
I reviewed these with Lauren and she r+'d them.

**Comment by claychaffin** [comment]
@alexgibson Hi Alex, I've updated the copy deck. Please refer to my comments there for specifics. Thanks.
https://docs.google.com/document/d/1PWPGF4m1Ju2-RUqiHiaknzlicspPfSOOjWXVB8kcLes/edit?usp=sharing

**Comment by alexgibson** [comment]
This experiment is in the wild and will be finishing shortly. Closing this issue out.
