### ISSUE TITLE
new-brand-download-pages: Update /firefox/new and /download/thanks with new Firefox branding

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#6949]
## Description

- a/b test with control and single variation w. new design
- en-US only audience
- Stephanie to code (need to confirm- done)
- Justin K to provide [new designs ](https://app.goabstract.com/projects/1ce3a550-a647-11e8-9633-0bbf4af2c21f/branches/master/files/F66D28BA-6A06-43CD-933A-9654D5B303B8/pages/AB220E6F-2DC2-4ED1-B130-AF242887BA77)

### Estimates (How much time in hours (up to 2), then in 1/2 day increments it will take each role to complete the work required to meet the Success Criteria established for this issue).

| Estimates |  |
| ------------- | ------------- |
| TL = TeamLead | |
| PM = Program Manager | |
| Eng = Engineer | |
| SEO | |
| ANA = Analytics | |
| DES = Design | 0 |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is rolled out behind a switch
- [ ] Schema orgs are fixed ( @rraue ) https://github.com/mozilla/bedrock/issues/5741

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] May mean new copy, impacting dev work further
- [ ] new template could break others (like for mac, chrome, etc)

#### Tasks
- [ ] Port the page to Protocol
- [ ] Build the (5) page variations for /new
- [ ] Build the (2) page variations for /thanks
- [ ] Set up the tests and sequence the execution of each

**Comment by ejregithub** [comment]
Questions-
- is the test plan baked
- where is design?
- has dev started?
- who is stakeholder(s) - and Accountable/Approver

**Comment by ejregithub** [comment]
@stephaniehobson - you've self-assigned this so i can safely assume you're taking the coding task for the two pages.  i need to confirm with you if you will also take on setting up traffic cop for the test and putting this behind a switch, please. If you have a timeline of when you expect to deliver (by end of Sprint 4?), please let me know that as well. Thank you!

**Comment by stephaniehobson** [comment]
I will take on the coding task including setting up traffic cop and the switch.

It would be helpful to me to get a deadline from the websites team for when you want to run the test. @hoosteeno was not sure if this was a sprint candidate when I talked to him this morning.

**Comment by hoosteeno** [comment]
The websites team will take this on.

**Comment by stephaniehobson** [comment]
FYI for the dev who picks this up. There is a Protocol version of the pre-download modal in https://github.com/mozilla/bedrock/pull/7033

**Comment by rraue** [comment]
I referenced the old issue around the markup on /new and pasted there the js+ld code we should use instead of the microdata. To really fix the issue, we need a solution to get aggregated ratings for firefox. My suggestion would be to take the ratings from itunes and playstore and show them to get the search snippet.

**Comment by alexgibson** [comment]
> I referenced the old issue around the markup on /new and pasted there the js+ld code we should use instead of the microdata. To really fix the issue, we need a solution to get aggregated ratings for firefox. My suggestion would be to take the ratings from itunes and playstore and show them to get the search snippet.

This sounds like it may be worth splitting out into a separate issue, as opposed to adding to scope here.

**Comment by rraue** [comment]
Sure, we just then shouldn't much care about the microdata or even delete it, as it has no value right now without rating and with errors.

**Comment by alexgibson** [comment]
Closing this, as the pages were redesigned for trailhead.
