### ISSUE TITLE
exp-predownload-newsletter-new: Code and launch the pre-download newsletter experiment on /new

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#6950]
## Description

Code and launch the pre-download newsletter experiment on /new (there are 4 queued up by Michael)

Experiment plan: https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=90742108

Depends on https://github.com/mozilla/bedrock/issues/6884

Related issues for each experiment treatment:

#6935 - Experiment: Accessibility improvements on /thanks
#6938 - Experiment: Newsletter modal on /new
#6939 - Experiment: Newsletter page on pre-download on /new
#6944 - Experiment: Newsletter CTA on /firefox/new

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | 4 days |
| SEO | |
| ANA | ? |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Experiment is launched in market
- [ ] Experiment data are observable

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Review copy when up on demo @claychaffin

**Comment by alexgibson** [comment]
I added links to each design / experiment in the issue description above.

I'm going to think this through more, but my initial reaction is that this may make sense for one person to do because:

- The ask is to measure install / retention. To facilitate this, all experiment variations will need to start on `/new` as the top of the funnel (even though some variations only effect /thanks visually).
- Because the flows effect multiple pages, all variations will likely need to be aware of eachother and use some unique query parameters to avoid conflict.

@hoosteeno I'll spend some more time thinking about this in the morning, but feel free to add any aditional thoughts.

**Comment by alexgibson** [comment]
@michaelmccombie @claychaffin @hoosteeno 

I've posted screenshots and links to demo for each variation. This is our one shot to try and get something that performs as good as (if not better) than the modal experince, so I'd very much welcome design/copy feedback and refinement. We can change pretty much anything we wish for copy, seeing as the experiment is en-US only.

#6935 - Experiment: Accessibility improvements on /thanks
- https://github.com/mozilla/bedrock/issues/6935#issuecomment-478003333

#6938 - Experiment: Newsletter modal on /new
- https://github.com/mozilla/bedrock/issues/6938#issuecomment-478005954

#6939 - Experiment: Newsletter page on pre-download on /new
- https://github.com/mozilla/bedrock/issues/6939#issuecomment-478010312

#6944 - Experiment: Newsletter CTA on /firefox/new
- https://github.com/mozilla/bedrock/issues/6944#issuecomment-478011282

Note this is still a WIP, so expect some rough edges.

**Comment by alexgibson** [comment]
Blocked on design, copy and SEO feedback.

This experiment also needs a test plan.

**Comment by rraue** [comment]
@hoosteeno @alexgibson I commented now on all four issues. I have no concerns about any of these tests, but if https://github.com/mozilla/bedrock/issues/6944 is a winner, we need to reconsider how to implement this permanently.

**Comment by alexgibson** [comment]
Analytics for this experiment are now in place:

Target audience: Windows, non-Firefox users.

Cohorts:

```
{
  'xv=pre-dl&v=a': 92,  // Control
  'xv=pre-dl&v=b': 2,   // Accessibility improvements on /thanks
  'xv=pre-dl&v=c': 2,   // Newsletter modal on /new (non-Firefox users)
  'xv=pre-dl&v=d': 2,   // Newsletter page on pre-download on /new
  'xv=pre-dl&v=e': 2    // Newsletter CTA on /firefox/new
}
```

Stub attribution params:

```javascript
{ 
  utm_source: "www.mozilla.org", 
  utm_medium: "experiment", 
  utm_campaign: "firefox_new_pre_download", 
  utm_content: "firefox_new_pre_download_v_[a|b|c|d|e|f]"
}
```

GA event:

```javascript
{
  'data-ex-name': 'firefox_new_pre_download',
  'data-ex-variant': 'v_[a|b|c|d|e|f]'
}
```

**Comment by hoosteeno** [comment]
@claychaffin can you review these 4 variations and suggest different copy if you wish?

**Comment by hoosteeno** [comment]
@sghoseWI can you review the experiment plan (https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=90742108)? I have 2 questions for you:

1) This is a brand new channel for this CTA (/new). We don't have a control for the experience we're piloting here. We want to compare it to historical rates on a _different channel_ (/firefox). Can we do that? Can you help with the hypothesis?
2) Can we go for 95% LoC? That will change the numbers section of the doc.

**Comment by sghoseWI** [comment]
@hoosteeno -- I believe the answer is yes to both questions.  Instead of a typical controlled experiment on the same page, we can compare the metrics for the /new variants against the same metrics on the /firefox page.  I also updated the confidence level, margin of error, requisite sample size, and traffic distribution in the experiment doc to reflect the change to 95% LoC -- let me know if you have any questions!

**Comment by alexgibson** [comment]
I think we've agreed on the variations being tested in terms of copy, so removing the blocker.

**Comment by alexgibson** [comment]
Copy deck for variations: https://docs.google.com/document/d/1PWPGF4m1Ju2-RUqiHiaknzlicspPfSOOjWXVB8kcLes/edit?usp=sharing

**Comment by alexgibson** [comment]
Experiment variations on demo have now been updated with the improved copy, thanks @claychaffin!

@hoosteeno whilst we get this code reviewed, it would be great if someone could help to verify that tracking is in place for this experiment on demo. Who can best help with this task?

**Comment by claychaffin** [comment]
@alexgibson Hello! Where can I view the demo or the page layouts with the copy in them, please? 
To be clear, I'm still finalizing copy this morning, which is why I left options in the copy deck.
I'll tidy up the deck once finalized. Thanks.

**Comment by alexgibson** [comment]
@claychaffin you can find links to each demo instance here https://github.com/mozilla/bedrock/issues/6950#issuecomment-478017208

**Comment by alexgibson** [comment]
Here are the dmeo links for convenvience:


- https://www-demo1.allizom.org/en-US/firefox/new/?xv=pre-dl&v=a (Control).
- https://www-demo1.allizom.org/en-US/firefox/new/?xv=pre-dl&v=b (Improved post-download newsletter on /thanks).
- https://www-demo1.allizom.org/en-US/firefox/new/?xv=pre-dl&v=c (Pre-download modal on scene 1).
- https://www-demo1.allizom.org/en-US/firefox/new/?xv=pre-dl&v=d (Pre-download embedded form on /thanks).
- https://www-demo1.allizom.org/en-US/firefox/new/?xv=pre-dl&v=e (Embedded form on scene1)

**Comment by ejregithub** [comment]
Moving this issue to the next sprint milestone.  Only code review is pending.
