### ISSUE TITLE
naexp02: Design Test on /new: Features above the Fold (#1)

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6951]
## Description

If the users visiting /new can see the three feature areas that are currently 'below the fold' on most screen sizes, they’ll be more likely to download leading to an increase in installs and active days. 

[Manapage](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=90739191)

[Copy](https://docs.google.com/document/d/1n2ZZmFgy_5yYhxAuc8P36HDtYjFO0Mz8x3E12nmgUuo/edit?usp=sharing)

[Trello card](https://trello.com/c/yix4WoVl)

While listed as an NA experiment, it is intended to go out to /new traffic in the following locales:
en-US
en-CA
en-GB
DE
FR

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] The test is out to each locale, running for the time specified by Analytics to reach the proper cohort sizes.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Code variations on demo
- [ ] Get stakeholder (Justin K) signoff
- [ ] Set up traffic cop
- [ ] Get Analytics QA review and signoff
