### ISSUE TITLE
exp-more-descriptive-features: Launch the more descriptive features experiment on /new

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#6952]
## Description

Launch the code that was built in https://github.com/mozilla/bedrock/issues/6830. Depends on https://github.com/mozilla/bedrock/issues/6830.

This is identified as euexp02

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Prior test is not complete as expected (date/cohort size)

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Wait prior experiment to end (the headline test ending next Wednesday/Thurs)
- [ ] Remove prior experiment code
- [ ] Code review/merge/enable in prod (via SWITCH)

**Comment by alexgibson** [comment]
This is now live in production
