### ISSUE TITLE
Change log-in to login on Fx Benefits page

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#6953]
## Description
The page at https://www.mozilla.org/en-US/firefox/accounts/ has a headline including the string "log-in". This should be changed to "login" the next time we make major string changes on the page (e.g. in  card https://github.com/mozilla/bedrock/issues/6914).

![Screen Shot 2019-03-20 at 11.35.41 AM.png](https://images.zenhubusercontent.com/5c871077d74bd07972c6db24/3116a5a3-285a-4b6a-84eb-f54296db9f7c)

Depends on https://github.com/mozilla/bedrock/issues/6914.

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] "log-in" is changed to "login" on the FxA benefits page, and that change is ready for localizers.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.
