### ISSUE TITLE
Specify an Experiments sandbox

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#6954]
## Description

We need to design a better experiments program that
a) protects our most valuable website assets while
b) giving experimenters more freedom and power to experiment

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] The solution is articulated well enough to go to code
- [ ] It works with existing tools (TrafficCop) and potential future tools (Google Optimize)
- [ ] It has a master switch that enables devs to turn off all experiments with minimal effort

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Identify a place where we can allow a bit more experimental freedom without perpetually putting our main download page at risk. E.g. a URL such as /firefox/download/.
- [ ] Research/specify the routing mechanism
- [ ] Begin documenting the program: It's capabilities, constraints, key processes

**Comment by alexgibson** [comment]
I tried to put together some thoughts for additional context for this issue:

**Current pain points with regard to experimentation on /new:**

- Experiments running directly on /firefox/new make an already complicated page even more complex. This increases the risk of breakage on our most high traffic download page. This is especially true when we have multiple experiments happening at the same time, often crossing over between different locales and user segments.
- This same risk will be amplified even further if we have a third-party tool (such as Google Optimize 360) running alongside first-party (Traffic Cop) experiments. Adding a new tool to the mix is unlikely to make coordination and prioritization any easier, especially given that different teams may be driving each tool.
- All this experimentation adds to page weight, load times, and effects overall performance of the /new page. There is also potential for negative SEO impact.
- With many different experiments and variations in place, the [view logic](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/views.py#L636-L745) for /new gets complicated, making long-term changes to the page more difficult and time consuming for the websites team.
- Running multiple experiments directly on /new also poses difficulty when it comes to automated testing. We need tests in place to ensure that the page functions correctly, but this is difficult when the page can randomly change in unknown ways due to someone running an unanticipated experiment.

**Possible solution (in two parts)**

1. Create a sandboxed experimentation page:

    - Stand up a new simplified download page purely for experimentation purposes. This could be any URL we decide, but could follow the same template the SEM team [is now using](https://www.mozilla.org/en-US/firefox/campaign/) to direct their Ad traffic. 
    - This new page doesn't need to have all the bells and whistles of /new (e.g. when it comes to existing FF users), but it could serve as a good test bed for the majority of experiments other teams are doing that target non-FF users (headlines, copy tests, page variations and new designs).
    - This new page is where the majority of experiments would run, requiring /new to be touched less frequently, and also making long-term features easier to roll out.
    - This new page could house as many page variations and designs as we want, removing the complexity from all these things living at /new.
    - The page is not indexed by search engines.

2. Create a tool to redirect segments of /new traffic to the sandbox:
    - A lightweight and well tested tool, responsible for redirecting segments of traffic to the sandbox could be implemented on /new.
    - Having a single tool be responsible for segmenting and redirecting to different experiments in the sandbox could make running things in parallel easier to reason about, since it is aware of all experiments that are active.
    - The tool could redirect small % of traffic to a sandbox experiment, and could also redirect based on other common factors we often have to (repeatedly) write custom code for:
      - Operating system (is the visitor on Windows/Mac etc).
      - Browser (FF vs non-FF)
      - Desktop / Mobile
      - Locale
    - The tool could be behind a switch, or configurable via switches, so the websites team could quickly and easily turn traffic to the sandbox on and off.

**Comment by jpetto** [comment]
Just walking through how this would work from a very high level:

- someone lands on `/new`
- a bit of code decides if they should be entered into one of X number of running experiments
- if yes, visitor is redirected to a different URL where the actual experiment is run

Is that about accurate?

**Comment by stephaniehobson** [comment]
That's how it reads to me.

**Comment by hoosteeno** [comment]
> Is that about accurate?

That's right. We could build a routing tool to route some /new/ visits to a version of the download page that is not as complicated, not as SEO-critical, not as heavy. We're doing this now with /firefox/campaign/ -- all SEM traffic will go that way (although, via a link in SEM config, not via routing on our site), and that page will have a different set of affordances, and will evolve independently.

Traffic to the experimental version could be shaped in some basic ways. It would also be capped, limiting the risk associated with running more experiments and having more experimenters. "Graduating an experiment" would thus mean getting a treatment from the experimental page over to /new, which would always require deliberate action and could not happen through inaction.

**Comment by stephaniehobson** [comment]
We should consider keeping users with existing gtm vars out of experiments. I think it would help with the complicated mix of things around attribution.

**Comment by alexgibson** [comment]
Another reason to try and mitigate such a high level of experimentation on /new. Other teams rely on stub attribution data for that one page to power functionality: https://github.com/mozilla/bedrock/issues/7003
