### ISSUE TITLE
  Update pages with latest link to the play store for Lockbox

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6981]
## Description

Lockbox is available for Android now. There are at least two places that need to be updated with a link to the play store.
https://www.mozilla.org/en-US/firefox/accounts/ 
https://www.mozilla.org/en-US/firefox/66.0/whatsnew/ 

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | 1|
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Play store link on accounts
- [ ] Play store link on What's New 66
- [ ] Check there are no other places that need links added.

#### Tasks
- [ ] Play store link on accounts
- [ ] Play store link on What's New 66
- [ ] Check there are no other places that need links added.

**Comment by alexgibson** [comment]
I believe this has all been done
