### ISSUE TITLE
Add link to Lockbox in Play store

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6982]
## Description

Lockbox is available for Android now. Every where we link to the App Store we should also link the the Play store.

These are two places I know about:
https://www.mozilla.org/en-US/firefox/accounts/ 
https://www.mozilla.org/en-US/firefox/66.0/whatsnew/

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | 1|
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Play store link on accounts
- [ ] Play store link on What's New 66
- [ ] Check there are no other places that need links added.

#### Tasks
- [ ] Play store link on accounts
- [ ] Play store link on What's New 66
- [ ] Check there are no other places that need links added.
