### ISSUE TITLE
Quantify daily unique users of Win10 S mode attempting to download Firefox on moz.org

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6984]
## Description

[Bug 1539214](https://bugzilla.mozilla.org/show_bug.cgi?id=) - Quantify daily unique users of Win10 S mode attempting to download Firefox on moz.org.

Now that[ we can detect visitors coming to www.mozilla.org with Win 10 in S mode](https://github.com/mozilla/bedrock/issues/6367#issuecomment-476256394), we need to implement that detection and gather the numbers.

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | 1 day |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Detection is implemented live on the site
- [ ] A people resource has verified it is working in prod immediately post launch
- [ ] A regular cadence and people resource has been established to monitor and report metrics

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Only after a certain date was the API added. We can't detect earlier than that milestone.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
Current plan to tackle this is to add a new property to the core dataLayer event that gets triggered for all pages on mozorg:

https://github.com/mozilla/bedrock/blob/master/media/js/base/core-datalayer-init.js

```javascript
var mode = window.external.getHostEnvironmentValue('os-mode')
```

As per https://github.com/mozilla/bedrock/issues/6367#issuecomment-476256394, a value of `2` indicated the Windows 10 user is in S mode.

**Comment by ejregithub** [comment]
@alexgibson - can you please estimate (Fibonacci scale, in the 'Estimatate' field in the right nav) the require effort to implement this?

**Comment by alexgibson** [comment]
An implementation of this is now up on demo: https://www-demo2.allizom.org/en-US/

@hoosteeno is kindly providing GA assistence to make sure things look good before we push this live.

**Comment by hoosteeno** [comment]
I need to walk through the steps defined [here](https://mixedanalytics.com/blog/ga-gtm-datalayer-custom-dimensions/). Will update the card when I have.

**Comment by hoosteeno** [comment]
I've made these changes and am waiting on review (from AnalyticsPros).

**Comment by alexgibson** [comment]
@hoosteeno can you give me a walkthrough of how to view this custom dimension in GA? I'd like to try and validate that my laptop correctly identifies as running s-mode. Thanks

**Comment by hoosteeno** [comment]
> @hoosteeno can you give me a walkthrough on how to view this custom dimension in GA? I'd like to try and validate that my laptop correctly identifies as running s-mode. Thanks

(We walked through this in Slack)

**Comment by hoosteeno** [comment]
Here's a link to [a report in GA that appears to contain the data we seek](https://analytics.google.com/analytics/web/#/report/acquisition-channels/a36116321w64087799p65789850/_.useg=builtin1&_.goalOption=2&explorer-table.secSegmentId=analytics.customDimension32&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.customDimension32%22,%22PT%22,%221%22,0%5D%5D&explorer-table-dataTable.sortColumnName=analytics.goal2Completions&explorer-table-dataTable.sortDescending=true).
