### ISSUE TITLE
Update /firefox/mobile/ with new branding

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#6987]
## Description

Update the Firefox Mobile landing page at https://www.mozilla.org/en-US/firefox/mobile/ with a temporary English only page that reflects the new brand.

***Tasks***
- [ ] Make the page available for stakeholder review on demo server
- [ ] Ensure UTMs persist from the existing page so we can measure historically
- [ ] Have @rraue review the UTMs

**Comment by stephaniehobson** [comment]
Copy: https://docs.google.com/document/d/1ydZuHHjTNOuNBH3NahRik-lXmPv2_3iEkQVIFGDjl40/edit

**Comment by stephaniehobson** [comment]
Design: https://app.goabstract.com/projects/2bf275c0-d87a-11e8-8c68-d31c3ed795db/branches/f8e70169-9bb0-4ac1-8b56-036052a2b42c/files/48E8EFB0-007F-46B2-80DE-38C3B7544453?changed=true

**Comment by stephaniehobson** [comment]
There are a couple animations with this design, they are being provided separately.

The design does not include mock ups of the app store buttons displaying for mobile users but those are part of the  💛 success criteria 💛

**Comment by stephaniehobson** [comment]
Closing in favour of https://github.com/mozilla/bedrock/issues/7858
