### ISSUE TITLE
WNP 67- PR for strings for L10n - Release date - 5/14

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#6993]
## Description

WNP 67 has strings due on 4/5 - we must put the strings in a PR immediately and the extract them to Pontoon for localization

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Insert new strings, wrapped

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Insert new strings, wrapped for L10n in a new PR and submit it
- [ ] Extract the strings to Pontoon
- [ ] Communicate to Peiying so she can inform the community

**Comment by amychurchwell** [comment]
**Note**: please remember that all strings **may not be included in copy dock**. Check for hero copy for when a user is _already_ signed into firefox accounts, include copy on all buttons such as 'create a firefox account', and all other action copy like "Have an account? Log in", .etc.

**Comment by alexgibson** [comment]
> Note: please remember that all strings may not be included in copy dock.

@ejregithub can we please try and make sure copy decks contain *all* strings that need to be on the page, and that they are double-checked against the design mockup first? This seems like an easy way for mistakes to happen otherwise. We need to be certain all the required copy is there before doing extraction.
