### ISSUE TITLE
Dry Market Experiment: Closure

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#6995]
## Description

This is a closure card. It doesn't mean "stop the experiment now", but it hopefully leads to that.

In a closure card, we should do the tasks below, in order.

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Experiment is stopped
- [x] Experiment report is published 

#### Tasks
- [x] Determine whether we have enough data, and when we do, signal to shut down the experiment (@sghoseWI)
- [x] Shut down the experiment (by e.g. changing a switch)
- [x] Publish an experiment report (@sghoseWI)
- [x] File any needed issues to remove or graduate experimental treatments (@hoosteeno)

**Comment by alexgibson** [comment]
This is blocking https://github.com/mozilla/bedrock/pull/6927

**Comment by alexgibson** [comment]
@sghoseWI @hoosteeno can this experiment be turned off?

**Comment by alexgibson** [comment]
Experiment disabled in https://github.com/mozmeao/www-config/commit/06b4a56a3cfa6137ff05a9b9626a3456234ff7c4

**Comment by alexgibson** [comment]
PR to remove the experiment code: https://github.com/mozilla/bedrock/pull/7008

**Comment by ejregithub** [comment]
@sghoseWI - the task in the description to "Publish an experiment report (@sghoseWI)" has been closed. If that's correct and done, can you please provide the link to that here?

**Comment by sghoseWI** [comment]
@ejregithub The report is done -- linked here: https://docs.google.com/document/d/1L3y9nxfGID3xKn5ZqYMWOM2Mz5fRITU41bKHKMQEdYk/edit#

**Comment by ejregithub** [comment]
Excellent, thanks @sghoseWI  (Now get some rest, man!)

**Comment by ejregithub** [comment]
All the tasks appear to be done, so I'm closing this.

**Comment by ejregithub** [comment]
@sghoseWI - thinking of what kind of effort this took and the complexity of it, use the Estimation tool in the right nav to gauge with the Fibonacci scale and apply a number.  1 is easy, probably just you doing the work and finishing in about a day. Compare this to a 21, which is probably 1 person for most of the sprint or multiple team members working to close the issue in around half the sprint.  Ping me with any questions!
