### ISSUE TITLE
Headline Experiment: Closure

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#6996]
## Description

This is a closure card. It doesn't mean "stop the experiment now", but it hopefully leads to that.

In a closure card, we should do the tasks below, in order.

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Experiment is stopped
- [x] Experiment report is published 

#### Tasks
- [x] Determine whether we have enough data, and when we do, signal to shut down the experiment (@sghoseWI)
- [x] Shut down the experiment (by e.g. changing a switch)
- [x] Publish an experiment report (@sghoseWI)
- [x] File any needed issues to remove or graduate experimental treatments (@hoosteeno)

**Comment by alexgibson** [comment]
How are we doing here? I'd very much like to shut this off as soon as we have enough data (which was supposed to be yesterday), given https://github.com/mozilla/bedrock/issues/7003

**Comment by alexgibson** [comment]
This is blocking https://github.com/mozilla/bedrock/pull/6927

**Comment by sghoseWI** [comment]
@alexgibson Based on the statistical parameters in the Mana doc, EN-US is ready to be shut off now and EN-GB should be ready to be shut off tomorrow.

With the current parameters set for CA and DE, the experiment will need to run for at least another week. 

To remedy this in DE, I suggest we reduce the confidence levels for DE to 97% from 99% and increase the margin of error threshold from 1% to 2% .  If we are okay with this, then DE is ready to be shut off now.

To remedy this in CA, I suggest we reduce the confidence levels for CA to 95% from 97% and increase the margin of error threshold from 3% to 4%.  If we are okay with this, then CA is ready to be shit off now as well.

**Comment by hoosteeno** [comment]
> If we agree with these suggestions, I can adjust the parameters in the Mana doc.

@sghoseWI I agree with these. 95% is a suitable baseline LoC for our experimental work going forward, and you can adjust them in the mana doc for this experiment. 

@alexgibson Considering that, it sounds like we have enough data to shut this down now.

**Comment by alexgibson** [comment]
Experiment disabled in https://github.com/mozmeao/www-config/commit/a33358a72f9afa30a71321ee9cdc37c5a451c7d7

**Comment by alexgibson** [comment]
It occured to me that because we're overriding stub attribution, we should remove the experiment code first, rather than disabling the switch. Re-opening until that's done.

**Comment by alexgibson** [comment]
PR to remove the code https://github.com/mozilla/bedrock/pull/7008

PR to disable the switch https://github.com/mozmeao/www-config/pull/214

**Comment by hoosteeno** [comment]
@sghoseWI do you have a sense of when the experiment report for this will be ready for review?

**Comment by sghoseWI** [comment]
@hoosteeno I've taken over duties for this report from George.  I'm hoping to have a draft of the report to show by end of week.  It seems more involved analysis-wise than some of the other recent reports, so I want to make sure I'm being thorough.  I'm also working on the report for the A/B brand test on /firefox -- hoping to have a draft of that by end of week as well.

**Comment by sghoseWI** [comment]
Experiment report: https://docs.google.com/document/d/1SzPkDKGSbkb5J3cuTAzr4-YuLV2Og8B1glk3OBFVcDs/edit

**Comment by hoosteeno** [comment]
Filed removal issue #7074.
