### ISSUE TITLE
Design explorations for /all

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7014]
## Description

Create some designs that explore UIs to surface the many dimensions of our distributed Firefox products in a single page.

WIP PRD: https://docs.google.com/document/d/1MtqVFAfnDJOoR2X0OZ1yFDdSkfVUSCChgIOye8PklXk/edit

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Designs are ready for review

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks

- [ ] Produce 2 unique designs exploring ways to surface this information
- [ ] Get copy input
- [ ] Get dev input

**Comment by ejregithub** [comment]
@mrkwvr - please provide a size Estimate for your work on this card. Do so with the Fibonacci scale in the Estimates section in the right nav.

**Comment by hoosteeno** [comment]
@mrkwvr can you link this card to the artifacts of this work? What's the current status?

**Comment by mrkwvr** [comment]
@hoosteeno sure thing. I've just place copy into the file this morning and will link to the sketch file once I've cleaned it up

**Comment by ejregithub** [comment]
Closing this issue. All the same, @mrkwvr - please link to the sketch file here

**Comment by mrkwvr** [comment]
as soon as I get final copy from Clay I will post the sketch file here

**Comment by mrkwvr** [comment]
final design file
[Firefox :all 04162019.sketch.zip](https://github.com/mozilla/bedrock/files/3085995/Firefox.all.04162019.sketch.zip)

**Comment by ejregithub** [comment]
@mrkwvr - please provide a size Estimate for your work on this card. Do so with the Fibonacci scale in the Estimates section in the right nav.
