### ISSUE TITLE
Update images on Leadership page

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#7018]
## Description

A handful of the headshots on /about/leadership have non-white backgrounds, which is inconsistent with the established standard for these headshots. Someone has painstakingly painted out those backgrounds where possible and we need to update the images with the new versions: https://mozilla.app.box.com/s/bsht5e7gvpgij8vxj01swqpunv8o52k1

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | 1 hour |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Old images are replaced with new ones.

#### Tasks
- [ ] New images need to be cropped square and sized for both low res (250x250) and high res (500 x 500) screens.
- [ ] New high-res print images need to be uploaded to assets.mozilla.net.

**Comment by ejregithub** [comment]
@hoosteeno - i'm not sure of the relative priority of this one. Nothing is broken and the effort is a half day for ENG. I've placed it in the 'Future Sprint' Milestone for later consideration.

**Comment by craigcook** [comment]
It's low priority for sure and I probably greatly overestimated. The only complicated thing is processing the images but there are only four of them. Let's call it an hour.
