### ISSUE TITLE
Update BiAnnual Transparency Report for 2018 H2

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7036]
## Description

Twice a year we update the Transparency Report. This issue is for doing so for H2/2018 (July-Dec). The work here entails created a new URL and updating data here (for 2018 H2) https://www.mozilla.org/en-US/about/policy/transparency/jul-dec-2018/ using the /jan-jun-2018/ page as a template. And, per Mika, this work will include the addition of a new Q in the FAQ. Legal will provide the copy and data.

All comments and questions about the content should be done in the internal bug - 
https://bugzilla.mozilla.org/show_bug.cgi?id=1564532

---

- [x] Is launched  on July 30, 2019 (to be managed in #7422)
- [x] NO DATA OR INFORMATION IS POSTED PUBLICLY BEFORE LAUNCH

#### Tasks
- [x] Create a private bug
- [x] Create the new URL
- [x] Code the page with[ copy/data from Legal ](https://docs.google.com/document/d/1pVGto0pNGgzuI-7mfyaSvUDABfQaNhkIBSQaHvXqVZU/edit)
- [x] Screenshots posted in private bug for QA by Legal

**Comment by amychurchwell** [comment]
@ejregithub 
The most recent report we have in production is [July-December, 2017](https://www.mozilla.org/en-US/about/policy/transparency/jul-dec-2017/). We are missing January-June, 2018. Are we skipping 2018 H1?
