### ISSUE TITLE
Update the Mozilla "Manage Your Email Preferences Page" 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7037]
## Description

- This is required by regulation and is on the critical path for paid customers.
- MVP Basket page to let users control their subscription preferences
- Add required new and change subscriptions
- L10n required for the locales in which content is provided/sent

* [7 sheets context](https://docs.google.com/document/d/13Tei50_G8mrPCblFugvu5eGD2-QSSGUcAP9403Co-3E/edit)
* [Copy doc](https://docs.google.com/document/d/1Dm5A6RsQidUJRFcKh9R0MDL_Rd3s__HxRvOIBkVk7Ic/edit#heading=h.824kr7p7xix1)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Update the existing email prefs page with accurate ways to change your communication preferences with Mozilla

#### Tasks
- [x] Set up meeting to gather requirements (Eric)
- [x] Create project plan
- [x] Determine resourcing
- [x] Execute plan (copy/design/QA/code/QA/code review/launch)
- [x] Get copy from LCM/Accounts/Legal teams
- [x] Roadmap tasks

**Comment by hoosteeno** [comment]
[Some notes](https://docs.google.com/document/d/1NJjPQfQwYWD7Pf_DJagwDTTY12TJrjzlOTijY4ACRAY/edit?ts=5cabd514) from a contexting session we had.

**Comment by stephaniehobson** [comment]
Closed by #7198.
