### ISSUE TITLE
Set up whatsnewpage on the Beta channel to be shown after each major version update

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7044]
## Description

Set up whatsnewpage on the beta channel to be shown after each major version update - https://bugzilla.mozilla.org/show_bug.cgi?id=1536665

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] The beta channel points to the WNP 66 content

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] How are locales managed? 

#### Tasks
- [ ] Create and set up new URL, provide this to Releng
- [ ] Add rule to show the given template at the URL above

**Comment by hoosteeno** [comment]
See also: https://github.com/mozilla/bedrock/issues/7043

**Comment by alexgibson** [comment]
Pull request: https://github.com/mozilla/bedrock/pull/7073
