### ISSUE TITLE
Fundraising banner to follow Internet Health Report Release

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/bedrock#7047]
## Description

MoFo is planning a late-April fundraising campaign and wants to bring back the home page banner for a brief time, with minor changes from Valentine's Day campaign: a) plain black background, and b) "Variant B" copy from the V-day campaign, as was implemented here: https://github.com/mozilla/bedrock/issues/6693 . It will be English-only.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Banner launched April 26
- [ ] Banner pulled down May 1st

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [x] Code it
- [x] Code switch

**Comment by ejregithub** [comment]
This is live. Eric will file a separate issue to turn it off.
