### ISSUE TITLE
Extract strings to Pontoon 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7055]
## Description

Extract strings to Pontoon for the following pages:

- [x] https://www.mozilla.org/en-US/firefox/mac/
- [x] https://www.mozilla.org/en-US/firefox/windows/
- [x] https://www.mozilla.org/en-US/firefox/linux/
- [x] https://www.mozilla.org/en-US/technology/what-is-a-browser/
- [x] https://www.mozilla.org/en-US/technology/browser-history/

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
Closing this out, this work was all completed last sprint.

**Comment by hoosteeno** [comment]
@alexgibson Could you size this? Was it 2 per page, or maybe 8 overall?

**Comment by alexgibson** [comment]
8 sounds good to me
