### ISSUE TITLE
Features experiment: closure

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7063]
## Description

The features experiment implemented in https://github.com/mozilla/bedrock/issues/6830 has now been [running in production for 9 days](https://github.com/mozmeao/www-config/commit/d8a690754491ec6e82652e7e4c2d49b09ead7c2f), which should hopefully be more than enough time to get the required data. Can we turn the experiment off?

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Experiment is stopped
- [x] Experiment report is published 

#### Tasks
- [x] Determine whether we have enough data, and when we do, signal to shut down the experiment
- [x] Shut down the experiment (by e.g. changing a switch)
- [x] Publish an experiment report
- [ ] File any needed issues to remove or graduate experimental treatments

**Comment by alexgibson** [comment]
This experiment has now been running for nearly 2 weeks. Unless anyone can confirm that we don't have enough data yet, I'm going to shut this off. Any objections @hoosteeno @ejregithub?

**Comment by alexgibson** [comment]
PR to disable the experiment: https://github.com/mozmeao/www-config/pull/218

**Comment by hoosteeno** [comment]
@sghoseWI The first step in a closure card is yours. Can you tell us if we have enough data to shut this down?

**Comment by hoosteeno** [comment]
Here's a link to a report template you can use to report on this: https://analytics.google.com/analytics/web/template?uid=OE4HJKOkQ_yE02tUL6JYdQ

**Comment by sghoseWI** [comment]
@hoosteeno -- Looks like there is a sufficient sample in each locale and variant -- we can safely shut off the experiment.

**Comment by hoosteeno** [comment]
Here's a link to a report template you can use to report on this: https://analytics.google.com/analytics/web/template?uid=OE4HJKOkQ_yE02tUL6JYdQ

**Comment by hoosteeno** [comment]
@sghoseWI when you're done with the experiment report on this, can you link here?

**Comment by sghoseWI** [comment]
@hoosteeno Yes - will do!

**Comment by sghoseWI** [comment]
Please see here for the report: https://docs.google.com/document/d/1SDrQlZyDtiNwbvsIVSh0_x2v550RKcps3rZqH3g4Qbk/edit?usp=sharing

**Comment by sghoseWI** [comment]
Experiment Report: https://docs.google.com/document/d/1SDrQlZyDtiNwbvsIVSh0_x2v550RKcps3rZqH3g4Qbk/edit

**Comment by alexgibson** [comment]
@hoosteeno what's the last step to closing this out. Is there a recommendation to keep one of the experiences, or can we remove this experiment code?

**Comment by hoosteeno** [comment]
Let's remove the experiment code with #7115. Thanks.
