### ISSUE TITLE
Remove unused front-end assets

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7066]
## Description

Here's a list of front-end JS and CSS assets in the bedrock repository that are no longer being actively used by any pages (as far as I can see). Rather than maintain them long-term, we can likely remove the files as many have not been actively used in a long time. Everything lives in git history, so can always be brought back from beyond? :)

Note: I didn't go through the image directory.

List of JavaScript assets:

- `/media/js/base/mozilla-firefox-default.js`
- `/media/js/base/mozilla-highlight-target.js`
- `/media/js/base/mozilla-image-helper.js`
- `/media/js/base/mozilla-svg-image-fallback.js`
- `/media/js/base/svg-animation-check.js`
- `/media/js/firefox/new-ios-redirect-helper.js`
- `/media/js/firefox/new-ios-redirect.js`
- `/media/js/firefox/platforms.js`
- `/media/js/firefox/private-browsing.js`
- `/media/js/libs/fxa-relier-client.min.js`
- `/media/js/libs/jquery.sequence.2.1.0.min.js`
- `/media/js/libs/mozcountdown.js`

CSS:

- `/media/css/base/platform-footer-links.less`
- `/media/css/base/svg-animation-check.less`
- `/media/css/libs/jquery.pageslide.css`
- `/media/css/libs/tipsy.css`

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Assets are removed from the repository.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] We should double check to make sure nothing is still using these assets

#### Tasks
- [x] Double check assets are no longer in use.
- [x] Remove if so.

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/7385
