### ISSUE TITLE
Add email-first form to backup/default firstrun page

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7067]
## Description

The backup/default firstrun experience that we recently changed in #6149 was an important source of new FxA. Now that we've removed the signup form, it is no longer an important source, and as a result FxA acquisitions are noticeably down (https://github.com/mozilla/fxa/issues/818). 

We should add the iframeless form to the backup/default firstrun experience.

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] The backup/default firstrun experience has an iframeless email-first FxA signup form
- [ ] The form's contributions to FxA signup/signin are observable in Amplitude

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.
