### ISSUE TITLE
Remove headline experiment code

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7074]
## Description

The [headline experiment we recently ran on /new](https://github.com/mozilla/bedrock/issues/6996) has run its course. We await any instruction on next steps from the stakeholders -- they may wish to make one of the headlines permanent -- but meanwhile, we can remove the experiment code. 

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Headline experiment code and templates only used for headline test are removed from production codebase

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
This code is already gone :)
