### ISSUE TITLE
Copy for /all

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7075]
## Description

Copy for /all

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Is done by 4/18

#### Tasks
- [ ] @claychaffin  to write copy and provide to @mrkwvr  to float into design
- [ ] Get SEO input
