### ISSUE TITLE
Pre/post measurement of impact of removing `en` conditional  in Global Navigation

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7082]
## Description

Pre/post measurement of impact of removing `en` conditional 

Currently users visiting the site w. Firefox are shown the Fx Accounts CTA in the global navigation. For locales that have not completed localization of the nav, the Fx CTA is not shown. This change will show that CTA, albeit in English until a/the locales catch up in completing their lang file(s)

From #7080 - we will remove the [`en` conditional](https://github.com/mozilla/bedrock/blob/master/bedrock/base/templates/includes/protocol/navigation/index.html#L27) on the FxA CTA in the global navigation. Some [locales are still behind](https://l10n.mozilla-community.org/langchecker/?locale=all&website=0&file=navigation.lang), but seeing an untranslated string will be a good prompt for those locales to catch up.

[Snapshot of locales having completed/not completed the navigation lang file on 4/16](https://docs.google.com/spreadsheets/d/1gg9sgORXaKZiwfMYxt4IDZVjYZtA6yvR1M05IJqSqv4/edit#gid=0) 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### Tasks
- [ ] Work with FxAccounts to understand the impact of showing the FxA to additional locales, post change

**Comment by amychurchwell** [comment]
#7080 has been merged to master. Will probably be pushed to production tomorrow.

**Comment by alexgibson** [comment]
This change is now in production, thanks all!

**Comment by ejregithub** [comment]
Chatted w. ADavis and Saptarshi just now. ADavis recommends we connect with Leif in Accounts to talk about data (task to @sghoseWI )

**Comment by ejregithub** [comment]
@sghoseWI - can you please revisit this Leif and let us know what you find out?

**Comment by sghoseWI** [comment]
@ejregithub please see below: 

1) Summary: https://docs.google.com/document/d/1UPF4Hat3qqBpDo22xQHKYgmjj4K6hyIVoKENq5HhW3Y/edit

2) Amplitude Dashboard: https://analytics.amplitude.com/mozilla-corp/chart/gs1wlt8/edit/td4f3oe

3) Underlying Data: https://docs.google.com/spreadsheets/d/1NsTfxYm-V7IYi5YbOjgc4vcoWSEEysKjzvQP-F60e00/edit#gid=0
