### ISSUE TITLE
naexp05 - Pre/post test - cross-posting blogs to medium

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7087]
## Description

Enable cross-posting of Blogs from WP to medium
[manapage](https://mana.mozilla.org/wiki/display/EN/Cross-posting+Blogs+to+medium)
[Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1543192)
https://trello.com/c/dfZ54iZZ

Driving Insight: We believe that a custom content block added to the Wordpress parent blog theme that allows blog editors to add call-out content that is distinct from the body content would help users find more content that is relevant to their needs.

Hypothesis: If we provide designed promo blocks within the body we will see a lift in download conversions because the CTA will be more apparent to the reader. If we keep high-performing content

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### Tasks
- [ ] Add/enable Medium plugin for Wordpress
- [ ] Configure for cross-posting blogs from Firefox Frontier blog (WP) to  https://medium.com/@firefox
- [ ] Determine measurement component w. @rraue
