### ISSUE TITLE
Remove Features experiment 

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7115]
## Description

Let's remove the experiment code for "Features" aka #6830. 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Code is removed from bedrock

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by ejregithub** [comment]
This is the done column, so I'm closing it.
