### ISSUE TITLE
Experiment: page hero rendering performance

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7118]
## Description

[Mana page for experiment](https://mana.mozilla.org/wiki/display/EN/Page+hero+rendering+performance)

In issue https://github.com/mozilla/bedrock/issues/6741 we conducted an analysis of existing page load times in GA and their effect on conversions. Looking at the GA data, it was determined that while there is a direct correlation between page load times and bounce rates in general, there wasn't as strong a relationship between page load and conversions, such as downloads. The _assumption_ here is that if people search for "Download Firefox", then they are more likely to endure a slow loading web page, as they are already comitted to wanting to download the product.

However, there are a couple of caveats with this type of analysis:

1. For people on slow data connections, GA might never load before they give up waiting. We likely don't have GA data on these visitors.
2. Using page load time has long been a common metric to measure website performance, but in some respects it is flawed. For example, a slow loading image further down a page might hold up a page load event by ~10 seconds, despite everything else already having finished rendering at the top of the page. In this scenario, a slow load time is much less likely to be a negative influence on conversions.

With the two above scenarios in mind, I plan to run an alternative type of performance experiment - concentrating on more modern metrics: [speed index](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index), and _last hero painted_. TL:DR - how long the main hero section of a page **actually takes to render**.

Hypothesis:

Variations of a page with a higher speed index score (lower is better), and a longer time to last hero painted, will have a higher bounce rate, and also a lower conversion rate on in-page CTAs.

Null hypothesis:

No matter how long a page variation takes to render, there will be no impact on either bounce rate or conversion rate.

Experiment criteria:

- Target audience : The [about page](https://www.mozilla.org/en-US/about/) (all locales). This is not a main product download page, so there is less risk in adversely effecting downloads. People viewing this page are also less likely commited to an immediate task.
- Experiment configuration: A multi variant test, which incrementally delays the time between start render and last hero painted (resulting in a higher speed index score per variant).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Experiment is runs for one week and provides enough data to satisfy the hypothesis.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Variations that are slowest to load may result in a decrease in conversions.

#### Tasks
- [x] Mana page created.
- [x] Code experiment.
- [ ] Launch experiment.
- [ ] Stop experiment.
- [ ] Provide analysis.

**Comment by alexgibson** [comment]
@sghoseWI this is not urgent, but could you please take a look at this issue and the associated mana page, and provide me with an estimate for how each variation in this experiment should be sized?

Ideally I'd like to run this experiment with the smallest amount of traffic possible, but to give me enough data within one week.

Any questions please ask, thanks!

**Comment by sghoseWI** [comment]
@alexgibson This all looks good - I'll size this and let you know if I have any questions!

**Comment by sghoseWI** [comment]
@alexgibson Here is what I'm seeing:

In the four week period between March 31,2019 and April 27, 2019, there were 267,023 sessions to the /about page across all locales (according to GA data).  This is an average of ~66,756 sessions per week.  

With that population level, assuming a margin of error of 3% and a 95% confidence level, we need 1,063 sessions per group.  Across the 9 variations and the control group, we need 1,063*10 = 10,630 total sessions (~16% of the total weekly sessions).  

In order to account for daily session variation, we should direct 2% of traffic to each experimental group — and run the experiment for 1 week.

**Comment by alexgibson** [comment]
Thank you for being so quick to provide this 🙂

**Comment by alexgibson** [comment]
@sghoseWI just to be super clear here, does this imply that the control group can also be 2% (as well as the variants)?

**Comment by sghoseWI** [comment]
@alexgibson that’s right - although as far as I know, we usually direct the remainder of the traffic not pushed to the experimental groups to the control.
