### ISSUE TITLE
Pre-download on /new: Closure

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7121]
This card will lead us to closure on the pre-download newsletter CTA on /new.

https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=90742108

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Experiment is stopped
- [ ] Experiment report is published 

#### Tasks
- [x] Determine whether we have enough data, and when we do, signal to shut down the experiment (@hoosteeno)
- [x] Shut down the experiment (by e.g. changing a switch)
- [x] Publish an experiment report (@sghoseWI)
- [x] File any needed issues to remove or graduate experimental treatments (@hoosteeno)

**Comment by hoosteeno** [comment]
We have plenty of sessions, and it's been a week. This experiment is ready to shut down.

**Comment by alexgibson** [comment]
@hoosteeno given we're about to port this page to Protocol, and also redesign it for trailhead, should we remove this experiment code?

**Comment by hoosteeno** [comment]
Yes, thank you.

**Comment by hoosteeno** [comment]
Experiment report is published. I link to it and have summarized its findings in the mana page. https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=90742108
