### ISSUE TITLE
Port /new to protocol in preparation for Trailhead

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7127]
## Description

We will want to need to port /new to protocol before the coming Trailhead changes. To begin with we can port the page without any design changes. Note: the campaign page has already been ported so that code can be used as a starting oint.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Existing /new page is ported to Protocol
- [ ] Minimal design changes
- [ ] No copy changes
- [ ] Protocol version is launched

#### Tasks
- [ ] Port existing /new design to Protocol
- [ ] Remove pebbles assets
- [ ] Code review

**Comment by alexgibson** [comment]
There are various intertwined dependencies in this task that aren't quite clear at first:

- The regular /new page needs porting to Protocol.
- The [/ru/firefox/new/ ](https://www.mozilla.org/ru/firefox/new/)page features locale and geo-specific content, and inhertis from /new, so this would also need porting.
- The [/de/firefox/new/](https://www.mozilla.org/de/firefox/new/) page features locale specific content, and inherts from /new, so this would also need porting.
- The [/en-GB/firefox/new/](https://www.mozilla.org/en-GB/firefox/new/) page features locale specific content, and inherts from /new, so this would also need porting.

Reviewing and merging https://github.com/mozilla/bedrock/pull/7089 would also help clear the forest in preparation for this work.

**Comment by alexgibson** [comment]
See also: https://github.com/mozilla/bedrock/issues/7121#issuecomment-488244457

**Comment by alexgibson** [comment]
It sounds like we're getting a final design for /new and /thanks as soon as EOD Friday, which is likely in less time than it would take to port all the pages detailed above. With that in mind, it may be less work just to start work on the redesigned page, with an aim to A/B test it before the trailhead launch.
