### ISSUE TITLE
WNP 67.0.5 for Trailhead

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7128]
## Description

Launch a WNP with Trailhead content on the dot release (target: 67.0.5) aligning to June 4th

[Master project doc](https://docs.google.com/document/d/1QC91C86M1vox6vRrtfui_vfu5rhrlLjPN1HIyrkQcis/edit)

[Releng bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1551749)
[Copy doc](https://docs.google.com/document/d/1NwYHLso1SZm2OwDF0_dBZKA-muZ-dgP2EteLnBlORCs/edit?ts=5cdb4f8c)
[.lang file](https://github.com/mozilla-l10n/www.mozilla.org/blob/de0f09a522cb824d449e8f5b910bdd4b1ffecb8c/en-US/firefox/whatsnew_67.0.5.lang)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is live for QA May 21
- [ ] Per Flod, this will not be opened to locales other than DE and FR

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [x] Receive Designs on or before May 7th
- [x] Receive Strings on or before May 10th
- [ ] For users signed in to sync, page includes a CTA that sends users to their monitor breach alert dashboard
- [x] For users NOT signed in to sync, page includes a CTA that (sends users to FxA signup with trailhead branding)(?)

#### Tasks
- [ ] Validate with users (or confirm existing validation is adequate) @wboucherfischer
- [x] Code the page
- [ ] Analytics (@sghoseWI) review
- [x] Extract strings to Pontoon for DE and FR _only_, when strings are ready (@peiying2 will help manage this)

**Comment by amychurchwell** [comment]
**Work in progress designs.**
- - -
**LOGGED OUT**
![image](https://user-images.githubusercontent.com/30483988/57241884-e6fcd000-6fe6-11e9-92e3-437d43b7968e.png)

**LOGGED IN**
![image](https://user-images.githubusercontent.com/30483988/57241906-fda32700-6fe6-11e9-8cce-c65b18e5a718.png)

**Comment by dzingeek** [comment]
[WIP copy doc](https://docs.google.com/document/d/1NwYHLso1SZm2OwDF0_dBZKA-muZ-dgP2EteLnBlORCs/edit)

**Comment by dzingeek** [comment]
@amychurchwell here is the link to the [sketch file for WNP 67.0.5](https://share.goabstract.com/0f76d593-5111-454a-ab25-240549435058) _design is not final but super close_

You will find the correct WNP [here](https://user-images.githubusercontent.com/3740746/57469626-edd05080-723b-11e9-98c7-87c49f3b56de.png)

[Here is the link to the copy doc](https://docs.google.com/document/d/1NwYHLso1SZm2OwDF0_dBZKA-muZ-dgP2EteLnBlORCs/edit?usp=sharing) _also not final yet but close_

**PNGs for refernece** 
[logged in](https://user-images.githubusercontent.com/3740746/57469802-56b7c880-723c-11e9-9794-28c275026e2e.png)
[logged out](https://user-images.githubusercontent.com/3740746/57469837-6b945c00-723c-11e9-98a5-7deddf5d1cb0.png)

**Comment by hoosteeno** [comment]
Here's the conceptual flow for users signed in to sync:

On load, get flowId and flowBeginTime from FxA server and append to CTA. _Use a uniform, standard whatsnew endpoint for this request_. Examples: 
* https://github.com/mozilla/bedrock/blob/master/media/js/base/mozilla-fxa-form.js#L66
* https://github.com/mozilla/blurts-server/blob/ada648fecce64e3b14e7de2427a5814026b01b1e/public/js/fxa-analytics.js#L67-L78

On CTA, send users to a monitor.firefox.com endpoint with required parameters (`utm params, form type, form action, flowId, flowBeginTime, entrypoint`). _Use the same uniform, standard whatsnew entrypoint parameter for this request. `https://monitor.firefox.com/oauth/init?utm_source=TBD&utm_campaign=TBD&form_type=email&flowId=XXXX&flowBeginTime=YYYY&entrypoint=ZZZZ`

From there, Monitor + FxA take over and help the user land in their breach report. Ping @groovecoder or @shane-tomlinson for more details.

**Comment by hoosteeno** [comment]
@ejregithub can you confirm approval status of copy and design?

Approved by accountable?
Approved by legal?

**Comment by dzingeek** [comment]
@amychurchwell here is the [link to svg](https://mozilla.box.com/s/y7s8o6en58kv25tqf81vbxg3cpn98i33) for the hero image. let me know if you have any issues.

**Comment by dzingeek** [comment]
@amychurchwell this is the last graphics update. please remove the current heart icon with this one (personal data promise or PDP)
[PDP-icon_flat.svg.zip](https://github.com/mozilla/bedrock/files/3180241/PDP-icon_flat.svg.zip)


see [img for reference](https://user-images.githubusercontent.com/3740746/57738308-c3c7c580-7663-11e9-90bc-8431ccccf488.png)

**Comment by ejregithub** [comment]
Copy, after legal review, remains unapproved on one string.  MEM is working on this with Michael. Design can go forward as final/approved.

**Comment by dzingeek** [comment]
@amychurchwell here are updated svgs for two icons on the logged out state.

[WNP-Icons.zip](https://github.com/mozilla/bedrock/files/3183299/WNP-Icons.zip)

**Comment by amychurchwell** [comment]
Copy has final approval & is frozen.
https://docs.google.com/document/d/1NwYHLso1SZm2OwDF0_dBZKA-muZ-dgP2EteLnBlORCs/

**Comment by groovecoder** [comment]
@amychurchwell - can you let us know if/when this is up on any kind of staging server where we can check it out?

**Comment by amychurchwell** [comment]
@groovecoder sure thing! It will be on demo for stakeholder review 5/21 but I can put a draft up sooner for Monitor functionality review.

**Comment by dzingeek** [comment]
@ejregithub final designs with final copy

**logged out**
![WNP-67 5-logged-out 1312](https://user-images.githubusercontent.com/3740746/58058417-befc8900-7b1d-11e9-91a7-6651c3226b55.png)

**logged in**
![WNP-67 5-logged-in 1312](https://user-images.githubusercontent.com/3740746/58058418-bf951f80-7b1d-11e9-836d-f4f118f343df.png)
