### ISSUE TITLE
/new for Trailhead

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7129]
## Description

Code the /new page for the Trailhead release in June.
[Copy doc](https://docs.google.com/document/d/1F-hIja0JTQTHEK0_zKEFL8vRBBfYK4-LdqzaS-hSvN4/edit)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] /new and /thanks pages are converted to Protocol
- [ ] /new and /thanks pages are done by 5/21

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [x] Convert the pages to Protocol
- [x] Code the pages with copy and design assets provided by Aleks and JKropp

**Comment by dzingeek** [comment]
Designs are still WIP but the main structure is solid for both /new and /thanks. 

**Things that will change:**
- Spot illustations
- Copy

**Resources:**
[Sketch file](https://share.goabstract.com/31ef3279-7899-43e6-9cc4-d3f905056529) in abstract
[Location](https://user-images.githubusercontent.com/3740746/57031262-1b921580-6bfc-11e9-9c9a-81a389fadf54.png) of pages in the sketch file
[/new png](https://user-images.githubusercontent.com/3740746/57031227-00270a80-6bfc-11e9-8099-b3b1ccadfde5.png) for refernece
[/thanks png ](https://user-images.githubusercontent.com/3740746/57031236-09b07280-6bfc-11e9-8605-cb8e5b1d8f00.png)for reference

**Comment by alexgibson** [comment]
Thanks @dzingeek - I'm going to get started on this. Will let you know if I have any questions.

**Comment by alexgibson** [comment]
WIP demo for /new: https://www-demo1.allizom.org/en-US/firefox/new/?xv=trailhead

Note: I still need to port the Firefox Accounts modal for signed-out FF users.

**Comment by dzingeek** [comment]
@alexgibson this is looking great! Nice work and so fast!! We will have, updated approved copy for you early next week (fingers crossed for Monday). Then we will get you updated spot illustrations for both /new and /thanks

Also, when you say 'port the FxA modal for signed-out FF user" are you referring to [this](https://user-images.githubusercontent.com/3740746/57150478-46f33c80-6d83-11e9-8c51-56b0f645d8fc.png)?

If so hold off on that, I am working on getting it removed. will keep you posted as soon as i have news.

**Comment by alexgibson** [comment]
> Also, when you say 'port the FxA modal for signed-out FF user" are you referring to this?

Yes, - ok will hold off on implementing until I hear more. Thanks!

**Comment by dzingeek** [comment]
@alexgibson question on the button color. It looks too dark..It could just be me, but I thought the blue download button color was #0060DF

**Comment by alexgibson** [comment]
The color on the page is #0250bb, because that's what's in the design system: https://protocol.mozilla.org/patterns/atoms/buttons.html

**Comment by dzingeek** [comment]
@alex ok two things. 

1. I got confirmation from MEM that we can kill the pre-download modal. We will NOT be asking users for email/fxa sign ups before about:welcome from /new

2. Let's change the blue button download color in protocol to #0060DF the current one is too dark which is problematic on darker backgrounds. 

[see example (proposed blue on left current blue on right)](https://user-images.githubusercontent.com/3740746/57160483-c1c95100-6d9d-11e9-97d9-950d6d1d0d7a.png)

**Comment by dzingeek** [comment]
@alexgibson WIP copy doc

[/new + /thanks](https://docs.google.com/document/d/1F-hIja0JTQTHEK0_zKEFL8vRBBfYK4-LdqzaS-hSvN4/edit)

**Comment by alexgibson** [comment]
Protocol PR to update the product button theme color: https://github.com/mozilla/protocol/pull/381

**Comment by rraue** [comment]
Question @dzingeek: Will the Join Firefox feature on the /new page get a link to any "learn more"? I expect it to be in the best case not speaking to customers at all and in the worse case being confusing and misleading (do I have to pay for this?)

**Comment by dzingeek** [comment]
@rraue we did go back and forth on this. we 'can' add it, however, the goal was to not distract users from downloading firefox. if you think it's important i don't see why we can't link it to /firefox/accounts/

**Comment by dzingeek** [comment]
I never did user testing on /new that was the website team and desktop growth team. that said as a UX designer I don't like dead ends and I think for those who came to this page **just to download** they can quickly and easily do that. So I am fine with adding a link. 

As far as the term 'Join Firefox' that we did test and no surprise some users needed more info and some didn't.

**Comment by alexgibson** [comment]
Demo is now updated with both /new and /thanks:

- https://www-demo1.allizom.org/en-US/firefox/new/?xv=trailhead
- https://www-demo1.allizom.org/en-US/firefox/download/thanks/?xv=trailhead

I'm now waiting on:

- Final design assets.
- Final copy.
- Experiment test plan.

**Comment by alexgibson** [comment]
@dzingeek it looks like this experiment is ready to go, pending final design and copy.

I question whether the updated icons are likely to have much impact on an A/B test, but it would be great to get final copy. Do you know when we can expect that to come in? I think this is the last real blocker to getting this test out the door.

**Comment by dzingeek** [comment]
@alexgibson spot illustrations have been updated in both /new and /thanks [sketch file](https://share.goabstract.com/5d279374-61ec-43c9-b07e-9c7b8e1efb5d)

**Comment by dzingeek** [comment]
@alexgibson copy is approved!!!

[copy deck](https://docs.google.com/document/d/1F-hIja0JTQTHEK0_zKEFL8vRBBfYK4-LdqzaS-hSvN4/edit)

**Comment by alexgibson** [comment]
Thanks @dzingeek - will update here when final bits and pieces are up on demo

**Comment by alexgibson** [comment]
Final copy and design are now up on demo: 

- https://www-demo1.allizom.org/en-US/firefox/new/?xv=th&v=b
- https://www-demo1.allizom.org/en-US/firefox/download/thanks/?xv=th&v=b

**Comment by dzingeek** [comment]
@alexgibson the svg for the browser image is rendering odd. can you try this version and see if it is any better?

[fx-browser-img.svg.zip](https://github.com/mozilla/bedrock/files/3167422/fx-browser-img.svg.zip)

**Comment by alexgibson** [comment]
@dzingeek updated thanks, should be on demo in 10 or so minutes.

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/7168
