### ISSUE TITLE
Update card #1 on German homepage

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7131]
## Description

Update card 1 on German homepage. Card content will arrive on Friday May 3.

Changes to the other cards will be complete but not published before then. Those changes should be published with the update to card 1.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Card 1 matches copy and image in [spreadsheet](https://docs.google.com/spreadsheets/d/1gLv1pfj7TIuGXZyPnzi3iwdG0heYVpID1HWe4wrLT3c/edit#gid=325263488 )
- [x] Publish all German homepage updates to production.

#### Tasks
- [x] Update card image
- [x] Update card text
- [x] Update card link
- [x] Publish all German homepage changes

**Comment by alexgibson** [comment]
> Card content will arrive on Friday May 3.

Just a note to say that if we want to push this content live on Friday, I'll need it a GTM timezone friendly hour.

/cc @kellymj

**Comment by stephaniehobson** [comment]
Sounds like it will not arrive until EOD even for Pacific people so no Friday updates.
