### ISSUE TITLE
Redesign /accounts page for Trailhead

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7132]
## Description

Redesign the /accounts page with content for Trailhead launch on June 4

[Master project doc](https://docs.google.com/document/d/13CqvenWPOc8MQpPFIROjoSumq2RldehhIeYIjmpDi9w/edit)

[Copy doc](https://docs.google.com/document/d/14yH7BAC2qN5LKq3FsZITJS21moCFQZGgstx-014Oeyw/edit?usp=sharing)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] UI designs are received by 5/7
- [x] Interaction designs per user state are received by 5/7
- [x] Copy is received by 5/10 (was 5/15)
- [x] Strings are extracted by 5/21 (earlier better)

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Code page w. delivered copy and design assets
- [ ] Analytics (@sghoseWI) review

**Comment by dzingeek** [comment]
@craigcook here is the link to the [latest sketch file](https://share.goabstract.com/c95e358c-269a-4d15-b807-a3ac8f23ae7b)

you will find /accounts in the far left under pages ([see img for reference](https://user-images.githubusercontent.com/3740746/57559018-d6c15980-7334-11e9-8e2b-f97348e42b03.png))

I will get you an updated hero image for users who are logged in on monday 05.13.19

**Comment by dzingeek** [comment]
@craigcook here is the [latest copy doc](https://docs.google.com/document/d/14yH7BAC2qN5LKq3FsZITJS21moCFQZGgstx-014Oeyw/edit). tweaks might happen early monday.

**Comment by claychaffin** [comment]
The copy doc is now final. Thanks.
https://docs.google.com/document/d/14yH7BAC2qN5LKq3FsZITJS21moCFQZGgstx-014Oeyw/edit?usp=sharing

**Comment by dzingeek** [comment]
@craigcook we are removing pocket at fb container from the section titled "Get technology that fights for you." 

[see image for reference](https://user-images.githubusercontent.com/3740746/57733400-49dc1000-7654-11e9-8718-9d98495a4804.png)

**Comment by dzingeek** [comment]
@craigcook SVG files for gradient noodles!! 

[fx account hero imgs.zip](https://github.com/mozilla/bedrock/files/3179953/fx.account.hero.imgs.zip)

**Comment by dzingeek** [comment]
@craigcook here is an updated noodle for the not logged in state. let me know if you have any issues with the svg or the box link. 

https://mozilla.box.com/s/7t9jdenl8wmckjhgcp553737icjqcwuz

**Comment by ejregithub** [comment]
@dzingeek - can we get an image with the final copy, please?  [Copy (final/approved](https://docs.google.com/document/d/1F-hIja0JTQTHEK0_zKEFL8vRBBfYK4-LdqzaS-hSvN4/edit))

**Comment by dzingeek** [comment]
I can/will but I tend to think it's not necessary. Also, no one should use a design mockup as reference for final copy..they should always go to the source of truth which should be the copy doc.

**Comment by dzingeek** [comment]
@ejregithub that link is to the wrong copy doc. it's for /new and /thanks

**Comment by dzingeek** [comment]
![accounts v1 1056 (4)](https://user-images.githubusercontent.com/3740746/57878285-8d5a8980-77ce-11e9-99d6-789a76fcf2f1.png)

@ejregithub ^

**Comment by ejregithub** [comment]
*Awesome*, thanks @dzingeek

**Comment by ejregithub** [comment]
> @ejregithub that link is to the wrong copy doc. it's for /new and /thanks

Noted and replaced, thanks!

**Comment by ejregithub** [comment]
@craigcook is going to add a sign in link under the form in the new page, effectively fixing this ask:

https://bugzilla.mozilla.org/show_bug.cgi?id=1552819

**Comment by ejregithub** [comment]
@dzingeek - tagging you regarding the 'sign in' CTA  ^^

**Comment by dzingeek** [comment]
Confirming that we should add "Already have an account? Sign In." text + cta under the "continue" button for users who already know/have an account. 

![Screen Shot 2019-05-20 at 8 46 33 AM](https://user-images.githubusercontent.com/3740746/58034688-ffd3ae00-7adb-11e9-8558-b94662b45b1f.png)

**Comment by dzingeek** [comment]
final design mockups with the final copy

**Logged in**
![accounts-logged-in-1312](https://user-images.githubusercontent.com/3740746/58041993-5c3fc900-7aee-11e9-9ba5-1d74461fd8b4.png)
**Logged out**
![accounts-logged-out-1312](https://user-images.githubusercontent.com/3740746/58041950-3fa39100-7aee-11e9-9bfd-60411a0c6214.png)

**Comment by hoosteeno** [comment]
This page can land in prod anytime after 10am PDT 20190529.

**Comment by dzingeek** [comment]
@craigcook here are stacked SVG versions of the send, monitor and master brand.
[logos-svg.zip](https://github.com/mozilla/bedrock/files/3213062/logos-svg.zip)

**Comment by craigcook** [comment]
I need to know any UTM parameters and/or data attributes I should include on the four product links (especially the offsite links to Lockwise, Send, and Monitor), the Personal Data Promise blog post, and the account signup form.

**Comment by craigcook** [comment]
Demo: https://bedrock-demo-craigcook.oregon-b.moz.works/firefox/accounts/

**Comment by hoosteeno** [comment]
> I need to know any UTM parameters and/or data attributes I should include on the four product links (especially the offsite links to Lockwise, Send, and Monitor), the Personal Data Promise blog post, and the account signup form.

**For Lockwise, Monitor and Send**
`utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=accounts-trailhead&utm_content=product-list-item&entrypoint=mozilla.org-accounts_page`

**For Personal Data Promise**
`utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=accounts-trailhead&utm_content=accounts-value&utm_term=respect-you-deserve`

**For Account Sign Up Form**
It should use [the fxa_email_form macro](https://github.com/mozilla/bedrock/blob/8ed53c9975aa1542c799d6e69d30f8241b011b7a/bedrock/base/templates/macros.html#L365), which auto-generates much of the below.

`action=email&context=fx_desktop_v3&service=sync&entrypoint=mozilla.org-accounts_page&form_type=email&flow_id=[dynamic]&flow_begin_time=[dynamic]&utm_source=www.mozilla.org&utm_campaign=accounts-trailhead&utm_medium=referral&utm_content=form-upper&utm_term=join-firefox&email=[dynamic]`

Please note: I have freehanded the above, and they are different than those we have used. Please scrutinize and ask if something looks off.

**Comment by justinkropp** [comment]
@craigcook The demo is so nice. Great work on this! I tested the page in Opera, Fx, Chrome, and Safari and everything's consistent. 👍 

Just a one piece of design feedback: on smaller breakpoints the font-size of all the headlines gets reduced, except for the two sections at the bottom before the footer. This makes those two particular headlines feel quite large compared to the other sections:

<img width="771" alt="Screen Shot 2019-05-24 at 5 55 50 PM" src="https://user-images.githubusercontent.com/1461798/58358704-03ee2b80-7e4e-11e9-9c33-78bfb62c8017.png">

Could you make the following headlines
> Help us build a better Firefox for all.
> Help us keep Big Tech in check.
the same font-size as
> Get the knowledge to keep you safe.
on those smaller breakpoints?

On the smallest breakpoint, it might make more sense to also center the associated icons above the headlines as well.

Does that make sense?

**Comment by hoosteeno** [comment]
@craigcook the accounts form on this page needs to pass through upstream utm parameters, if they exist. @amy previously built this; if it's not clear how to set it up, she can consult.

**Comment by ejregithub** [comment]
Placing the blocked tag as the URL for the 'privacy promise' is not yet live, the content published - so we can't take this page live as intended (10 am PDT on 5/29)

**Comment by craigcook** [comment]
This page is now controlled by the switch `firefox_accounts_trailhead` to unblock it from merging or pushing to production. We'll flip that switch to activate the page when we've confirmed the blog post is live.

The blog post is being translated into German and French, but that can't begin until the original English is completed and approved (targeting end of business today, May 29). Given the short timeline there's a likelihood that translations won't be complete in time for the June 4 trailhead launch, so we're playing it safe and only linking to English for the initial page launch. We can update later to add the links to German and French when they're available.
