### ISSUE TITLE
/thanks for Trailhead

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7139]
## Description

Code the /thanks page for the Trailhead release in June.
[Copy doc](https://docs.google.com/document/d/1F-hIja0JTQTHEK0_zKEFL8vRBBfYK4-LdqzaS-hSvN4/edit)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] /thanks pages are converted to Protocol
- [ ] /thanks pages are done by 5/21

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [x] Code the page with copy and design assets provided by Aleks and JKropp

**Comment by alexgibson** [comment]
WIP up on demo: 

- https://www-demo1.allizom.org/en-US/firefox/download/thanks/?xv=trailhead
