### ISSUE TITLE
Trailhead - /new & /thanks experiment: Closure

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7142]
## Description

This is a closure card. It doesn't mean "stop the experiment now", but it hopefully leads to that.

In a closure card, we should do the tasks below, in order.

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Experiment is stopped
- [x] Experiment report is published 

#### Tasks
- [x] Determine whether we have enough data, and when we do, signal to shut down the experiment (@sghoseWI)
- [x] Shut down the experiment (by e.g. changing a switch)
- [ ] Publish an experiment report (@sghoseWI)
- [x] File any needed issues to remove or graduate experimental treatments (@hoosteeno)

**Comment by hoosteeno** [comment]
We have enough data. We can shut this experiment down.

**Comment by hoosteeno** [comment]
Let me clarify the above. 

We can stop the TrafficCop experiment that is sending a random % of visitors to two variations. That means all visitors will see the current treatment, which is identical to the control. However, we do not need to remove the Trailhead variation from Bedrock; next week, we will want the Trailhead variation to go live. Furthermore, QA may wish to visit the Trailhead variation's URL (xv=th&v=b) for QA, so we should leave the routing in place if we can.

**Comment by alexgibson** [comment]
Report is here: https://docs.google.com/document/d/1un9HIrY_aFr_hstTSSzFU8R5p7YwgyP2ODbjQoqq9f0/edit

All tasks for this issue are now complete, so I'm going to close this as done.

**Comment by ejregithub** [comment]
@alexgibson @sghoseWI @hoosteeno - this card was not sized, please apply an Estimate
