### ISSUE TITLE
Remove zh-TW whatsnew page template, use the global one instead

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7152]
## Description

https://bugzilla.mozilla.org/show_bug.cgi?id=1545705

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Current zh-TW /whatsnew page is removed.
- [ ] Regular /whatsnew page is shown instead.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
Closing, we already have an issue for this.
