### ISSUE TITLE
Help with email preferences center redesign

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7164]
## Description

LCM Team is redesigning the email preferences center as part of Trailhead deliverables. 

We *may* contribute some UX/UI consultation to the effort. It depends whether the project timeline has space for it, which won't be clear until the majority of implementation is complete. This is a lower priority for the LCM team than all other work on the project, and a low priority for the websites team, too.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] LCM team's implementation is improved in any way by design

#### Tasks
- [ ] Add new strings in bedrock
- [ ] Extract strings to Pontoon
- [ ] Implement UI changes (indentations, etc.)
- [ ] Change bg to white

**Comment by dzingeek** [comment]
**current ui of page**
![Screenshot_2019-05-09 Newsletter Subscriptions](https://user-images.githubusercontent.com/3740746/57472991-aea5fd80-7243-11e9-8473-c82285b014aa.png)

**Comment by dzingeek** [comment]
https://docs.google.com/document/d/1Dm5A6RsQidUJRFcKh9R0MDL_Rd3s__HxRvOIBkVk7Ic/edit#

**Comment by dzingeek** [comment]
Suggestion for basic tweaks to visuals would be to:

- [ ] Updated font
- [ ] Update font color (ink) #20123A
- [ ] Change background to be white
- [ ] make button blue #0060DF

attached image for reference 
![newsletter pref 1312 copy](https://user-images.githubusercontent.com/3740746/57555771-05860280-732a-11e9-8d74-62113b62524c.jpg)

**Comment by hoosteeno** [comment]
I'm calling this done -- thanks @dzingeek . Track implementation over in https://github.com/mozilla/bedrock/issues/7178.
