### ISSUE TITLE
Remove jQuery as a dependency on /firefox/download/thanks/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7166]
## Description

Right now, the `/firefox/download/thanks/` page relies on jQuery's non-standard `:visible` selector in order to [determine which download URL to trigger](https://github.com/mozilla/bedrock/blob/master/media/js/firefox/new/scene2.js#L10). All this is hinged upon a [crafty piece of CSS](https://github.com/mozilla/bedrock/blob/master/media/css/firefox/new/scene2.scss#L13-L25) that hides the button visually on the page, but still permits jQuery to consider it as visible for the auto-download to work. This feels like a brittle dependency between our (complex) download button CSS, jQuery's non-standard selector engine, and some page-specific CSS trickery.

Given that we have hopes of deprecating jQuery on bedrock, and coupled with the news that future versions of jQuery will [remove the Sizzle selector engine](https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/), it's about time we pay off this piece of technical debt and refactor how we handle auto-downloading.

I'd like to suggest that we switch to a vanilla JS solution that can be more easily unit tested.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] jQuery is removed as a dependency in `scene2.js`.
- [ ] jQuery is removed as a dependency from `mozilla-pixel.js`.
- [ ] Vanilla JS solution now handles auto-downloading.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] There's a risk of error that could impact downloads.

#### Tasks
- [ ] Implement vanilla JS solution.
- [ ] Write unit tests for the new code.

**Comment by alexgibson** [comment]
Note there is also another file on this page [mozilla-pixel.js](https://github.com/mozilla/bedrock/blob/master/media/js/base/mozilla-pixel.js) that also uses jQuery.

**Comment by alexgibson** [comment]
I'm going to tackle this as part of https://github.com/mozilla/bedrock/issues/9102
