### ISSUE TITLE
Experiment: Test variations of new brand on /firefox

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7183]
## Description

In https://github.com/mozilla/bedrock/issues/6865 we launched a new version of /firefox with new branding, and it didn't convert as well. We want to run an experiment with several variations of the new brand so we can learn what aspects of it contribute to the decline.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Experiment is designed
- [ ] Experiment is launched according to designs
- [ ] Experiment is analyzed/closed

#### Tasks
- [x] Build experiment plan (@hoosteeno)
- [x] Review experiment plan (@sghose)
- [x] Build variations (@shobson)
- [x] Configure experiment (@shobson)
- [ ] Launch experiment (@shobson)
- [ ] Build closure card

**Comment by hoosteeno** [comment]
Experiment plan under development here: https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=95587541

**Comment by hoosteeno** [comment]
@stephaniehobson the experiment plan is ready for your review/implementation. It would be very helpful if you could post a comment like [this one](https://github.com/mozilla/bedrock/issues/7159#issuecomment-490476566) with the parameters you use. I'm happy to consult.

**Comment by stephaniehobson** [comment]
```
{ 
"data-ex-name": "firefox_desktop_brand", 
"data-ex-variant": "v_a" 
}
```

Can we do stub attribution from this page? Do we need stub attribution to evaluate this experiment?

**Comment by hoosteeno** [comment]
I don't think we need to do stub attribution; this is really a download experiment.

I'm not sure the feature we built to make it repeatable works on /firefox right now.
