### ISSUE TITLE
Add deep linking in redesigned /all page

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7208]
## Description

On the new /all page, we have some installers that we wish to link people directly to. Specifically, we would like to deep link people to the list of installers corresponding to the /all pages we will decommission:

```
    https://www.mozilla.org/en-US/firefox/organizations/all/
    https://www.mozilla.org/en-US/firefox/beta/all/
    https://www.mozilla.org/en-US/firefox/developer/all/
    https://www.mozilla.org/en-US/firefox/nightly/all/
    https://www.mozilla.org/en-US/firefox/android/all/
    https://www.mozilla.org/en-US/firefox/android/beta/all/
```

This will enable us to redirect traffic from those URLs to a pre-filled form on the new /all page that serves the same product.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] A request to specific valid configurations change dynamic elements on the page to match that configuration.

#### Tasks
- [ ] Identify what we want to create deep links for in /all page 
- [ ] Create the deep links and add to the page

**Comment by alexgibson** [comment]
There are likely some edge cases to think through here:

- Not all products are available in the same languages all the time (e.g. Nightly might add/drop some locales).
- Not all products support the same platforms (e.g. desktop vs android).
- Some products have more than one version at times (e.g. ESR).

If we're to make configuring the form deep-linkable in this way, we may want to think about how we handle at least some of the above edge-cases, and if we need to communicate that in some way when people land on the page.

**Comment by hoosteeno** [comment]
>     * Not all products are available in the same languages all the time (e.g. Nightly might add/drop some locales).
>     * Not all products support the same platforms (e.g. desktop vs android).

I'm not clear on the risks here. Is it that someone might manually modify the fragment -- for example, incrementing the version or changing the platform while assuming the locale will persist? If so, could we mitigate this with some messaging indicating that an invalid fragment was detected and we've reset dropdowns to the default?

>     * Some products have more than one version at times (e.g. ESR).
Could we mitigate this by including an optional version parameter in the fragment, and specifying what to do when it is missing or invalid?

**Comment by alexgibson** [comment]
@hoosteeno I don't think there's a risk per-say, other than someone not quite getting the download they expect. URLs can stay around for a long time once shared, so i think it may at least be worth taking some time to think through what should happen on the page.

**Comment by alexgibson** [comment]
A couple of other points to consider:

- I've been asked to add Firefox for iOS to the page. We don't provide configurable builds for this product, and can only point to the app store. So we'd need to figure out how to handle this.
- On page load, we auto-detect the user's language (based on the page language), and also try to best guess their operating system. This existing behavior would need overriding by the URL params, if we also make these options configurable via deep linking.

As a side note: I've also been wondering if this is a feature set our own team has created as an idea, or if this is a real request for functionality by another team? I'm a little cautious that we may be building a complex system of deep linking, when there may not yet be an overwhelming need from consumers of this page. A simpler option could be, for example, to only make each product deep-linkable e.g. `https://www.mozilla.org/firefox/all/#product-desktop-beta`. The page then already tries to make the most appropriate selection for the other options based on the variables of the user agent. Could this be enough?

**Comment by hoosteeno** [comment]
Let's not work on this until the page is launched and we see a real need for it.

**Comment by stephaniehobson** [comment]
It would be nice to retire these pages and replace them with /all or a copy of /all with the defaults pre filled (not sure what's best for SEO):

- https://www.mozilla.org/en-US/firefox/beta/all/
- https://www.mozilla.org/en-US/firefox/developer/all/
- https://www.mozilla.org/en-US/firefox/nightly/all/
- https://www.mozilla.org/en-US/firefox/android/all/
- https://www.mozilla.org/en-US/firefox/android/beta/all/

**Comment by alexgibson** [comment]
The plan is to decomission and redirect all these old pages just as soon as the new unified page is localized. Currently that's blocked on #7209, but hopefully we can get moving again soon.

**Comment by stephaniehobson** [comment]
Okay, that means there's a need for deep linking.

**Comment by alexgibson** [comment]
I think we need to spend some time refining what we mean by deep linking. I agree it would be nice to link directly to each product, but i’m not yet convinced that we need something as complex as originally described here.

**Comment by hoosteeno** [comment]
I updated the description of this issue to make it less prescriptive and potentially easier to solve for known use cases.

It would be possible to solve this by handling each and every possible combination (e.g. `#os&locale&product`). It would also be possible to solve this by handling a subset of combinations that we know we want to handle (e.g. `#msi` or `#esr` or `#devedition`), and adding to that subset when new deep link needs come up.

**Comment by ejregithub** [comment]
@hoosteeno - please research further on the requirements here

**Comment by hoosteeno** [comment]
I updated the requirements to include a minimal set of deep links to satisfy the most certain use case. We can enhance as new use cases come online.

**Comment by stephaniehobson** [comment]
We have one more certain use case:

<img width="361" alt="Screen Shot 2019-07-22 at 3 50 38 PM" src="https://user-images.githubusercontent.com/854701/61670443-87829800-ac98-11e9-8ca3-91a4a6b5432f.png">

**Comment by hoosteeno** [comment]
While I agree, there is an MSI link on the /enterprise page now, it does not have to be there. We're redesigning that page. Will it have a download button for MSI? A link to /all? These are TBD, and we can punt including them in this work right now.

**Comment by alexgibson** [comment]
Based on the revised scope of this task, I'm going to estimate this as a 3.
