### ISSUE TITLE
Created URL & redirect for /firefox/account - /firefox/accounts

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7210]
## Description

Currently the URL www.mozilla.org/firefox/account/ leads to a 404. Given the possibility of users entering that URL in an attempt to reach the accounts page we should create that URL and set a 301 redirect from it to www.mozilla.org/firefox/accounts

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] The redirect is in place at go live

#### Tasks
- [x] Create the URL www.mozilla.org/firefox/account/ 
- [x] Set a 301 redirect from it to www.mozilla.org/firefox/accounts

**Comment by ejregithub** [comment]
@craigcook - this done, correct?

**Comment by craigcook** [comment]
It's included with the new page: https://github.com/mozilla/bedrock/pull/7197/files#diff-4223a0866ea97c5a79021d7e1e267ee0R608

**Comment by ejregithub** [comment]
Cool, closing as it's in place, just pending the go live
