### ISSUE TITLE
EN Hompage Card 5

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7221]
## Description

TAG: (no change) FIREFOX
HEADLINE: (no change)  Get the latest Firefox
IMAGE: (new) https://blog.mozilla.org/wp-content/uploads/2019/05/FX67_Blog_Speed_1200x660.png
BLURB: (new copy) The latest Firefox brings fast and private together with new features to keep your personal information safe while you’re online with us.
LINK: (new) https://blog.mozilla.org/blog/2019/05/21/latest-firefox-release-is-faster-than-ever/

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Updates made
- [ ] Updates launched

#### Tasks
- [x] Update card copy
- [x] Update card link
- [x] Update card image
- [x] Test on dev
- [ ] Test on stage
- [ ] Publish updates
- [ ] Test on prod
