### ISSUE TITLE
/all - User testing

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7231]
## Description

Description, good enough that reading the card 1 month from now, you still know what it means.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] A test plan is written.
- [ ] There is a usability report written
- [ ] The results are presented to the group.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] The /all page is not ready.
- [ ] I don't understand the /all page design.

#### Tasks
- [ ] A test plan is written.
- [ ] A test plan is posted in usertesting.com
- [ ] A prototype is created in Invision.
- [ ]  The test is launched and we get 10 users to take it.
- [ ] The videos are watched and notes taken.
- [ ] There is a usability report written
- [ ] The results are presented to the group.

**Comment by ejregithub** [comment]
@wboucherfischer - please flesh out the description as well as adding tasks and success criteria (the definition of done).

**Comment by wboucherfischer** [comment]
@ejregithub  done!
