### ISSUE TITLE
Rename "Firefox Lockbox" to "Firefox Lockwise" after May 28

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#7242]
## Description

Lockbox is getting a new name on 28 May, 2019 in time for the trailhead release. We'll need to find any pages where we refer to it by name and update them to Lockwise. We also need to update any links from lockbox.firefox.com to lockwise.firefox.com.

https://www.mozilla.org/firefox/accounts/ (the redesign (see #7132) already changes to Lockwise but most locales will still see the old page for a while until they can translate the new one)
https://www.mozilla.org/firefox/64.0/whatsnew/
https://www.mozilla.org/firefox/66.0/whatsnew/
https://www.mozilla.org/firefox/67.0/whatsnew/
https://www.mozilla.org/en-GB/firefox/new/ (SEO experiment)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] All mentions of Lockbox are updated to Lockwise
- [ ] All links to lockbox.firefox.com are updated to lockwise.firefox.com

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by rraue** [comment]
Not sure whats the status of this, but I included "Lockbox" in my crawl today and found two more pages with Lockbox mentions:

- https://www.mozilla.org/en-US/ (The blogpost teaser on the homepage mentions still lockbox)

- https://www.mozilla.org/en-US/about/legal/terms/services/ (in the ToS of Services we still talk about Lockbox

**Comment by ejregithub** [comment]
@amychurchwell - Please size the work done here in the Estimate menu

**Comment by amychurchwell** [comment]
@ejregithub I added an estimate. I went with 2 because it was not a difficult task, just a bit time consuming.
