### ISSUE TITLE
Set up switch for Trailhead WNP to be shown on Beta and DevEd

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7253]
## Description

In order to not show the Trailhead WNP content to beta and DevEd users updating before June 4th, we need to put these, assigning content to the designated URLs, behind a switch.

---

#### Tasks
- [x] Show Trailhead WNP content at /firefox/68.0beta/whatsnew/
- [x] Show Trailhead WNP content at  /firefox/68.0a2/whatsnew/
- [x] Flip the switch(es) just before 6am PDT on Tuesday June 4th

**Comment by alexgibson** [comment]
PR to enable switches on Tuesday: https://github.com/mozmeao/www-config/pull/228

**Comment by alexgibson** [comment]
Switches are flipped and should be live shortly, pending cache expiry.
