### ISSUE TITLE
June/Trailhead en homepage updates

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7273]
## Description

MJ will be providing updates to the www homepage in en. These will need to land on or before June 4th, depending on the timing of the delivery of the new assets.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Live on or before June 4

#### Tasks
- [x] Update (code) www.mozilla.org/en page with new content
- [x] Code review, launch

**Comment by stephaniehobson** [comment]
Pull request is here: https://github.com/mozmeao/www-admin/pull/39

Possible further changes:
- Carolyn may want to provide new versions of the images for cards 3 and 4.
- The image provided for card 1 was not large to create a high res version, it'd be nice if that was high res.

**Comment by ejregithub** [comment]
@stephaniehobson  - Please size the work done here in the Estimate menu
