### ISSUE TITLE
fr-language homepage: Code it, integrate with publishing system

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7282]
## Description

New French language homepage.

[Cards and translations](https://docs.google.com/spreadsheets/d/1fYa0WrMTpIOqP8gGvW16ekWCy73bbgzytFf6DXX1m30/edit#gid=320304329).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Visiting mozilla.org/fr/ results in a card-based French homepage

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [x] Card 3 blog post is not translated yet and will be arriving late.

#### Tasks
- [x] Add page in bedrock
- [x] Add/update tests in bedrock
- [x] Add folder and cards in www-admin
- [x] bedrock code review
- [x] publish to demo for client review
- [x] client review of card updates
- [x] www-admin launch
- [x] bedrock launch

**Comment by stephaniehobson** [comment]
Updated the description.

**Comment by stephaniehobson** [comment]
Holding off on this one until after the All Hands.
