### ISSUE TITLE
Build and launch a fr-language homepage

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7284]
## Description

The EU Brand Team is nearly finished with content for a fr-language homepage. They expect to have final copy ready for a homepage on Friday Jun. 7. We should build that homepage and integrate with our homepage publishing system. 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Content delivered
- [x] Page built, integrated with publishing system
- [x] Page reviewed by stakeholders
- [ ] Page launched

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by stephaniehobson** [comment]
@ejregithub Do they know they need to provide translations of all the content on the page and not just card content? When I've done previous translation work with them we had a spreadsheet with English in one column and French in the other, do you know if we provided them with something like that to fill in?

**Comment by alexgibson** [comment]
This is live in production: https://www.mozilla.org/fr/
