### ISSUE TITLE
Update metadata on /accounts page

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7285]
## Description

The metadata on the /accounts page did not change with Trailhead, which means it still uses pre-Trailhead CTAs ("Get a Firefox Account") and imagery.

1. We should update the <title>, og:title, and og:description copy. We need copy for this. Current copy below:

```
<title>Get a Firefox Account – Keep your data private, safe and synced</title>
<meta property="og:title" content="Get a Firefox Account – Keep your data private, safe and synced">
<meta property="og:description" content="Securely sync your passwords, bookmarks and tabs across all your devices. Get a Firefox Account now – One login – Power and privacy everywhere.">
```

2. We should update the global meta image. Current image below:

![page-image.4b108ed0b8d8.png](https://images.zenhubusercontent.com/5c871077d74bd07972c6db24/2c9e525c-3e81-4199-b580-4e13d7bcf84c)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] New copy delivered
- [x] New image delivered
- [ ] Metadata updated
- [ ] Changes released in appropriate locales

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by hoosteeno** [comment]
@dzingeek Can you provide the image requested by this issue? If you have questions about sizing, ping @craigcook.

@claychaffin Can you provide the copy requested by this issue?

**Comment by dzingeek** [comment]
@hoosteeno I think this issue is a copy of this one??
https://github.com/mozilla/bedrock/issues/7286

**Comment by craigcook** [comment]
Oops, I hadn't realized this issue also covered the image when I filed the other one. Sorry for the dupe.

**Comment by claychaffin** [comment]
@hoosteeno Yes, I will provide copy.

**Comment by claychaffin** [comment]
Copy deck for this Issue, a WIP: https://docs.google.com/document/d/1hCI5gcQ-CBr4U4N9SGOKDGAwIYmgbJ1Rgrel3aV88Kk/edit?usp=sharing

**Comment by ejregithub** [comment]
@claychaffin - Please size the work here in the Estimate menu

**Comment by claychaffin** [comment]
@ejregithub @rraue here are some copy options -- thanks for your help, @rraue 
https://docs.google.com/document/d/1hCI5gcQ-CBr4U4N9SGOKDGAwIYmgbJ1Rgrel3aV88Kk/edit?usp=sharing

**Comment by claychaffin** [comment]
Revised the copy to address @rraue 's feedback. Good to go now? @hoosteeno @rraue 
https://docs.google.com/document/d/1hCI5gcQ-CBr4U4N9SGOKDGAwIYmgbJ1Rgrel3aV88Kk/edit?usp=sharing

**Comment by claychaffin** [comment]
@craigcook

**Comment by hoosteeno** [comment]
r+, ship it :shipit:

**Comment by rraue** [comment]
Ship it
-- 
______
Send via mobile

Raphael Raue
Global Head of Seo
www.mozilla.org

twitter.com/raue

**Comment by ejregithub** [comment]
@craigcook - what's the status on this one?
