### ISSUE TITLE
Update standard Firefox meta image

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#7286]
## Description

Most Firefox pages use a standard page image that appears when the URL is shared on social media like Facebook, Twitter, Slack, etc. The current standard image is still Quantum branded (blue background) and we should update that to the new Firefox branding.

Once the new image is in production we can force Facebook and Twitter to update their cached images for a few key pages (/firefox, /firefox/accounts, probably a few others).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] New image is added to firefox-branded base templates.
- [ ] New image begins to appear when the pages are shared.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] External sites may continue to show the old image from their own caches.
- [ ] This is an example of a risk.

#### Tasks
- [x] Create the image.
- [x] Add the image to the Firefox base templates.
- [ ] Trigger Twitter/Facebook to update their cached images for key pages.

**Comment by dzingeek** [comment]
@craigcook here is the image that should be used for general Firefox things (non-browsers). WIll have a Firefox browser image for you tomorrow. 

![FX_display_1920x1080-6](https://user-images.githubusercontent.com/3740746/58982094-8947d900-8788-11e9-8e8f-197959ccc386.jpg)

**Comment by dzingeek** [comment]
@craigcook here is one for all things browsers.  
![blog - img_FX_1200 x 630 12](https://user-images.githubusercontent.com/3740746/58997284-c32cd580-87b0-11e9-9769-1a6dc3c917c2.jpg)

**Comment by craigcook** [comment]
At the moment the majority of our Firefox-themed pages are about the browser, so I'm thinking we go with that one as the default and use the master brand image only on certain pages where it's fitting (like /accounts).

**Comment by stephaniehobson** [comment]
@craigcook Was this closed by #7285?

**Comment by craigcook** [comment]
Yeah, and actually it should have been closed a long time ago because the other issue covered updating the image as well. Closing now!
