### ISSUE TITLE
Update design and copy for hero section on mozilla.org

### ISSUE THREAD

**Issue by claychaffin** [mozilla/bedrock#7292]
## Description
As part of Trailhead, we are 1) moving away from the term "Accounts" (and "accounts") and the product positioning "Firefox Accounts" to support a new membership model ("Join Firefox") and 2) updating mozilla.org everywhere with a new brand design. 
To that end, we need to update design and copy for the "hero section" (the topmost main headline and subhead) on mozilla.org with Trailhead messaging, including eliminating the reference to "Account" in our existing subhead ("Take your privacy and bookmarks everywhere with a Firefox Account.").

In a separate Issue -- https://github.com/mozilla/bedrock/issues/7190 -- we are creating new copy to replace the existing FxA global CTA copy (existing: "Get A Firefox Account"). 
When we publish/push this new FxA global CTA live, we should simultaneously (or as soon as practicable) also publish/push the content created under this Issue https://github.com/mozilla/bedrock/issues/7292  

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] - add master brand logo
- [ ] - write headline 
- [ ] - write subhead
- [ ] - what is best, button or link?
- [ ] - write button or link copy
- [ ] - update graphic

**Comment by hoosteeno** [comment]
This is done. 

![image](https://user-images.githubusercontent.com/94519/71934690-3db43e00-3162-11ea-9bd0-08e3861a0f3b.png)
