### ISSUE TITLE
Find a more reusable approach to fundraising banners

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#7301]
## Description

For the past several years we've done an end-of-year fundraising campaign on the home page (and other pages). Each time we've done this, the home page has changed so much in the year since the last campaign that we've mostly had to do it over from scratch each time.

Lately we've been asked to bring the banner back at other times during the year. Given the way templates are structured it still has to be done by hand each time, even if it's mostly copy-pasting the previous banner. This has become a repetitive task.

If this is going to keep coming up so regularly, we should build it in a more easily reusable manner. We could also get some evergreen copy localized.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Build a reusable fundraising banner component.
- [ ] Banner content can be updated (within constrains).
- [ ] Banner design can be updated (within constraints).
- [ ] Some basic evergreen content exists that we can have widely localized.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by craigcook** [comment]
Bah, just saw this was a duplicate of https://github.com/mozilla/bedrock/issues/7185
