### ISSUE TITLE
Update newsletter ID on the /contribute page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7305]
## Description

Change the newsletter Id on the `/contribute/` page to `about-mozilla`.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Newsletter is updated and in production.

#### Tasks
- [ ] Update newsletter ID.
- [ ] Verify newsletter subscriptions are working.
