### ISSUE TITLE
German June/Trailhead homepage updates

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7308]
## Description

June / trailhead update for the German homepage. [Requirements](https://docs.google.com/spreadsheets/d/1gLv1pfj7TIuGXZyPnzi3iwdG0heYVpID1HWe4wrLT3c/edit?ts=5cfa3eca#gid=320304329).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Content cards updated and published
- [x] Homepage layout updated from 13 to 12 card layout.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [x] Card 3 blog post is not translated yet and will be arriving late.

#### Tasks
- [x] Update layout in bedrock.
- [x] Update cards in www-admin
- [x] Figure out how best to launch a layout change to a page that depends on content cards.
- [x] bedrock code review
- [x] publish to demo for client review
- [x] client review of card updates
- [x] www-admin launch
- [x] bedrock launch

**Comment by stephaniehobson** [comment]
Note: updated cards must publish before the bedrock changes.

**Comment by stephaniehobson** [comment]
Increasing the estimate to 3 because of #7319

**Comment by stephaniehobson** [comment]
Never mind, I'll add the increased time to #7319 itself.

**Comment by stephaniehobson** [comment]
Published!
