### ISSUE TITLE
/accounts - improve the signed-in state

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7315]
## Description

We need to fix the signed-in state on /accounts. 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### Tasks
- [ ] [Copy](https://docs.google.com/document/d/1nyg_trea3ew3dBMA_GP_kW2Bw5W7T4rAWCzQUH-DvZg/edit?usp=sharing) - @claychaffin 
- [ ] Design - @mrkwvr 
- [ ] Code - @alexgibson

**Comment by ejregithub** [comment]
From @claychaffin - Copy doc for _non-signed in_ users:
https://docs.google.com/document/d/1nyg_trea3ew3dBMA_GP_kW2Bw5W7T4rAWCzQUH-DvZg/edit?usp=sharing

**Comment by ejregithub** [comment]
Closing, this is a duplicate to #6907
