### ISSUE TITLE
Improve functional tests for /firefox/accounts/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7327]
## Description

Now that #7318 has merged, we have two distinct states for the /firefox/accounts/ page. One for signed-out users, showing the "Join Firefox" form, and one for signed-in users, showing a Firefox Monitor CTA.

Our current functional tests for this page are pretty basic. All we have is a [single test](https://github.com/mozilla/bedrock/blob/master/tests/functional/firefox/test_accounts.py#L13) that asserst that the form is displayed, but not much else.

To better test that this page works as intended it would be good to:

1. Expand the existing test to cover the functionality of the form itself. If we enter information and click "Continue", does it do the right thing? I don't think we need to test the full account signup flow, as that is not within bedrock's remit. However it would be good to assert that the right URL is loaded, together with the expected email parameter e.g. 

    - https://accounts.firefox.com/signup?action=email&entrypoint=mozilla.org-accounts_page&form_type=email&flow_id=d45ef062b25c7428583c2b765dbd370457275bfbf6f29bec07629fbe1bed551c&flow_begin_time=1561365277162&utm_source=accounts_page&utm_content=form-upper&utm_medium=referral&utm_campaign=accounts-trailhead&style=trailhead&email=success%40example.com

2. Add a new functional test to cover the signed-in state. Automating the full sign-up and verification flow is likely to be a large and complicated task. That would be good to cover at some point, but for now we could provide a shortcut just for testing purposes e.g. if `&s=t` is in the URL, show the signed-in state. It's not ideal, but would at least provide a lower effort testing mechanism. This param might also be helpful for stakeholder demo reviews.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] New tests are passing in automation.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Not improving tests increases risk of accidental breakage.

#### Tasks
- [x] Improve signed-out test.
- [x] Add signed-in test.

**Comment by stephaniehobson** [comment]
Closed by #7329
