### ISSUE TITLE
Extract l10n string changes for /firefox/accounts/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7328]
## Description

Task to extract strings added in #7318
---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] New strings are extracted for translation.

#### Tasks
- [x] PR to dev L10n repo.
- [x] PR to prod L10n repo.

**Comment by alexgibson** [comment]
Completed in:

https://github.com/mozilla-l10n/www.mozilla.org/pull/302
