### ISSUE TITLE
Test pre-download FxA CTA for Firefox users modal #7235

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7340]
## Description

We to understand the impact of the redesigned modal

- Set up traffic cop to route and build cohorts
- Log clicks on the FxA CTA
- Log clicks on the download CTA
- Log clicks on the modal dismissal
- Find out how many people sign up for accounts coming from the page (via 'v' params - just not UTM)
- Measure actual installs (stub installer attribution)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Test is in place and live before the end of the sprint

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
We decided that we're not testing this modal and instead we're rolling it out as is. Closing this issue.
