### ISSUE TITLE
/Firefox brand experiment: Closure

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7341]
## Description

This is a closure card. It doesn't mean "stop the experiment now", but it hopefully leads to that.

In a closure card, we should do the tasks below, in order.

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Experiment is stopped
- [x] Experiment report is published 

#### Tasks
- [x] Determine whether we have enough data, and when we do, signal to shut down the experiment
- [x] Shut down the experiment (by e.g. changing a switch)
- [x] Publish an [experiment report](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=95587541) 
- [ ] File any needed issues to remove or graduate experimental treatments (@hoosteeno)

**Comment by stephaniehobson** [comment]
@hoosteeno So it looks like all of the following improved the original design:
- Remove "quantum"
- Add "browser"
- Use a product shot

But no single change improved the conversion to where the original was.

I see three options:
1) Put all the changes together on one page and run a new a/b test to see the combined affect.
2) Put all the changes together one one page and launch it.
3) Remove the test, keep the original.

Some things to help inform your decision:
- the current page includes the word "quantum" and the test showed removing that improved conversions for the new page
- /firefox will likely not be used to sell the desktop browser by the end of the summer
- it's only an hour or so of coding work to do any of the three options, a third a/b test would involve @sghoseWI's time as well.

**Comment by stephaniehobson** [comment]
@hoosteeno Ping, now that you're back from PTO.

**Comment by stephaniehobson** [comment]
Given the plans for this page I'm going to remove the experiment code. It can be recovered from git history if we need it later.

**Comment by ejregithub** [comment]
@hoosteeno - it looks like there's no need to 'File any needed issues to remove or graduate experimental treatments'. Please confirm and I'll close this issue.

**Comment by hoosteeno** [comment]
The page is evolving in a different direction than we explored in these tests. We may with to revive these someday for the Firefox browser download page; for now, removing from the site makes sense.
