### ISSUE TITLE
Update platform /new URLs to trailhead design

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7345]
## Description

The three platform-specific download pages for Windows, Mac and Linux still feature the old /new page design. We should update them to the new trailhead branding / messaging.

- https://www.mozilla.org/en-US/firefox/windows/
- https://www.mozilla.org/en-US/firefox/mac/
- https://www.mozilla.org/en-US/firefox/linux/
---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Pages are updated with the trailhead design in production.

#### Tasks
- [ ] Update the three URLs to show the new design.
- [ ] Expose new strings for L10n behind a tag.

**Comment by hoosteeno** [comment]
See also #6798 , which suggests simplifying these pages since their traffic is primarily non-Fx users.

**Comment by alexgibson** [comment]
Done in https://github.com/mozilla/bedrock/pull/8532
