### ISSUE TITLE
Leadership page updates - July 15th

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7347]
## Description

Update the Leadership page with new folks and remove Nick

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Updates are live before the end of July

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Delivery of headshots on or before July 15th

#### Tasks
- [ ] Add Add [Joe Hildebrand](https://bugzilla.mozilla.org/show_bug.cgi?id=1558629) to the Mozilla leadership page
- [ ] Add [Reese Wood](https://bugzilla.mozilla.org/show_bug.cgi?id=1557503) to the Mozilla Leadership page
- [ ] Remove Nick N. content

**Comment by ejregithub** [comment]
Duplicate to #7348, closing.
