### ISSUE TITLE
Leadership page updates 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7348]
## Description

Update the Leadership page with new folks and remove Nick

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Updates are live shortly after assets are final

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Delivery of headshots on or before July 15th

#### Tasks
- [x] Add Add [Joe Hildebrand](https://bugzilla.mozilla.org/show_bug.cgi?id=1558629) to the Mozilla leadership page
- [x] Add [Reese Wood](https://bugzilla.mozilla.org/show_bug.cgi?id=1557503) to the Mozilla Leadership page
- [x] Remove Nick N. content

**Comment by craigcook** [comment]
Blocked until we get headshots
