### ISSUE TITLE
Pre/post analysis of /all page after launch

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7349]
## Description

After launching the revisions to /all we need to understand the page's performance by way of a  pre/post analysis

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Date ranges for pre/post analysis are determined
- [ ] Measurements are established
- [ ] Measurements are recorded and analyzed 
- [ ] Recommendations are provided

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] The changes could tank downloads, resulting in the need to revert.

#### Tasks
- [ ] Gather data at set intervals
- [ ] Analyze and report

**Comment by ejregithub** [comment]
@sghoseWI - I think you're 'back' (welcome to FTE) tomorrow, Wednesday, July 10th. Can you please pick up this card?

**Comment by sghoseWI** [comment]
@ejregithub I'm on it!

**Comment by sghoseWI** [comment]
@ejregithub please see here for the report: https://docs.google.com/document/d/17aTgaDpLq2lysWrh3k9Ib5C5jDdszktwDHTA0wGCfTc/edit

**Comment by ejregithub** [comment]
@hoosteeno - please review Saptarshi's findings ^^ and recommendation to stay the course (Please confirm no further action need be taken on the /all pertinent to / as a result of this report

**Comment by ejregithub** [comment]
@sghoseWI - can you please apply an Estimate for you work here? (Like, half a day, just you, would be a '1', whole day, a '2')

**Comment by hoosteeno** [comment]
Thanks for confirming the conversion rate was steady. Let's stay the course with the /all page.

**Comment by ejregithub** [comment]
Thanks to you both. Closing this issue.
