### ISSUE TITLE
 Update BiAnnual Transparency Report for 2019 H1

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7356]
## 
Description

Twice a year we update the Transparency Report. This issue is for doing so for H1/2019 (Jan-June). The work here entails created a new URL and updating data here (for 2019 H1) https://www.mozilla.org/about/policy/transparency/jan-jun-2019/ using the /jul-dec-2018/ page as a template. Legal will provide the copy and data.

All comments and questions about the content should be done in the internal bug - 
https://bugzilla.mozilla.org/show_bug.cgi?id=1564533

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Is launched  on July 30, 2019 (to be managed in #7422)
- [x] NO DATA OR INFORMATION IS POSTED PUBLICLY BEFORE LAUNCH

#### Tasks
- [x] Create a private bug
- [x] Create new URL - https://www.mozilla.org/en-US/about/policy/transparency/jan-jun-2019/ 
- [x] Add [new content](https://docs.google.com/document/d/1ScybevfXbzulCz2csF0e0sVD_1fAg5lwH2kosQKp0LY/edit)
- [x] Screenshots posted in private bug for QA by Legal
