### ISSUE TITLE
Decommission old /whatsnew templates.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7370]
## Description

Our logic for displaying the `/whatsnew` page is [growing unwieldly](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/views.py#L594-L629). It's time to remove some of the older templates that we're shown to past releases.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Old templates are removed.
- [ ] URLs fallback to the default /whatsnew page.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] We should make sure traffic is acceptably low to templates being removed.

#### Tasks
- [ ] Remove templates and associated assets.
- [ ] Update tests.

**Comment by craigcook** [comment]
I propose killing off everything prior to 67.0.1 (the trailhead page) since everything older than that is now off-brand.

At the same time, we should replace the default page (also off-brand) with the new modular template coming with Fx69, but with evergreen content. We'll probably need to keep the old default page around for a transitional period as a fallback while locales translate the evergreen content, but can plan on permanently decommissioning the old page soon after.
