### ISSUE TITLE
Write functional tests for release notes pages.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7388]
## Description

We don't currently have any functional tests for release notes pages. We have many different release notes URLs, but they all use the same base template and shared code. Testing a handful of URLs (like below) should give us good enough base coverage for functionality and conditional states.

URL: https://www.mozilla.org/en-US/firefox/75.0/releasenotes/

- Assert download button is displayed in header for non-Firefox browsers.
- Assert secondary download button is displayed in footer for all-browsers.
- Assert "Pre-releases" menu is displayed on click.

URL: https://www.mozilla.org/en-US/firefox/android/68.7.0/releasenotes/

- Assert Google Play button is displayed in header for non-Firefox browsers.
- Assert secondary Google Play button is displayed in footer for all-browsers.

URL: https://www.mozilla.org/en-US/firefox/ios/25.0/releasenotes/

- Assert App Store button is displayed in header for non-Firefox browsers.
- Assert secondary App Store button is displayed in footer for all-browsers.

URL: https://www.mozilla.org/en-US/firefox/77.0beta/releasenotes/

- Assert download button is displayed in header for non-Firefox browsers.
- Assert secondary download button is displayed in footer for all-browsers.

URL: https://www.mozilla.org/en-US/firefox/78.0a1/releasenotes/

- Assert download button is displayed in header for non-Firefox browsers.
- Assert secondary download button is displayed in footer for all-browsers.

URL: https://www.mozilla.org/en-US/firefox/android/68.7beta/releasenotes/

- Assert download button is displayed in header for non-Firefox browsers.
- Assert secondary download button is displayed in footer for all-browsers.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Functional tests are passing in CI cross-browser.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Not having tests in place increases the risk of accidental breakage to these pages.

#### Tasks
- [ ] Add functional tests.
- [ ] Push the branch to `run-integration-tests` before merging to make sure they all pass.

**Comment by alexgibson** [comment]
@pdehaan If you would still be interested in some functional testing, this may be a good place to start ^

You can find existing [functional tests here](https://github.com/mozilla/bedrock/tree/master/tests/functional), and their respective [page objects here](https://github.com/mozilla/bedrock/tree/master/tests/pages). These should hopefully serve as good examples. [Docs are here](https://bedrock.readthedocs.io/en/latest/testing.html).

**Comment by alexgibson** [comment]
Note: to make testing the download buttons easier on these pages, it may be worth giving each button an unique `id` in the DOM. Doing this may require some minor changes to the [release notes template](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/releases/notes.html), as currently both the download buttons in the header/footer share the same id, which seems like a bug.

**Comment by pdehaan** [comment]
Awesome, thanks!

I don't seem to have collaborator permissions to this repo. Can you try assigning the bug to me so it will be in my queue.

---

Interesting. Google Lighthouse detects the duplicate IDs and flags it as a "Best Practices" error:

> ### `[id]` attributes on the page are not unique
> The value of an id attribute must be unique to prevent other instances from being overlooked by assistive technologies. [Learn more](https://dequeuniversity.com/rules/axe/3.1/duplicate-id?application=lighthouse).
>
> **Failing Elements**
> `div#download-button-desktop-release.download-button.mzp-c-button-download-container`

If I manually install the axe add-on via https://addons.mozilla.org/en-US/firefox/addon/axe-devtools/?src=search, it displays 4 issues:

- Elements must have sufficient color contrast (5 results)
- id attribute must be unique (1 result) 
- Heading levels should only increase by one (1 result)
- All page content must be contained by landmarks (1 result)

But it **doesn't** look like webhint.io scanner flags the same axe "duplicate id" error: https://webhint.io/scanner/21d57505-3ec4-48b1-bc70-463ecdd465e5

**Comment by alexgibson** [comment]
@pdehaan I assigned the issue to you - anything I can help with, let me know!

**Comment by alexgibson** [comment]
This has been inactive for some time, so I'm going to take ownership and see if we can get tests for these pages done.
