### ISSUE TITLE
Re-evaluate browser support on bedrock.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7389]
## Description

The front-end team spend a considerable amount of time supporting older browsers, such as IE9 & IE10. We should evaluate how much traffic we still get from these old browsers, and whether or not the time invested coding for them is still a worthwhile investment. 

Can we consider dropping first-class support for IE9 or IE10, and instead giving them the universal stylesheet we serve to IE8? Doing so may have the following advantages:

- It enables us to ship code faster.
- It enables us to use more advanced browser features.
- It reduces the number of polyfills we need to bundle.

Bedrock's browser support matrix isn't formally documented anywhere (yet), but here's the current snapshot:

- We deliver 1st class CSS & JS to:
  - All evergreen browsers (Firefox, Chrome, Safari, Edge, Opera etc).
  - IE 9, 10 & 11.
- We deliver degraded * support to:
  - IE 8 and below.

* Degraded support consists of no page-specific CSS or JS. Instead, we deliver basic semantic HTML, a universal CSS stylesheet that gets applied to all pages, and a universal JS bundle that only handles downloading Firefox (click a button, get a file), and Google Analytics. The only pages where we make an exception is for `/firefox/new/` and `/firefox/download/thanks/`, which still deliver 1st class CSS to all browsers (but not 1st class JS).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] A recommendation is made on which (if any) browsers we can drop 1st class support for.
- [x] The decision is documented.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Dropping 1st class support for a browser can potentially impact download conversions.

#### Tasks
- [x] Evaluate IE9 and IE10 traffic. How do they compare to IE8, or IE11 levels of traffic?
- [x] Make a recommendation for which browsers we still need to deliver 1st class support for.
- [x] Add a "Browser support" section to the bedrock docs to document the decision.

**Comment by alexgibson** [comment]
See also: https://github.com/mozilla/bedrock/issues/7390

**Comment by hoosteeno** [comment]
Excluding /new and /thanks, the /firefox page handles nearly 50% of all IE9/10 visits, and those visitors tend to be high quality (i.e. they don't bounce, the download at good rates). I suspect this is because the /firefox page probably outranks the /new page in some locales.

Soon, /firefox will be the brand home for all Firefox products. Broad distribution of a compelling experience there will continue to be valuable and may support non-download business goals.

The volume of traffic on IE9/10 continues to drop, but it's not insignificant now (appx. 2% of non-Fx sessions/conversions). Outside /new and /thanks, those visitors primarily hit /firefox and the home page. 

Considering all that, I think we should remove these browsers from the list, but I'd like to explore a few mitigations from a feasibility/effort perspective:

1. Could we include /firefox in the list of pages we except from the degraded experience? 
2. Could we give users having a degraded experience a quick explanation (with a download CTA)?
3. Can we revisit the universal stylesheet to address specific issues that show up on e.g. /firefox/, to see if we can do anything to improve the degraded experience further?

@alexgibson, how would you rank those in terms of preference and ease?

**Comment by hoosteeno** [comment]
I'd like the conversation about mitigations to continue. That said, I think we should continue offering first-class support to all evergreen browsers (Firefox, Chrome, Safari, Edge, Opera etc) and IE 11 and can offer degraded experiences to IE<11.

**Comment by hoosteeno** [comment]
This issue is ready to close, but I'm leaving open to continue discussion above.

**Comment by alexgibson** [comment]
@hoosteeno this is wonderful, thanks.

In terms of needing to support /firefox - considering the importance of that page now and in the future, I think we can justify considering it a special page like we do for /new and /thanks. Adding it to that list seems like a small consession if it means we can drop the level of support for the rest of the site.

If you agree, then I think we can close this issue? :)
