### ISSUE TITLE
Move to a feature-detection system for delivering 1st class browser support

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7391]
## Description

We usually do a good job of making sure to deliver usable experiences to people both with and without JS enabled, but handling scenarios where JS fails to load is a much more common problem on most websites today. We often resort to using feature detection for this type of problem, but it's nearly always done on a page-by-page basis, or at a component level. 

If we moved toward using a global `cutsTheMustard()` type feature detect (real name TBD), and only ran page-specific JS if the function passes, then we could much more confidently ship code without worrying that we're breaking the site in old browsers.

My initial idea was a function that runs a callback only if the feature detect returns true, but there may be other ways to do this too.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Deliver feature detection on a single page (e.g. /firefox/all)
- [ ] Document the feature detection snippet and incorporate into norms going forward

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Where should this live - should it be in the `<head>`, so we can leverage it for CSS class hooks, or should it be in the common bundle only? There are likely tradeoffs for each.

#### Tasks
- [ ] Create a feature detect. Ideally it should **return false for IE10, but true for IE11 and above**.
- [x] Decide where to implement it and how to should be used (see risks above).
- [x] Update the page-specific JS on /firefox/all/ to use the new feature detect.
- [ ] Document the feature detect and how it should be used on our [browser support page](https://bedrock.readthedocs.io/en/latest/browser-support.html).

**Comment by alexgibson** [comment]
See also: https://github.com/mozilla/bedrock/issues/7391

**Comment by alexgibson** [comment]
Since IE10 does not support conditional comments (the mechanism we currently use to facilitate basic browser support for legacy IE), this issue will become important in order to drop support for IE10.

We may want to consider moving away from conditional comments entirely, and moving more toward a feature-detection model that uses graceful degredation.
