### ISSUE TITLE
WNP 69

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7403]
## Description

Create and launch a WNP 69 built with a modular system of reusable components

[Project roadmap board](https://github.com/mozilla/bedrock/projects/26)

[Master Project Doc](https://docs.google.com/document/d/1xjU1TN1WiDyQDf4QbRFtdrJU8bbc9O_nv36Vj8vygO8/edit#) (include schedule and links to all pertinent artifacts including copy, etc.)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is build with reusable modules
- [ ] MVP is shown to users at launch of the Firefox 69 release

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks & Deadlines

- [x] [Copy](https://docs.google.com/document/d/1z7WhTOsagWocyILHKDXoC0q50WhN27CTpf64OH3h03g/edit?usp=sharing) - Deadline for final (EN) copy - 7/23
- [x] ["Testing Variants" Copy (not part of this build)](https://docs.google.com/document/d/1ZWA6sgH0Mx9IfzO1p8qJ3jQe6ZxMZgqvfInsa1UIO0Q/edit?usp=sharing) 
- [x] [Design](https://github.com/mozilla/bedrock/issues/7456) - Deadline for final design - 07/30
- [x] QA/review of design concept
- [ ] Code modules
- [ ] Code content in modules
- [ ] QA of page on demo - for stakeholder QA review - 08/06
- [ ] Code review
- [ ] WNP 69.0 go live - on or before - 08/23

**Comment by claychaffin** [comment]
copy deck in progress
https://docs.google.com/document/d/1z7WhTOsagWocyILHKDXoC0q50WhN27CTpf64OH3h03g/edit?usp=sharing

**Comment by dzingeek** [comment]
design in progress
![Screen Shot 2019-07-18 at 3 07 47 PM](https://user-images.githubusercontent.com/3740746/61491171-85040380-a963-11e9-8b2a-7eaa73f6f0e1.png)

**Comment by claychaffin** [comment]
Approved copy for WP 69, now tidied up in this deck
https://docs.google.com/document/d/1z7WhTOsagWocyILHKDXoC0q50WhN27CTpf64OH3h03g/edit?usp=sharing

**Comment by claychaffin** [comment]
Testing Variants copy deck fro WP 69
https://docs.google.com/document/d/1ZWA6sgH0Mx9IfzO1p8qJ3jQe6ZxMZgqvfInsa1UIO0Q/edit?usp=sharing

**Comment by craigcook** [comment]
Question: The Pocket promo includes a link. In the past we've used such links to open a modal window with a QR code to install the app. Do we want to do the same treatment here, or just link directly to getpocket.com?
