### ISSUE TITLE
Update eslint and gulp-eslint 

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7404]
## Description

Update eslint and gulp-eslint to version 6.0.0

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Packages are up to date.
- [x] Linting and tests pass in CI.

#### Tasks
- [x] Update dependencies.
- [x] Code changes where needed.

**Comment by alexgibson** [comment]
This issue is not yet complete, it's still waiting on code review.
