### ISSUE TITLE
WNP 69 - copy July 19th

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7421]
Description:

In order to maximize the opportunity for localization of the WNP for the 69 release the en-US copy must be final on July 23rd with strings extracted to Pontoon by July 25th. This is for the MVP copy for the WNP 69 release.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Copy final/approved on or before July 19th
- [x] CTA buttons (e.g. "Try Monitor") for signed-in and non-signed-in states both
- [x] Links okay for evergreen content if we want them, depending on what they link to 
- [x] Consider using a unique primary CTAs for signed-in and non-signed in as the audiences are somewhat different, but weight this with team against goal of simplifying engineering and testing 

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [x] Reviews and approvals

#### Tasks
- [x] [Copy](https://docs.google.com/document/d/1z7WhTOsagWocyILHKDXoC0q50WhN27CTpf64OH3h03g/edit?usp=sharing)

**Comment by claychaffin** [comment]
copy deck in progress
https://docs.google.com/document/d/1z7WhTOsagWocyILHKDXoC0q50WhN27CTpf64OH3h03g/edit?usp=sharing

**Comment by ejregithub** [comment]
@claychaffin - I made this issue to be copy specific given the revised timeline. Could you please spend a minute or so thinking about sizing and then indicate your Estimate of the time/effort required to complete this task?

**Comment by claychaffin** [comment]
Of course, @ejregithub! Raw number of hours or Fibonacci?

**Comment by ejregithub** [comment]
@claychaffin - Fibonacci, per our current method, please.

Also - based on approval from Lauren today in our review meeting I'm going to close this issue as done.

**Comment by claychaffin** [comment]
Approved copy for WP 69, now tidied up in this deck
https://docs.google.com/document/d/1z7WhTOsagWocyILHKDXoC0q50WhN27CTpf64OH3h03g/edit?usp=sharing
