### ISSUE TITLE
Decommission content blocking tour pages

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7424]
## Description
As per: https://bugzilla.mozilla.org/show_bug.cgi?id=1564367, the content-blocking UITour is being removed as of Firefox 70. This means that sometime **after 2019-10-22**, we can decommission and remove the tour from mozorg at:

- `/firefox/content-blocking/start/`
- `/firefox/tracking-protection/start/`

The proposed URL to redirect these pages to is: https://support.mozilla.org/kb/content-blocking

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Pages are removed and redirected in production (x) weeks after the launch of FIrefox 70.

#### Tasks
- [ ] Remove templates.
- [ ] Redirect URLs to SUMO.
- [ ] Update UITour documentation.

**Comment by Patil2099** [comment]
@alexgibson  Should I make a Pr for this issue?

**Comment by alexgibson** [comment]
@Patil2099 this can't be decomissioned until after Firefox 70 is released. I'd suggest waiting until then, thanks.

**Comment by Patil2099** [comment]
@alexgibson Firefox 70 has been released. Can I work on this issue now?

**Comment by alexgibson** [comment]
@Patil2099 the Firefox 70 update only just launched, so I think we should probably wait a few weeks for people to update.

**Comment by alexgibson** [comment]
@Patil2099 if you're still interesting in working on this issue, I think we've now given enough time that we can safely remove and redirect the pages.

**Comment by Patil2099** [comment]
@alexgibson I will start working on it.

**Comment by alexgibson** [comment]
@Patil2099 please let me know if you're actively working on this, else I'd like to pick it up and get it done soon. Thanks again

**Comment by Patil2099** [comment]
@alexgibson I will make a PR within 12 hours.
