### ISSUE TITLE
Deprecate jQuery functions with equivalent native events.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7431]
## Description

I was reading about how GitHub [removed jQuery from their front-end](https://github.blog/2018-09-06-removing-jquery-from-github-frontend/) and noticed they linked to a handy [ESLint plugin](https://github.com/dgraham/eslint-plugin-jquery), which can be configured to disallow jQuery calls. This might be useful to add to bedrock as it could allow us to:

- Throw warnings on all existing jQuery calls in the codebase. This will help us keep track of how much legacy code we have left to remove.
- Throw errors on any new jQuery calls, so it can caught in code review.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Warnings are thrown for existing code.
- [ ] Errors are thrown for new code.

#### Tasks
- [x] Plugin is added to existing ESLint config.
- [x] Throw warnings for existing jQuery calls.
