### ISSUE TITLE
Decommission the /ITU page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7434]
## Description

The [ITU page](https://www.mozilla.org/en-US/ITU/) on mozorg is very old (hasn't really been touched since 2012). Most of the links contained in that page are also now 404. We should retire this page.

I'm not quite sure where we could redirect the URL to. If we can't find something appropriate, then we could allow it to 404.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is removed in production.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Remove template and assets.
- [ ] Redirect URL if appropriate.
