### ISSUE TITLE
Decommission the /about/history/ slideshow

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7435]
## Description

The `/about/history/` [slideshow page](https://www.mozilla.org/en-US/about/history/) has seen its day. We should retire this old design, and instead show the contents of https://www.mozilla.org/en-US/about/history/details/.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] The URL `/about/history/` shows the [long form history](https://www.mozilla.org/en-US/about/history/details/) of the Mozilla project.
- [ ] URL `/about/history/details/` URL redirects to `/about/history/`.

#### Tasks
- [ ] Port `/about/history/details/` template to Protocol.
- [ ] Show the template at `/about/history/`.
- [ ] Retire slideshow template and assets.
- [ ] Redirect `/about/history/details/` to `/about/history/`.
