### ISSUE TITLE
Decommission /firefox/feedback/ page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7436]
## Description

The [Firefox feedback](https://www.mozilla.org/en-US/firefox/feedback/) page has received just over 2200 page views in the past year, and averages between 3-15 page views per day.

Given the age of this page and the low traffic referrals, I'm going to suggest we redirect the URL to [SUMO](https://support.mozilla.org/en-US/products/firefox). We should check in with whomever owns this page first, just to be safe.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is removed and redirected in production.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [x] Need approval from whomever owns this legacy page.

#### Tasks
- [x] Remove template and assets.
- [x] Redirect URL to SUMO.

**Comment by alexgibson** [comment]
Another potential destination for the redirect could be https://qsurvey.mozilla.com/s3/FirefoxInput/

**Comment by alexgibson** [comment]
@hoosteeno who would be the correct owner for this page? Can we try and contact them to determine if this is still needed?

**Comment by hoosteeno** [comment]
We reached out to the owners of this page (Strategy and Insights team). The page was previously used for [a Heartbeat survey recipe asking users to rate Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1108828). The owners agree: We can decommission this page. 

We should redirect it (both happy and sad experiences) to the [Ask A Question](https://support.mozilla.org/questions/new/desktop) page on SUMO.

**Comment by ejregithub** [comment]
@Errolyn  - this one is good for review, please.
