### ISSUE TITLE
Decommission old /whatsnew and /firstrun pages for Dev Edition.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7437]
## Description

These pre-quantum pages are now pretty old, and are still built using Sandstone & Less. I think they likely pretty safe to remove, and the URLs can default to the generic /whatsnew and /firstrun templates that get shown for release versions.

- https://www.mozilla.org/en-US/firefox/56.0a2/whatsnew/
- https://www.mozilla.org/en-US/firefox/56.0a2/firstrun/

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] URLs default to the generic /whatsnew and /firstrun templates in production.

#### Tasks
- [ ] Remove templates and assets.
- [ ] Update tests where needed.

**Comment by stephaniehobson** [comment]
As part of this work could we update the headlines on the generic pages to be more generic by removing the Quantum messaging?

"Welcome to the all-new Firefox Quantum: Developer Edition"
"This isn’t just an update. This is Firefox Quantum: A brand new Firefox that has been rebuilt from the ground-up."
