### ISSUE TITLE
Archive past annual-report pages

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7438]
## Description

We have several old annual-report pages built on Sandstone / Less, which are now some of the oldest pages on the website. The reports probably need to stay around in some accessible form, but we need to move those pages to not be dependent on Sandstone / Less if we are ever to remove the old frameworks:

- https://www.mozilla.org/en-US/foundation/annualreport/2010/
- https://www.mozilla.org/en-US/foundation/annualreport/2011/
- https://www.mozilla.org/en-US/foundation/annualreport/2012/
- https://www.mozilla.org/en-US/foundation/annualreport/2013/
- https://www.mozilla.org/en-US/foundation/annualreport/2014/
- https://www.mozilla.org/en-US/foundation/annualreport/2015/
- https://www.mozilla.org/en-US/foundation/annualreport/2016/

Two possible options come to mind:

1. Port all of the above URLs to use the newer Protocol-based template [used here](https://www.mozilla.org/en-US/foundation/annualreport/2017/).
2. Build an archived-reports template, which can link to all the respective PDFs for past years.

Option 1 is the most effort, but would mean we retain all the content of past reports.

Option 2 would mean we lose the long-form copy and videos for past years, whilst retaining only the legal/financial PDF reports.

The URLs seem to get pretty low traffic (less than 10,000 page views in the last year combined between all versions).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] URLs are no longer dependant on legacy CSS frameworks.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] We should check-in with whomever owns the annual report pages.

#### Tasks
- [ ] Convert pages to whichever Protocol-based solution is chosen.
- [ ] Remove legacy assets.
