### ISSUE TITLE
Port /firefox/ios/testflight/ to Protocol

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7439]
## Description

The [TestFlight for Firefox iOS](https://www.mozilla.org/en-US/firefox/ios/testflight/) page is built upon Sandstone / Less, but can probably be ported to Protocol pretty easily (swapping out the blue hero background for purple).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is updated in production using Protocol.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] Update tests where needed.

**Comment by amychurchwell** [comment]
Can I use `email_newsletter_form` for the newsletter on this page? or is it it's own special kind of newsletter?

**Comment by alexgibson** [comment]
@amychurchwell looking at the existing template I can see a couple of special cases for this newsletter form:

- https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/testflight.html#L46-L47
- https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/views.py#L753-L754

There may well be a neater way to accomplish this as it stands currently, but I probably wouldn't spend too much time on it given this page is very old. Hope that helps
