### ISSUE TITLE
Remove old /about/ page template.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7442]
## Description

The redesigned `/about/` page now covers [38 locales](https://l10n.mozilla-community.org/langchecker/?locale=all&website=0&file=mozorg/about-2019.lang) (96.27% of our l10n userbase). This should be enough to now remove the old template, and remaining locales can hopefully catch up.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Legacy template is removed in production.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Some locales have not yet caught up, but this is a lower priority page so the risk may be OK.

#### Tasks
- [ ] Remove old template and assets.
- [ ] Remove legacy .lang file.

**Comment by alexgibson** [comment]
PR to remove lang files: https://github.com/mozilla-l10n/www.mozilla.org/pull/325
