### ISSUE TITLE
Create issues on Protocol for missing components

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7444]
@wboucherfischer commented on [Mon Jul 08 2019](https://github.com/mozilla/protocol/issues/406)

## Description
Build issues in Protocol repository for components that are...
* identified in roadmap for Protocol
* in use on www.mozilla.org
* not already built in Protocol

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Issues filed
- [ ] Sketch library and symbols created

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [x] We design a new look and feel for Fx or Mozilla.
- [x] Designers don't talk to developers and developers don't talk to designers

#### Tasks
- [x] Conceptualize design system and explore
- [x] PRD written
- [x] Review by Team

See PRD: [PRD](https://docs.google.com/document/d/1NgIKryJ0dCoPOGqE5A6rFgjDomd-PuVuLulFhPkN3N8/edit)

**Comment by wboucherfischer** [comment]
have been filing issues for first pass of components in prd and responding to comments from developers: 

https://github.com/mozilla/protocol/issues/436
https://github.com/mozilla/protocol/issues/435
https://github.com/mozilla/protocol/issues/434
https://github.com/mozilla/protocol/issues/433
https://github.com/mozilla/protocol/issues/430
https://github.com/mozilla/protocol/issues/429
https://github.com/mozilla/protocol/issues/428
https://github.com/mozilla/protocol/issues/427
https://github.com/mozilla/protocol/issues/426
https://github.com/mozilla/protocol/issues/417
https://github.com/mozilla/protocol/issues/416
https://github.com/mozilla/protocol/issues/414
https://github.com/mozilla/protocol/issues/409

**Comment by wboucherfischer** [comment]
Added: 

https://github.com/mozilla/protocol/issues/439
https://github.com/mozilla/protocol/issues/438
https://github.com/mozilla/protocol/issues/437

**Comment by ejregithub** [comment]
Separating the task "Sketch library and symbols created" to a new story

**Comment by ejregithub** [comment]
Based on the conversation w. Wendy during the Protocol stand-up I'm closing this issue as done, noting the comment above that a task was pulled out to be completed independently
