### ISSUE TITLE
Determine the fate of /about/mozilla-based/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7448]
## Description

This is a [very old page](https://www.mozilla.org/en-US/about/mozilla-based/) that still uses Sandstone & Less, and I doubt we'll redesign it anytime soon. We could port the page to Protocol and keep design changes minimal, or alternatively decommission the page entirely.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is either updated or removed and redirected.

#### Tasks
- [x] Determine what to do.
- [x] Make the required changes.

**Comment by alexgibson** [comment]
We could also decide to retire this page entirely. Looking in GA this received around 10 page views per-day, and is completely orphaned.

**Comment by alexgibson** [comment]
We discussed this as a team in Slack, and given the very low level of traffic this page receives, we're going to go ahead and remove / redirect it. If needed, we can always bring the page back in the future and redesign it with more up-to-date content.
