### ISSUE TITLE
Make .scss equivalent of mozilla-modal.less

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7449]
## Description

There are several page bundles in bedrock that are using Pebbles (.scss) for page styles, but are importing`mozilla-modal.less`.

This is a relatively small file. If we make .scss equivalents then it become much easier to remove as a dependency.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Pages use scss equivalent and no longer have a .less dependency.

#### Tasks
- [ ] Convert file to have .scss equivalent.
- [ ] Update bundles to use .scss versions

**Comment by alexgibson** [comment]
mozila-accordion.less is being removed in https://github.com/mozilla/bedrock/issues/8019

**Comment by alexgibson** [comment]
This is no longer required.
