### ISSUE TITLE
Port /mission/ page to Protocol

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7450]
## Description

The `/mission/` page is very outdated and still uses Sandstone / Less. It would be great to redesign, but I don't know of any plans to do so. We should figure out a strategy for porting this page to Protocol, so that we can get rid of Sandstone.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is in production using Protocol.

#### Tasks
- [ ] Determine the appropriate design treatment.
- [ ] Update the template.
- [ ] Remove legacy assets.
