### ISSUE TITLE
Update Nightly /firstrun page to use Protocol

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7451]
## Description

The [Nightly firstrun page](https://www.mozilla.org/en-US/firefox/nightly/firstrun/) is still using Sandstone / Less. I don't know of any plans to invest time in redesigning this, so we need to figure out a way to port it to Protocol.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is updated in production using Protocol.
- [x] Page uses new Nightly logo.

#### Tasks
- [x] Figure out the appropriate design treatment.
- [x] Update the template to use Protocol.
- [x] Remove legacy .less assets.

**Comment by alexgibson** [comment]
This is perhaps timely, since we also have a logo to update (added it to the success criteria).

**Comment by alexgibson** [comment]
WIP demo link: https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/nightly/firstrun/

**Comment by alexgibson** [comment]
It would be good to get some design feedback on the above ^

**Comment by alexgibson** [comment]
Updated the buttons to blue, as per @dzingeek's suggestion.
