### ISSUE TITLE
Update /firefox/channel/ page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7452]
## Description

The [Firefox channel](https://www.mozilla.org/en-US/firefox/channel/desktop/) page is still using Sandstone / Less and needs updating to use the new branding. I'm not sure if the NA brand team have any immediate plans to redesign this page, so we need to figure out a low effort way to port it to Protocol.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is updated in production using Protocol,

#### Tasks
- [ ] Firgure out the appropriate design treatment.
- [ ] Update the template.
- [ ] Remove old assets.

**Comment by stephaniehobson** [comment]
The brand team is working on a Protocol port :)

**Comment by stephaniehobson** [comment]
I think this has fallen off the brand team's radar. I'm going to take myself off for now but I'll also see if I can get some renewed interest.

**Comment by amychurchwell** [comment]
My plan is to port this to protocol with as low design impact as possible.
I would like to update the hero to use a more on-brand "swoosh", if possible.

@cgonz0 - I was curious if you had thoughts about an existing background asset for this hero that might work?

![Screenshot_2019-11-26  Try New Browser Features in Pre-Release Versions Firefox ](https://user-images.githubusercontent.com/30483988/69701902-db681800-10a2-11ea-9e4b-e7f74aeaaa05.png)

**Comment by amychurchwell** [comment]
@cgonz0 hi Cristina! 
I have a rough draft on demo: https://www-demo1.herokuapp.com/firefox/channel/desktop/

Would love any input or feedback you may have.

**Comment by cgonz0** [comment]
@amychurchwell hey! 

here is some feedback from where the demo is currently at.
i added a gray background in the screenshot below, but it's not necessary.
some other tweaks:
- removing margin from hero description helps vertically center text (doesn't affect if using white background)
- tighten up space between content and notes - and notes font-size could be smaller (14px)
- ideally it’d be better to have a max width on all the content, the notes especially get hard to read when the line-length is this long
- can also stretch out the “see something isn’t working?” section - doesn’t need to be constrained within a card
- i think a different sign-up that’s not Mozilla branded would fit better here
- @1055 breakpoint. i don’t think we should hide the logo, but flow it above the content. 
that being said, i know there are current limitations on protocol. below is a screenshot with the tweaks above:

![Screenshot_2019-12-03  Try New Browser Features in Pre-Release Versions Firefox (2)](https://user-images.githubusercontent.com/29640968/70094618-c118c780-15d7-11ea-9ec9-7352f48da323.png)

**Comment by amychurchwell** [comment]
@cgonz0 thank you so much for your feedback, I really appreciate it. 👏 

> i think a different sign-up that’s not Mozilla branded would fit better here

I'm not sure if I understand this comment? Do you mean to omit the firefox logo on the hero? I left it in to follow the screenshot you provided. (Thank you again, so incredibly helpful.)

> @ 1055 breakpoint. i don’t think we should hide the logo, but flow it above the content.

Totally agree. This was a customized call-out from Protocol. It'd be a touch fiddly to do this for an mvp considering that this page will be redesigned in the future, so for now I think we should leave it hidden just to get it on Protocol in general. Definitely something I'd like to revisit though.

**Comment by cgonz0** [comment]
> @cgonz0 thank you so much for your feedback, I really appreciate it. 👏
> 
> > i think a different sign-up that’s not Mozilla branded would fit better here
> 
> I'm not sure if I understand this comment? Do you mean to omit the firefox logo on the hero? I left it in to follow the screenshot you provided. (Thank you again, so incredibly helpful.)
> 
no prob:) i was referring to the newsletter sign-up component on the bottom of the page, it feels like the mozilla branding is out of place for this browser page. do we have another, more relevant one available?
