### ISSUE TITLE
WNP 68 - post release experiments to inform WNP 69

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7457]
Description:
We want to test some of our concepts and questions about our WNP69 design. We can do this with WNP68 content and audience.
- Build WNP69 components and compose into a layout that can accommodate signed-out WNP68 content.
- Build variations for signed-out audiences and split with TrafficCop.
- Measure rate of signed-out users registering accounts with Amplitude.

**Success criteria:**
- [x] Experiment design is built and approved by analytics team
- [x] Experiment is launched and gathering data
- [x] Variants use modular WNP69 layouts including protocol components

**Tasks**
- [x] Write [experiment](https://mana.mozilla.org/wiki/display/EN/Testing+WNP69+on+WNP68+Experiment)(s) and get vetted by analytics (control and 3 vars, light & dark, no notification)
- [x] Design (from Mark) w. new layout that has Monitor CTA in both states
- [x] Code page with 68 content (in new 69 layout)
- [x] Create closure card (Eric)

**Comment by ejregithub** [comment]
Ensure one change per variation - get specific in 69  vars in the test

**Comment by ejregithub** [comment]
Tagging @sghoseWI for the experiments write up here.

**Comment by craigcook** [comment]
Adding here for posterity and easy reference. The variants in this test will be:

A: Control
B: New layout, light version
C: New layout, dark version
D: Notification icon
E: Monitor signin flow for signed-in users

**Comment by ejregithub** [comment]
@craigcook - in case you didn't see it yet, @sghoseWI posted [the experiment plan](https://mana.mozilla.org/wiki/display/EN/Testing+WNP69+on+WNP68+Experiment) in the WNP 69 Slack channel (and I added it in the description, above, here).

**Comment by craigcook** [comment]
New layout, light: https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/68.0/whatsnew/?v=b
New layout, dark: https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/68.0/whatsnew/?v=c
Notification icon: https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/68.0/whatsnew/?v=d
Monitors CTA for signed-out users: https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/68.0/whatsnew/?v=e

**Comment by ejregithub** [comment]
[Closure card](https://github.com/mozilla/bedrock/issues/7558) to close this issue
