### ISSUE TITLE
Code: Update Firefox newsletter sign up form with new copy

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7460]
## Description

The newsletter-container for subscribing users to the Firefox email newsletter is used on several pages including:

https://www.mozilla.org/en-US/firefox/linux/
https://www.mozilla.org/en-US/firefox/mac/
https://www.mozilla.org/en-US/firefox/windows/

We need to change the copy under the email field from:

We will only send you Mozilla-related information.

to:

We will only send you Firefox-related information.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Copy is updated wherever newsletter container for Firefox newsletter is used

#### Tasks
- [ ] Get legal's approval of the new copy
- [ ] Update (code) with the new copy
- [ ] Ensure new string is Pontoon for localization (show the current string until it is updated)

**Comment by hoosteeno** [comment]
@ejregithub would you be up for taking the copy in this card to legal? If it was approved, this could be ready for code.

**Comment by alexgibson** [comment]
This string is [in Fluent](https://github.com/mozilla/bedrock/blob/master/l10n/en/newsletter_form.ftl#L23), so we can't change this until we flip the switch in Pontoon.

**Comment by alexgibson** [comment]
@ejregithub we should be unblocked to make this string change. Is the copy approved and ready?

**Comment by alexgibson** [comment]
The URLs listed above in the issue no longer contain a newsletter module, but I've updated it globally and pushed to demo. It can be seen on pages such as:

- https://www-demo2.allizom.org/en-US/firefox/channel/desktop/
- https://www-demo2.allizom.org/en-US/newsletter/firefox/

**Comment by ejregithub** [comment]
I pinged Emily for legal review

**Comment by ejregithub** [comment]
@alexgibson - we're good to go with the new copy from Legal's perspective.

**Comment by hoosteeno** [comment]
@alexgibson want to get this ready for review?
