### ISSUE TITLE
WNP 69 - Code & code review

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7465]
## Description

Code the WNP 69 page with the new modular design
---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is ready for stakeholder review on or before

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Code page
- [ ] Create components in Protocol
- [ ] QA of page on demo - for stakeholder QA review - 08/06
- [ ] Code review
- [ ] WNP 69.0 go live - on or before - 08/23

**Comment by amychurchwell** [comment]
We need to keep in mind this issue for WNP69: https://github.com/mozilla/bedrock/issues/7532

Meaning, we can't reference `js/base/mozilla-fxa-form.js` and `js/base/mozilla-monitor-button.js` in the same bundle because they both request flow IDs which fudges the numbers.
We should put these in their own JS blocks with some conditional logic- "if user is signed out, `fxa_email_form` JS, if signed out `monitor_button` JS"

**Comment by craigcook** [comment]
WIP on demo at http://www-demo1.allizom.org/firefox/69.0/whatsnew/

Note you'll need to whitelist the domain in browser.uitour.testingOrigins for it to detect your signed in state.

**Comment by ejregithub** [comment]
@craigcook - could please provide screenshots for each state, attaching them here?

**Comment by craigcook** [comment]
## Signed Out
![image](https://user-images.githubusercontent.com/205591/62901316-4d456d00-bd11-11e9-9139-fe731f97c03e.png)

## Signed In 
![image](https://user-images.githubusercontent.com/205591/62901242-20915580-bd11-11e9-8bba-e132584fea73.png)

(Not sure why the "up to date" banner isn't showing when signed out... that's a bug, I'll figure it out.)

**Comment by craigcook** [comment]
Temporarily blocked by the Monitor button work happening in https://github.com/mozilla/bedrock/pull/7546 since this page has a Monitor button.

**Comment by ejregithub** [comment]
Monitor button as blocker removed.

**Comment by ejregithub** [comment]
@craigcook - we the page to go live with the dark variation, based on the findings from the analysis that @sghoseWI and @hoosteeno did from the 68 test.
