### ISSUE TITLE
new /enterprise page: UX/UI for /enterprise

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7467]
## Description

Create the UX/UI (in wireframe to be coded) a new /enterprise page

[Brief](https://docs.google.com/document/d/14gH4XEZQB2ZxSFhwnltlSkhNM-WuhbS9JnYa-hiPYys/edit?ts=5cb9f164#)

[Seven Sheets](https://docs.google.com/document/d/1YPIK9SsBVqlQtOv_ATfCuW44mJTmm2S1wTuNQsLG5FY/edit)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Wireframes are approved by stakeholders

#### Tasks
- [ ] Investigate and document user journeys for /enterprise page(s)
- [ ] UI design & wireframes for landing page created with modular layout for future iteration (to be built in Protocol)
- [ ]  Modular layout for future iteration. Content subject to change.
- [ ] Identify & include navigation to more detailed information.

**Comment by ejregithub** [comment]
@wboucherfischer - please provide a sizing estimate for this work. Also, please indicate when you think you'll have the initial version so we can look at that with @claychaffin 's copy.

**Comment by wboucherfischer** [comment]
initial wireframes will be available monday. I am brainstorming today with @claychaffin

**Comment by wboucherfischer** [comment]
Wireframes: 
[](https://share.goabstract.com/9ea594b3-4fc0-475b-9bab-b5b3208a0108
)
PDF of Wireframes:
[](https://drive.google.com/open?id=1KarjW0Uf1vTSEH0q_KE5qHoL85SpQAsE)

Met with Tyler Ahn on 8//5 to review wireframes. Made changes.

Meeting today with /enterprise team to review wireframes.

**Comment by wboucherfischer** [comment]
Updated wireframes from discussion with /enterprise team

https://share.goabstract.com/396a6b0a-19e0-4880-b0e4-93085cb23e62

pdf: 
https://drive.google.com/file/d/1L_EKAtLvYIatmKDKiiRqlgRxXl2aZH-V/view?usp=sharing

**Comment by wboucherfischer** [comment]
Removed customer success section and moved call to action below benefits. 

pdf; https://drive.google.com/file/d/1srYOYANNOlxWRGcXYfSiGXJiJGQftRWs/view?usp=sharing

**Comment by wboucherfischer** [comment]
Updated wireframes and added copy. 
https://drive.google.com/file/d/1UiycJ2Kk3o1y7f0ExtFX-RAyZkCk1oOK/view?usp=sharing

Met with Tyler Ahn and enterprise team to review copy in wireframes. 
Changes need to be made. Probably one more day of work to finish wireframes and annotate. 

https://drive.google.com/open?id=1Q-YbQ2l5b7YghxVfAJI-z027F-UJ0b1I

**Comment by wboucherfischer** [comment]
wireframes at https://share.goabstract.com/e1d360d8-1dcf-40d6-8e32-e62727808474

**Comment by ejregithub** [comment]
@stephaniehobson - Maciej mentioned in our dependencies meeting that your Brand team was looking at a refresh for this page. We've not yet started coding - please take a look at the wireframes (and have your designer do so) and we can talk about who will need to do what. We have the deadline, from PMM, to get the updated page live the week of Sept 16 - see  #7491
