### ISSUE TITLE
Build WNP69 components in Protocol

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7468]
## Description

Build WNP69 components so the page at the 69 launch is fully in Protocol
---

**WNP69 components**

- [x] Notification banner. (https://github.com/mozilla/protocol/issues/383)
- [x] Shadow content card. (https://github.com/mozilla/protocol/issues/385)
- [ ] Update picto card component. (https://github.com/mozilla/protocol/issues/382)
- [x] Narrow content layout. (https://github.com/mozilla/protocol/issues/232)
- [ ] Header component. (https://github.com/mozilla/protocol/issues/91)

A lot of these components propose variants outside what WNP69 will utilize them for, we should focus on mvp for this project. We can open protocol issues as we build these to add variants later on.

**Tasks** 
- [ ] Identify which of these will need to support dark theme variant, dependent on design.

**Comment by ejregithub** [comment]
ID cards in Protocol and size them, making them subordinate to this as an Epic

**Comment by amychurchwell** [comment]
**WNP69 components**, cc: @craigcook 

- Notification banner. (https://github.com/mozilla/protocol/issues/383)
- Shadow content card. (https://github.com/mozilla/protocol/issues/385)
- Update picto card component. (https://github.com/mozilla/protocol/issues/382)
- Narrow content layout. (https://github.com/mozilla/protocol/issues/232)
- Header component. (https://github.com/mozilla/protocol/issues/91)

A lot of these components propose variants outside what WNP69 will utilize them for, we should focus on mvp for this project. We can open protocol issues as we build these to add variants later on.

**to do:** identify which of these will need to support dark theme variant, dependent on design.

**Comment by hoosteeno** [comment]
Closing this epic as we're no longer tracking it as a collection of work.
