### ISSUE TITLE
 Handle additional parameters for stub attribution

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7474]
## Description

(Copied from https://bugzilla.mozilla.org/show_bug.cgi?id=1567331).

In [bug 1515172](https://bugzilla.mozilla.org/show_bug.cgi?id=1515172) we are adding 2 additional attributes to the stub attribution handlers in the browser. In bug [1567320](https://bugzilla.mozilla.org/show_bug.cgi?id=1567320) we will modify the stubattribution service (https://github.com/mozilla-services/stubattribution) to handle these. We need bedrock to send these parameters when an experiment is present on a download page.

The parameters are:

```
funnel_experiment: name/id of the enrolled experiment
funnel_variation: name/id of the variation cohort used in the enrolled experiment
```

Expected behavior:

* We would like to be able to send these parameters independently of utm parameters. If utms are present, validate/send as usual. If these parameters are present, validate that characters are safe, and send in the same manner.

There are certainly questions and edge cases. We can use this issue to identify/discuss.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Experiments can pass through these additional parameters to stub attribution
- [x] This feature is integrated into any testing around the stub attribution code

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by pmac** [comment]
One comment I'll make is that the storage space in the stub installer for the data is very limited. These parameter names are quite long and will take up more of that space than they need to. I suggest considering shorter names. The final data can't be longer than 200 characters.

https://github.com/mozilla-services/stubattribution/blob/ad50b0d9a94a9c357db4d3f9da17b191ab5b0fda/attributioncode/validator.go#L53-L56

**Comment by mixedpuppy** [comment]
I'll shorten to experiment and variation as the parameters in the attribution service.  We'll need to possibly strip "funnel_" from any url params received.

**Comment by pmac** [comment]
We can definitely change them on the fly before sending them to bouncer if that would be best. It will only affect how the data appears in telemetry I think. But we can definitely map these parameters to any other name we'd like to use.

**Comment by hoosteeno** [comment]
This capability is now needed for https://bugzilla.mozilla.org/show_bug.cgi?id=1406005. @pmac, @alexgibson , who can work on this and when might you be able? What can I do to make it easier?

**Comment by pmac** [comment]
I'm not the best for most of this work as it's modifying the client-side code to collect and send these new parameters to the signing service. I can help update the signing service if need be though. So I think @alexgibson will be the best one to take the first stab ab this and he can tag me in if he needs an assist with the back-end bits.

**Comment by hoosteeno** [comment]
The stub attribution service is wanting to see 'funnel_experiment' and 'funnel_variation' parameters:

https://github.com/mozilla-services/stubattribution/pull/95/files#diff-253081adbe418770bdbe47b1f11c8320R20-R21

Once these are built, we can design an experiment to put non-Fx UAs in them.

**Comment by Mardak** [comment]
> I'll shorten to `experiment` and `variation` as the parameters in the attribution service

The `funnel_`-less keys are what ended up landing in Firefox, so the "utm_" stripping behavior will probably need to be updated before passing the data to stub attribution service and for hmac computation.

https://github.com/mozilla/bedrock/blob/67a2debdfcbd4a72cc3b5b0998a136aea7964704/bedrock/firefox/views.py#L95-L96

https://hg.mozilla.org/releases/mozilla-release/file/2c8be14a89c92e56dbfc10ad32284e628a517a93/browser/components/attribution/AttributionCode.jsm#l33

Do we want a separate bedrock issue for client-side vs signing service related changes?

**Comment by hoosteeno** [comment]
Let's not strip funnel_; instead, let's just not send it. Nothing downstream seems to depend on it. Let's send `experiment` and `variation` -- sound good @Mardak ?

**Comment by Mardak** [comment]
Sounds good. From my quick glance of views.py, it'll at least want the additional keys and skip the removal of the first 4 characters for these new keys.

**Comment by alexgibson** [comment]
> who can work on this and when might you be able? What can I do to make it easier?

@hoosteeno please add this to a sprint and I'd be happy to work on it.

**Comment by hoosteeno** [comment]
@alexgibson this is in the specify column with a "ready" tag, which is our new 2020 way of signaling that it's ready to pull into progress. Do you need any more information before pulling?

**Comment by alexgibson** [comment]
@hoosteeno there's already a pull request for this, it's just waiting on code review 👍

**Comment by hoosteeno** [comment]
https://github.com/mozilla/bedrock/pull/8363
