### ISSUE TITLE
WNP 69 - Copy - Evergreen content

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7480]
With the new modular design we will have the opportunity to show evergreen content in locales, some or all, based on stakeholder requirements and due to the fact that some products are/will be available in only some locales and not others.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Evergreen copy is done, stakeholder approved

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Identify and write [copy for evergreen content](https://docs.google.com/document/d/1djkmVYsi5z2MZQWkJ5TLAr5URlg3Mdl3CP79PPBCIhg/edit?usp=sharing)

**Comment by ejregithub** [comment]
@claychaffin - please provide an Estimate for this story

**Comment by claychaffin** [comment]
Thanks. For this specific evergreen content, Fibonacci: 2

**Comment by claychaffin** [comment]
Copy deck (still a work in progress, awaiting NL feedback on options):
https://docs.google.com/document/d/1djkmVYsi5z2MZQWkJ5TLAr5URlg3Mdl3CP79PPBCIhg/edit?usp=sharing
