### ISSUE TITLE
Display channel appropriate content on whatsnew page

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7488]
Because the Release, Beta, and DevEd pages share the same template now all 3 have the same logo. As a DevEdition I found it confusing to be informed I'd been updated to the most recent version of Firefox with the Release logo. What did I just get updated to?!?

Putting the channel appropriate logo on that page would reduce user confusion.

Bonus: Also naming the channel in the update notification "Congrats! You're running the most recent version of Firefox Developer Edition" or whatever it is.

### Success Criteria
- [ ] WNPs show channel-appropriate logos
- [ ] WNPs show channel-appropriate links to release notes

***Tasks***
- [ ] Beta channel WNP - show a link to the beta release notes when displaying the (fallback w. mobile CTA) WNP to beta

**Comment by amychurchwell** [comment]
When updating dev edition, the messaging is rather odd for someone who was already using the browser:
> Congrats. You now have Firefox Browser Developer Edition.

![Screen Shot 2020-01-08 at 12 16 58 PM](https://user-images.githubusercontent.com/30483988/72012646-1ff1e200-3211-11ea-8562-3525486736d9.png)
`firefox/73.0a2/whatsnew/all/?oldversion=72.0`

**Comment by ejregithub** [comment]
Currently (and going forward) the beta channel is shown the default WNP content w. mobile CTA (the /whatsnew.lang file).  Currently that does not include a link to the beta release notes (as it does in the rapid release versions of whatsnew).  MWarther has that we include that blurb and link "Read the Release Notes to know more about what’s new in your Firefox browser." to the content shown to beta users (this *may* mean a new template/lang file?)

<img width="991" alt="Screen Shot 2020-01-08 at 1 07 02 PM" src="https://user-images.githubusercontent.com/20547886/72016678-19ffff00-3219-11ea-86d0-39cda2717e7e.png">

**Comment by alexgibson** [comment]
The Firefox Beta product uses the same logo as the main release version of Firefox, so I'm not entirely sure that the logo change is the right thing to do here. Displaying the same logo as the release version seems more consistent to what users see day to day.

<img width="559" alt="image" src="https://user-images.githubusercontent.com/400117/72799259-ba541b80-3c3c-11ea-943d-877fd2c32f65.png">

**Comment by hoosteeno** [comment]
Moving to research until it's clearer what needs done here.

**Comment by alexgibson** [comment]
Closing this old issue. 

Firefox release channel, Dev Edition, and Nightly all show the correct logos on their respective release notes pages. Firefox Beta uses the same logo as release, so it seems appropriate to show the same for there.

Will file a separate bug to update the release notes link for beta /whatsnew pages.

**Comment by alexgibson** [comment]
Ah, looks like the right release notes link is already displayed, no need for a separate issue

https://www.mozilla.org/en-US/firefox/107.0beta/whatsnew/ links to https://www.mozilla.org/en-US/firefox/107.0beta/releasenotes/ as an example
