### ISSUE TITLE
new /enterprise page: Content

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7490]
## Description

Create the UX/UI (in wireframe to be coded) a new /enterprise page

[Brief](https://docs.google.com/document/d/14gH4XEZQB2ZxSFhwnltlSkhNM-WuhbS9JnYa-hiPYys/edit?ts=5cb9f164#)

[Seven Sheets](https://docs.google.com/document/d/1YPIK9SsBVqlQtOv_ATfCuW44mJTmm2S1wTuNQsLG5FY/edit)

[MVB - minimum viable brief](https://docs.google.com/document/d/14u2-f-6WH3ZOgW9nCekZACy84gDLBGxP8TspNywiAj8/edit?usp=sharing)

[Copy Deck](https://docs.google.com/document/d/1nbSDIpMxmkLcy9Uts54IMB9LVZiTFGpwHRrC-_AFmD8/edit?usp=sharing)
---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Content is approved by stakeholders
- [ ] Is live during the week of Sept 16th - 22nd
- [x] Primary CTA is to download
- [x] Secondary CTA is  - "request more info (from sales)" - (confirm this)
- [ ] Download links should link to the contextually correct download option
- [ ] Links to onboarding guide - onboarding guide is included in Enterprise Download packages

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] We may need forms that don't yet exist
- [ ] We may be asked to include content that doesn't yet exist (from other teams, not us)
- [ ] Localization requirements are not yet clear

#### Tasks
- [x] Meta data (tags & title) and page copy
- [x] Write headline for landing page
- [x] Include "Useful content about the browser (for enterprise)"
- [x] Include "Useful content about the support offering"
- [ ] Identify & include navigation to more detailed information
- [ ] Pick up copy for "Request More Info" form from elsewhere
- [x] Write for SEO - informative and specific (more meaty), not marketing alphabet soup

**Comment by wboucherfischer** [comment]
Met with Clay Chaffin on 7/30 to discuss plan of action.

Meeting today for brainstorming session.

**Comment by claychaffin** [comment]
Yesterday morning I shared an MVB with our key stakeholder. It contains questions about possible messaging, supporting facts for our possible messaging, and more. Many of these questions seek to clarify the info in the PMM brief (the official "Brief") that the stakeholders shared with us. I've linked to the MVB above, under "Description."

**Comment by claychaffin** [comment]
On Monday Aug 5 @wboucherfischer and I are meeting with our R-stakeholder to talk wireframes and copy

**Comment by claychaffin** [comment]
Copy-deck-in-progress: https://docs.google.com/document/d/1nbSDIpMxmkLcy9Uts54IMB9LVZiTFGpwHRrC-_AFmD8/edit?usp=sharing

**Comment by wboucherfischer** [comment]
Copy of Wireframes we shared with Tyler Ahn on 8/6 meeting 
https://drive.google.com/open?id=1svL5hahLC-GrfvDqaapsRyWUflBgek09

Notes in PDF from meeting with Tyler Ahn from 8//6
https://drive.google.com/open?id=1I2vVQ0gTtLxvvHpQMtx3grxGACYXUnJH

**Comment by wboucherfischer** [comment]
Updated wireframes with comments from Tyler Ahn. 

Wireframes in Abstract
https://share.goabstract.com/f5eb72bc-e255-4eb3-833c-9c78d7c40289

PDF of wireframes
https://drive.google.com/open?id=1KarjW0Uf1vTSEH0q_KE5qHoL85SpQAsE

**Comment by wboucherfischer** [comment]
Updated wireframes from discussion with /enterprise team

https://share.goabstract.com/396a6b0a-19e0-4880-b0e4-93085cb23e62

pdf: 
https://drive.google.com/file/d/1L_EKAtLvYIatmKDKiiRqlgRxXl2aZH-V/view?usp=sharing

**Comment by wboucherfischer** [comment]
Updated wireframes and added copy. 
https://drive.google.com/file/d/1UiycJ2Kk3o1y7f0ExtFX-RAyZkCk1oOK/view?usp=sharing

Met with Tyler Ahn and enterprise team to review copy in wireframes. 
Changes need to be made. Probably one more day of work to finish wireframes and annotate. 

https://drive.google.com/open?id=1Q-YbQ2l5b7YghxVfAJI-z027F-UJ0b1I

**Comment by claychaffin** [comment]
The meta data is written and in the copy deck.

**Comment by ejregithub** [comment]
closing, ready for coding

**Comment by alexgibson** [comment]
I took a look at the copy above and have asked some questions in the doc ^

**Comment by claychaffin** [comment]
Info from D. Reams re links (he is still working on FAQ): 
"Documentation and Community Support"
https://support.mozilla.org/products/firefox-enterprise/ (drop the locale, it will redirect to the right language for folks)
"Release Notes"
https://support.mozilla.org/en-US/kb/where-find-release-notes-firefox-enterprise (this gives links to the two “flavors” of release notes for the two release speeds) (edited) 

not a biggie either way to me as we can change and test it all pretty easily in next phases of design/implementation
cchaffin 11:53 AM
