### ISSUE TITLE
new /enterprise page: code & code review

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7491]
## Description

Code /enterprise, using 100% Protocol components, building those as required to do so

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Is built fully in Protocol
- [x] Modular layout (for easier future iteration w. content)
- [x] Primary CTA is to download
- [ ] Is live during the week of Sept 16th - 22nd
- [ ] Target is Tier 1 locales but  . . . (Comment from Romain: If en-US can launch first and not let loc hold up the process)

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [x] Code
- [x] Identify analytics requirements and include in page - @sghoseWI 
- [x] Create redirects:  /organizations & /organizations/all to firefox/enterprise.
- [ ] ~Set up hosting for [onboarding guide .pdf,](https://drive.google.com/file/d/1sbF9ghhFa2fZek7NFAjXJabak3R02Enl/view) linked to in /enterprise~ (this is no longer valid - we will not host this guide, which will be included in the download bundles to which we will link as provided by the Enterprise team)
-  [ ] Extract strings to Pontoon, opt-in, none required for launch

**Comment by alexgibson** [comment]
Attempting to piece together the related parts for this work (for when it's ready):

Copy doc is here: https://docs.google.com/document/d/1nbSDIpMxmkLcy9Uts54IMB9LVZiTFGpwHRrC-_AFmD8/edit?usp=sharing

I don't think the copy has been reviewed by a dev, despite the issue being closed as complete. I asked a bunch of questions in the doc.

Wireframes are still being worked on in https://github.com/mozilla/bedrock/issues/7467

There's also a style tile being worked on here: https://github.com/mozilla/bedrock/issues/7555

@ejregithub I have to call a big red flag here on the "Enterprise package downloads" section. I don't know where these downloads are supposed to go to, or where these pckages are meant to be hosted. Any ideas?

**Comment by hoosteeno** [comment]
> @ejregithub I have to call a big red flag here on the "Enterprise package downloads" section. I don't know where these downloads are supposed to go to, or where these packages are meant to be hosted. Any ideas?

* There will be 3 major download buttons on the page for Win32, Win64, and Mac, which lead to a zipped archive that includes the latest Firefox RR, latest ESR, and a mix of other documents aimed at enterprise users. The enterprise team will manage keeping these links up to date in the short term.
* These buttons will be links, probably to an AWS bucket. If the links change, the team will file Bedrock PRs to update them.
* Anyone can download the package, but the browsers included will be en-US only.

@devinreams added these to [the requirements doc he's maintaining for this](https://docs.google.com/document/d/1ZslDMR-q17rBTa0SDRulRMXa4UMayn0oTlDTVSM4HJA/edit).

**Comment by alexgibson** [comment]
We have final copy and wireframes, so I think this is good to get started on, although we're still waiting on download packages and the style tile.

**Comment by alexgibson** [comment]
@wboucherfischer @claychaffin @hoosteeno 

Here is a WIP prototype for the new enterprise page layout, complete with copy:

https://www-demo2.allizom.org/en-US/firefox/enterprise/

In terms of content I have one main piece of feedback at this time: 

As far as this new page goes, I can't recommend we remove and redirect the [old firefox organisations](https://www.mozilla.org/en-US/firefox/organizations/) page. I don't think this new enterprise page clearly explains what ESR is (or what it stands for), and it doesn't provide a clear way to download it on its own. We have to consider that some people are not based within an organization, and whom may wish to use ESR either for legacy reasons (e.g. Add-ons), or they are on an older system which the latest Firefox no longer supports. Without a clear way for those users to download ESR, I'm not sure we can justify retiring the old page yet.

Thoughts?

**Comment by hoosteeno** [comment]
I agree with Alex's assessment above. It's the same one that @rraue offered earlier, in the context of search visitors who're looking to download ESR. A couple factors that would mitigate this for me:

1. A week ago we seemed on the verge of a copy direction[0] that Raphael and I felt better about moving forward with:

Alternative subhead - to address search traffic (ESR) concern: `Download Firefox Extended Support Release (ESR) or Rapid Release in the install package you need to manage your enterprise.`

2. The "Need other languages" link is probably not adequate for getting this class of user to the /all page where they can find other languages _and other installers_. We should explain this better, e.g. by following the pattern set by the /new page: 

<img width="279" alt="Screen Shot 2019-08-16 at 9 14 05 AM" src="https://user-images.githubusercontent.com/94519/63178065-837f3700-c006-11e9-9a32-794231d4a14a.png">


`

**Comment by alexgibson** [comment]
> Set up hosting for onboarding guide .pdf, linked to in /enterprise

@ejregithub can you please clarify what this is, and if it's still needed? Thanks

**Comment by ejregithub** [comment]
@alexgibson - I asked Tyler to confirm that [this is correct file](https://drive.google.com/file/d/1sbF9ghhFa2fZek7NFAjXJabak3R02Enl/view) for the onboarding guide.  It was flagged in our contexting sessions as a requirement.

**Comment by alexgibson** [comment]
@ejregithub I don't see anywhere in the design where there's a direct link to that file. The deployment guide is listed in the package downloads, so if that's the only place it surfaces then I don't think we need to figure out hosting for it here.

**Comment by wboucherfischer** [comment]
@alexgibson 

Can you please make the following correction:

![Get Firefox for your enterprise — ESR  RR and premium support](https://user-images.githubusercontent.com/50332473/63304210-1cc47c80-c297-11e9-9456-71c2f0265785.png)

**Comment by ejregithub** [comment]
> @ejregithub I don't see anywhere in the design where there's a direct link to that file. The deployment guide is listed in the package downloads, so if that's the only place it surfaces then I don't think we need to figure out hosting for it here.

Agreed- MKaply said they're figuring that out, we'll just point to that when we receive it.

**Comment by wboucherfischer** [comment]
> I agree with Alex's assessment above, and I would like to find a solution that lets us decommission the archaic /organization page. It's the same issue that @rraue raised earlier, in the context of search visitors who're looking to download ESR. A couple factors that would mitigate this for me:
> 
>     1. A week ago we seemed on the verge of a copy direction[0] that Raphael and I felt better about moving forward with:
> 
> 
> Alternative subhead - to address search traffic (ESR) concern: `Download Firefox Extended Support Release (ESR) or Rapid Release in the install package you need to manage your enterprise.`
> 
>     1. The "Need other languages" link is probably not adequate for getting this class of user to the /all page where they can find other languages _and other installers_. We should explain this better, e.g. by following the pattern set by the /new page:
> 
> 
> <img alt="Screen Shot 2019-08-16 at 9 14 05 AM" width="279" src="https://user-images.githubusercontent.com/94519/63178065-837f3700-c006-11e9-9a32-794231d4a14a.png">
> 
> Any solution that incorporates the above 2 features, directionally, would probably solve this issue.

My recommendation is that we redesign the ESR page and make it a child sub page of /enterprise. If we are using the ESR terminology going foward still, then I think we need a page to describe what it is. I do not think the focus of the /enterprise page should be ESR, as the focus should be on getting people to contact sales about information on the Firefox Premium Support Plan. 
 @hoosteeno  i am fine with your recommendation around the pattern to get users to /all. The 'Need other languages' came from the enterprise team and the concept sketches.

**Comment by claychaffin** [comment]
@hoosteeno I shared the alternative subhead (or one close to it) to address search traffic (ESR) with Tyler last week ("Download Firefox Extended Support Release (ESR) or Rapid Release in the install package you need to manage your enterprise"), but she preferred the subhead we have because it contains this differentiating claim: "...comprehensive security and data protection..." (there's not enough room in the subhead to accommodate both messages). Please let me know if you want me to re-approach her about this, given concern about losing ESR folks.

**Comment by alexgibson** [comment]
@wboucherfischer can you please be explicit on the changes you would like to make for the "Need other languages" link? Thanks

**Comment by alexgibson** [comment]
@wboucherfischer ok I think this is now ready for design review: https://www-demo2.allizom.org/en-US/firefox/enterprise/

**Comment by alexgibson** [comment]
Marking this as blocked on the package download URLs.

**Comment by hoosteeno** [comment]
Let's also block on the subhead question. I don't consider it resolved yet.

**Comment by hoosteeno** [comment]
Here are my suggestions for the subhead and the "other languages" link. @wboucherfischer @claychaffin @skrelnick23, please reach out to me in Slack if you'd like to discuss.

![Screen Shot 2019-08-20 at 8 50 46 AM](https://user-images.githubusercontent.com/94519/63358410-38c42e80-c328-11e9-807f-e1900ee652e0.png)
![Screen Shot 2019-08-20 at 8 52 03 AM](https://user-images.githubusercontent.com/94519/63358424-3d88e280-c328-11e9-9ff0-a65bbd1a1ffa.png)

**Comment by alexgibson** [comment]
My comment to the above is that I feel like we don't really explain what "ESR" stands for in the subhead (whereas we don't abbreviate Rapid Release)^

**Comment by ejregithub** [comment]
Currently blocked on:
- URLs from Product Team to package downloads - @ejregithub to track this.
- FAQ going live on SUMO - @hoosteeno - who owns this?
- Decisions on design (accounting for ESR & language) in subhead - @wboucherfischer  - please provided guidance

**Comment by skrelnick23** [comment]
1. Package downloads: I can hustle up the team to provide the zip files
(are all languages en-US, en-GB, en-CA, fr-FR, de-DE?). I assumed the
website team would help us host this? or is that on product team?
2. FAQ: To my understanding, Wendy thought that the FAQ would be a
standalone page on the website, separate from the enterprise sumo
<https://support.mozilla.org/en-US/products/firefox-enterprise> page. Is
this not correct?
3. ESR: I understand the SEM/SEO need and I absolutely defer to Justin's
expertise and recommendation here. To solve for the issue that Alex raises,
can we simply spell out ESR?

**Comment by ejregithub** [comment]
> 1. Package downloads: I can hustle up the team to provide the zip files (are all languages en-US, en-GB, en-CA, fr-FR, de-DE?). I assumed the website team would help us host this? or is that on product team? 

Hi @skrelnick23 - yes - per MKaply & Devin's replies in Slack, Product will find a place to host and provide the Websites team with the URLs

> 2. FAQ: To my understanding, Wendy thought that the FAQ would be a standalone page on the website, separate from the enterprise sumo <https://support.mozilla.org/en-US/products/firefox-enterprise> page. Is this not correct? 

As above, (comments in Slack), the Websites team will point to the SUMO page as the FAQ. It looks like Devin is going to spruce that up a bit, too.

> 3. ESR: I understand the SEM/SEO need and I absolutely defer to Justin's expertise and recommendation here. To solve for the issue that Alex raises, can we simply spell out ESR?

I think that's where it's going to end up, yes.

**Comment by hoosteeno** [comment]
Let's roll with this subhead:

![Screen Shot 2019-08-20 at 1 42 03 PM](https://user-images.githubusercontent.com/94519/63382905-fa933300-c358-11e9-9e15-6cd3f8f8e96c.png)


Let's roll with this link below the buttons:

![Screen Shot 2019-08-20 at 2 31 51 PM](https://user-images.githubusercontent.com/94519/63382850-d7688380-c358-11e9-9677-eaf796fa48fc.png)

@rraue has approved this combination of changes as solving for the search case because 
1. The title continues to mention ESR (`<title>Get Firefox for your enterprise — ESR, RR and premium support</title>`)
2. The subhead will mention Extended Support Release
3. The link below the download buttons will mention ESR

Tyler has granted us license (above) to implement needed changes to solve for this case. 

I believe this combination adequately solves for users seeking ESR with either the abbreviated or complete product name, which will enable us to redirect /organizations pages here.

**Comment by ejregithub** [comment]
> 1. Package downloads: I can hustle up the team to provide the zip files (are all languages en-US, en-GB, en-CA, fr-FR, de-DE?). I assumed the website team would help us host this? or is that on product team? 

Hi @skrelnick23 - yes - per MKaply & Devin's replies in Slack, Product will find a place to host and provide the Websites team with the URLs

> 2. FAQ: To my understanding, Wendy thought that the FAQ would be a standalone page on the website, separate from the enterprise sumo <https://support.mozilla.org/en-US/products/firefox-enterprise> page. Is this not correct? 

As above, (comments in Slack), the Websites team will point to the SUMO page as the FAQ. It looks like Devin is going to spruce that up a bit, too.

> 3. ESR: I understand the SEM/SEO need and I absolutely defer to Justin's expertise and recommendation here. To solve for the issue that Alex raises, can we simply spell out ESR?

I think that's where it's going to end up, yes.

**Comment by wboucherfischer** [comment]
Here is feedback from Clio and Jennifer. 

https://miro.com/app/board/o9J_kwmWXV4=/

@alexgibson I have scheduled something for 7:00am tomorrow to go over and discuss and see what we can do.

**Comment by wboucherfischer** [comment]
> @wboucherfischer can you please be explicit on the changes you would like to make for the "Need other languages" link? Thanks

Sorry, I just saw this:

Instead of 'Need other Languages?" please use @hoosteeno's suggestion above. Download Firefox ESR or Rapid Release for another language or platform.

**Comment by wboucherfischer** [comment]
@alexgibson For the feature image, please switch out the image with the dark background with one to white, per Clio.
![light bg](https://user-images.githubusercontent.com/50332473/63476156-bd03d800-c434-11e9-8aaa-2a9d832c49a2.png)

**Comment by wboucherfischer** [comment]
Please see if we can put the offer section heading on 2 lines per jrouse:

<img width="831" alt="Screen Shot 2019-08-21 at 5 41 39 PM" src="https://user-images.githubusercontent.com/50332473/63477653-035c3580-c43b-11e9-8c12-0f2711f07020.png">

**Comment by alexgibson** [comment]
I've pushed new proposed copy to demo, and also made tweaks based on design feedback:

https://www-demo2.allizom.org/en-US/firefox/enterprise/

Still blocked on package download URLs and FAQ.

**Comment by devinreams** [comment]
Thanks @alexgibson. Tyler and I took a quick pass and things are looking great!

@wboucherfischer and team: what will be the most efficient way to help provide some feedback and capture questions at this stage? Doc with a list of things? Comments here? A quick "intake" meeting to talk through before we write a bunch out? Some examples: potential ideas for linking content to support pages, spacing or layout concerns, alignment questions.

**Comment by alexgibson** [comment]
Note that this is also blocked on the analytics plan: https://github.com/mozilla/bedrock/issues/7572

**Comment by wboucherfischer** [comment]
> Thanks @alexgibson. Tyler and I took a quick pass and things are looking great!
> 
> @wboucherfischer and team: what will be the most efficient way to help provide some feedback and capture questions at this stage? Doc with a list of things? Comments here? A quick "intake" meeting to talk through before we write a bunch out? Some examples: potential ideas for linking content to support pages, spacing or layout concerns, alignment questions.

Let me put the updated wireframes on miro and send out a link for feedack. @ejregithub  can you schedule a review with the team?

**Comment by wboucherfischer** [comment]
@devinreams here is link to miro with screenshot. Please provide feedback there. https://miro.com/app/board/o9J_kwk_fKo=/

**Comment by alexgibson** [comment]
Download links are now in place, removing the blocker on this page moving forward.

Note: the downloads are en-US only at present, so whilst we can ship this page, we can't localize it until the product team produce packages in multi-language.

**Comment by skrelnick23** [comment]
Sorry to have a change in opinion so late here. We say "get" a couple of
times, how about "Learn more" instead of "Get more info"?
