### ISSUE TITLE
CRO Sandbox - Create simplified version of /new in the sandbox

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7506]
## Description

Create simplified version of /new in the sandbox
- Duplicate template, don’t extend
- /en-US/exp/firefox/new/
- en-US only to start; de or fr may come later
- No modals
- Assume only first-class browsers
- No custom stub attribution overrides
- Include 3rd-party a/b tool
---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Duplicate template, don’t extend
- [x] /en-US/exp/firefox/new/
- [ ] en-US only to start; de or fr may come later
- [x] No modals
- [x] Assume only first-class browsers
- [x] No custom stub attribution overrides
- [x] Include 3rd-party a/b tool

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
This will be covered in #7508

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/7702
