### ISSUE TITLE
Build /accounts in CRO sandbox

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7507]
## Description

We should build the /en-US/firefox/accounts/ page in the CRO sandbox.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] /en-US/exp/firefox/accounts/ is a copy of /en-US/exp/firefox/accounts/
- [ ] it includes Convert snippets
- [ ] Maintain signed-in, signed-out states

#### Tasks
- [ ] Drop page into django application
