### ISSUE TITLE
Remove shapeoftheweb content

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7520]
## Description

As far as I know, the shapeoftheweb content that lives in bedrock was never used (also the site https://shapeoftheweb.mozilla.org no longer exists). I think we're probably good to remove the code from bedrock? It looks like the content was never localized.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] [shapeoftheweb app ](https://github.com/mozilla/bedrock/tree/master/bedrock/shapeoftheweb)is removed from bedrock.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Was this data ever used anywhere?

#### Tasks
- [x] Verify we're ok to remove.
- [x] Remove it.

**Comment by alexgibson** [comment]
@pmac are we ok to remove this? ^

**Comment by rraue** [comment]
Could we redirerect the url to https://internethealthreport.org?

**Comment by pmac** [comment]
I had completely forgotten that we hosted anything for that site from bedrock. It looks from [bug 1088752](https://bugzilla.mozilla.org/show_bug.cgi?id=1088752) that this was done for l10n purposes, and yes, that site is now very much gone. I think it's quite safe to remove this. Thanks for the ping.

**Comment by pmac** [comment]
> Could we redirect the url to https://internethealthreport.org?

We could, but it's been disabled for so long that I doubt it'd do any good. It was a site setup that we advertised for the Firefox (29) Australis release. Do you see anything in SEO tools about that subdomain?

**Comment by pmac** [comment]
or was that webwewant.mozilla.org? Either way I think it's been quite a while.

**Comment by alexgibson** [comment]
Yeah I think webwewant was something else. I don’t think shapeoftheweb ever officially launched, due to issues with the site itself.

**Comment by rraue** [comment]
I honestly doubt it will help as well, but yes I see a couple of hundred inlinks, and if the redirect wont hurt, lets do it. If it is more than 5 min of work, lets drop it

**Comment by pmac** [comment]
There is no infrastructure for the domain. If we do want a redirect it would be a bug to IT to setup the domain and redirect. It would be easy for them, but not nothing. I'd say if you think it would be at all useful just file the bug and indicate that it's low priority.
