### ISSUE TITLE
Remove jQuery dependency from base-page-init.js

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7523]
## Description

Our base bundle [init script](https://github.com/mozilla/bedrock/blob/master/media/js/base/base-page-init.js) still relies on jQuery DOM `ready()` and `load()` events for invoking common functions. We should refactor these to use vanilla JS equivalents.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Code is replaced with vanilla JS event handlers.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [x] Need to make sure the solution plays well with IE10+

#### Tasks
- [x] Refactor code.
- [x] Push to run-integrations-tests.

**Comment by amanbora** [comment]
Hi, I would like to contribute to this issue, are there any more specifications for the issue?? Thanks
