### ISSUE TITLE
Define localization approach for existing content

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7527]
Per page we need to connect with content owners and determine a localization approach.

- [ ] Identify content owners in the l10n audit -- people who can decide about sections of content for localized content.
- [ ] Connect with each content owner and an l10n project manager to decide the localization approach for content.
- [ ] Implement non-default decisions about l10n approaches in content-specific config rules.

**Comment by alexgibson** [comment]
Link to the original L10n page audit that Craig worked on: https://docs.google.com/spreadsheets/d/1ViVvQyH0IWYBDYaY8N-TKXeBsuYCgsFVUGyIz3WPg-g/edit?usp=sharing

Whilst I think this maps out most of the (current) system, it may not be exhaustive. But It should still help us to make a call as to the community/vendor/hybrid approach as we port pages to the new Fluent system. That said, it's been a while since this was put together, and we have a clearer idea of how the new system will work - so I think it may be worthwhile regrouping to discuss how this will work in terms of configuration.

**Comment by hoosteeno** [comment]
We should identify a content owner for all the localized content on the site and involve that person along with an l10n project manager in decisions about content localization approaches. 

How does this look? 

## Tasks ##

- [ ] Identify content owners in the l10n audit -- people who can decide about sections of content for localized content. 
- [ ] Connect with each content owner and an l10n project manager to decide the localization approach for content. 
- [ ] Implement non-default decisions about l10n approaches in content-specific config rules.

**Comment by hoosteeno** [comment]
@hoosteeno to identify content owners & schedule meetings for general intro.

**Comment by alexgibson** [comment]
@hoosteeno now we've landed on using explicit locale lists for vendor/pontoon with more specific options for the available approaches, does this issue still serve a reasonable purpose? 

We do still need to choose one of the available L10n strategies for each piece of existing content, but that's not something we need to do up-front any more, and can instead be tackled on a rolling basis. I'm not sure on the best way to keep track of that, but it may not be a single github issue. Thoughts?

**Comment by alexgibson** [comment]
Ok, so it seems like we still need a way to decide which pages are defined as "owned by marketing" (and go through staff/vendor), and which pages are not (and can go entirely through Pontoon).

I'm not sure what rules are being used to govern this choice currently, but it feels like deciding this manually on a page-by-page basis isn't going to scale well over time. Can we establish a relatively simple set of rules to help decide which configuration a page should use?

**Comment by alexgibson** [comment]
@hoosteeno given the audit we conducted in Q1, is there anything here that is left to be done?

**Comment by hoosteeno** [comment]
I don't think we need to do this, in particular because we will only have one localization approach for the foreseeable future.
