### ISSUE TITLE
Implement "Generic CTA" datalayer attributes

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7541]
We want to replace the dataLayer attributes on all _non-download-button_ CTA's on the site. 

Why _non-download-button_? Changing our download buttons is risky. Let's not do that now.

What's a CTA? A CTA is most often the top of an acquisition funnel. We have CTAs for e.g. registering for a Firefox Account, trying Firefox Monitor, signing up for a newsletter.

What's *not* a CTA? Links to other parts of the site often are not CTAs. For example, on https://www.mozilla.org/en-US/firefox/ we have many instrumented links that take users to other parts of the site to learn more. We might eventually want to consolidate these under the same dataLayer schema, but doing so is not the priority now.

### General specs:

We want to replace all `data-link-type`([0](https://github.com/mozilla/bedrock/search?p=2&q=data-link-type&unscoped_q=data-link-type)), `data-link-name`([1](https://github.com/mozilla/bedrock/search?q=data-link-name&unscoped_q=data-link-name)), and `data-button-name`([2](https://github.com/mozilla/bedrock/search?q=data-button-name&unscoped_q=data-button-name)) attributes on CTA links/buttons with a single standard:

```
data-cta-type="<name/category for the cta>" // REQUIRED, Ex: FxA-Sync, FxA-Monitor, FxA-Lockwise
data-cta-text="<indication of cta text>" // OPTIONAL, Ex: Sign Up, Join Now, Start Here. We use this when the link text is not useful, as is the case with many FxA forms that say, "Continue". We replace "Continue" with "Register". 
data-cta-position="<position of the cta>" // OPTIONAL, Ex: Primary, Secondary, Header
```

[https://app.zenhub.com/files/1616665/8d985673-d466-4d60-9ee2-7177e10fda02/download](https://app.zenhub.com/files/1616665/8d985673-d466-4d60-9ee2-7177e10fda02/download)

### Success Criteria

Make this change to all dataLayer attributes in...

- [x] macros.html
- [x] /firefox/accounts/ (lockwise/send/monitor CTAs in secondary content block)
- [x] global navigation ("Get a Firefox Account" CTA)
- [x] FxA modal on /firefox/new/ 
- [x] Newsletter signup in newsletter/includes/form and form-protocol

### Tasks 
- [x]  Determine if there are additional locations where this change should be made (CTAs)
- [x] Make this change to all dataLayer attributes identified above.

**Comment by alexgibson** [comment]
@hoosteeno two questions on above:

> FxA modal on /firefox/new/

Do you mean the modal on the old page design? The new design just links to /firefox/accounts/.

> Newsletter signup in newsletter/includes/form and form-protocol

Given that newsletters aren't directly related to account services, what should the `data-cta-type` value here be? Just `Newsletter`?

Thanks.

**Comment by hoosteeno** [comment]
> @hoosteeno two questions on above:
> 
> > FxA modal on /firefox/new/
> 
> Do you mean the modal on the old page design? The new design just links to /firefox/accounts/.

Ah, yes. Disregard that one, thanks.

> Given that newsletters aren't directly related to account services, what should the `data-cta-type` value here be? Just `Newsletter`?

Would it be possible to do "Newsletter-{{ no-spaces-newsletter-identifier }}" ?
