### ISSUE TITLE
Implement use of ES2015 in bedrock via transpiling build step

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7542]
## Description

As part of bedrock's technical roadmap we'd like to enable front-end developers to write JavaScript using ES2015 (ES6), with an aim to making code cleaner, more pleasing to write and easier to maintain. To enable this we'll need to add a transpiling build step to our existing [Gulp script](https://github.com/mozilla/bedrock/blob/master/gulpfile.js), using a tool like [Babel](https://babeljs.io/).

Some key considerations:

- Transpiled code will need to work in IE9 if we're to use it broadly (until we can drop 1st class support for that browser at least).
- We'll likely not want to transpile everything. If existing JavaScript code is already written in ES5, there's no need to transpile it. Some pages & bundles will also likely need to support legacy browsers, so may need excluding. Perhaps we could specify a particular file format to identify code that needs transpiling? (e.g. my-script.es6.js or similar).
- We'd need to consider how transpiling works in relation to running unit tests (via `gulp js:test`).
- We'd need to update our ESLint config to enable ES2015 in our source.
- We may want to compare bundle sizes of before / after transpilation with regard to performance.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Transpiling is implemented in build system.
- [ ] One page (TBD) in production is using transpiled code.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Need to ensure performance impact is acceptable.
- [ ] Need to ensure that supported browsers can still run transpiled code.

#### Tasks
- [ ] Implement build step.
- [ ] Document the changes.
- [ ] Port a single page (TBD) to use transpiled code.

**Comment by Errolyn** [comment]
From what I cant tell IE9 will be work fine with the ES5 polyfills, but I'm going to venture a guess that there will be some caveat we'll run into.

**Comment by hoosteeno** [comment]
@Errolyn is this still in progress?

**Comment by Errolyn** [comment]
Yes is it part of the webpack work  that is still on going, though this portion in the webpack work is mostly done. I don't want to close this until all the webpack stuff is done and merged.

**Comment by alexgibson** [comment]
Closing this until we circle back on webpack evaluation.
