### ISSUE TITLE
(11/4) - Display page content specific to users physically located in India

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7552]
## Description

The Taipei team wants to leverage the WNP to show content promoting Firefox Lite (which will be rebranded) to users located in India who have updated their Firefox desktop browser to the latest version at 11/4

Issue #6084 has described how this may be accomplished by parsing information out of request headers to then create a URL or convert an existing URL that will look at the country code and redirects the user to a URL based on the country, such as /en-US/firefox/whatsnew/?country=IN , in this particular case where users in India are the target audience.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Country (India) specific content is shown to users when updating their Firefox desktop browser 

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [x] Obtain content, copy and design assets, from the Taipei team - MVP is copy and images (QR code)
- [ ] Set up URL for users located in India
- [ ] Configure forwarding via header content identifying country
- [x] Provide assets to Silverorange to code
- [ ] QA (team and stakeholder) of coded page on demo
- [ ] Code review
- [ ] Merge, launch on Nov 4 (India Standard Time Zone)

**Comment by alexgibson** [comment]
It’s worth noting here that the functionality described in #6084 does not yet exist, and is likely either non-trivial or requires a level of engineering effort tbd.

**Comment by hoosteeno** [comment]
Regarding feasibility, [Slack conversation](https://mozilla.slack.com/archives/G7ACJHJCB/p1565371997480400) makes it sound like this is a problem we can solve using a solution like the one described in #6084 without risking site stability. I will explore priority.

**Comment by alexgibson** [comment]
Note: if we're going to do this for FF 70 then we'll need an English version of the Firefox Lite whatsnew page: https://www.mozilla.org/id/firefox/whatsnew/

**Comment by StellaTseng** [comment]
Yes, I will provide the English version of the Firefox Lite whatsnew page for India users.
Like what we did before for Indonesia users (but this time we will use QRcode instead of email): https://www.mozilla.org/id/firefox/whatsnew/ 
We are working on the assets and target to share it in the end of September (around 9/25). 
Is that okay for you to meet the FF 70 launch? Thank you!!

**Comment by alexgibson** [comment]
In order to answer this I need to fully understand the ask here:

- If someone is physically located in India, and has their browser language preference set to English -> show them the English Firefox Lite web page.
- If someone is physically located in India, but does not have their browser language preference set to English -> show them ?

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/pull/7627

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/7637

**Comment by StellaTseng** [comment]
Hi Alex, 
For the case - If someone is physically located in India, but does not have their browser language preference set to English -> We have no plan for this part yet, so maybe just leave this to the original content provider. Thanks!

**Comment by alexgibson** [comment]
If there are no additional L10n requirements then 9/25 should give us ample time before the FF70 launch on 10/22. Thanks!

**Comment by alexgibson** [comment]
Note for Silver Orange when it comes to implmentation:

https://github.com/mozilla/bedrock/issues/7637 changed our /whatsnew URLs to use the geo-redirector class. Docs are here: https://bedrock.readthedocs.io/en/latest/coding.html#geo-redirect-view

To display a page for people physically located in India, we'll need to add the appropriate country code [here](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/views.py#L540), pointing to a new view for India specific/whatsnew pages. For example:

```
geo_urls = {
    'IN': 'firefox.whatsnew.india',
}
```

The URL for this view could be defined in `urls.py` like so:

```
whatsnew_re_india = latest_re % (version_re, 'whatsnew/india')

...

url(whatsnew_re_india, views.WhatsnewIndiaView.as_view(), name='firefox.whatsnew.india'),
```

Happy to help if there are any questions.

**Comment by sgarrity** [comment]
@alexgibson I've got a quick question about the view code for this new India what's new page. We've got a temporary draft PR that is working fine, but it includes duplicating a block of code for the nightly/alpha/beta channels. Can you take a look at let us know if this view needs to address those channels? https://github.com/silverorange/bedrock/pull/5/files#r335430149
