### ISSUE TITLE
Deliver Enterprise Style Tile 

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7555]
## Description

**In week 1 of the sprint** deliver a completed, reviewed style tile for the Enterprise page, ready for developers to work from.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] This entire ask is completed during week 1 of the sprint
- [x] A reviewed style tile is delivered to developers ready for them to apply to enterprise wireframes
- [ ] Developers (S), business stakeholder (A), and PM (R) have reviewed/approved the style tile

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by wboucherfischer** [comment]
**Link to Style Tile in abstract:**
https://share.goabstract.com/87ff71ab-c989-4eb0-a1fd-6835563a68ca

**Link to Sketch file:**
https://share.goabstract.com/e1d360d8-1dcf-40d6-8e32-e62727808474

**PNG's**
![style tile page 2](https://user-images.githubusercontent.com/50332473/63271170-650b7c80-c24e-11e9-993a-e878d7d063cc.png)
![style tile page 1](https://user-images.githubusercontent.com/50332473/63271172-65a41300-c24e-11e9-9104-09deb2d6ebc5.png)

We are keeping the hero image the same. 
I need a spot illustration for the Features section from @mrkwvr or from Michael Ham. I created some examples of what I was thinking.

**Comment by ejregithub** [comment]
@wboucherfischer - we should leave this one open until it is truly closed out / when we have the asset for the Features section. (reopening).

**Comment by alexgibson** [comment]
Icons and imagery from the style tile is now in place on demo: https://www-demo2.allizom.org/en-US/firefox/enterprise/

I'm still tweaking spacing and typography.

**Comment by claychaffin** [comment]
Please add a colon to subhead, unless that breaks the template (see bolded copy). Thanks:

Section 3 — premium support key benefits
[section headline]
Get Firefox premium support for your enterprise 
[subhead]
Fast and dedicated support

 Firefox premium support provid**es:** 
- 24/7 private help for customization, deployment and management of Firefox
- SLAs on critical security bug fixing
- Access to the enterprise critical issues distribution list
- Access to a private customer portal 
- The ability to contribute to Firefox and our roadmap

**Comment by wboucherfischer** [comment]
@alexgibson I talked to Michael Ham and he said to continue using the spot illustration for the feature section that you have on the web page. He is finalizing the illustration guidelines and said we will update it later once the brand illustration guidelines are finalized.

**Comment by ejregithub** [comment]
@wboucherfischer - this page is now live in production - should this issue be closed?  Please drag to the Closed column if so.
