### ISSUE TITLE
Wireframe Lifecycle pages

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7556]
## Description

We need to build out some new pages as part of our new Lifecycle Pages channel. This work should be informed by [the contexting sessions we've held about this channel](https://docs.google.com/document/d/1VH6D5A3vnI7MWfR8XEIxMY_hrwNACqpmMGM2TzpFDL4/edit). 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] This entire package of success criteria are delivered by the end of the sprint
- [x] Reviewed wireframes suitable for UI design and development are delivered
- [x] Developers (S), PM (R), and Business Stakeholder (A) have reviewed wireframes

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.
