### ISSUE TITLE
Closure - WNP 68 - post release experiments to inform WNP 69 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7558]
## Description

This is a closure card. It doesn't mean "stop the experiment now", but it hopefully leads to that.

In a closure card, we should do the tasks below, in order.

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Experiment is stopped
- [ ] Experiment report is published 

#### Tasks
- [x] Determine whether we have enough data, and when we do, signal to shut down the experiment
- [x] Shut down the experiment (by e.g. changing a switch)
- [ ] Publish an experiment report  
- [ ] File any needed issues to remove or graduate experimental treatments (@hoosteeno)

**Comment by craigcook** [comment]
Submitted https://github.com/mozmeao/www-config/pull/235 to disable the experiment.

**Comment by sghoseWI** [comment]
Experiment report: https://docs.google.com/document/d/1BNpzciUIAkgtPXiVuzs2ruiS1eK1d0BsyubcC3TWHC4/edit#
