### ISSUE TITLE
Drop 1st class browser support for IE9

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7559]
## Description

We have the [go-ahead](https://github.com/mozilla/bedrock/issues/7389) to drop 1st class JS & CSS support for IE9. It can be served the same universal CSS & JS bundle as IE8, on the condition that we make an excpetion for the /firefox page.

For the /firefox page, we need to deliver some enhanced (but not necessarily 1st class) CSS, to at least style the main CTA.

Note: IE10 doesn't support conditional comments, so we'll need to cover that separately in https://github.com/mozilla/bedrock/issues/7391.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] IE9 is served the universal CSS and JS bundles for legacy browsers.
- [x] The /firefox page is served enhanced CSS on IE9.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This browser support change has been evaluated in https://github.com/mozilla/bedrock/issues/7389, so risk should hopefully be minimal.

#### Tasks
- [x] Update conditional comments to include IE9 in legacy browser treatment.
- [x] Add IE9 specific styles for /firefox.
- [x] Ensure downloads still function as expected in IE9.
- [x] Remove any [IE9 specific polyfills](https://github.com/mozilla/bedrock/blob/master/bedrock/base/templates/base-pebbles.html#L106-L108).

**Comment by alexgibson** [comment]
@hoosteeno I did some preliminary investigation on serving `/firefox` 1st class CSS for IE9, and I think the most sane approach might be to actually serve it Universal CSS, but with a page specific stylesheet targeted at IE9 only to serve as an "enhancement". The result is a slightly nicer set of universal styles, just for that one page.

I'd like to propose we try and just serve IE9 the CSS required for the top hero section. The rest of the page would get universal CSS, but I'd like to see if this is adequate enough to maintain conversions in IE9.  You can see how the hero would look below:

![firefox-ie9](https://user-images.githubusercontent.com/400117/63593874-df206600-c5ac-11e9-912b-b8e9cd9708ee.png)

We could potentially add more CSS enhancements if required once we see how it performs. I think this may be a better long term approach, rather than comitting to keep everything on that page working in IE9 long term.

Thoughts?

**Comment by alexgibson** [comment]
This is on demo here: https://www-demo1.allizom.org/en-US/firefox/

**Comment by hoosteeno** [comment]
I don't have a viable IE9 test box, but the screenshots look good. If this seems like the most efficient way to maintain this functionality, then I support it. Thank you!
