### ISSUE TITLE
Add /firefox to the list of pages we deliver enhanced to legacy browsers

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7565]
## Description

In https://github.com/mozilla/bedrock/issues/7389#issuecomment-520327033 we agreed to remove IE9/10 from the list of browsers getting [enhanced support](https://bedrock.readthedocs.io/en/latest/browser-support.html#technical-details). We also agreed to add /firefox to the list of pages where we try to provide enhanced support for browsers going all the way back to IE6.

This bug is about adding /firefox to that list.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] /firefox continues to work well in IE9/10 after we move them to the list of browsers that get a more basic experience

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
Going to close this as a dupe of https://github.com/mozilla/bedrock/issues/7559 (adding /firefox to the excluded pages is a sub-task there, and makes sense to do at the same time).
