### ISSUE TITLE
Update Beta and Dev Edition logos for Fx69 (2019-09-02)

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#7568]
## Description

The new Firefox logo is riding the trains for Fx70, so we'll have updated versions for Beta and Dev Edition channels coinciding with the Fx69 release. We should update them on the website for the 2019-09-02 release date.

Reference: https://docs.google.com/spreadsheets/d/1hbHhihkm8za4diQ_uaTEvNcd2jWeKlSU7X2_pYtnZcM/edit#gid=0

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Firefox Beta logo updated everywhere it appears.
- [ ] Firefox Dev Edition logo updated everywhere it appears.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Find all the logos for Beta and Dev Edition
- [ ] Change them to new logos

**Comment by alexgibson** [comment]
It looks like Beta/Dev Edition are now shipping with the new logos:

<img width="641" alt="Screenshot 2019-08-30 at 14 33 55" src="https://user-images.githubusercontent.com/400117/64024852-3f765100-cb33-11e9-8f22-ac22d5b7371c.png">
