### ISSUE TITLE
Lockwise Product Page (Epic)

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7569]
## Description

The goal is to re-implement the Lockwise product site  in a system that enables localization. This is on www.mozilla.org at www.mozilla.org/firefox/lockwise

[Master Project Doc](https://docs.google.com/document/d/1Wh4odUEnzNx71fPfw_EdR38lRLFaS1TOXzUdODUesb8/edit)

[Context sheet](https://docs.google.com/document/d/18M4hPXM37KBDKKnp8dxlaImbwokIZsdrBYNo8gcGtT0/edit#)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is live at www.mozilla.org/firefox/lockwise on or before Oct 22nd
- [ ] Strings are localized to Tier One at launch

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] We will put the marketing content for lockwise at www.mozilla.org/firefox/lockwise
- [ ] We will add a tiny bit of additional content to help it do good marketing

**Comment by alexgibson** [comment]
This page is done and live
