### ISSUE TITLE
Enterprise: Build analytics instrumentation plan

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7572]
## Description

In https://github.com/mozilla/bedrock/issues/7491#issuecomment-520981154 we note that links on this page will go to a different download than other download links on the website. We need an analytics instrumentation plan for these links.

Notes
* The links will go from a download button off site, so we need an event on the button
* We might be able to use our new [Generic CTA](https://github.com/mozilla/bedrock/issues/7541) tooling for this, in which case we simply need to specify the values of the CTA datalayer attributes

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Analytics plan is specified adequately for a developer to implement

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
@sghoseWI this page is now ready for an analytics implementation. 

Can you please provide a plan that outlines what the most important things are that we should track on this page? (is it downloads, sales leads, both?)

You can find the page up on demo here: https://www-demo2.allizom.org/en-US/firefox/enterprise/

**Comment by sghoseWI** [comment]
@alexgibson -- @hoosteeno and I met and we think the following tags make sense for our analytics tracking needs here:

Tags
On download buttons:
data-cta-type="Enterprise-Package" 
data-cta-text="Windows32|Windows64|Mac" // There are 3 of these buttons; use only one text option depending on the platform
data-cta-position="Primary" 

On ‘contact sales’ buttons:
data-cta-type="Enterprise-Sales" 
data-cta-position="Primary|Secondary" There are 2 of these buttons; the higher one is primary.

On SUMO links (Docs, release notes links at bottom of page):
utm_source=www.mozilla.org-enterprise
utm_campaign=enterprise
utm_medium=referral

Some additional documentation here (likely not needed for your purposes): https://docs.google.com/document/d/14A64kaLCBBviz2aHy_aMgG8hcYziwGc_MMZ0MnPavlg/edit

**Comment by alexgibson** [comment]
Analytics are now in place on demo: https://www-demo2.allizom.org/en-US/firefox/enterprise/

**Comment by ejregithub** [comment]
@sghoseWI  @alexgibson - I'm assuming that since the page is now live we can close this issue - please drag to done if that's the case.

**Comment by sghoseWI** [comment]
@ejregithub that's right, thanks -- now marked as done.
