### ISSUE TITLE
Browser Comparison SEO pages 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7574]
## Description

The idea is to provide a one-stop content resource that compares Firefox against our top five competitors in the market. This will consist of one main overview page that provides an intro and overview graphic, and that then links to the five sub-pages (repurposing SEM content) comparing Firefox side-by-side against competitors.

[Brief](https://docs.google.com/document/d/1BkZL_29Qx9rhf1_foCYMD8kju4bHdaGhpv2PcXvPImo/edit)

Structure:
Overview page: Compare Web Browsers
Chrome page: Compare Firefox vs Google Chrome
Safari page: Compare Firefox vs Safari
Edge page: Compare Firefox vs Microsoft Edge
Internet Explorer page: Compare Firefox vs Internet Explorer
Opera page: Compare Firefox vs Opera

We are doing this to boost our organic non-brand visibility and to drive incremental downloads from SEO content. 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks (in this order for go live priority)
- [x] Launch Overview page: Compare Web Browsers
- [x] Launch Chrome page: Compare Firefox vs Google Chrome
- [ ] Launch Safari page: Compare Firefox vs Safari
- [ ] Launch Edge page: Compare Firefox vs Microsoft Edge
- [ ] Launch Internet Explorer page: Compare Firefox vs Internet Explorer
- [ ] Launch Opera page: Compare Firefox vs Opera

**Comment by ejregithub** [comment]
Design for Overview page: Compare Web Browsers

![image](https://user-images.githubusercontent.com/20547886/63061057-d0e59200-bea8-11e9-8a89-9cb6908cf264.png)

**Comment by guyfitzpatrick** [comment]
Main page English back-translation from German: https://docs.google.com/document/d/1W3CgeHU0-IOY-XZlBIhxPY88Oszx_li8aApHmhJB4AA/edit#heading=h.zgjwb84g9sby

**Comment by rraue** [comment]
The urls will be:
Main page: /firefox/browsers/compare/
Chrome: /firefox/browsers/compare/chrome/
Safari: /firefox/browsers/compare/safari/
Opera: /firefox/browsers/compare/opera/
Edge: /firefox/browsers/compare/edge/
Internet Explorer: /firefox/browsers/compare/internet-explorer/

**Comment by ejregithub** [comment]
@sgarrity ^^ for URLs!

**Comment by sgarrity** [comment]
@rraue & @ejregithub Thanks for the URL scheme. I can update accordingly.

Is it acceptable that anyone manually altering the URLs could end up with the partial URL `/firefox/browsers/` that is a 404?

**Comment by ejregithub** [comment]
We are planning to have a new page at https://www.mozilla.org/firefox/products/browsers, likely by the end of November, which currently redirects to /firefox/

@rraue - should we have /firefox/browsers/, currently the 404 that @sgarrity noted, redirect to that new page /firefox/products/browsers/ when live? Should we do anything in the interim?

**Comment by rraue** [comment]
No, it’s totally fine to be an 404 in the meantime
-- 
______
Send via mobile

Raphael Raue
Global Head of Seo
www.mozilla.org

twitter.com/raue

**Comment by ejregithub** [comment]
https://www.mozilla.org/firefox/browsers/compare/ | https://www-demo-browser-compar-nvjrww.herokuapp.com/en-US/firefox/browsers/compare/

https://www.mozilla.org/firefox/browsers/compare/chrome/ | https://www-demo-browser-compar-nvjrww.herokuapp.com/en-US/firefox/browsers/compare/chrome/

https://www.mozilla.org/firefox/browsers/compare/safari/ | https://www-demo-browser-compar-nvjrww.herokuapp.com/en-US/firefox/browsers/compare/safari/

https://www.mozilla.org/firefox/browsers/compare/opera/ | https://www-demo-browser-compar-nvjrww.herokuapp.com/en-US/firefox/browsers/compare/opera/

https://www.mozilla.org/firefox/browsers/compare/ie/ | https://www-demo-browser-compar-nvjrww.herokuapp.com/en-US/firefox/browsers/compare/edge/

https://www.mozilla.org/firefox/browsers/compare/edge/ | https://www-demo-browser-compar-nvjrww.herokuapp.com/en-US/firefox/browsers/compare/ie/

**Comment by cgonz0** [comment]
for reference, here's the mock with added download links/bttn for 1:1 pages

![firefox vs chrome - proposed CTAs(1).png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/ad03e73d-5072-4f24-85e7-92a61d2c0052)
