### ISSUE TITLE
Browser Comparison SEO Overview page: Compare Web Browsers

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7575]
## Description

The idea is to provide a one-stop content resource that compares Firefox against our top five competitors in the market. This will consist of one main overview page that provides an intro and overview graphic, and that then links to the five sub-pages (repurposing SEM content) comparing Firefox side-by-side against competitors.

[Original brief](https://docs.google.com/document/d/1TRJO1g9ZT6CBR94iApXOfkAcq_54G8aoLu_PYxC2tX4/edit#)

[Updated, SEO specific brief](https://docs.google.com/document/d/1BkZL_29Qx9rhf1_foCYMD8kju4bHdaGhpv2PcXvPImo/edit)

[FINAL EN COPY](https://docs.google.com/document/d/1W3CgeHU0-IOY-XZlBIhxPY88Oszx_li8aApHmhJB4AA/edit?usp=sharing)

***Tasks***
- [x] Write de copy for the page (get it from the EU team)
- [x] Write fr copy for the page (get it from the EU team)
- [x] Write [en copy for the page](https://docs.google.com/document/d/1W3CgeHU0-IOY-XZlBIhxPY88Oszx_li8aApHmhJB4AA/edit?usp=sharing)
- [x] Get Legal signoff on copy
- [x] Complete design assets (@cgonz0 )
- [x] Specify Protocol 
- [x] Code the page
- [x] Extract strings, notify EU team and Peiying

**Comment by ejregithub** [comment]
![image](https://user-images.githubusercontent.com/20547886/63061785-3aff3680-beab-11e9-87b0-69d8e8f23876.png)

**Comment by ejregithub** [comment]
@rraue @claychaffin - here's the translation to EN from the original DE, done in Google Translate.  
https://docs.google.com/document/d/1HnUwtbt8aui-uDpIC65VZLoGy0ftHH4xKtd37xbvTPY/edit

I'm sure it needs review by @rraue and it does not include any meta data.

**Comment by rantley** [comment]
Here is my edited, (much shorter) version of the google translated copy. https://docs.google.com/document/d/1HnUwtbt8aui-uDpIC65VZLoGy0ftHH4xKtd37xbvTPY/edit

However, I did some digging yesterday and Anika actually created an English translated version of the original script (retaining the original length and content) link here:
https://docs.google.com/document/d/1W3CgeHU0-IOY-XZlBIhxPY88Oszx_li8aApHmhJB4AA/edit#

It's worth discussing how we want to proceed.

**Comment by rantley** [comment]
@ejregithub Moving forward with this version

@rraue This page contains SEO content related to comparing web browsers.  The meta items are also included at the top of the document. Please review. 

https://docs.google.com/document/d/1W3CgeHU0-IOY-XZlBIhxPY88Oszx_li8aApHmhJB4AA/edit#

**Comment by rantley** [comment]
@hoosteeno please see comment directly above and let me know if there is a different protocol for getting this properly reviewed.

**Comment by rraue** [comment]
SEO is fine. I actually would like test the longer german version against the shorter english version. I would assume the longer version will perform better, but I want to know, so lets move forward with the short version from you @rantley.

**Comment by ejregithub** [comment]
MFeldman (Legal) signed off on [the copy](https://docs.google.com/document/d/1W3CgeHU0-IOY-XZlBIhxPY88Oszx_li8aApHmhJB4AA/edit?usp=sharing) on 10/8

**Comment by cgonz0** [comment]
Header image forthcoming...

![BCH_mockup_notfinal.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/3fe88964-eaea-46f0-9b11-ae62076c9575)

**Comment by sgarrity** [comment]
@ejregithub  Will this overview page be going live before the individual browser comparison pages? I'm wonder if all six pages should get merged into a single feature-branch to launch together, or if each page should be managed independently?

**Comment by ejregithub** [comment]
@sgarrity - These can/should go separately as they become r+ed, please. They're not dependent (no internal links) on one another. We may look to change that when they're all live, but that is TBD.
