### ISSUE TITLE
Copy - Browser Comparison SEO Chrome page: Compare Firefox vs Google Chrome

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7576]
## Description

The idea is to provide a one-stop content resource that compares Firefox against our top five competitors in the market. This will consist of one main overview page that provides an intro and overview graphic, and that then links to the five sub-pages (repurposing SEM content) comparing Firefox side-by-side against competitors.

[Brief](https://docs.google.com/document/d/1BkZL_29Qx9rhf1_foCYMD8kju4bHdaGhpv2PcXvPImo/edit)

[Copy - US version](https://docs.google.com/document/d/1ASRLjRbGs2CDnKnYTder6DvK_lzIAuHNOhw2KkLzOx0/edit#)

[DE version]

***Tasks***
- [x] SEO review of copy (@rraue)
- [x] brand review of copy (@rantley)
- [x] @hoosteeno 's Team Lead review
- [x] Legal review of copy (@ejregithub)

**Comment by rantley** [comment]
Here's first draft of Chrome vs Firefox https://docs.google.com/document/d/1ASRLjRbGs2CDnKnYTder6DvK_lzIAuHNOhw2KkLzOx0/edit?usp=sharing

**Comment by ejregithub** [comment]
Noting that brand review has occurred (Tim and Natalie).

**Comment by ejregithub** [comment]
Flagging that copy is still in flux here (@rraue commented on this). @rantley can you please provided status?

**Comment by rantley** [comment]
As discussed those comments pertain to the comparison overview page, not this one.

**Comment by ejregithub** [comment]
@hoosteeno - could you please review the copy here before I pass to Legal?

**Comment by rantley** [comment]
@ejregithub per @hoosteeno 's request I updated the copy here to align closer to the Firefox brand voice. After our call yesterday, I chatted with Raphael about scaling back (losing) the third person POV and he thought that was a fine compromise.  

https://docs.google.com/document/d/1ASRLjRbGs2CDnKnYTder6DvK_lzIAuHNOhw2KkLzOx0/edit#heading=h.x2v9wtcveazf

**Comment by ejregithub** [comment]
Noting that copy changes were not substantial, none in claims were made to necessitate additional legal review.  Closing this issue as done.

**Comment by hoosteeno** [comment]
I  have reviewed this and think we should ship it. :shipit:
