### ISSUE TITLE
Copy - SEO - Browser Comparison SEO Safari page: Compare Firefox vs Safari

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7577]
## Description

The idea is to provide a one-stop content resource that compares Firefox against our top five competitors in the market. This will consist of one main overview page that provides an intro and overview graphic, and that then links to the five sub-pages (repurposing SEM content) comparing Firefox side-by-side against competitors.

[Copy - en-US](https://docs.google.com/document/d/1KpxsHVtge3bk5l8BYHz4E_UpWI4PR6sYcx5ZdTAifrI/edit#heading=h.oo63piaiuqi8)

Copy - DE version (NOT READY)

***Tasks***
- [x] SEO review of copy (@rraue)
- [x] brand review of copy by Natalie (@rantley)
- [ ] Legal review of copy (@ejregithub)
- [x] @hoosteeno 's Team Lead review

**Comment by rantley** [comment]
@rraue for your review sir. This is my first draft of Firefox vs Safari. 

https://docs.google.com/document/d/1KpxsHVtge3bk5l8BYHz4E_UpWI4PR6sYcx5ZdTAifrI/edit#

**Comment by rraue** [comment]
@rantley reviewed, just minor change requests.

**Comment by ejregithub** [comment]
Rob noted copy is WIP, not yet reviewed by Brand (updating now, 30 min send to Natalie)

**Comment by rantley** [comment]
https://docs.google.com/document/d/1KpxsHVtge3bk5l8BYHz4E_UpWI4PR6sYcx5ZdTAifrI/edit#heading=h.232o7jq2u2hb

For @hoosteeno review

**Comment by hoosteeno** [comment]
I have reviewed this and think we should ship it. :shipit:
