### ISSUE TITLE
Copy - Browser Comparison SEO Edge page: Compare Firefox vs Microsoft Edge

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7578]
## Description

The idea is to provide a one-stop content resource that compares Firefox against our top five competitors in the market. This will consist of one main overview page that provides an intro and overview graphic, and that then links to the five sub-pages (repurposing SEM content) comparing Firefox side-by-side against competitors.

[Copy - en-US](https://docs.google.com/document/d/1QSX6lr2VSpLA8gb-Sbotiwb0AySntNCadBVXKly7UJY/edit)

***Tasks***
- [x] SEO review of copy (@rraue)
- [x] brand review of copy (@rantley)
- [x] @hoosteeno 's Team Lead review
- [ ] Winston Bowden review (Consulted)
- [ ] Guy Fitzpartick review (the 'A' requesting stakeholder)
- [ ] Legal review of copy (@ejregithub)

**Comment by ejregithub** [comment]
Rob noted - draft not started, will have ready for review on date (EOW 12/9)

**Comment by rantley** [comment]
@rraue for your review. @ejregithub **note:** the chromium based Edge browser isn't launching until next month, I wrote this as if it had already launched so it would have a longer shelf life. 

https://docs.google.com/document/d/1QSX6lr2VSpLA8gb-Sbotiwb0AySntNCadBVXKly7UJY/edit?usp=sharing

**Comment by ejregithub** [comment]
@hoosteeno - this has gone through Brand review, it's ready for yours.  Note that Raphael is out and cannot provide his review til he returns.

**Comment by rraue** [comment]
Review done, just minor changes requested. @hoosteeno your turn.

**Comment by rantley** [comment]
@ejregithub @rraue 

Revisions complete from Raphael review

**Comment by hoosteeno** [comment]
My review is in with a few tiny suggestions.

**Comment by rantley** [comment]
@ejregithub revisions are done based on Justin's review.

**Comment by hoosteeno** [comment]
I have reviewed this and think we should ship it. :shipit:
