### ISSUE TITLE
Copy - Browser Comparison SEO Internet Explorer page: Compare Firefox vs Internet Explorer

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7579]
## Description

The idea is to provide a one-stop content resource that compares Firefox against our top five competitors in the market. This will consist of one main overview page that provides an intro and overview graphic, and that then links to the five sub-pages (repurposing SEM content) comparing Firefox side-by-side against competitors.

Brief

[Copy - en-US](https://docs.google.com/document/d/1tMtr1tU5c7kDvmRcnEUgjnAsNDrWYaM7yiTdQkZR5hw/edit#)

***Tasks***
- [x] SEO review of copy (@rraue)
- [x] brand review of copy (@rantley)
- [x] @hoosteeno 's Team Lead review
- [ ] Winston Bowden review (Consulted)
- [ ] Guy Fitzpartick review (the 'A' requesting stakeholder)
- [ ] Legal review of copy (@ejregithub)

**Comment by ejregithub** [comment]
Rob noted - draft not started, will have ready for review on date (EOW 12/9)

**Comment by rantley** [comment]
@rraue @ejregithub 

Here's the IE comparison
 https://docs.google.com/document/d/1tMtr1tU5c7kDvmRcnEUgjnAsNDrWYaM7yiTdQkZR5hw/edit?usp=sharing

**Comment by ejregithub** [comment]
@hoosteeno - this has gone through Brand review, it's ready for yours.  Note that Raphael is out and cannot provide his review til he returns.

**Comment by rraue** [comment]
Review done, @hoosteeno have fun.

**Comment by rantley** [comment]
revisions from @rraue done

**Comment by hoosteeno** [comment]
My review is in with a few tiny suggestions.

**Comment by rantley** [comment]
@ejregithub revisions are done based on Justin's review.

**Comment by hoosteeno** [comment]
I have reviewed this and think we should ship it. :shipit:
