### ISSUE TITLE
Copy - Browser Comparison SEO Opera page: Compare Firefox vs Opera

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7580]
## Description

The idea is to provide a one-stop content resource that compares Firefox against our top five competitors in the market. This will consist of one main overview page that provides an intro and overview graphic, and that then links to the five sub-pages (repurposing SEM content) comparing Firefox side-by-side against competitors.

[Copy - en-US](https://docs.google.com/document/d/1zSMcQwsHJkrrxJ4X9x7jZmwbWCpdG6Cq66FcvZI0Dsk/edit)

Copy - DE version - (NOT READY)

***Tasks***
- [x] SEO review of copy (@rraue)
- [x] brand review of copy (@rantley)
- [x] @hoosteeno 's Team Lead review
- [x] Winston Bowden review (Consulted)
- [x] Guy Fitzpartick review (the 'A' requesting stakeholder)
- [x] Legal review of copy (@ejregithub)

**Comment by ejregithub** [comment]
Rob noted  - WIP, not yet reviewed by Brand (Working on, Will send to Brand on 12/9)

**Comment by rantley** [comment]
@ejregithub sent to Natalie this evening. https://docs.google.com/document/d/1zSMcQwsHJkrrxJ4X9x7jZmwbWCpdG6Cq66FcvZI0Dsk/edit?usp=sharing

**Comment by ejregithub** [comment]
@rraue - did you get a look at this copy for Firefox vs. Opera?

**Comment by rraue** [comment]
I did, with just a small ask for change in the introduction.

**Comment by rantley** [comment]
Version Post Raphael and Natalie review

https://docs.google.com/document/d/1zSMcQwsHJkrrxJ4X9x7jZmwbWCpdG6Cq66FcvZI0Dsk/edit#

**Comment by ejregithub** [comment]
@sgarrity - copy updates as noted in Slack, please- they are reflected in the copy doc as well (but easier to flag here).

[Page Title Tag]

[Firefox vs. Opera: Which is the better browser for you?]

[Page Description Tag]

[Compare Opera to the Firefox Browser to find out which is the best browser for you.]

And in the first sentence in the first paragraph, b in Browser needs to be capitalized. 

[The Firefox Browser and Opera are two of the oldest browsers still releasing frequent updates.]

**Comment by hoosteeno** [comment]
I have reviewed this and think we should ship it. :shipit:
