### ISSUE TITLE
UX/UI/Design - Lockwise product page on www.mozilla.org

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7582]
UX/UI/Design - Lockwise product page on WMO

With new copy and 'on brand' updates to the current page we should add/update content to make that have a better marketing pitch.

The overarching goal is to maintain, not recreate or create anew, the imagery in the page

***Success Criteria***
- [x] Includes an interaction design based on user state (desktop browser version, mobile)
- [x] Has download CTA (for the add-on) if user is <70
- [ ] Users at >70.0 see informational content about using the product (likely pointing to the SUMO FAQ)
- [x] Is stakeholder approved (yes, in Slack on 8/22)

***Tasks***
- [x] Design new page maintaining as much original content imagery w. new copy (@wboucherfischer to wireframe)
- [x] Figure out how it integrates with global nav and footer
- [ ] Source localized images - get them (@mrkwvr)
- [ ] Understand how horizon bar and mozilla.org nav interrelate

**Comment by ejregithub** [comment]
Making that note that, from Slack, @wboucherfischer is going to provide wireframes with the option showing with and without out the horizon bar and its CTA to get a FxAccount.  Thank you Wendy!

<img width="613" alt="Screen Shot 2019-08-20 at 8 45 44 PM" src="https://user-images.githubusercontent.com/20547886/63401282-963d9700-c38b-11e9-8f4d-cb889f88a5f3.png">

**Comment by wboucherfischer** [comment]
**Link to Sketch file in Abstract**
https://share.goabstract.com/8d2db792-8e2c-46c3-b8fc-78cd0856ac84

**Link to Abstract Collection for Commenting:**
https://share.goabstract.com/321bc547-708a-43a9-8ad4-213049388fcc

Added version with banner/no banner at the top to join Firefox. My recommendation is that we don't have the banner. As the web page should be consistent with other Firefox navigation the recommendation is that we lose the current footer, add the global footer, and make the links items under resources as part of the web page. 
Also, the recommendation is to use an inverted button for the hero area, rather than a solid button.

![lockwise-mobile-banner](https://user-images.githubusercontent.com/50332473/63463302-bb74e880-c411-11e9-8bc3-bea462f0d68e.png)
![lockwise-mobile-no-banner](https://user-images.githubusercontent.com/50332473/63463303-bb74e880-c411-11e9-8759-8c5ac711bf2d.png)
![lockwise-page-option2-banner](https://user-images.githubusercontent.com/50332473/63463304-bc0d7f00-c411-11e9-8776-a38066b0624a.png)
![lockwise-page-option1-no-banner](https://user-images.githubusercontent.com/50332473/63463305-bc0d7f00-c411-11e9-94b3-783297a339d9.png)

**Comment by hoosteeno** [comment]
I've reviewed this and have no change requests. Good job! 🎇

**Comment by ejregithub** [comment]
@mrkwvr - can you please attach a/the sketch file for this page and @  @Errolyn when you do?

**Comment by mrkwvr** [comment]
design is complete and files have been delivered to @Errolyn. file was too large to post here
