### ISSUE TITLE
Add optional entrypoint_experiment and entrypoint_variation parameters to FxA referral macros.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7589]
## Description

If a referral link to accounts.firefox.com or monitor.firefox.com is part of an experiment, we can highlight that fact by passing along `entrypoint_experiment` and `entrypoint_variation` parameters in the href. So far we haven't used either of these parameters in production, so they currently aren't supported in the macros we use. This is a task to implement them and document their existence.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Both `entrypoint_experiment` and `entrypoint_variation` are available as optional parameters in the following macros:
  - [ ] `fxa_link_fragment`
  - [ ] `fxa_cta_link`
  - [ ] `monitor_button`
  - [ ] `fxa_email_form`

#### Tasks
- [ ] Update macros.
- [ ] Document the changes [here](https://bedrock.readthedocs.io/en/latest/firefox-accounts.html).

**Comment by alexgibson** [comment]
This was done recently in https://github.com/mozilla/bedrock/pull/8104
