### ISSUE TITLE
Lifecycle page - Closure Card: monitor, close, provide analysis

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7590]
## Description

Stop and analyze the lifecycle pages staged rollout experiment.

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Experiment is stopped
- [ ] Experiment report is published 

#### Tasks
- [ ] Determine whether we have enough data, and when we do, signal to shut down the experiment
- [ ] Shut down the experiment (by e.g. changing a switch)
- [ ] Analyze initial launch period & determine next steps (changes)
- [ ] Publish an experiment report  
- [ ] File any needed issues to remove or graduate experimental treatments (@hoosteeno)

**Comment by ejregithub** [comment]
Since we're not doing a staged rollout we don't need a closure card (there is no experiment). Closing.
