### ISSUE TITLE
Lifecycle page - Build SUMO FAQ

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7591]
## Description

Associated with the Lifecycle pages to be shown to users in their Firefox browser at various moments in time, we want to inform users as to the significance of them - what they are, why they're seeing them and, eventually, instructions on how they can opt out of being shown them.

[copy deck](https://docs.google.com/document/d/1eCaz2Zp9GRN7BA5pxooTZJADEtFYVvcRzwVfKlaF1kw/edit?usp=sharing)
---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Page on SUMO is live with relevant content
- [x] Is reviewed/approved by Team Lead
- [ ] Is review and accepted by SUMO
- [x] Is reviewed/approved by the (A)ccountable person identified in the project RASCI

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [x] Create the content
- [x] Identify URL - https://support.mozilla.org/en-US/kb/firefox-browser-welcome-content/
- [ ] Get the page approved by SUMO folks

**Comment by ejregithub** [comment]
@hoosteeno - can you please review [the copy](https://docs.google.com/document/d/1eCaz2Zp9GRN7BA5pxooTZJADEtFYVvcRzwVfKlaF1kw/edit) for this SUMO page and let us know of any edits and/or if it should be reviewed for final signoff by MEM?

**Comment by claychaffin** [comment]
@ejregithub @hoosteeno Heads up, please: I pinged Natalie about whether to rename "Lifecycle Pages" to something more more user-facing, and she's discussing it with Tim.

**Comment by ejregithub** [comment]
@hoosteeno - could you please review this page? - https://support.mozilla.org/en-US/kb/firefox-browser-welcome-content/edit#preview

**Comment by hoosteeno** [comment]
Done, I'm good with this being published.
