### ISSUE TITLE
Lifecycle page - Content: copy & design the page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7592]
## Description

This work will result in the copy and design, asset creation, for the new lifecycle page to be launched between Firefox 69 and 70.

---

***Success Criteria:***
- [ ] Is reviewed/approved by Team Lead
- [ ] Is reviewed/approved by the (A)ccountable person identified in the project RASCI
- [ ] Page is live between 69 and 70 rapid release dates
- [ ] Ensure this first page fits is considered within the broader view of the user lifecycle roadmap journey (implying we flesh out that full lifecycle in a separate task)
- [ ] We've ensured that the first page fits within broader view of the lifecycle roadmap journey
- [ ] We've taken the 68 experiment learnings into the journey

***Risks***
- [ ] this is a risk

***Tasks***
- [ ] [Write copy](https://docs.google.com/document/d/1t35rV9FRFvx42WNNog-I2IwqMpOv0PWua-LbtasxCQI/edit?usp=sharing) for page presenting Monitor, which includes headline, body, SUMO and Opt-Out link language.  - Meghan Trowbridge is writing this copy
- [ ] Design the page (wireframes at least)
- [ ] Create whimsy in the content
- [ ] Some kind of visualization to add fun and whimsy to the page.

**Comment by ejregithub** [comment]
Meg is writing the copy for this initial page

**Comment by ejregithub** [comment]
@hoosteeno @wboucherfischer  - MEM asked in the [copy doc](https://docs.google.com/document/d/1t35rV9FRFvx42WNNog-I2IwqMpOv0PWua-LbtasxCQI/edit#) if "could/should this be conditional? e.g., if someone is signed-in, is the messaging different (e.g., did you know your account also includes Firefox Monitor)? vs. not signed in (e.g., sign up to get even more protection with Firefox Monitor)?"

As we did in WNP 69 for "signed in" and "not signed in/not sure you have an account" could we do the same/similar here? Or was there something happening with user state detection that I've forgotten about here?

![Screen Shot 2019-08-29 at 6 22 27 PM](https://user-images.githubusercontent.com/20547886/63987664-f9b37d00-ca8d-11e9-80de-fe418c243ca9.png)

![Screen Shot 2019-08-29 at 6 15 15 PM](https://user-images.githubusercontent.com/20547886/63987665-f9b37d00-ca8d-11e9-94f0-bbb9d6699b15.png)

**Comment by wboucherfischer** [comment]
@ejregithub @hoosteeno @clay yes we can, but I need copy written. Meg Trowbridge is not on github.

**Comment by hoosteeno** [comment]
I answered in the copy doc. I'm not convinced that signed in/out state...
a) is an important signal here
b) has any impact

I suggest we don't complexify just because we can, but because it makes sense. I don't see a compelling reason yet to do so here.

**Comment by wboucherfischer** [comment]
Here is first draft at visual design for Lifecycle page. 
![lifecycle-page-1440@2x](https://user-images.githubusercontent.com/50332473/64049547-04bbeb00-cb2a-11e9-95f4-d4209f5841ef.jpg)

Link to Abstract File: https://share.goabstract.com/acef1b6f-cec0-45f2-9ce6-ca954a4a147b

Link to Miro Board: https://miro.com/app/board/o9J_kwqyWSc=/

**Comment by dzingeek** [comment]
just a heads up the design wendy posted above still needs to go through design review. so...feel free to start development if you haven't already but just know this is not final and has not been through any design feedback process yet.

**Comment by wboucherfischer** [comment]
Can we just have Mark work on this when he gets back?

**Comment by dzingeek** [comment]
@wboucherfischer yes, @mrkwvr  can start working on that today.

**Comment by mrkwvr** [comment]
here's the initial design I started but still needs work and copy updates
![Screen Shot 2019-09-03 at 1 30 04 PM](https://user-images.githubusercontent.com/29285941/64195247-000b7580-ce4f-11e9-9769-a7fdd33a5002.png)

link to abstract file: https://share.goabstract.com/b158157a-f2df-4780-b7b1-74d89f479476

**Comment by craigcook** [comment]
Recording here that the design evolved further from the above after review with Clio. Current working version (as of this comment):

![Lifecycle 1 Copy 5](https://user-images.githubusercontent.com/205591/64464319-58937a80-d0bc-11e9-9ce2-11f0be89a79c.jpg)

**Comment by ejregithub** [comment]
Noting here, after discussing in Slack and email, based on comments from Anika that we will:

- In the "Stay ahead of hackers" section we're now linking to https://blog.mozilla.org/firefox/what-to-do-after-a-data-breach/
as that's basically the same content as in /tips AND it has been localized to DE and FR.

- We're simply hiding the "Stay in the know" section for other locales.
