### ISSUE TITLE
Lifecycle page - Instrumentation & measurement

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7593]
## Description

This work will establish the analytics plan for the new lifecycle page to be launched betwee 69 and 70

---

***Success criteria:***
- [ ] Can measure sessions/conversions on the page
- [ ] Implements FxA referral instrumentation standards

***Risks***
- [ ] This is a risk

***Tasks:***
- [ ] Build analytics plan for lifecycle pages (including the initial one for launch between 69 and 70)
- [ ] Analyze initial launch period & determine next steps (changes)
- [ ] Build experiment to expose survey to % of initial audience

**Comment by sghoseWI** [comment]
Lifecycle Page 1

Tags
On  Monitor button:
data-cta-type=“Lifecycle-Monitor”
data-cta-text=“Check Your Breach Report”
data-cta-position="Primary"

On offsite links (Monitor Security Tips, Evite data breach “party”, Why am I seeing this?):
utm_source=Lifecycle-resources
utm_campaign=LifecycleP1
utm_medium=referral
