### ISSUE TITLE
Lifecycle page: Code

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7594]
## Description

This first lifecycle page is to be launched between Firefox 69 and 70 with the main goal of promoting the Firefox Monitor product. 

[URL structure](https://docs.google.com/document/d/1T-MPx9idmrSzMi_w91BM6HiVJ8WhyH7D9BW6Hh--hZw/edit?usp=sharing)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] The life cycle page should be reusable
- [x] The page is built in a modular fashion
- [ ] The page is built 'Protocol first '- use existing, build new as required
- [x] Localized to Tier One locales (DE, FR, en-US, en-GB, en-CA) at launch

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Code
- [ ]  Extract strings to Pontoon for L10n (dev)
- [ ] Notify EU team of incoming strings
- [ ] Remit strings to EU team in advance for DE and FR localization, work with Peiying on Pontoon
- [ ] Set page to no-index
- [ ] Set as canonical URL
- [ ] Include links to FAQ on SUMO - https://support.mozilla.org/en-US/kb/firefox-browser-welcome-pages/
- [ ] Get coded page on demo server
- [ ] Coded page on demo - reviewed/approved by @hoosteeno and acknowledged here
- [ ] Coded page on demo - reviewed/approved by Approver in RASCI (cpark) and acknowledged here
- [ ] Code review

**Comment by ejregithub** [comment]
https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/welcome/stage1/ - first incarnation of page on demo server

**Comment by craigcook** [comment]
@sghoseWI The page is on demo at https://bedrock-demo-craigcook.oregon-b.moz.works/firefox/welcome/1/ and the pull request is #7737 for analytics review.
