### ISSUE TITLE
Need enterprise spot illustration for features section in Style Tile

### ISSUE THREAD

**Issue by wboucherfischer** [mozilla/bedrock#7598]
## Description

Need the creation of a spot illustration for the features section of the enterprise page.
The image should convey the benefits and features of the enterprise premium support plan.

Copy: https://docs.google.com/document/d/1nbSDIpMxmkLcy9Uts54IMB9LVZiTFGpwHRrC-_AFmD8/edit?usp=sharing
[section headline]
Get Firefox premium support for your enterprise
[subhead]
Fast and dedicated support
 Firefox premium support provides: 
- 24/7 private help for customization, deployment and management of Firefox
- SLAs on critical security bug fixing
- Access to the enterprise critical issues distribution list
- Access to a private customer portal 
- The ability to contribute to Firefox and our roadmap

Style Tile: https://share.goabstract.com/87ff71ab-c989-4eb0-a1fd-6835563a68ca
Abstract:  https://share.goabstract.com/e1d360d8-1dcf-40d6-8e32-e62727808474

I included some example illustrations on my thoughts for the illustration for the enterprise premium support plan benefits. Please also let me know if we can use anything I created.

![style tile page 2](https://user-images.githubusercontent.com/50332473/63272358-c46a8c00-c250-11e9-873b-41153738b471.png)
![style tile page 1](https://user-images.githubusercontent.com/50332473/63272359-c46a8c00-c250-11e9-8764-6669450d46eb.png)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Creation of spot illustration

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!

#### Tasks
- [ ] Creation of a spot illustration
- [ ] Review

**Comment by alexgibson** [comment]
If useful for context, I'll be incorporating @wboucherfischer's style tile into the page layout that's up on demo here: https://www-demo2.allizom.org/en-US/firefox/enterprise/

**Comment by alexgibson** [comment]
Icons and imagery from the style tile is now in place on demo: https://www-demo2.allizom.org/en-US/firefox/enterprise/

I'm still tweaking spacing and typography.

**Comment by wboucherfischer** [comment]
We are going to use the spot illustration, per Michael Ham, for now. Once Michael is done with the Illustration guidelines in September we can update at a later date.

**Comment by wboucherfischer** [comment]
@ejregithub Would I close this?

**Comment by ejregithub** [comment]
Indeed, thanks @wboucherfischer !
