### ISSUE TITLE
Update notifications to use notification component

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7615]
## Description

Notifications have been added to Protocol as a component. There's a few places in bedrock where notification already exist. It'd be great up update them to use the shiny new component.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] All existing notifications use the component code

#### Tasks
- [ ] Update Modular what's new page.
- [x] Update thanks page.

**Comment by stephaniehobson** [comment]
Tagging @amychurchwell because she knows the component best. Amy, feel free to unassigned yourself if your workload doesn't give you time for this.

**Comment by alexgibson** [comment]
Blocked by: https://github.com/mozilla/protocol/issues/525

![image](https://user-images.githubusercontent.com/400117/74819054-b24cd180-52f7-11ea-8fa9-c340591dbc79.png)

**Comment by alexgibson** [comment]
Also depends on: https://github.com/mozilla/protocol/issues/541
