### ISSUE TITLE
Email Preferences Page updates

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7620]
## Description

Email mailing list managers have asked for some minor improvements to the email preferences center, which they delivered in bullets in this [brief](https://docs.google.com/document/d/1ahtsCMOlf3tBNFnW11qehTLPK1ER-4XycKY40HQ3B_Y/edit). We should reach out to them to learn what problems they're trying to solve, and collaborate with them on designing a solution. 

This work can wait until we have a UI designer available.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Updates are live
- [ ] the page is ported to Protocol

#### Tasks
- [ ] Get a designer to review the requested changes (below) and vet for approval or further iteration
- Make the Subscribe and Unsubscribe text persistent above the list of emails
- Make the list vertically scrollable (create a new Protocol component)
- Remove the text ‘yes’ and ‘no’ next to each radio button, they’re superfluous and can confuse users.

**Comment by hoosteeno** [comment]
@cgonz0 can you update with recent status, any artifacts?

**Comment by cgonz0** [comment]
initial mocks/ideas(pages 3-5) [here](https://docs.google.com/document/d/1ahtsCMOlf3tBNFnW11qehTLPK1ER-4XycKY40HQ3B_Y/edit)
Status: need additional feedback from email marketing team based on issues that were raised during previous discussion:
-toggle on/off buttons preferred - but will results funnel into CRM?
-do we have Yes/No localized?
-can we display scroll bar as always visible, not just on hover?

**Comment by ejregithub** [comment]
We've done our part, closing this issue. We can create a new one for implementation when a decisions is made on the open questions here.
