### ISSUE TITLE
Update trademark policy, distribution policy, and product identity assets pages

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7622]
## Description

https://bugzilla.mozilla.org/show_bug.cgi?id=1571920

Copy updates here in [this doc](https://docs.google.com/document/d/1p4Lr4EQMmzsRHwtt3OYyl9eObALTBjdnie5Oqku9y48/edit#)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Updates are live

#### Tasks
- [x] Update https://www.mozilla.org/en-US/foundation/trademarks/distribution-policy/
- [x] Update https://www.mozilla.org/en-US/foundation/trademarks/

**Comment by Errolyn** [comment]
First PR is in, this will need a second pr to update https://design.firefox.com/photon/visuals/product-identity-assets.html

**Comment by Errolyn** [comment]
I have PR's open for both repo's now.

**Comment by Errolyn** [comment]
I have the changes up on a demo:
https://bedrock-demo-errolyn.oregon-b.moz.works/en-US/foundation/trademarks/distribution-policy/
and:
https://bedrock-demo-errolyn.oregon-b.moz.works/en-US/foundation/trademarks/

Let me know if you need me to make any changes :D
