### ISSUE TITLE
Sept 10th - Support Product and Legal with page updates

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7623]
## Description

Internal (Legal) bug - https://bugzilla.mozilla.org/show_bug.cgi?id=1575696

Legal will set up the URLs and post the content; the websites team just has to make it live.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Private until Sept 10, live on Sept 10

#### Tasks
- [ ] Coordinate w. MFeldman on go live plan
- [ ] Review the PR in legal-docs, merge and push to meet the (wide) launch window on Sept 10

**Comment by alexgibson** [comment]
This is blocked on creation of the markdown files that live in https://github.com/mozilla/legal-docs/

> Legal will set up the URLs and post the content; the websites team just has to make it live.

This needs to be done in bedrock, so will likely need a developer to create said URLs.

**Comment by alexgibson** [comment]
We're going to hard-code these pages to remove the waterfall dependency. Removing blocker.

**Comment by alexgibson** [comment]
PR is now open in the private repo.
