### ISSUE TITLE
Survey Enterprise page visitors

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7624]
## Description

The new /enterprise page will replace an existing acquisition funnel on www.mozilla.org/firefox/organizations. The legacy funnel has served 3 audiences we know of:
* A group of email-list members who have deployed Firefox in their organizations
* People on the web searching for Firefox ESR for a variety of reasons
* People on the web searching for Firefox to deploy in their organization

The new page radically repositions our enterprise offerings with new copy and new download packages. We intend to redirect the organizations URL to the new enterprise page. When we do so we want to be sure we are still adequately addressing the users who visit the page.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] We understand better the reason audiences arrived at this page
- [ ] We know what they are looking for
- [ ] We know whether they feel like they found it

#### Tasks
- [ ] Draft survey questions
- [ ] Vet questions with Survey Team, request survey
- [ ] Get link to survey from team and pass to dev for inclusion to /enterprise page

**Comment by hoosteeno** [comment]
Sharon offered a UR perspective on next steps here: https://docs.google.com/document/d/1cBIWsd3CtaT6tWxjyzNpbeTEGd995aDniOEKrOQdm28/edit?ts=5d66becc. She advises a launch, followed by quantitative analysis, followed by deeper user research.

I'm going to put this in the icebox for the moment. Removing from current sprint.

**Comment by hoosteeno** [comment]
Closing WONTFIX.
