### ISSUE TITLE
Change the URLs on the site that point Lockwise.firefox.com

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7628]
## Description

So we don't nuke our analytics 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Required for launch of the page
- [ ] No UTM parameters on same-site links

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Find the links
- [ ] Change the links

**Comment by stephaniehobson** [comment]
Note to dev: please update www-admin links too.

**Comment by ejregithub** [comment]
@Errolyn - this one isn't assigned to you, so I don't know if I'm correct in thinking that you were taking care of it as part of the overall lockwise project?

**Comment by Errolyn** [comment]
I am :D but since the other issue was closed why don't we just assign this one to me. I have a PR up and am testing all the links

**Comment by Errolyn** [comment]
I tried to update bedrocks sub-module to pull in the legal-docs change but ran into an issue. I'm not sure if the docs are up to date for the process or if there is some setup step that needs to happen to make it possible. I will be out Monday & Tuesday, but I don't think this is super urgent so I can try to finish that part of the update when I get back.
