### ISSUE TITLE
Update the Impressum page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7630]
## Description

We need to update the contents of the "Impressum" to comply with German law -- https://www.mozilla.org/de/about/legal/impressum/

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Page is updated with [new content](https://docs.google.com/document/d/1gh6-SDbUYwQKVDPg9y83pAe-0HL5V6PmMyC55I9_JG8/edit?usp=sharing)

#### Tasks
- [x] Put the page on demo with the new content from legal (forthcoming)
- [ ] Upon approval by legal, update the page in production

**Comment by ejregithub** [comment]
@alexgibson - Tyler gave the Legal thumbs up, in email.  We're good for code review.
