### ISSUE TITLE
Deprecate send_yourself widget

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7632]
## Description

As per: https://github.com/mozilla/bedrock/issues/7614, there's only one page that uses the send-yourself widget. So let's update send-to-device as it's less work.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] All pages use the send-to-device widget in production.

#### Tasks
- [ ] All pages use the send-to-device widget.
- [ ] Update send-to-device widget to handle multiple forms on one page.
- [ ] Update docs.
