### ISSUE TITLE
Make /whatsnew urls use the new Geo redirector view class

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7637]
## Description

In https://github.com/mozilla/bedrock/pull/7627 @pmac wrote a handy Geo redirector view class, so that we can use a server-side geo-location. There is an ask in https://github.com/mozilla/bedrock/issues/7552 to use this new functionality to show a custom /whatnsew page to people located in India. Before we can do that, we need to convert our existing /whatsnew URs to use this new `GeoRedirectView` class.

Docs are here: https://bedrock.readthedocs.io/en/latest/coding.html#geo-redirect-view

There's a rough POC here: https://github.com/alexgibson/bedrock/commit/520514ac7c48a1367ddde45e7e6c05c02d602e20

Open questions are:

- What URL slug should we use for our default (global) view? `/whatsnew/all/`, `/whatsnew/global/`?
- What type of slug should we use for country specific views? `/whatsnew/india/`, `/whatsnew/canada/`?

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Current /whatsnew URLs are turned into Geo redirector URLs.
- [x] A new URL is created for default experiences, and all current templates are shown there.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] May need to monitor load performance when this goes to prod?

#### Tasks
- [x] Create geo redirector view for /whatsnew.
- [x] Create new default view for current templates.
- [x] Update unit and functional tests where needed.

**Comment by alexgibson** [comment]
Adding this to the current sprint.

**Comment by alexgibson** [comment]
@hoosteeno this is up on demo: https://www-demo2.allizom.org/en-US/firefox/70.0/whatsnew/

One thing we need to bikeshed is the redirect URL naming convention. At present I've set the default (non-geo specific) redirect to be `/firefox/%VERSION%/whatsnew/all/`, but it clould be anything we choose.

When we do a country-specific redirect, we could then set it to `/firefox/%VERSION%/whatsnew/%COUNTRY_NAME%/`.

Any thoughts / opinions, or does this sound ok?

**Comment by hoosteeno** [comment]
This solution seems totally adequate for the need at hand -- thank you!

If we hear a need for more of these server-side headless redirectors for geographic-specific content -- especially on search-indexed pages -- we need to put some time into designing the URL structure optimally so search engines don't mistake the geography node as a topic.
