### ISSUE TITLE
Update headlines for Dev Edition landing pages

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7648]
## Description

Now that Dev Edition has a new wordmark logo, we should update the landing page headlines to better reflect how we're naming the browser.

- https://www.mozilla.org/en-US/firefox/developer/
- https://www.mozilla.org/en-US/firefox/70.0a2/whatsnew/
- https://www.mozilla.org/en-US/firefox/70.0a2/firstrun/

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1578601

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Headlines and subheads are updated where appropriate.

#### Tasks
- [ ] Get updated copy.
- [ ] Implement the changes.
- [ ] Localize new strings.

**Comment by amychurchwell** [comment]
Does this need copywriter input? or are we just renaming headlines:
> Firefox Quantum: Developer Edition

to

> Firefox Browser: Developer Edition

**Comment by stephaniehobson** [comment]
@rraue Have you managed to get official product names from anyone? What's the official name for Dev Edition?

**Comment by rraue** [comment]
Yes, its "Firefox Browser Developer Edition" as stated with all other products in this document, approved by Tim and Brad. https://docs.google.com/spreadsheets/d/1oozpYeRwGQQzZvVovVniy_qw--M3DUIRNbK1VPAw_QI/edit#gid=0

**Comment by rraue** [comment]
We should update the title and meta description as well to:

title: "Download Firefox Browser Developer Edition"
description: "Firefox Browser Developer Edition is the blazing fast browser that offers cutting edge developer tools and latest features like CSS Grid support and framework debugging"

**Comment by alexgibson** [comment]
I just asked this question to the brand team yesterday and was told a different thing, that it should be: `Firefox Developer Browser`

**Comment by Patil2099** [comment]
@alexgibson Can I work on this?

**Comment by alexgibson** [comment]
@Patil2099 I'm not sure this issue is ready to work on just yet, as there's still discussion above about what the new strings need to be.

**Comment by alexgibson** [comment]
This was fixed in https://github.com/mozilla/bedrock/pull/7870
