### ISSUE TITLE
Direct traffic at CRO sandbox versions of pages

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7652]
## Description

After we have copies of some content in the CRO sandbox, we should build any tooling that we will require to direct some traffic to those copies. This may mean using TrafficCop, perhaps with some standardized settings, or it may mean something else.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] A percentage of visitors to pages we've duplicated in the CRO sandbox can be redirected to the CRO sandbox duplicates.
- [x] Starting a new CRO experiment using the sandbox is a simple configuration change away.
- [x] URL parameters will be preserved between redirects.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
Initial architecture doc for reference: https://docs.google.com/document/d/1RXzBVUk3LSbyBeJOesPrKcekvA5bOUBiUIiQy7frHgQ/edit#heading=h.ui1wp7dez36o

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/7508

**Comment by amychurchwell** [comment]
Sandbox pages with experimental tool behind `/ex/` example: `/ex/firefox/accounts`

- URL parameters preserved on redirection.
- Adjust traffic percentage without a production push.
- Adjusting locale without a production push may need be a need in the future.
- Should be able to target any URL.

Server-side redirect solution may be preferable? Maybe convo with @jgmize ?

**Comment by jgmize** [comment]
Please see https://github.com/mozmeao/infra/issues/1050 for some links and an example of how Cloudflare workers might help with this.

**Comment by alexgibson** [comment]
Another requirement for this solution should be that it does not interfere with our functional test runs. 

Either it should only execute on www.mozilla.org / www.allizom.org domains (where it already won't interfere), or alternatively we could build a mechanism whereby our test runs can opt-out on incurring redirects.

**Comment by pmac** [comment]
> Initial architecture doc for reference: https://docs.google.com/document/d/1RXzBVUk3LSbyBeJOesPrKcekvA5bOUBiUIiQy7frHgQ/edit#heading=h.ui1wp7dez36o

FYI for anyone without access to the above doc, "CRO" stands for "Conversion Rate Optimization".

The more you know 🌈

**Comment by alexgibson** [comment]
> FYI for anyone without access to the above doc

Anyone at Mozilla has access to this doc ^

**Comment by pmac** [comment]
This page is fully public, and that doc is not. That's why I was trying to keep everyone up to speed. I had to login to look at the doc to learn what "CRO" meant, so I was just trying to help others.

**Comment by alexgibson** [comment]
@pmac the term CRO not being explained in the title of this issue, and the reason this doc is not public are, I feel, two separate issues. I’d be happy to discuss this with you in person, but I don’t feel async here is likely the appropriate place.

**Comment by pmac** [comment]
Fair enough. I just assumed since the issue was public and this repo has 115 watchers and 851 stars as of this comment that people would appreciate some explanation, like I wanted since this whole thing made no sense w/o context. If things need to be private that's fine, but it's also a capability we have with confidential bugzilla flags.

**Comment by alexgibson** [comment]
Whether we use confidential bugs in bugzilla, or an employee only gdoc - it will likely turn up here in GitHub, linked in some way, as that’s currently the nature of how we track progress of our work. But as I say, this feels like a different discussion as to why the meaning of CRO was not originally explained. Again, i’d be more than happy to discuss this with you in person, rather than here where we can concentrate in discussing the issue at hand.

**Comment by alexgibson** [comment]
@jgmize just talked to @hoosteeno and we'd like to test out using cloud workers on staging, providing a) you have some time & availability to work on it, and b) it's not a high level of effort / from yourself (it didn't sound like it from our meeting, but just to double check).

Happy to discus further in person if it helps.

**Comment by jgmize** [comment]
@alexgibson and I just had a short pairing session where we experimented with temporarily deploying some code generated with http://sloth.cloud to www.allizom.org. Unfortunately sloth couldn't generate exactly what we wanted for this, so we will need to write a bit of custom code to conditionally return a 302 redirect from https://www.allizom.org/en-US/firefox/new/ to https://www.allizom.org/en-US/exp/firefox/new/ a small percentage of the time while preserving query params. We plan on working on this together again on Monday.

**Comment by alexgibson** [comment]
I wrote some pseudo-ish code that could serve as a redirector here: https://gist.github.com/alexgibson/3425f57088d6fde02b6f0797eb738e08

This is aimed at the browser, but hopefully something we can adapt easily enough for a worker environment.

**Comment by alexgibson** [comment]
Both myself and @jgmize paired on another session today and we we're able to modify the code linked above in the gist to run in a cloudflare worker. We spent some time testing the redirector on stage and it seemed to be performing as expected.

Next steps:

- I'm going to tidy the code up and perform some more testing on stage.
- Once I'm happy that it's doing the right things, we're going to commit this boilerplate code to version control (in bedrock).

Once the above is complete, I think we're good to do a full end-to-end experiment test on stage.

**Comment by pmac** [comment]
My apologies for this tangent, but this talk of cloudflare workers has me curious: could such a worker be a better solution for our GEO redirects for whatsnew and others? Can a worker use the country of request origin as a data point in its logic?

**Comment by jgmize** [comment]
@pmac yes, there's an example of doing exactly that here: https://developers.cloudflare.com/workers/templates/?q=count

**Comment by pmac** [comment]
Nice. I'm interested to see how the development and deployment automation for CF workers goes then. It'd be a nice way to accomplish these kinds of things, and much more compatible with moving to a more static deployment w/o sacrificing features.

**Comment by alexgibson** [comment]
We set up a new repo called www-workers, and I've submitted a PR for the redirector code: https://github.com/mozmeao/www-workers/pull/1

**Comment by alexgibson** [comment]
The code for this now lives at https://github.com/mozmeao/www-workers and is running on stage. @jgmize still has some infra work to do with automation in that repo, which is detailed here: https://github.com/mozmeao/www-workers/issues/2

On that basis, I'm going to close this particular issue and followups can be discussed in the www-workers repo.
