### ISSUE TITLE
Update Browser logo for Fx70 (2019-10-22) 

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7656]
## Description

The new browser logo will launch for "release" with Firefox 70 on Oct 22. We should be ready to publish the new logo before that.

---

#### Tasks
- [x] Inventory current logo use
- [x] Determine what sizes and formats are needed for each asset
  - [x] Sizes https://github.com/mozilla/protocol-assets/issues/32
  - [x] Formats https://github.com/mozilla/protocol-assets/issues/27
- [x] Add sizes and formats to protocol-assets https://github.com/mozilla/protocol-assets/pull/36
- [x] Update Protocol to consume new version of protocol-assets https://github.com/mozilla/protocol/pull/491
- [x] Update bedrock to consume the new version of Protocol #7789 
- [x] Update bedrock to remove old logos and use new ones https://github.com/mozilla/bedrock/issues/7956 ~Blocked on #7863~
- [x] Update structured data to reference logos
- [x] generate favicons with new logo #7889 
- [x] update bedrock to use new favicons #7915

**Comment by stephaniehobson** [comment]
Product's logo inventory:
https://docs.google.com/spreadsheets/d/1hbHhihkm8za4diQ_uaTEvNcd2jWeKlSU7X2_pYtnZcM/edit#gid=0

Bedrock specific logo inventory:
https://docs.google.com/spreadsheets/d/1F-__ZuJIvKGkjsp_vOWiSXSJr5z3xltt3gRXKnLoF3A/edit#gid=0
