### ISSUE TITLE
Move 'fights-for-you' pages into folder

### ISSUE THREAD

**Issue by Errolyn** [mozilla/bedrock#7661]
## Description

Move the three "fights-for-you" pages into their own folder under `/firefox/templates/firefox/` then update the path anywhere that is needed

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] The three fights for you pages are in their own folder
- [ ] The pages are still accessible from the same URL: /en-US/firefox/fights-for-you/

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Links, paths, and URL could be broken

#### Tasks
- [ ] Move `fights-for-you.fr.html`, `fights-for-you.de.html`, `fights-for-you.html` into a folder
- [ ] Update and links or paths pointing to that page

**Comment by craigcook** [comment]
We might be able to decommission these pages.

**Comment by Errolyn** [comment]
@craigcook who should we ask to find out if we can?

**Comment by Errolyn** [comment]
This can be closed because of: https://github.com/mozilla/bedrock/issues/7670
