### ISSUE TITLE
Decommission fights-for-you

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7670]
## Description

We no longer drive traffic to the fights-for-you page, and it's not doing much work, and it's going out of date. We should decommission the page and redirect traffic to /firefox.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] In all active locales, a visitor to /firefox/fights-for-you will be permanently redirected to /firefox
- [ ] Content, routes, tests and assets specific to this page are removed from Bedrock

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by rraue** [comment]
No seo value found besides incoming links, if we redirect to /firefox/ it will be good to delete.

**Comment by Patil2099** [comment]
@hoosteeno Can I work on this issue?
