### ISSUE TITLE
WNP 70 code

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7677]
## Description

Code the WNP 70 page.
Epic - https://github.com/mozilla/bedrock/issues/7678

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is live in Production October 11

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Code it

**Comment by hoosteeno** [comment]
Like the protection report page, this page will have 3 states to determine the CTA:

For Firefox 70+: See what Firefox has blocked for you (uses [a new uiTour function](https://bugzilla.mozilla.org/show_bug.cgi?id=1577031) to open a newtab)
For Firefox <70: [Update your Firefox browser](https://support.mozilla.org/kb/update-firefox-latest-release)
For non-Fx: [Download the Firefox browser](https://www.mozilla.org/firefox/download/thanks/) 

The first two of these should be instrumented with our Generic CTA datalayer attributes. The third is instrumented already. @sghoseWI do you agree about this? Do you have ideas for the actual attribute values?

**Comment by amychurchwell** [comment]
![image](https://user-images.githubusercontent.com/30483988/65799997-442a2700-e12a-11e9-88d6-6d4a6e6686f9.png)
(design for my quick reference.)

**Comment by hoosteeno** [comment]
We need localized strings in fr/de. @ejregithub can you help us keep this moving?

**Comment by ejregithub** [comment]
@hoosteeno - yes, the card in Airtable is for just that  - https://airtable.com/tbl05XxAo8cjqzcvY/viw9kla3Mmk5qMErn/recCbq6Mccece15dL  - I've added you to the Slack channel #marketing-l10n-requests, where you can see the same request to Anika and Malcolm that I posted yesterday (Sunday).

**Comment by amychurchwell** [comment]
instrumentation for reference - https://github.com/mozilla/bedrock/issues/7742

**Comment by cgonz0** [comment]
@amychurchwell  **Design feedback below**
UI is looking awesome - please let me know if you have any questions or need me to clear anything up.
___________________________________

**Conditional content -- Signed in/Signed out of Firefox account:**

- Currently, for both: 
_Have you checked out Firefox Monitor? It’s included with your Firefox account. 
Button: “Sign Up for Monitor”_

- Should be:
Signed in: _Have you checked out Firefox Monitor? It’s included with your Firefox account. Button: “Sign in”_
Signed out: _Have you checked out Firefox Monitor? Button: “Sign Up for Monitor”_

- Link direction seems to be correct, just text fix.

___________________________________

**Conditional content -- Browser version**

- Firefox < 70 —> “Update your Firefox browser” √ looks good
- Firefox 70+ —> “See what Firefox has blocked for you” √ - should this open new tab as referenced above?

- Edge case for non Firefox users - “Download Firefox browser” √  
I don't think we specified header/cta - very rare case, just documenting here. Currently displaying:
"Have you checked out Firefox Monitor? It’s included with your Firefox account" no CTA.

___________________________________

**UI**

- Can we keep the background img centered, instead of to the left - and have it take up full width?
background-size: 100% on .content-wrapper and remove background-position.

- Since the columns for the content below the emphasis box are a bit narrower than the mockup, I think we should give it a little more breathing room in between. Can we bump up the padding to 0px 20px; on .c-picto-block?

- Don’t think we need bold + outline on links - can we remove bold font-weight?


**Breakpoint 767px**

- Line-length a bit too wide - can we add padding: 0 48px; to .c-picto-block for this breakpoint and below?

__________________________________

**Additional notes**

- How to test page with protection report link? Non locale.

**Comment by hoosteeno** [comment]
> Edge case for non Firefox users - “Download Firefox browser” √
> I don't think we specified header/cta - very rare case, just documenting here. Currently displaying:
> "Have you checked out Firefox Monitor? It’s included with your Firefox account" no CTA.

We usually don't plan on this edge case on the Whats New page. If it's already coded, then we should make it behave exactly like the signed out user: 
> Signed out: Have you checked out Firefox Monitor? Button: “Sign Up for Monitor”

**Comment by amychurchwell** [comment]
@hoosteeno speaking of edge cases, it has become increasingly unclear why we are including the conditional for non-firefox users. Can we remove this conditional?

**Comment by hoosteeno** [comment]
> @hoosteeno speaking of edge cases, it has become increasingly unclear why we are including the conditional for non-firefox users. Can we remove this conditional?

We originally agreed that having a public web page with a CTA (go to your protection report) that doesn't work for some user agents was not good practice. That seems like a reasonable target to me; do you agree?

An acceptable way to address this would be the one I suggest in https://github.com/mozilla/bedrock/issues/7677#issuecomment-539281791, which is to reduce our cases to 2, and pick the one most suitable for non-Fx users: 
* They are not syncing, so non-sync messaging ("Sign Up" instead of "Sign In")
* They are not in Fx, so non-UITour messaging ("Go to SUMO to learn how to update Firefox")

If this is substantially easier to implement, it's OK with me. But if it requires special coding for non-Fx users, then encouraging such users to do something more appropriate seems better, no?

**Comment by amychurchwell** [comment]
@cgonz0

> Can we line up the sub-header with the columns (max-width: 640px) and reduce font-size (1rem)? Please also unbold links on the 2 columns.

Yes, all but reducing font-size that small. Makes it too difficult to read for a heading.

**font-size: 1.5rem;**
![Screen Shot 2019-10-08 at 5 40 55 PM](https://user-images.githubusercontent.com/30483988/66443164-de278480-e9f2-11e9-9c78-fb43654a586d.png)

**font-size: 1rem;**
![Screen Shot 2019-10-08 at 5 42 09 PM](https://user-images.githubusercontent.com/30483988/66443198-fac3bc80-e9f2-11e9-887c-1f7897adf271.png)

**Comment by amychurchwell** [comment]
also,
> Currently, for both:
Have you checked out Firefox Monitor? It’s included with your Firefox account.
Button: “Sign Up for Monitor”

is not so:

![Screen Shot 2019-10-08 at 6 05 12 PM](https://user-images.githubusercontent.com/30483988/66444006-53e11f80-e9f6-11e9-8612-812222e0167c.png)

you should get expected behavior now that ui tour is setup in your about:config. 😄

**Comment by ejregithub** [comment]
@amychurchwell - please apply a size estimate for this work

**Comment by cgonz0** [comment]
> @cgonz0
> 
> > Can we line up the sub-header with the columns (max-width: 640px) and reduce font-size (1rem)? Please also unbold links on the 2 columns.
> 
> Yes, all but reducing font-size that small. Makes it too difficult to read for a heading.

> **font-size: 1rem;**
> ![Screen Shot 2019-10-08 at 5 42 09 PM](https://user-images.githubusercontent.com/30483988/66443198-fac3bc80-e9f2-11e9-887c-1f7897adf271.png)

@amychurchwell ^the smaller font size here is ok. it should be de-emphasized and smaller than the column headers. maybe sub-header is a misnomer. here's the original design below - i think it works better at this size.

<img width="647" alt="Screen Shot 2019-10-09 at 10 55 38 AM" src="https://user-images.githubusercontent.com/29640968/66507280-be8c6c80-ea83-11e9-890f-799393811e65.png">

**Comment by cgonz0** [comment]
> also,
> 
> > Currently, for both:
> > Have you checked out Firefox Monitor? It’s included with your Firefox account.
> > Button: “Sign Up for Monitor”
> 
> is not so:
> 
> ![Screen Shot 2019-10-08 at 6 05 12 PM](https://user-images.githubusercontent.com/30483988/66444006-53e11f80-e9f6-11e9-8612-812222e0167c.png)
> 
> you should get expected behavior now that ui tour is setup in your about:config. 😄

@amychurchwell  thanks for the help in setting it up! i'm now seeing the correct Button text for both, but the signed out version is showing _"Have you checked out Firefox Monitor? It’s included with your Firefox account"_ The second line: **It’s included with your Firefox account** should be removed for this version

**Comment by ejregithub** [comment]
This is live, closing
