### ISSUE TITLE
WNP 70

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7678]
## Description

The /whatsnew page to be shown at the 70 release to users updating their browser from <70.0

[Master Project Doc](https://docs.google.com/document/d/1Z73EAgTGSqzeE7xQxayqq114ThQMUGEeh389jFgWp8g/edit)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Is live by Oct 10 to allow time for QA (external) testing
- [ ] Uses a/the modular design 

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by amychurchwell** [comment]
Code issue - https://github.com/mozilla/bedrock/issues/7677
