### ISSUE TITLE
Update the banners at the top and bottom of the homepage

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7684]
## Description

Update the banners at the top and bottom of the homepage in all Teir 1 languages.

Assets will be attached to [this Trello card](https://trello.com/c/dK19hesi/538-web-work-coding-new-headers-on-mozorg-in-en-de-and-fr-3) in the NA Firefox Brand team's sprint board.

[Bug 1569237](https://bugzilla.mozilla.org/show_bug.cgi?id=1569237)

---

#### Tasks
- [x] Update all strings
- [x] Remove old assets
- [x] Add new assets
- [x] Tweak typography
- [x] String change on /accounts to support the "family" language change.

**Comment by stephaniehobson** [comment]
On [demo/6](https://bedrock-demo-6.oregon-b.moz.works/)
