### ISSUE TITLE
Pull Firefox Private Network privacy notice and legal terms from legal-docs repo

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7687]
## Description

In https://github.com/mozilla/bedrock/pull/7686 we hard-coded the privacy notice and legal terms for Firefox Private Network due to confidentiality rules and a hard release time.

- https://www.mozilla.org/en-US/privacy/firefox-private-network/
- https://www.mozilla.org/en-US/about/legal/terms/firefox-private-network/

We should port these two pages to pull from the [legal-docs repo](https://github.com/mozilla/legal-docs/), once the content for both pages exists there. This is a blocker to exposing localized versions of these pages.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Pages are updated in production to pull from legal-dcos repo.

#### Tasks
- [ ] Remove hard-coded template content.
- [ ] Generate replacement content from markdown in legal-docs submodule.

**Comment by mitchell-frost** [comment]
If it is open, can I work on this?

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/issues/9120
