### ISSUE TITLE
Define a process for facilitating CRO experiments

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7688]
## Description

As part of epic https://github.com/mozilla/bedrock/issues/7504, we're working on implementing a conversion rate optimization (CRO) tool for our main landing pages. Before we can start using that tool, we need to establish a clearly defined process by which expeirments are to be run. This probably needs to include things like:

- An intake and approval process for experiment ideas.
- An implementation process for approved experiments.
- QA process (code review, testing on stage, launching on prod).
- Reporting process (ending an experiment, publishing reports, defining next steps).

This issue is to track discussion for how the above will work, and once agreed, to have it clearly documented and published.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Process is agreed upon by both stakeholders and the websites team.
- [x] Process is documented.

#### Tasks
- [x] Produce a document defining the process.
- [x] Publish it (where TBD).

**Comment by alexgibson** [comment]
Process doc is being formulated here (Mozilla access only) https://docs.google.com/document/d/1SK4DZWFfKsJjFcs-hkrx_3crfwMQrbtP7LBgqt0bBaw/edit

**Comment by alexgibson** [comment]
The process for creating experimental pages on bedrock, as well as code reviewing Convert experiments, has been documented here: https://bedrock.readthedocs.io/en/latest/abtest.html
