### ISSUE TITLE
Transform /firefox into a landing page for all Firefox products.

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7696]
## Description

We're transforming /firefox into a landing page for all Firefox products.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] New design and copy are live at /firefox by Oct 22

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] L10N story is still a big ❓ 

#### Tasks
- [x] Re-name old template and assets to avoid confusion with new one
- [x] Add Menu List to Protocol
- [x] Add Inline List to Protocol 
- [x] Add strings in components
- [x] Add custom page styling

**Comment by stephaniehobson** [comment]
This is mostly a mirror of the Trello card [where I am tracking my work](https://trello.com/c/Cvkyn7Jt/593-firefox-dev).

**Comment by dzingeek** [comment]
@stephaniehobson see feedback below..btw this is looking amazing! 

**Hero section:**
Space above and below the image feels too much. Especially on larger screens. Can we tighten them up some. Maybe centering the text might help?
![Screen Shot 2019-09-25 at 4 43 00 PM](https://user-images.githubusercontent.com/3740746/65647731-639f4380-dfb4-11e9-944f-54bc6cc38383.png)


**"Get the respect" section:**
The “Get the respect you deserve” callout jumps to full viewport width at smaller breakpoints: Can we keep some white space on both sides for all breakpoints?  
![Screen Shot 2019-09-25 at 4 43 25 PM](https://user-images.githubusercontent.com/3740746/65647626-11f6b900-dfb4-11e9-95a1-f83cbd40f7e8.png)
![Screen Shot 2019-09-25 at 4 43 35 PM](https://user-images.githubusercontent.com/3740746/65647627-11f6b900-dfb4-11e9-8c51-6507b9e93e85.png)

on mobile view the card no longer has the shadow
![Screen Shot 2019-09-25 at 4 43 42 PM](https://user-images.githubusercontent.com/3740746/65647628-11f6b900-dfb4-11e9-974c-ba68a0c4d2c5.png)

**Copy Sections:**
The text boxes feel too wide which has me worried for longer blocks of text. Now that I know that component is based on max width of the site (1420) let's talk about maybe making the sites max-width smaller for protocol. I will reach out to Stephen H. to see what product does for their sites.
![Screen Shot 2019-09-25 at 4 43 14 PM](https://user-images.githubusercontent.com/3740746/65647568-00adac80-dfb4-11e9-82a5-7417994ceb73.png)




**Assets:**
Updated assets coming tomorrow

**Comment by dzingeek** [comment]
@stephaniehobson here are two updated SVGs for /firefox. Also, I am still waiting on the hero image (pending financial approval)...will get you that as soon as I can.

[updated svgs - outlines.zip](https://github.com/mozilla/bedrock/files/3672446/updated.svgs.-.outlines.zip)

**Comment by stephaniehobson** [comment]
Design review changes made. (but I did too good a job removing white space around the hero and need to add a bit back).

L10N will be coming from the EU team, I need to talk to them about if it's going through Pontoon first or not.

**Comment by dzingeek** [comment]
@stephaniehobson updated hero img + 2 other svgs. this should do it!!

[fx-hmpg-imgs.zip](https://github.com/mozilla/bedrock/files/3683915/fx-hmpg-imgs.zip)
