### ISSUE TITLE
Lifecycle Page #2 - Pocket

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7698]
## Description

Launch the 2nd Lifestyle page with content promoting Pocket

Refer to the cards in  #7557 for more background

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] [Copy](https://docs.google.com/document/d/1QA517lcRfjKWKqmrIjBVnwLJumHSNPRKoaZ5JYwCARk/edit#heading=h.oo63piaiuqi8)
- [ ] UI/Design
- [ ] Team QA 
- [ ] Team Lead QA/signoff
- [ ] Stakeholder QA of design & copy
- [ ] Analytics
- [ ] Code 
- [ ] Page on demo
- [ ] Stakeholder QA of page on demo
- [ ] Code review

**Comment by alexgibson** [comment]
All dependencies for this epic are completed, closing.
