### ISSUE TITLE
Testing breadcrumps on /new

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#7699]
## Description

Google displays for quite a while on mobile breadcrumps instead of urls in search results and now started this on desktop as well. Because of the uniqueness of the /new url the breadcrump looks right now a bit confusing for users:

<img width="577" alt="Screenshot 2019-09-11 at 13 26 51" src="https://user-images.githubusercontent.com/36700618/64693675-15f4e800-d498-11e9-82a4-33522cf75024.png">

We should test, if we can shape this by the [breadcrump structured data for rich snippets](https://developers.google.com/search/docs/data-types/breadcrumb). We should test it only on /en-US/  for now. And we need to make sure, that the code is not included in the campaign pages and not in /mac, /windows and /linux.

Code:
`<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [{
    "@type": "ListItem",
    "position": 1,
    "name": "Mozilla",
    "item": "https://www.mozilla.org"
  },{
    "@type": "ListItem",
    "position": 2,
    "name": "English",
    "item": "https://www.mozilla.org/en-US/"
  },{
    "@type": "ListItem",
    "position": 3,
    "name": "Firefox",
    "item": "https://www.mozilla.org/en-US/firefox/"
  },{
    "@type": "ListItem",
    "position": 4,
    "name": "Desktop Download",
    "item": "https://www.mozilla.org/en-US/firefox/new/"
  }]
}
</script>`

If the test is succesful, we can roll it out to other locales and more pages, but for now, the easiest way is to hard code it in the page, as it could be that for the breadcrump we need not just the structured data but an actual visible breadcrump on the page. This test will inform us about this. 

If the test is succesful and the defined breadcrump will show up in search results, @rraue will analyse the ctr in serps via search console.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] The code is live on /en-US/firefox/new/ 

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [x] The code must not be included in other locales than en-US
- [x] The code must not be included in /mac, /windows, /linux or any campaign page

#### Tasks
- [x]  Coding
- [ ] Historical Analysis of CTR change in SC
