### ISSUE TITLE
Update websites privacy notice

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7700]
## Description

Our [websites privacy notice](https://www.mozilla.org/en-US/privacy/websites/) needs updating to reflect the Convert CRO tool being implemented in #7508.

The current privacy policy still talks about Optimizely, which is a tool we no longer use. We should update it to reference [Convert](https://www.convert.com/), and also detail the [opt-out mechanism](https://www.convert.com/opt-out/) that people can use, if they don't want to take part in experiments.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Websites privacy policy is updated to reflect the above changes.

#### Tasks
- [ ] Seek assistance from legal to update the privacy notice.
- [ ] Once changes are in legal-docs, update bedrock to pull the latest copy.

**Comment by alexgibson** [comment]
Also: we may want to consider building an opt-out URL on www.mozilla.org for this, as the opt-out link on https://www.convert.com/opt-out/ only applies to their own domain. 

Building a page on bedrock for this should be relatively straight forward.

**Comment by stephaniehobson** [comment]
Do/can we honour DNT with convert?

**Comment by alexgibson** [comment]
> Do/can we honour DNT with convert? 

Convert already honors DNT, and is fully GDPR compliant.

**Comment by stephaniehobson** [comment]
I guess I'm wondering if we can avoid loading convert at all for people with DNT. Or if we don't think it's necessary because they honour DNT?

**Comment by alexgibson** [comment]
We’re doing that also 👍

**Comment by hoosteeno** [comment]
https://github.com/mozilla/legal-docs/pull/1311

**Comment by alexgibson** [comment]
The privacy notice source has been updated. I'm pulling that into bedrock as part of https://github.com/mozilla/bedrock/pull/7702
