### ISSUE TITLE
COPY -  (firefox/privacy/products) Protection Report Landing Page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7706]
## Description

The copy is being written by the Brand Team but we need to shepherd the process and convert the copy (for DE and FR) in an acceptable localization template.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Copy is stakeholder approved ([check for this in the copy doc](https://docs.google.com/document/d/1khFCkPtMVI5Miy-Fxefka0ylZA1YoQLSvMQRG4aA1Fw/edit#))

#### Tasks
- [x] Shepherd copy creation using Websites team copy template
- [ ] Move copy to localization doc template and provide to Staff for DE and FR

**Comment by alexgibson** [comment]
Copy doc: https://docs.google.com/document/d/1S4MtBCqxvvkZspKu3i4GthY3lrOC40yubpWgqgmEVB0/edit?usp=sharing

**Comment by ejregithub** [comment]
@alexgibson - the above is not the correct copy doc.  This one is - https://docs.google.com/document/d/1khFCkPtMVI5Miy-Fxefka0ylZA1YoQLSvMQRG4aA1Fw/edit?usp=sharing

The original was not in our copy template and including copy for both this and the /firefox/privacy page as well.

**Comment by alexgibson** [comment]
I have some brand related copy questions for @dzingeek that may impact L10n for this page:

- Should "Firefox browsers" be localized, or are we treating it like a product name (it appears as a wrod-mark in the page design).
- In strings such as "Download the Firefox browser" and "Update your Firefox browser", should "Firefox browser" be localized? (I'm assuming yes in the context of a sentance, but double-checking).
- In "Get Enhanced Tracking Protection", should "Enhanced Tracking Protection" be localized?

I'm not going to localize the following strings as they are more easily identifiable product names:

- Firefox Monitor
- Firefox Lockwise
- Firefox Send
- Pocket

**Comment by alexgibson** [comment]
L10n string extraction for this page is blocked on the questions above, plus the question in the copy doc about "Add Lockwise to Firefox”.

**Comment by dzingeek** [comment]
@alexgibson these are great questions that I, unfortunately, don't have the answer to. I have some guesses on what we should but let me see if I can track down an answer for you.

**Comment by dzingeek** [comment]
@alexgibson had a quick convo with clio, stephen and tim...this is what was decided. 

> "... logos shouldn't be localized. Any other application that refers to the browser in copy and or CTA could be localized."

does that answer your questions?

**Comment by alexgibson** [comment]
> does that answer your questions?

The "could be localized" part here sounds pretty vague to me. Whilst this does provide some direction (I'm inferring from this that "Firefox browsers" where it appears as a wordmark should not be localized), it would be great to have a more formal rule set defined somewhere (I'm looking at https://mozilla.design/firefox/logos-usage/ specifically).

**Comment by dzingeek** [comment]
Still looking into this for more clarification and i will also note that we need more formal rules defined. I think the issue is we don't really want to use the word Browsers with Firefox but we still don't have a name for the browser. 

Will let you know what else I find out. I would suggest (for now) copy in a logo lockup stays as is and copy in text (button or body copy) gets localized.

**Comment by dzingeek** [comment]
It's been confirmed, if with the logo (so lockup) it **does not** get localized but if it's in text (body copy or button) then the word "browser(s)" **does** get localized. 

does this help clear things up? also talking with tim and others to see how we can better document this.

**Comment by alexgibson** [comment]
@ejregithub copy here is all done I believe, can we close this issue?
