### ISSUE TITLE
 (privacy/products) Protection Report Landing page instrumentation plan

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7710]
## Description

Create an instrumentation & measurement plan for the Protection Report Landing page. It can probably just use the generic CTA datalayer elements for event tracking.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Can measure sessions/conversions on the page

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Build analytics plan
- [ ] Inform dev for in page requirements
- [ ] Analyze initial launch period & determine next steps (recommended changes, if any)

**Comment by alexgibson** [comment]
@sghoseWI these pages are now on demo and ready for instrumentation:

- https://www-demo1.allizom.org/en-US/firefox/privacy/
- https://www-demo1.allizom.org/en-US/firefox/privacy/products/

**Comment by sghoseWI** [comment]
DRAFT Instrumentation Plan". 

Privacy Products:

For any and all FxA-like-things (e.g. Monitor) referrals, pings, flow begins, etc:
utm_source=www.mozilla.org-privacy-products
utm_campaign=privacy-products
utm_medium=referral

On Offsite links only (not on any onsite links):
utm_source=www.mozilla.org-privacy-products
utm_campaign=privacy-products
utm_medium=referral

On FxA creation button: 
data-cta-type=“fxa-sync”
data-cta-position=“primary"


entrypoint = mozilla.org-privacy-products

**Comment by sghoseWI** [comment]
@hoosteeno Would you please review the above when you have a moment?

**Comment by alexgibson** [comment]
> On FxA creation button:
> data-cta-type=“fxa-sync”
> data-cta-position=“primary"

This is currently implemented site-wide as:

```
data-cta-type="FxA-Sync"
data-cta-text="Register"
data-cta-position="Primary"
```

Are we saying we want to change this to lowercase everywhere (on every page?)

**Comment by alexgibson** [comment]
> utm_source=www.mozilla.org-privacy-products

On every other page of the website we use `mozilla.org-*` (no `www.` prefix). Is this an intentional change?

**Comment by alexgibson** [comment]
Last question: do we need additional analytics on the "See what Firefox has blocked for you" and "Update your Firefox browser" links?

**Comment by sghoseWI** [comment]
> > utm_source=www.mozilla.org-privacy-products
> 
> On every other page of the website we use `mozilla.org-*` (no `www.` prefix). Is this an intentional change?

Let's remove the prefix -- I'll make that change to future analytics plans as well.  Thanks for pointing this out.

**Comment by sghoseWI** [comment]
> > On FxA creation button:
> > data-cta-type=“fxa-sync”
> > data-cta-position=“primary"
> 
> This is currently implemented site-wide as:
> 
> ```
> data-cta-type="FxA-Sync"
> data-cta-text="Register"
> data-cta-position="Primary"
> ```
> 
> Are we saying we want to change this to lowercase everywhere (on every page?)
> 
> Should these also be `secondary` for position, seeing as they aren't in the main hero?

@hoosteeno and I chatted about standardizing all parameters so that they are all lowercase moving forward.  The reasons we had for this suggestion are:
1. Easier for devs
2. Harder to mess up 
3. Removes one factor in hard-to-find bugs
4. As a data customer on the analytics end, it makes it easier to find all relevant data for an analysis/experiment (some of which might be missed otherwise). 

Let me know if this rational doesn't make sense to you.  We can certainly revisit with @hoosteeno 's input too.
-----------------
In terms of primary vs. secondary, I think you are correct.  Let's go with secondary for anything that is not a _main_ action we are trying to drive and/or is not featured as prominently as the _primary_  CTAs.
-----------------
And on your last question about "do we need additional analytics on the "See what Firefox has blocked for you" and "Update your Firefox browser" links?"  --- I'll reach out to you on Slack before giving my thoughts (and will update the notes here once we've had a chance to discuss).

**Comment by alexgibson** [comment]
> @hoosteeno and I chatted about standardizing all parameters so that they are all lowercase moving forward.

Ok, I've changed this in the macro to be lowercase. Please note that this will effect all instances of the FxA form on all pages of the website.

**Comment by alexgibson** [comment]
> I chatted with Justin about this and we do not need additional data attributes on this. We need to trigger a generic CTA click -- which he said is "accomplished under the hood with a dataLayer.push().

Ok, I'm suggesting the following. Let me know if you need something else:

```
window.dataLayer.push({
    'event': 'in-page-interaction',
    'eAction': 'link click',
    'eLabel': 'See what Firefox has blocked for you'
});
```

**Comment by alexgibson** [comment]
@sghoseWI Ok I think everything above should be in place for this page. Can you please take a look to confirm? Thanks

**Comment by hoosteeno** [comment]
> Ok, I'm suggesting the following. Let me know if you need something else:
> 
> ```
> window.dataLayer.push({
>     'event': 'in-page-interaction',
>     'eAction': 'link click',
>     'eLabel': 'See what Firefox has blocked for you'
> ```

Is there a reason not to implement this as a [generic CTA](https://github.com/mozilla/bedrock/issues/7541)? 

E.g. 
```
data-cta-type="uitour-protection-report" 
data-cta-position="secondary"
```

**Comment by alexgibson** [comment]
@hoosteeno I was asked to use a dataLayer.push() here, but I'm happy to use anything set forth in the spec. I'll take what you suggest.

**Comment by alexgibson** [comment]
Actually, there is a good reason to use a dataLayer.push(), since the three ETP items underneath the main hero are also clickable for opening about:protections (but they aren't regular links).

**Comment by sghoseWI** [comment]
@alexgibson After review, the params look good to me -- thanks!

**Comment by alexgibson** [comment]
Closing this as done
