### ISSUE TITLE
Firefox header and footer

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7711]
## Description

Add a Firefox specific navigation and footer.

<img width="759" alt="Screen Shot 2019-09-11 at 2 17 39 PM" src="https://user-images.githubusercontent.com/854701/64736202-f8774c80-d49e-11e9-8d3c-de3e6dcebc1e.png">

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Pages in /firefox have a Firefox specific header (Tier 1 locales)
- [ ] Pages in /firefox have a Firefox specific footer (Tier 1 locales)
- [ ] Nav is localized by the community and can be rolled out to more locales once ready
- [ ] Browsers and Products pages can be activated in nav once they are ready

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Localization of global elements is complicated
- [ ] Products and browsers landing pages will not be done before localization needs to begin

#### Tasks
- [x] Move the current header into it's own namespace
- [x] Firefox header & navigation
- [x] Firefox footer
- [x] Add to Firefox pages
- [ ] String extraction

**Comment by stephaniehobson** [comment]
Copy doc: https://docs.google.com/document/d/1E4SaL1quIoO-E2Z9Lb6nLX4JqSPsT26nIGi8CELi9Qs/edit#heading=h.vvqh5av6uul

**Comment by stephaniehobson** [comment]
Rough timeline:
- Sept 10th: English copy & all image assets delivered
- Sept 13th: demo ready for approvals
- Sept 16th: sign off
- Sept 17th: string extraction & code review
