### ISSUE TITLE
Build Convert opt-out page in sandbox

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7714]
## Description

Build an opt-out page for Convert.com opt outs, which will come in with the URL

https://www.mozilla.org/exp/opt-out/?convert_optout=1

If this page loads Convert, then the parameter at the end will opt the user out. 

The opt-out may pop open a Javascript confirmation. If it does not, we should build some confirmation into the page.

See also: https://github.com/mozilla/bedrock/issues/7700

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Opt out page is built

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by alexgibson** [comment]
i can take care of this as part of #7508

**Comment by alexgibson** [comment]
Thank you, updated

**Comment by hoosteeno** [comment]
See also https://github.com/mozilla/bedrock/pull/7702

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/bedrock/pull/7702
