### ISSUE TITLE
Update bedrock to @mozilla-protocol/core v8.1.0

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7734]
## Description

Protocol 8.1.0 is out: https://www.npmjs.com/package/@mozilla-protocol/core

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Bedrock is updated in production to use the latest Protocol version.

#### Tasks
- [x] Update NPM dependency.
- [x] Update pages / templates where needed.

**Comment by alexgibson** [comment]
A few things to note:

- We now have the [emphasis box](https://protocol.mozilla.org/patterns/molecules/emphasis-box.html).
- We have a new [narrow content theme modifier](https://protocol.mozilla.org/patterns/templates/content-layout.html) (I don't think we've used this anywhere yet, but there are many pages with custom narrow styles that could do with standardizing):

Other changes here: https://github.com/mozilla/protocol/blob/master/CHANGELOG.md#810
