### ISSUE TITLE
Lifecycle #1 page analysis

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7744]
## Description

The Lifecycle page #1 will require performance analysis post-launch

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Session-to-register and session-to-login is clear
- [ ] 7-day retention is clear
- [ ] Comparison with recent WNP 

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by hoosteeno** [comment]
Here is a quick take on early returns for welcome page 1. Since it contains raw data from analytics tools, it is Mozilla Staff only.  https://docs.google.com/spreadsheets/d/1pu92rWobk3GYWYAVjheY95k0bkX1M8CfJJpehcfPezA/edit#gid=1955448126

**Comment by sghoseWI** [comment]
Here is an initial analysis report re: early performance on the first moments page: 
https://docs.google.com/document/d/1d8ooHPknKid-fqw2ukNNPHPR9xutvDhAC8RnEP2PEug/edit
