### ISSUE TITLE
UI/Design - /firefox/privacy/ - Privacy Hub page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7763]
## Description

Design tasks, including team lead, stakeholder and code review, for the new Firefox privacy hub page

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Is live, simultaneously, as /firefox/privacy/products
- [ ] Is live prior to/at Skyline on Oct 22

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] --

#### Tasks
- [ ] Design the page (apply to wireframes from #7762 )
- [ ] Funcational Team review as required
- [ ] Team Lead review in Miro board
- [ ] Stakeholder review in Miro board
- [ ] Provide design files, Sketch/Abstract to dev via #7765

**Comment by ejregithub** [comment]
@mrkwvr - when you can, please apply an Estimate to provide size for this work

**Comment by alexgibson** [comment]
We have final design files and assets for this page now, closing.
