### ISSUE TITLE
Analytics - /firefox/privacy/ - Privacy Hub page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7764]
## Description
Create an instrumentation & measurement plan for the Firefox Privacy Hub page. It can probably just use the generic CTA datalayer elements for event tracking.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Is live, simultaneously, as /firefox/privacy/products
- [ ] Is live prior to/at Skyline on Oct 22

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] --

#### Tasks
- [ ] Design the page (apply to wireframes from #7762 )
- [ ] Funcational Team review as required
- [ ] Team Lead review in Miro board
- [ ] Stakeholder review in Miro board
- [ ] Provide design files, Sketch/Abstract to dev via #7765

**Comment by sghoseWI** [comment]
DRAFT Instrumentation Plan:

Privacy Hub (looks like there are no buttons on this page outside of the header):

On Offsite links only (not on any onsite links):
utm_source=www.mozilla.org-privacy
utm_campaign=privacy
utm_medium=referral
entrypoint = “mozilla.org-privacy”

**Comment by alexgibson** [comment]
```
utm_source=www.mozilla.org-privacy
utm_campaign=privacy
utm_medium=referral
entrypoint = “mozilla.org-privacy”
```

I believe both utm_source` and `entrypoint` should always be the same? If so, I'd suggest we drop the `www.` prefix on utm_source.

**Comment by sghoseWI** [comment]
@alexgibson I agree, that makes sense.  Let's drop the www. prefix on utm_source.

**Comment by alexgibson** [comment]
Closing this as done
