### ISSUE TITLE
/firefox/privacy/ - Privacy Hub page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7766]
## Description

The hub main/landing page for Firefox Privacy. 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page uses[ this copy](https://docs.google.com/document/d/1khFCkPtMVI5Miy-Fxefka0ylZA1YoQLSvMQRG4aA1Fw/edit#heading=h.2o8h97r5u6gs) from the Brand Team

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by dzingeek** [comment]
@stephaniehobson I wanted to give you an update on where we are at and an updated link to the sketch file. 

**Design:** 
- general design direction is good, there is still some work to do on images and james is doing some spot illustrations but he is OOO until tuesday. 

**Sketch File:** 
- [link to the latest file](https://share.goabstract.com/36cde4df-0cb7-432b-8d70-eee3e613a198?sha=bda284235640424fb34dda1008d6666b8a8be776)
- artboards can be found on **/firefox/privacy/** under pages
- please open sketch file, I have started to spec things out which live outside of the artboard (see attached img for reference)
- I have also started early designs for breakpoints

**other notes:**
- I will continue on design tweaks/images on monday
- As soon as I have assets I will package them up and add them to this issue
- Let me know when you are ready to start work on this and I can walk you through the sketch file. 

![Screen Shot 2019-09-20 at 3 10 35 PM](https://user-images.githubusercontent.com/3740746/65364201-14789d80-dbc5-11e9-931d-ac51e5f10fd1.png)

**Comment by dzingeek** [comment]
@alexgibson [sketch file](https://share.goabstract.com/27ed31d2-c719-48c2-bb35-9a2792eb38df?sha=2faced350a4a5114e7b428b490b4c7f53618aa3c) has been updated to reflect more specs + all breakpoints. Also, attaching images/assets... but they are still FPO as we need sign-off to purchase some of them, but these should help you get things further along. Thanks!

[privacy-hubhmpg-imgs.zip](https://github.com/mozilla/bedrock/files/3649592/privacy-hubhmpg-imgs.zip)

attaching latest png for reference
![fx-privacy-promise-1312](https://user-images.githubusercontent.com/3740746/65553622-1b145700-dedc-11e9-94fe-af4281fe03b5.png)
