### ISSUE TITLE
Remove 2018 firefox/accounts page

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7796]
## Description

I can't find any locales that are active but have not translated the 2019 page. Which means the 2018 page `accounts.html` is not being displayed to anyone. We should remove the old page.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Old accounts page is retired

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Am I wrong about the l10n activation status?

#### Tasks
- [ ] Remove `accounts.html` and associated CSS, JS, and assets.
- [ ] Update the `firefox_accounts` view to remove references to it
- [ ] Update tests
