### ISSUE TITLE
Links to 'Download high resolution photo' no longer appear on /about/leadership/

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7839]
## Description

Store and create links to links for leadership images on /about/leadership for MoCo listings.

***Success Criteria***
- [ ] Is live with links for each leader to their individual zip file containing images

***Tasks***
- [ ] Use AWS bucket for .zip files with leadership photos ([zip files here](https://drive.google.com/drive/folders/1AwXSIvQbsl3TK3Qp-BdiP-fSyjqC7evF))
- [ ] Use URL pattern - https://assets.mozilla.net/leadership/firstname-lastname
- [ ] Post blurb "Download photos" and link to each leader's .zip file with photos in their listing on the leadership page

**Comment by craigcook** [comment]
I removed the download links because we weren't provided with high-resolution versions of the new headshots. I know they must exist somewhere, but I was only given 500x500 images. If we can get high res images we can link to them.

**Comment by craigcook** [comment]
High-res, print-ready assets should be 300dpi and a sufficiently large dimension when printed, but it's hard to say exactly what those dimensions should be. A 3000px x 3000px image at 300dpi would print at about 10x10 inches, which is a good size to aim for if we can get it, depending on the source images. 

For reference, the previous high-res photos were 2400x3600 at 300dpi which prints at about 8x12 inches.

**Comment by ejregithub** [comment]
<img width="359" alt="image" src="https://user-images.githubusercontent.com/20547886/67417834-83f3fb00-f57e-11e9-8d09-b5437e14b5e4.png">

Use the same icon, font and text color as previously used in the page but with the new copy "Download photos"

**Comment by craigcook** [comment]
We'll also update the boards of directors while we're at it:
https://blog.mozilla.org/blog/2019/10/24/longtime-mozilla-board-member-bob-lisbonne-moves-from-foundation-to-corporate-board-outgoing-ceo-chris-beard-corporate-board-term-ends/

- [ ] Remove Chris Beard from MoCo board
- [ ] Move Bob Lisbonne from MoFo to MoCo
