### ISSUE TITLE
Determine the fate of /developer/

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7840]
## Description

The [Developer Hub](https://www.mozilla.org/en-US/developer/) page was made ~2 years ago, but has never been updated since. I'm not sure if the team that created are still doing the same kind of work.

Some of the content is evergreen (e.g. pulled from our blog feed), but some of the other content is now pretty outdated.

For example:

- The main hero still talks about "Firefox Quantum: Developer Edition"
- The Developer roadshow section links to https://github.com/mozilla/devroadshow2017

The page is linked in the main navigation, but it was never localized.

The template is odd as it's built on Pebbles, but the CSS is compiled using .less.

We need to decide either to update the page, or to decommission it.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is either updated or decommissioned.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Who owns this page?

#### Tasks
- [ ] Determine the fate of the page.
- [ ] Do something about it.

**Comment by ejregithub** [comment]
@rraue @hoosteeno - the team that owned/worked on this page originally is now defunct and the DevRel team is working on a new website specific to . . . developer relations.  I can't see them supporting this page either.  

I don't know if it would make sense to link off to that new site when it exists or if we simply 301 this /developer/ page to /firefox/developer ?  

The traffic to /developer/ is anemic

![Screen Shot 2019-10-07 at 11 29 00 AM](https://user-images.githubusercontent.com/20547886/66341732-bc4bd600-e8fc-11e9-81cb-fdf5bef6bc3f.png)

**Comment by rraue** [comment]
With this page are coming these two other pages as well: /en-US/developer/css-grid/ and /en-US/developer/browsertest/. We should include them in our thoughts, as they would otherwise be orphaned. 

The css-grid page has some sort of seo value we wouldnt get with just redirecting. Maybe the content would be best suited to move to mdn or a redirect to a fitting page on mdn? 

For /developer/ I agree, we probably should just redirect it to /firefox/developer/ or whichever ne hub the team is building.

The browsertest doesnt seem to have much traffic or influence, but maybe we find a good place to redirect it to as well.

**Comment by alexgibson** [comment]
I believe /developer/browsertest/ was only set up on mozorg because the MDN team didn't have capacity at that time to host the page. It's already completely orphaned. Looking in GA, it gets less than 10 page views per day, and has had < 1500 views in the past year. I think we can redirect this page to MDN at https://developer.mozilla.org/docs/Learn/Tools_and_testing/Cross_browser_testing/Automated_testing

As for developer/css-grid/, this is some nice developer content, but honestly I don't know if mozorg is the right place for it. Again, I think this ended up here because we could accomodate the ask at a particular time. Looking in GA, it gets ~100 views per day. We could keep it, but I think over time the examples will become out of date. MDN is better suited for [this type of content](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grids) imho, as it stands a better chance of being maintained.

**Comment by alexgibson** [comment]
Developer portal is now live https://developer.mozilla.com/
