### ISSUE TITLE
Extract strings -  /firefox update into a landing page for all Firefox products

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7843]
## Description

We're transforming /firefox into a landing page for all Firefox products and string extracted for Tier 1 locales (FRENDE)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Strings are extracted in time for localizers to make launch

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Timing

#### Tasks
- [x] Extract strings - en-US copy can be found [in this spreadsheet, 1st tab, 3rd column](https://docs.google.com/spreadsheets/d/1ZauHdr73MOTh-IFfvIa3fybI8OrkPcogrEtGYWrUE0w/edit?ts=5d9cebf6#gid=757298539)
- [x] Coordinate w. Peiying on PR
- [ ] File Airtable l10n request and ensure staff has copy prior to extraction and are provided links to Pontoon when available

**Comment by craigcook** [comment]
Strings sent to Pontoon in https://github.com/mozilla-l10n/www.mozilla.org/pull/341
