### ISSUE TITLE
(12/3 - 5:15am PT) FPN - Update Term and Privacy pages

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7850]
## Description

Internal (Legal) bug - https://bugzilla.mozilla.org/show_bug.cgi?id=1575696

Updates to the FPN Term and Privacy pages

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Private until FPN is ready to go live
- [ ] Go live when Product (Tony) indicates

#### Tasks
- [ ] Coordinate w. MFeldman on go live plan including timing 
- [ ] Maintain in private repo til launch
- [ ] Merge and launch when Product gives us the go ahead

**Comment by amychurchwell** [comment]
I can pick this up, just need access to the private bug. Marking as blocked.

**Comment by ejregithub** [comment]
Yes, please. Thank you @amychurchwell - I've cced on the bug

**Comment by amychurchwell** [comment]
PR opened in private repo. Blocked until go-live date has been determined.

**Comment by ejregithub** [comment]
@amychurchwell - this is now on for 12/3 go live. Tony indicated final edits were coming forth we expected delivery today (11/18).

**Comment by ejregithub** [comment]
Removing blocker, final edits are available.
