### ISSUE TITLE
Update /new for Skyline

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7851]
## Description

We want update copy to be inline with Skyline marketing efforts. The new copy and addition of new product icons intends to put the /new page in line with Skyline brand and Product branding.

The intent is to launch as some sort of (TBD) experiment

Hypothesis: If we update the copy and icons on the /new page, we will have a net neutral or positive effect on CTR, because we will inform users about new benefits available in Firefox.

[Copy doc](https://docs.google.com/document/d/1XBtyYBJD_Ly_OKf2iLCdvjYPkyy6xe_6RZTjEDBaoPs/edit)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Page includes new content
- [x] Page is out in a controlled environment (a/b test, switch, etc.)
- [x] Page is monitored when live (add a separate github issue for this)

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Amount of media spends for ads intending to lead to the page

#### Tasks
- [x] Get and understanding of media buys (@hoosteeno )
- [x] Determine, based on media spend, if we apply /new designs to campaign page for ad buy deployment (@hoosteeno )

**Comment by alexgibson** [comment]
Based on the experiment report it sounds like we're ok to promote this to production code? Let's make it happen if so.

**Comment by hoosteeno** [comment]
Yes! We can translate the experimental variation into production templates.

**Comment by alexgibson** [comment]
@hoosteeno should we apply this change to /campaign as well?

**Comment by alexgibson** [comment]
I've opened a pull request to add the new copy / images to both /new and /campaign.

**Comment by alexgibson** [comment]
Pull requests to update translations for both /new and /campaign:

- https://github.com/mozilla-l10n/www.mozilla.org/pull/353
- https://github.com/mozilla-l10n/www.mozilla.org/pull/354
