### ISSUE TITLE
(11/4) - Update WNP for Indonesia

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7852]
## Description

Update the hard coded template for the WNP shown to users w. Indonesia locale (id)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is live at start of day in Indonesia on Nov 4th

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Firefox version on Nov 4th

#### Tasks
- [x] Obtain content, copy and design assets, from the Taipei team
- [x] Provide assets to Silverorange to code
- [ ] QA (team and stakeholder) of coded page on demo
- [x] Code review
- [ ] Merge, launch on Nov 4 (Indonesian Time Zone)

**Comment by ejregithub** [comment]
@alexgibson  - @sgarrity, as indicated in email as well, has this PR in for review when you have time (let me know if we need to assign to another dev, please). I've created the dependency here on PR #7952

**Comment by ejregithub** [comment]
@alexgibson  - @sgarrity, as indicated in email as well, has this PR in for review when you have time (let me know if we need to assign to another dev, please). I've created the dependency here on PR #7952

**Comment by alexgibson** [comment]
@ejregithub @sgarrity I ran the design past the brand team, and the wordmark "The New Firefox Lite" has some issues that I think need to be addressed:

1. The wordmark text should be "Firefox Browser Lite". It should not contain "The New..." since that isn't the real product name, and will only be true for a short length of time. If they need to highlight the product being "new", it should not be in the wordmark, but elsewhere in the page.
2. The wordmark should use the font "Firefox Sharp Sans".

Thanks

**Comment by alexgibson** [comment]
The brand team have now changed their feedback re: the wordmark https://github.com/mozilla/bedrock/pull/7952#discussion_r336616037
