### ISSUE TITLE
Add /wnp70 to CRO sandbox

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7855]
## Description

We should add Whatsnew 70 to the CRO sandbox when the page is ready..

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] /en-US/exp/firefox/70.0/whatsnew/ is a copy of /en-US/firefox/70.0/whatsnew/all/
- [ ] it includes Convert snippets

#### Tasks
- [ ] Drop page into django application
