### ISSUE TITLE
Add new /firefox/ to CRO sandbox

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7856]
## Description

We should add the *new* /firefox/ page to the CRO sandbox when it is available.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] /en-US/exp/firefox/ is a copy of /en-US/firefox/
- [ ] it includes Convert snippets

#### Tasks
- [ ] Drop page into django application
