### ISSUE TITLE
Run an experiment on /new using Convert

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7857]
Target Experiment - #7851

We should test new strings/icons on en-US/firefox/new using Convert. This card should likely become an epic for a handful of additional cards, including...

***Tasks***
- [x] Design the experiment
- [x] Build/review the experiment in Convert
- [x] Monitor the running experiment
- [x] Analyze the experiment

**Comment by alexgibson** [comment]
@hoosteeno Both Convert and the redirector worker are active on www.allizom.org, so there should not be any blockers to start on implementing this.

**Comment by hoosteeno** [comment]
@alexgibson I have built the experiment here: 

https://app.convert.com/#/projects/1003350/experiments_report/10031777

I cannot get any variations in my browser and cannot get the report to increment the visitor count, using Incognito and clearing cookies. 

I think the Convert snippet may not be doing what it needs to. Specifically, in the source of [the experience page](https://www.allizom.org/en-US/exp/firefox/new/), I don't see the snippet Convert provides. I do see some [bundled convert code](https://www.allizom.org/media/js/BUNDLES/convert.eb14ea70d301.js), but it does not seem to include the variations I built (you can see them [here](http://cdn-3.convertexperiments.com/js/10039-1003350.js); scan for 'Automatic'). 

Is it possible we are not loading the snippet of code that contains the experience I've built?

**Comment by stephaniehobson** [comment]
The `convert-experiment-script` switch needs to be toggled on on staging.

**Comment by stephaniehobson** [comment]
Never mind, that was done ages ago, it just wasn't done the way I expected it to be.

**Comment by alexgibson** [comment]
@hoosteeno looking in the Convert dashboard, I see your experiment is confugured to run in the project thast targets www-dev. I've updated the project names to be more explicit to avoid confusion here. Once you have this moved over, let me know and am happy to review further.

**Comment by alexgibson** [comment]
Some review notes:

- The CSS look a-ok.
- Is the a/a version needed, seeing as the original is already a variation? The last test I tried putting together on stage indicated that this may not be required.
- How can we verify that events and goals are working ok? You're using a fancy regex that targets both stage and prod URLs, which makes testing the experiment on staging first problematic. It also means all the preview links open against prod. I'd like us to test this fully on staging (seeing traffic, verifying events are working OK) before running in production.
- I think you can make the download goal more reusable as a site-wide goal, since we use the same download button code on all our pages. It shouldn't need to match a specific URL. The selector you're using should also target the link itself, as opposed to the `li` element. I'd suggest something along the lines of the following:

```
.download-button .download-list > li > a.download-link 
```

Also a side note: the Tier 1 geography seems ok, but I'm not sure if it's really required. The only thing I don't want is for people to confuse this with language.

**Comment by alexgibson** [comment]
Oh - another note. I'd like us to leave a paper trail for each experiment. Please include this GitHub issue number in the title of the experiment (or somewhere else where people can find it), so that we can link back to where and when this was reviewed in the future.

**Comment by alexgibson** [comment]
I sucessfully tested and reviewed the experiment on staging. I've enabled the experiment for production.

Next step: I'll coordinate with Josh about routing some production traffic to the experiment page.

**Comment by alexgibson** [comment]
Oops, I'll leave this issue open, as we want to monitor the results here too.
