### ISSUE TITLE
/mobile page design

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7858]
## Description

Continue and close out the redesign of /firefox/mobile

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Meets brand requirements
- [x] Is completely reviewed according to RASCI and ready for devs to pick up

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [x] Determine page states
- [x] Include app store badges in landing page and modal windows
- [x] Finalize and deliver design assets

**Comment by cgonz0** [comment]
Updated header:
![Mobile 1280_Update.png](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/e9c63cd9-b800-4a95-9345-82062fd93beb)

New assets:
![img-browser-mobile.svg](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/2be1ff72-9208-48df-b2a5-08b1217d6c5e)
![img-mobile-noodles.svg](https://images.zenhubusercontent.com/5d7c23b1d8206c00011723a8/21a2ee80-71a2-4a85-bc06-86c20a7f01ae)

**Comment by ejregithub** [comment]
This is done, closing. Thanks @cgonz0
