### ISSUE TITLE
Remove obsolete .lang files for 2018 /firefox/accounts/ page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7864]
## Description

The 2018 /firefox/accounts/ page was removed in https://github.com/mozilla/bedrock/pull/7820.

Once this goes to production, we should file a PR on the L10n repo to remove the obsolete .lang files.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] .lang files are removed from the repo.

#### Tasks
- [x] PR to L10n repo.
- [x] PR to langchecker repo.

**Comment by Shivansh2407** [comment]
Please can I work on this?

**Comment by alexgibson** [comment]
> Please can I work on this?

Thanks for showing interest, but this is something contributors don't have the correct permissions to do easily.
