### ISSUE TITLE
Add /lockwise to CRO sandbox

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#7867]
## Description

We should add the /lockwise/ page to the CRO sandbox when it (the sandbox) is available.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] /en-US/exp/firefox/lockwise/ is a copy of /en-US/firefox/lockwise/
- [ ] it includes Convert snippets

#### Tasks
- [ ] Drop page into django application
