### ISSUE TITLE
Add functional tests for the new /firefox page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7898]
## Description

The redesigned page doesn't yet have any functional tests.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is covered in some way in our automated test runs.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Not having any coverage increases the risk of accidental breakage.

#### Tasks
- [ ] Write some tests.
- [ ] Push to `run-integration-tests` branch prior to merging to make sure they pass.
