### ISSUE TITLE
Add functional tests for firefox/lockwise page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7899]
## Description

The new firefox/lockwise page doesn't yet have any functional tests.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Page is covered in some way in our automated test runs.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Not having any coverage increases the risk of accidental breakage.

#### Tasks
- [x] Write some tests.
- [x] Push to `run-integration-tests` branch prior to merging to make sure they pass.

**Comment by sandrocottus** [comment]
I want to contribute to this, but I am not sure what all things need to be done.
Can I send a draft PR?
