### ISSUE TITLE
Add survey to lifecycle 1

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#7911]
## Description

We have a survey for lifecycle pages:

`https://qsurvey.mozilla.com/s3/Firefox-Page`

We should add this survey to the page. We can link to it from e.g. "Feedback".

We can add it to the bottom links, similar to the links on /firefox/lockwise (separated by 24px padding), as in the attached mockup.

We want at least 1000 responses, and don't need a lot more than that.

We will show it to en-US only.

We can probably get away with just putting the link on the page for a short while, rather than using TC to segment audience. We can put the link behind a switch, turn it on, turn it off after we have enough responses.

![Screen Shot 2019-10-15 at 10.49.19 AM.png](https://images.zenhubusercontent.com/5c871077d74bd07972c6db24/10ecc1b2-fc55-49e3-a5f6-0dcd9f8b2a37)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Quick design review with @cgonz0 
- [ ] Link added to the page, behind a switch
- [ ] Switch enabled
- [ ] hoosteeno notified so he can monitor responses

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by jenniferdavidson** [comment]
Next to the "Why am I seeing this?" instead of "Page Feedback" let's change the link text to "Share feedback about this page". 

And I already chatted with hoosteeno, but let's try to get both weekend days and weekdays represented (i.e. let's turn the survey on for a weekday or two as well as a weekend day or two).
