### ISSUE TITLE
Update favicons

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#7915]
## Description

Since #7889 there is now a central source of browser favicons. All favicon references in bedrock should be updated to use those.

---

#### Tasks
- [x] Mozilla
- [x] Firefox master brand
- [x] Firefox Browser
- [x] Firefox Browser Beta
- [x] Firefox Browser Developer
- [x] Firefox Browser Nightly
- [x] Firefox Lockwise
- [x] Pocket

**Comment by stephaniehobson** [comment]
I think this is done.
