### ISSUE TITLE
MOSS pages cleanup

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7970]
## Description

Some cleanup after https://github.com/mozilla/bedrock/pull/7713 merged.

- Remove /moss/mission-partners-india/ and redirect to /moss/mission-partners/
- Removed unused legacy MOSS landing page (inaccessible since the newest version of the landing page was never translated).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Legacy india page is removed and redirected.

#### Tasks
- [x] Remove Inida template and redirect.
- [x] Remove legacy landing page template.
- [ ] Remove any unneeded files from l10n repo.
