### ISSUE TITLE
WNP minor updates for Indonesia

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#7991]
## Description

- Copy updates
- Less padding at top of the page
- Hide SMS messaging if in the US.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Updates are approved by stakeholder on demo.
- [ ] Push to production once approved.

#### Tasks
- [x] Update copy.
- [x] Update design.
- [x] Fix around SMS bug.
