### ISSUE TITLE
Add functional tests for whatsnew pages

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#8000]
## Description

We have some tests for the legacy fallback page, but none for the current version-specific pages. We should have test coverage to make sure active whatsnew pages render correctly.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] All active whatsnew pages have automated test coverage.
- [ ] Each test verifies that the requested page renders as expected (could include a check for a CTA button, for example).

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.
