### ISSUE TITLE
Remove obsolete .lang files

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8014]
## Description
I've been looking through pages that are no longer part of bedrock and (I think) we're safe to remove a number of .lang files from the (soon to be) legacy L10n repo:

- `firefox/whatsnew_66.lang`
- `firefox/whatsnew_63.lang`
- `firefox/whatsnew_61.lang`
- `firefox/whatsnew_59.lang`
- `firefox/whatsnew_57.lang`
- `mozorg/moss/index.lang`
- `mozorg/moss/mission-partners-india.lang`
- `mozorg/contribute/signup.lang`
- `mozorg/about/history.lang`
- `tabzilla/tabzilla.lang`
- `foundation/leadership-network.lang`
- `foundation/issues.lang`
- `foundation/index.lang`
- `foundation/advocacy.lang`

Clearing out obsolete files will help us prepare for migration of content that's still needed to the new Fluent system.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] .lang files are removed from the repository.
- [ ] Configs are removed from langchecker.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Need to double check that none of the above are, in fact, still in use.

#### Tasks
- [ ] PR to remove from langchecker repo.
- [ ] PR to remove .lang files from www repo.

**Comment by Patil2099** [comment]
@alexgibson  Can I work on this issue?

**Comment by alexgibson** [comment]
@Patil2099 sorry, contributors do not have access rights to push to the repositories that this work needs to happen in.

**Comment by alexgibson** [comment]
L10n repo RP: https://github.com/mozilla-l10n/www.mozilla.org/pull/343
Langchecker PR: https://github.com/mozilla-l10n/langchecker/pull/936

**Comment by alexgibson** [comment]
Fixed
