### ISSUE TITLE
Remove legacy mozilla-accordion.js jQuery script

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8019]
## Description

As soon as #7530 is fixed, I think we're in a position to remove the legacy jQuery `mozilla-accordion.js` script from the repository.

Looking through the repo, the [accordion bundle](https://github.com/mozilla/bedrock/blob/master/media/static-bundles.json#L1481-L1487) is still in use on several pages, but from what I can see that code is redundant, since all the pages it's on are now ported to Protocol, which uses the `details` JS component instead.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] JS library is removed from the repository.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Need to double check code is not still being used by any pages.

#### Tasks
- [ ] Remove library.
- [ ] Remove bundles.
- [ ] Remove unit tests.
- [ ] Remove documentation.
