### ISSUE TITLE
Internal link audit to /firefox/

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#8020]
#### Description:
The purpose of /firefox/ changed and so should our internal link structure on www and all mozilla owned properties/subdomains. We need to control all links to mozilla.org/firefox/ and its locales if the link should point still to it or to /new/ as its mainly about the browser.
---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] An actionable list of links to change from /firefox/ to /new/

#### Tasks
- [x] Audit all links from search console ([sheet](https://docs.google.com/spreadsheets/d/1za8GnoNNoCDxgpXz-Y4WMwP0VtYBMMni1bNIzdG502g/edit?usp=sharing))
- [x] Audit all links from ahref 1 ([sheet](https://docs.google.com/spreadsheets/d/1lAyUc7-HsXceh-wiUw5vsnenrYNAkkB3KCXu_20tOt4/edit?usp=sharing))
- [x] Audit all links from ahref 2 ([sheet](https://docs.google.com/spreadsheets/d/1pjrXisSDHPfjN7zE-E0b5Xvs9AkXhYS--19YrFwW5-o/edit?usp=sharing))
- [x] Audit firefox.com and its subdomains
- [x] Audit mozilla.design and its subdomains
- [x] Transfer all audits to this ([sheet](https://docs.google.com/spreadsheets/d/1yKTe1fQD4Wz_2AOs29RRR5-QkdQt44QUsbfmvQho54w/edit#gid=0))

**Comment by rraue** [comment]
Actionable audit list here: https://docs.google.com/spreadsheets/d/1yKTe1fQD4Wz_2AOs29RRR5-QkdQt44QUsbfmvQho54w/edit#gid=44879094
