### ISSUE TITLE
wnp 71 - code

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8026]
## Description

Revised description: We are going take to the winning version,[ v7](https://www.mozilla.org/en-US/firefox/70.0/whatsnew/all/?v=7), from the experiment run on WNP 70.0 and make that the content for WNP 71.0

[Releng bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1594956)

***Tasks***
- [x] Display content to be shown to users coming from <71.0 to the 71.0 release currently schedule for December 3rd, 2019.
- [x] Reuse the v=7 WNP 70.0 experiment content, (with one noted string change from the welcome/3/ page project)
- [x] Tier One locales receive the new content (Tier One = de, en-CA, en-GB, en-US, fr)
- [x] Tier Two locales continue to receive the content shown in WNP 66.0 and lower (/whatsnew.lang)

**Comment by alexgibson** [comment]
@ejregithub what's the reasdon this issue is blocked?

**Comment by alexgibson** [comment]
@ejregithub this is up on demo: https://www-demo1.allizom.org/en-US/firefox/71.0/whatsnew/all/

I'll hold off on extracting strings & code review until the blocker is removed here. Thanks

**Comment by alexgibson** [comment]
@ejregithub note that the description in the rel eng bug no longer matches the ask here. You may want to update in bugzilla to avoid confusion on their end?

**Comment by ejregithub** [comment]
@alexgibson - removing the blocker based on the report in which "v=7 (promoting a Sync button, new copy, and new icons) was the clear winner." - https://docs.google.com/document/d/1y-iJNSRp6QmxRHnpgce8l5uMCbzReDbSmA6pSmMwwQM/edit#

**Comment by alexgibson** [comment]
@hoosteeno @ejregithub before I go and extract strings, I'd like to request that the content is approved on demo (by whoever needs to approve this page):

https://www-demo1.allizom.org/en-US/firefox/71.0/whatsnew/all/

In particular, I feel I should highlight that this page only has a single conditional state (signed out). If we move forward with this, I'd like to try and avoid a fire drill when someone demands that we shoe horn in more conditional content later, or people start filing bugs because it's not what we typically do with these pages.

I'd also like someone to formally approve that we're showing this content only to `en`, `de` and `fr`, whilst everyone else sees the [default WNP](https://www-demo1.allizom.org/es-ES/firefox/71.0/whatsnew/all/).

Thanks

**Comment by ejregithub** [comment]
@alexgibson - Lindsey gave the go ahead in Slack with the comment "Ship it!"
