### ISSUE TITLE
WNP 71 - make strings available to remaining locales

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8028]
## Description

We need to make the 2 strings in /whatsnew.lang file used for **non**-Tier One locales in WNP 70.0 available to all locales. These are the two new strings introduced in the fallback page w. Mobile CTA content with the send-to-device widget and the QR code.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] strings are opened to localizers in Pontoon to complete the remaining unfinished lang files.
- [ ] those that aren't completed should still be shown the original fallback page content.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Timing

#### Tasks
- [ ] Expose strings in coordination w. Peiying w. the ask to localizers that they complete by Nov 25 (2019)
- [ ] Determine if a new lang file for 71.0 - /firefox/whatsnew_71.lang - can/should be created or if should we just continue to point to the same /whatsnew.lang file

**Comment by ejregithub** [comment]
@alexgibson - could you please review? I'm not sure if the best path forward is to continue using the /whatsnew.lang file as we're doing now in WNP 70.0, showing it to Tier-N locales (all others than FRENDE, for which we'll have hardcoded templates again in WNP 71.0)

**Comment by alexgibson** [comment]
@ejregithub I'm not sure I understand what's being asked here. Is the WNP for 71 going to be this template? https://www.mozilla.org/en-US/firefox/whatsnew/all/, or something else? You mention 2 strings, but don't say what those strings are, or where they will be used?

**Comment by ejregithub** [comment]
@alexgibson - that's precisely it, that template, yes. I chatted w. Peiying last night and got a better understanding - what you've stated about the strings already being exposed - and asked that she convey the request to the remaining locales to complete the two strings there in the lang file.  I'm closing this issue (as invalid . . .)
