### ISSUE TITLE
WNP 71

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8029]
## Description

Revised description: We are going take to the winning version,[ v7](https://www.mozilla.org/en-US/firefox/70.0/whatsnew/all/?v=7), from the experiment run on WNP 70.0 and make that the content for WNP 71.0

[Releng bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1594956)

------
Create and display content to be shown to users coming from <71.0 to the 71.0 release currently schedule for December 3rd, 2019.

The intent for this instance to product the webpage via a new workflow to 'build it in a day'.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Page is live, URL assigned

#### Tasks (Follow the new project plan/schedule to):
- [ ] Use the content from https://www.mozilla.org/en-US/firefox/70.0/whatsnew/all/?v=7 for the WNP 71
- [ ] Assign the standard URL 
- [ ] set to show users coming from <71.0 and receiving the 71.0 release
- [ ] Tier One locales receive the new content (Tier One = de, en-CA, en-GB, en-US, fr)
- [ ] Tier Two locales continue to receive the content shown in WNP 66.0 and lower (/whatsnew.lang)
