### ISSUE TITLE
Build/launch/monitor/analyze WNP70 experiment

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8030]
## Description

Build/launch/monitor/analyze an experiment on WNP70 in the interim prior to the 71.0 release on 12/3/19

[Document with content variations](https://docs.google.com/document/d/1EGIx4pd2lBopQwuonHa04sFob7djkbC2DvNtB6ic9Gw/edit)

[Experiment doc](https://docs.google.com/document/d/1cFYYXLam6ic27tEsd2pplFPsvu-AyaA1rDsA8L1qR6g/edit)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Is live Thursday Nov 7th

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] specify the experiment
- [ ] copy/design sprint
- [ ] build in convert
- [ ] launch/monitor/analyze

**Comment by craigcook** [comment]
On demo:

https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/70.0/whatsnew/all/?v=1
https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/70.0/whatsnew/all/?v=2
https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/70.0/whatsnew/all/?v=3
https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/70.0/whatsnew/all/?v=4
https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/70.0/whatsnew/all/?v=5
https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/70.0/whatsnew/all/?v=6
https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/70.0/whatsnew/all/?v=7

**Comment by hoosteeno** [comment]
Our accountable (MEM) approved in person during review meeting.

I have done analytics review (with this [spreadsheet I built](https://docs.google.com/spreadsheets/d/1Wj509WwEnMb1cP8akzUtlbqMo-ALQWXc3mjB8iJwbY4/edit#gid=0), which is so helpful) and can't see any referral bugs.

**Comment by sghoseWI** [comment]
Experiment report: https://docs.google.com/document/d/1y-iJNSRp6QmxRHnpgce8l5uMCbzReDbSmA6pSmMwwQM/edit#
