### ISSUE TITLE
WNP70 test - copy/design sprint

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8032]
## Description

Design sprint to create copy and design for experimentation on the WNP70 page

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] No state-based switching based on sync auth state.
- [ ] Live in prod by EOD Thursday Nov 7

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ]  Can we use a button for sync CTAs? (hoosteeno asked in #fxa)

#### Tasks
- [ ] Design 2 layouts, low-fidelity, for 7 variations (copy variations 1-4, 5, 6, 8). Sketches. Pictures of paper.
- [ ]  Find or build graphics for bulleted lists.
- [ ] Use existing layouts & components wherever possible.

**Comment by hoosteeno** [comment]
Nlinden provided this document: https://docs.google.com/document/d/1EGIx4pd2lBopQwuonHa04sFob7djkbC2DvNtB6ic9Gw/edit

**Comment by hoosteeno** [comment]
The copy doc implies a few design variations we  need to vet for feasibility.

**Comment by hoosteeno** [comment]
Design requirements:
* 2 layouts, low-fidelity (1-4; 5&6&8). Sketches. Pictures of paper.
* Find or build graphics for bulleted lists. 
* Use existing layouts & components wherever possible.

Details:
* No state-based switching based on sync auth state. 🙌 

Outstanding questions:
* Can we use a button for sync CTAs? (hoosteeno asked in #fxa)

* @cgonzo to SWARM with @craigcook and nlinden on this.
