### ISSUE TITLE
WNP70 test - build variations, segmentation, and tracking

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8033]
## Description

Using TrafficCop, build 7 variations that incorporate copy, design, and instrumentation specs. Give each 5% of WNP en-US traffic. Put it all behind a switch or flag.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Experiment is live on demo
- [ ] Experiment is merged and ready to switch on in prod

**Comment by hoosteeno** [comment]
Depending on CTA complexity, convert might or might not be the right tool. Our alternatives are:

1. build static templates or dynamic switching, use TrafficCop and GA for routing/measuring
2. build a few static templates, use Convert for routing/measuring
3. use Convert for building dynamic switching and for routing/measuring

TBD based on specs.

**Comment by hoosteeno** [comment]
Updated the issue description with specs.

**Comment by hoosteeno** [comment]
Review feedback on demo below. 

Variation 0:
- [ ] Remove utm_content from URL
- [ ] Add device_id, flow_begin_time, and flow_id to URL

Variation 1, 2:
- [ ] Add device_id, flow_begin_time, and flow_id to URL

Variation 3, 4:
- [ ] Verify device_id, flow_begin_time, and flow_id get values (I can't get them to include values)

Variation 5
- [ ] Add form_type to URL
- [ ] Add device_id, flow_begin_time, and flow_id to URL
- [ ] Add periods to the end of each bullet 

Variation 6
- [ ] Add form_type to URL
- [ ] Add device_id, flow_begin_time, and flow_id to URL
- [ ] Add "And counting." to the end of the subhead
- [ ] Add periods to the end of each bullet subhead

 Variation 7:
- [ ] Add form_type to URL
- [ ] Add device_id, flow_begin_time, and flow_id to URL
- [ ] Add periods to the end of each bullet subhead

**Comment by craigcook** [comment]
device_id, flow_begin_time, and flow_id aren't being fetched because of a CORS error blocking the request from the demo server. I believe there's a way to make this work on demos with FxA stage but there's some step I'm missing. It does work for me locally but I'd like to get it testable on demo as well. Maybe Alex or pmac can help.
