### ISSUE TITLE
/new experiment - long content 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8035]
## Description

David Tenser's team is going to provide the required elements to launch a test on /new involving 'long content'

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [x] Establish what the EU Growth team will provide for this experiment (and modify this issue accordingly)
- [ ] The spec/test plan (@sghoseWI ) - a/b test - (estimate: 3)
- [ ] Copy (EU Growth team)
- [ ] Design (EU Growth team)
- [ ] Launch (websites team)
- [ ] Monitor (websites team)
- [ ] Analyze (@sghoseWI)  - (estimate: 5)

**Comment by hoosteeno** [comment]
Brief in development here: https://docs.google.com/document/d/1pFdPpjwalN74B0_HD5zem2P_51AvFlu4SJiOwS-v5u4/edit?ts=5dd3fb3b

**Comment by sghoseWI** [comment]
@hoosteeno @rraue Are we planning to configure this experiment in Convert?

**Comment by hoosteeno** [comment]
I believe we are blocked on this until the NA/EU growth teams are ready. Moving to research with blocked tag.

**Comment by hoosteeno** [comment]
Archiving this for now. Reopen if it's a priority in the future.
