### ISSUE TITLE
Design/build nav on /new experiment

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8037]
## Description

Design and build an experiment testing the addition of navigation on the /new page

Experiment plan: https://docs.google.com/document/d/1qQVvOPlz-E5ZRWrRUxFnzGsFwQ0mZ9rs_dTeT92P9VA/edit

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Regular nav is in the /new page, live.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Write up the experiment
- [ ] Validate instrumentation in the nav

**Comment by ejregithub** [comment]
Alex commented that we could do this on the page, for a single local, behind a switch.

**Comment by stephaniehobson** [comment]
Hoosteno asked me to put together a exp version of the /new page with the navigation on it. I think that means he is thinking of using convert to forward users to the variant with the nav.

**Comment by hoosteeno** [comment]
I have built an a/b test in Convert that needs review and, if good, merging/enabling/traffic sending in prod. @alexgibson , couldya?

Notes:
* The redirect code is in the `custom javascript` input for each variation, and when we're ready to enable, we need to change it to redirect to prod URLs.
* You can trigger the experiment by visiting https://www.allizom.org/en-US/exp/firefox/new/; you should be redirected to one of two variations, and you can reset your experiment flags by clearing local storage and cookies.
* Both variations should redirect; the control redirects to itself.
* The experiment only applies to Non-Fx Tier 1 .
* We're measuring download clicks to see if nav causes downloads to drop. Also measuring bounce/engage, which may be interesting.
* When we activate in prod, we should also reset the experiment (in [settings panel here](https://app.convert.com/v#/projects/1003343/experiments_report/10032480)).

**Comment by alexgibson** [comment]
Some notes from review:

- We probably could have built this experiment without requiring an entirely separate URL using `/nav/`. This works though, and is now in production so let's use it. We'll need to remember to decomission the URL once the experiment is over and redirect it.
- The redirects currently wipe out URL params should they exist in the originating request. For example, `https://www.allizom.org/en-US/exp/firefox/new/?utm-source=getfirefox.com` redirects to `https://www.allizom.org/en-US/exp/firefox/new/nav/`. Should this be considered a bug, or are we ok with this for this particular experiment?
- The experimental page at `/exp/firefox/new/` has not yet been updated with the [skyline branding](https://www.mozilla.org/en-US/firefox/new/) (which was rolled out to the main page whilst the previous experiment was still running). This is not a blocker, seeing as the control is also outdated. But we _could_ fix this before running the test. Thoughts? 
- What % of traffic should this experiment go out to?

**Comment by alexgibson** [comment]
Another question:

- The `/nav/` variation includes the secondary download button in the header. We may want to consider hiding it, since the main download button [on /new/](https://www.allizom.org/en-US/firefox/new/) is a little different to other download buttons (it doesn't link to a locale neutral /thanks/ URL).

**Comment by hoosteeno** [comment]
@agibson, I think the minor data loss associated with losing incoming params is acceptable.

@sghose, can you specify % of traffic per variation, and then we'll direct 2x that to the sandbox?

@shobson, would you be up for hiding the nav CTA button for this experiment on the /nav variation? If we graduate the /nav variation to prod, we can figure out how to fix that button more long term.

**Comment by alexgibson** [comment]
I opened a pull request to update the branding: https://github.com/mozilla/bedrock/pull/8294

This need not be a blocker to the experiment though (it can sit and wait until after if not essential)

**Comment by alexgibson** [comment]
PR to redirect 6% of traffic: https://github.com/mozmeao/www-workers/pull/6

**Comment by alexgibson** [comment]
I've enabled the redirector on https://www.allizom.org/en-US/firefox/new/ for 6%. We can flip this on for production once the experiment has been promoted to production.

**Comment by hoosteeno** [comment]
@alexgibson If this issue is still open when you're back online, would you help push it over the finish line? I think all the loose ends are ready to tie up.

**Comment by alexgibson** [comment]
I'll get this flipped on in prod just as soon as we've pushed removing the button to prod.

**Comment by alexgibson** [comment]
@hoosteeno this experiment is now running in production and data is coming in.

**Comment by hoosteeno** [comment]
The experiment has been turned off in Convert.
