### ISSUE TITLE
WNP 70 - update headline (hero) string for FR/DE/EN

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8038]
## Description

We need to update the headline copy on FRENDE templates for the WNP 70 page with something that we believe will perform better than the current copy based on testing in another location (mobile).

Lauren will deliver the new string today (Monday) 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] New string is live in FRENDE

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [x] We don't receive the new string

#### Tasks
- [ ] Update headline copy in DE,FR,EN and submit PR
- [ ] Flag Alex for review of PR with request to merge and push if r+

**Comment by amychurchwell** [comment]
Adding blocked label until we are provided strings.

**Comment by ejregithub** [comment]
@amychurchwell - we have the FRENDE strings here (you reference the [original source if needed](https://docs.google.com/spreadsheets/d/1MhR63xWtbUsD4Arf815_F-VD573UhQxFxoVzmiKVmIs/edit#gid=0&range=18:18)). 

en:
Stay ahead of hackers. Check for data breaches with Firefox Monitor.

de:
Sei Hackern einen Schritt voraus. Checke Datenleaks mit Firefox Monitor.

fr:
Vérifiez si vous avez été victime d’une fuite de données avec Firefox Monitor.
