### ISSUE TITLE
WNP 70.0 - non-FRENDE locales - assign old WNP fallback content w. Mobile CTA (widget or QR code)

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8039]
## Description

The ETP in the non-FRENDE locales for WNP70 is not working to advance the building of relationships/cross-promote other products and services.

The ask here is to leverage the [existing fallback content in the WNP with the mobile CTA](https://www.mozilla.org/it/firefox/66.0/whatsnew/all/), widget and QR code, and assign that to the WNP 70 URL for all locales EXCEPT fr, de, en-US, en-CA & en-GB

Instrumentation in the page will need to be updated such that params will reflect the page/version.

NOTE: The hardcoded Indonesian WNP template promoting Lite still needs to be shown as it is.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Non-FRENDE locales are shown the fallback WNP content when updating from a <70.0 version of Firefox to the 70.0 release.

#### Tasks
- [ ] Assign the fallback content for WNP to all locales EXCEPT fr, de, en-US, en-CA & en-GB to be shown at https://www.mozilla.org/firefox/70.0/whatsnew/all/ 
- [ ] Update page instrumentation
