### ISSUE TITLE
Welcome Page #4 - mobile CTA - QR code

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8040]
## Description

We need a new QR code to replace the one in the WNP so we can understand the referring source as this welcome/4/ page. I've asked Loren Austin to provide this to us by EOD on Tuesday Oct 29th.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is live
- [ ] Bug is filed w. Eng to show page at interval x (TBD)

#### Tasks
- [ ]  Set up URL https://www.mozilla.org/firefox/welcome/4/
- [ ] Use old WNP fallback content w. mobile CTA, widget and QR code
- [ ] Update QR code image to be supplied by Mobile Team PMM (Loren)
- [ ] Page instrumentation

**Comment by ejregithub** [comment]
![qr-code](https://user-images.githubusercontent.com/20547886/67790889-c95b7100-fa33-11e9-9164-2f4fd0f1c9ce.png)

**Comment by ejregithub** [comment]
This is currently being put on hold for better planning of implemenation
