### ISSUE TITLE
Put Pocket button on firefox/pocket page.

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8059]
## Description

We built a new Pocket button with the CTA to 'Activate Pocket' in the [Welcome 2](https://www.mozilla.org/en-US/firefox/welcome/2/) browser welcome page and should put that button, with proper instrumentation, on firefox/pocket page.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Activate Pocket button is on the /firefox/pocket/ product page
- [ ] Is live prior to end of S2/Q4

#### Tasks
- [x] Add Pocket button
- [x] Instrument for attribution
- [x] Set it up as a Python helper
- [x] Add unit tests

**Comment by alexgibson** [comment]
As part of this I think we should also tackle https://github.com/mozilla/bedrock/issues/7985

**Comment by alexgibson** [comment]
Blocked by https://github.com/mozilla/bedrock/issues/7985

**Comment by alexgibson** [comment]
Instrumentation for this buttons on this page is as follows:

Primary button
---------------

- `entrypoint`: `mozilla.org-firefox-pocket`
-  `s`: `ffpocket`
- `data-cta-text`: `Try Pocket Now`
- `data-cta-type` : `activate pocket`
- `data-cta-position`: `primary`

Secondary Button
------------------

- `entrypoint`: `mozilla.org-firefox-pocket`
-  `s`: `ffpocket`
- `data-cta-text`: `Try Pocket Now`
- `data-cta-type` : `activate pocket`
- `data-cta-position`: `secondary`
