### ISSUE TITLE
WNP 70.0 - New strings to WNP fallback page content w. mobile CTA

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8064]
## Description

We need to update strings in the fallback WNP page (the mobile CTA) and assign the content to WNP70.0 for all non-Tier One locales.

The current string (shown in https://www.mozilla.org/en-US/firefox/66.0/whatsnew/all/)

Send Firefox to your phone
and unleash your Internet.

The new string, which should be split out to different headline sizes, is/are:

Want privacy on every device? 

You got it. Get Firefox for mobile.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is live w. new strings
- [ ] Shown to non-TierOne users updating from <70.0 to the 70.0 release

#### Risks
- [ ] Note that Amy has set the current page up to fall back to all non-Tier One locales in #8039
- [ ] Locales have not yet been determined (WIP) and will likely go to BW/Agencies for rapid return

#### Tasks
- [ ] Assign content / show to non-Tier One locales at the WNP70 URL
https://www.mozilla.org/%locale%/firefox/70.0/whatsnew/all/
- [ ] Apply latest background image to page

**Comment by ejregithub** [comment]
Kind of, but not exactly, like this:

![Screen Shot 2019-10-30 at 2 19 34 PM](https://user-images.githubusercontent.com/20547886/67903233-47993f80-fb28-11e9-832b-ed3ae1e9ac4c.png)

**Comment by craigcook** [comment]
On demo: https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/firefox/66.0/whatsnew/all/

The 66 page is the easiest way to see it in English, but as of #8053 this is also the page shown to locales other than EN/FR/DE even for the latest version.
