### ISSUE TITLE
WNP 70.0.2 - assign fallback (/whatsnew.lang) content to dot release WNP URL

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8091]
## Description

See https://bugzilla.mozilla.org/show_bug.cgi?id=1593777

We want to show a WNP to users updating from 70+ to the 70.0.2 (presumably) release. 

The content for the page is already done, currently being shown to 70.0 Tier-N locales (not Tier One).  We need to show the page to all locales, including TierOne (FRENDE) that are 100% in time for the dot release.

For reference: @amychurchwell first assigned the content to WNP 70.0 in #8039 and @craigcook update the strings in #8064

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Page is shown to locales at 100% 
- [x] Page is shown to users updating from a 70+ release to the 70.0.2 release (users updating from <70 should still be shown the WNP 70.0 page)

#### Tasks
- [ ] Assign the /whatsnew.lang content to show to all completed locales at the 70.0.2 release - URL - https://www.mozilla.org/%locale%/firefox/70.0.2/whatsnew/all/

**Comment by ejregithub** [comment]
@alexgibson - would you mind taking this one on? Currently I'm hearing the 12th as a possible ship date for the dot release.

**Comment by ejregithub** [comment]
@alexgibson - this dot release and showing a WNP with it has been killed (MEM just sent the email about it). If releng doesn't enable it, the WNP won't be shown, I'm just not sure if anything needs backing out/ removing for clean up on our part.

**Comment by alexgibson** [comment]
@ejregithub if the update from 70.0 -> 70.0.2 isn't going to trigger a WNP, then I don't think there's any need for us to revert anything in bedrock. People should just continue seeing the regular 70.0 WNP.
