### ISSUE TITLE
Decommission old /firefox/all/ pages

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8096]
## Description

The new /firefox/all/ page is now [active for 44 locales](https://l10n.mozilla-community.org/langchecker/?locale=all&website=0&file=firefox/all-unified.lang), which represents 94.97% of our l10n user base. Whilst the [old page](https://l10n.mozilla-community.org/langchecker/?locale=all&website=0&file=firefox/all.lang) is still active for more locales (84), it seems doubtful that we're going to get those locales to catch up. Those communities may not be as active today as they used to be.

The new page has now been around for several months. It's time to remove the old template, and redirect the old legacy /firefox/{product}/all/ URLs to the new unified /firefox/all/ page.

/cc @peiying2 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Old pages are removed and redirected in production.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] We're going to lose some locales, but given the nature of the /all page, those builds will still be accessible.

#### Tasks
- [x] Remove the old templates.
- [x] Clean up view.py code.
- [x] Update tests.
- [x] Redirect old URLs.
