### ISSUE TITLE
Build a new fallback WNP for Tier 1 locales

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8126]
## Description

We want to build a new fallback WNP for Tier 1 locales. The "fallback WNP"...

* Is shown to all legacy updaters on versions <67 e.g. visitors to 63.0.3/whatsnew or 33.0/whatsnew. 
* 67 is arbitrary, based on the current behavior of the fallback page. For the new page we might decide to use this for all versions < current.
* Is shown to anyone visiting a URL that looks like a whatsnew URL for a legacy update, e.g. visitors to 42.42.424242/whatsnew.
* Is shown to really really old versions that send traffic to /firefox/whatsnew without a version number.

We already have such a page, which is localized to 90% of the site audience, but we want a newer one for Tier 1 locales. This new page will have different content than the current fallback WNP.

The specific content is still TBD.

The layout and design are still TBD.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Fallback WNP is published
- [ ] It appears in Tier 1 locales at URLs like
- https://www.mozilla.org/firefox/63.0.3/whatsnew/
- https://www.mozilla.org/firefox/42.42.424242/whatsnew/ 
- https://www.mozilla.org/firefox/whatsnew/
- https://www.mozilla.org/firefox/33.0/whatsnew
- [ ] It does not appear at non-Tier-1 locales

**Comment by hoosteeno** [comment]
In meeting last week, accountable stakeholders agreed to a general content strategy for this page.

1. Use the same content as on v7 of the WNP test, which is also going to WNP71. 
2. Include a link to upgrade instructions.
3. Trim the secondary content, which is less "evergreen". 

@antlam is working on the layout/designs for this.

**Comment by hoosteeno** [comment]
@ejregithub we need to specify the localization approach for this page. What locales are we hoping it will show up for? Recall that we can localize for de, fr with staff; we can localize for 16-ish other locales with vendors; and we can localize for the rest of locales with community.

**Comment by hoosteeno** [comment]
The experiment plan is here: https://docs.google.com/document/d/1qQVvOPlz-E5ZRWrRUxFnzGsFwQ0mZ9rs_dTeT92P9VA/edit

**Comment by alexgibson** [comment]
All dependencies are closed here.
