### ISSUE TITLE
Build a new Moments page about mobile

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8127]
## Description

We want to build a new page in the firefox/welcome hierarchy at /firefox/welcome/4. This page will be about mobile. We should assume it will use existing page templates. We should swarm on it until it is done. We should launch in all Tier 1 locales. It should be ready to distribute by  by 12/3.

[Master project doc](https://docs.google.com/document/d/1kDxf9ATASBwh5oMGT-I4iV7VDHmttyZRSIN7CU6VNYQ/)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Ready to distribute by 12/3
- [x] About mobile
- [x] Localized in Tier 1 
- [x] At /firefox/welcome/4
- [x] Uses existing templates for welcome pages

**Comment by hoosteeno** [comment]
In meeting with stakeholders just now, the following decisions were made:

1) We will distribute the new moments page to Tier 1 audiences.
2) We'll segment page visitors by their mobile device status (using UITour) 
3a) For visitors with >0 mobile devices, the page will have a Sync CTA at the top, and a mobile app CTA at the bottom
3b) For visitors with 0 mobile devices, the page will have a mobile app CTA at the top, and a Sync CTA at the bottom
4) The headline, subhead, button copy, images, and body copy will remain the same for both segments of visitors. 

We need a copy card; an analytics plan/validation card; a design card; and a coding card.

**Comment by Left47** [comment]
Added a placeholder for UJ triage: https://bugzilla.mozilla.org/show_bug.cgi?id=1595911
