### ISSUE TITLE
Help Windows 10S users on /new to de-activate the S mode

### ISSUE THREAD

**Issue by rtestard** [mozilla/bedrock#8139]
## Description

Issue 6367 allowed putting in place a mechanism to detect Windows 10S users so we can quantify them.
https://github.com/mozilla/bedrock/issues/6367#issuecomment-476256394 confirmed that the current detection method in place is now supported by Chromium Edge, which makes it a reliable long term solution to identify Windows 10S users attemtping to download Firefox.

Proposal:
- Leverage work from issue 6367 to identify Windows 10S users on /new
- Expose a UI informing Windows 10S users that they have to disable the S mode in order to run Firefox. It could potentially be a message pointing to https://support.mozilla.org/en-US/kb/windows-10-s-wont-let-me-install-firefox for more details.

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Windows 10S users see a message on /new informing them how to disable the S mode in order to install Firefox
- [ ] Windows 10S users having de-activated the S mode stop seeing the message and can now download/run Firefox

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Incorrectly identify S mode users

#### Tasks
- [ ] Implement 10S detection on /new
- [ ] Expose a custom message for 10S users

**Comment by alexgibson** [comment]
Note that we may need to update our UA check for Chromium Edge here: https://github.com/mozilla/bedrock/blob/master/media/js/base/core-datalayer.js#L66

**Comment by alexgibson** [comment]
@hoosteeno given that MS confirmed they are changing their restrictions in the future, should we close this issue, and remove the current detection code from bedrock?

**Comment by hoosteeno** [comment]
@alexgibson let's leave detection code in place while those are still in the wild. But we can close this.

**Comment by alexgibson** [comment]
@hoosteeno the current detection code only works in the old Edge, not the Chromium version. So it’s likely inaccurate if people still want to keep this around. We’d need to update the user agent detection for it to still be accurate.
