### ISSUE TITLE
/firefox/windows-64-bit/ extract strings

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#8140]
## Description

We should get the /firefox/windows-64-bit/ page ready for localization, so we can scale the SEO traffic to this page. The page has a very good ctr and gets a decent amount of traffic plus the search interest is higher in other countries than the US. 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Strings are extracted and available in Pontoon as opt-in for all locales

#### Tasks
- [x] Extract strings
- [ ] File Airtable entry to get staff to localize in DE and FR
- [ ] Communicate w. Peiying to open strings in Pontoon to all other locales

**Comment by alexgibson** [comment]
L10n PR https://github.com/mozilla-l10n/www.mozilla.org/pull/356
Langchecker PR: https://github.com/mozilla-l10n/langchecker/pull/947

**Comment by alexgibson** [comment]
This is now in Pontoon
