### ISSUE TITLE
(11/21) - Sync Moments Page - Welcome/3/

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8148]
## Description

Create a new Moments page with CTA for Sync leveraging the content from the v7 winning variant in the WNP 70 test and inserting that to the Welcome pages template layout.

[Copy](https://docs.google.com/document/d/1YWNIG5jJ-daKTZWXUaiVRivsnUjGK72YGsJOqhBW1R8/edit#)  

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Ready to distribute by 11/21
- [x] About Sync
- [x] Localized in Tier 1 
- [x] At /firefox/welcome/3
- [x] Uses existing templates for welcome pages
