### ISSUE TITLE
Lockwise CTA - Moments page - Welcome/5/ 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8157]
## Description

We need create a Moments page the promotes the benefits of password safety in Lockwise, in particular benefit to customers in which the product makes passwords safe and easy. 

[Copy ](https://docs.google.com/document/d/1oJIQUP7fhWExfjbRhE6HyeW1wF_paP5gK0wl7KHbHHY/edit)(from Natalie)
CTA: Get Lockwise for mobile
PMM messaging (as reference):
- Protect yourself from hackers, directly in the Firefox browser with Lockwise + Monitor
- Easily generate secure passwords and improve your password hygiene 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Uses the 'welcome' page template
- [ ] Is localized to Tier One

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Swarm with those identified in the RASCI
- [ ] Copy, design, code, analytics plan & validation
- [ ] l10n copy template (@ejregithub ), ship to staff localizers for DE and FR
- [x] Get new Adjust link and shorten it - https://mzl.la/2rTJ1Hq
- [ ] Investigate user states and conditional content based on that (signed in/not signed in)
- [ ] Request FMS and release

**Comment by ejregithub** [comment]
Notes from meeting w. Lindsey:

- Page Trigger via FMS - Determine if users don't have Lockwise mobile app (then show them this moment page if they don't)
- CTA is to get the application on mobile via the STDWidget (get slugs from Brynne)
- Natalie to work more on copy
- Eric to find out if we can show the page around the end of December

**Comment by ejregithub** [comment]
@craigcook - the full app Adjust link - https://bhqf.adj.st/?adjust_t=mclvdo7&adj_deeplink=lockwise%3A%2F%2F&adj_fallback=https%3A%2F%2Fwww.mozilla.org%2Fen-US%2Ffirefox%2Flockwise

I'll ask Liz to shorten it.

**Comment by ejregithub** [comment]
And here's that shortened link - https://mzl.la/2rTJ1Hq

**Comment by alexgibson** [comment]
Passing note: we went through quite a lot of effort to standardize how we use Adjust links across the site already, and built helpers to make them even easier. I'd encourage us to keep using that convention, as opposed to start introducing random URLs again each with diffeent behavior.

https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templatetags/misc.py#L703

**Comment by alexgibson** [comment]
This page is in production https://www.mozilla.org/en-US/firefox/welcome/5/
