### ISSUE TITLE
(11/21) SOM 2018

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8177]
## Description

Description, good enough that reading the card 1 month from now, you still know what it means.

---

Description: Create new State of Mozilla page for 2018 following format of previous years (URL structure and content layout). 

Deliverables for requestor (Erica):

Content for:
- https://www.mozilla.org/foundation/annualreport/2018/

Additional content items:
- 2018 Audited financial statement (PDF)
- 2018 Form 990 (PDF)
---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Code is in the bedrock private repo prior to launch 
- [ ] Must be stakeholder approved (QA of coded page)
- [ ] Is live on, not before 11/21 (must launch midday or before, Pacific Time)

#### Tasks
- [ ] Code page, keep in private repo til launch date 
- [ ] add pdfs to hosted instance and link to those
