### ISSUE TITLE
 Global FxA CTA in site nav

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8179]
We want to build a global FxA CTA to show on our busiest pages to promote FxA features and drive FxA MAU. We can use the existing foundation promotion banner and the WNP70 v7 copy/CTA as a jumping off point.

## Success Criteria ##
- [ ] Pages for this treatment are identified
- [ ] Measurement/analytics plan is established
- [ ] Copy and design are approved by RASCI
- [ ] Promotional banner is live on pages specified
- [ ] Measurement/analytics is validated

## Tasks ##
- [ ] Finalize RASCI
- [ ] Swarm method
- [ ] Copy
- [ ] Design
