### ISSUE TITLE
Global FxAccount CTA in site navigation

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8183]
## Description

The project here is to determine if replacing the site-wide "Get a Firefox Account" nav with a site-wide promotional block that will reach the same size audience but talks more about Firefox Accounts benefits will result if more conversions (hopefully leading to ^ MAU for FxA). If it does, we'll deploy the winning variation.

Determine experimentation scope and plan, deploy test. Monitor and provide experiment analysis to maintain control or promote the winning variation.

Initial test ideas: 
a) as a persistent page element 
b) in the global nav promo area 
c) ???

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### Tasks
- [ ] specify the experiment
- [ ] copy/design sprint
- [ ] code - build variations, segmentation, and tracking
- [ ] launch and monitor
- [ ] analyze and report findings

**Comment by hoosteeno** [comment]
Closing for now. Reopen if it becomes a priority.
