### ISSUE TITLE
Code - newsletter subscription preferences page UI updates

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8186]
## Description

In #7620 the new design was established for the newsletter subscription preferences page. This is the issue to code and implement those changes

[brief](https://docs.google.com/document/d/1ahtsCMOlf3tBNFnW11qehTLPK1ER-4XycKY40HQ3B_Y/edit). 

Consult @cgonz0 for more detail on the updates
---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Updates are live
- [ ] the page is ported to Protocol

#### Tasks
- [ ] Code updates
- [ ] String update - change “Country” to “Country or Region”, above the corresponding drop down menu with listing. 
- [ ] Maintain the localization as 'opt-in'/allow for mixed locales as in the current version of the page.

**Comment by ejregithub** [comment]
![emal_preferences_approved](https://user-images.githubusercontent.com/20547886/69093407-3a72c080-0a03-11ea-91fc-a8cb59d77d26.png)

**Comment by Errolyn** [comment]
After a conversation in the durable team room, we are going to see about using checkboxes instead of the switch, they will be more accessible, and easier to understand. I'm marking this blocked until those details are confirmed by Cristina.

**Comment by ejregithub** [comment]
@Errolyn - please note the additional tasks - 

- String update - change “Country” to “Country or Region”, above the corresponding drop down menu with listing.
- Maintain the localization as 'opt-in'/allow for mixed locales as in the current version of the page.

**Comment by Errolyn** [comment]
Having trouble with getting a demo working correctly but here is a screenshot for now
![Screenshot_2019-12-02 Newsletter Subscriptions](https://user-images.githubusercontent.com/1214589/70002524-1fc93d00-1515-11ea-8a74-85094a20c095.png)

**Comment by cgonz0** [comment]
> Having trouble with getting a demo working correctly but here is a screenshot for now


@Errolyn looking good. can we change all the link/button/checkbox/radio etc colors to our firefox blue (#0060df)?

**Comment by Errolyn** [comment]
Sure I will give it a go :)

**Comment by Errolyn** [comment]
@cgonz0 so after looking at it, it looks like to change the color of the checkbox I basically have to hide the checkbox then create a new one from scratch. It looks like Stephanie is already working on a component to do that. So I think it might be best to leave the checkbox as/is for and create a separate issue to port this page over to protocol, and use the new checkbox component. 

If that doesn't work I can go ahead and make a custom checkbox for this page. (We will want to think through how we want this component to look cross browser/ and os ) Either way we should probably port this page to protocol when the component is ready and use that.

**Comment by cgonz0** [comment]
hey @Errolyn - i'm looking at the existing page and all the elements are already blue. i guess i'm just wondering why these are purple in your screenshot. 
also, we would be able to change the [save preferences] button and link colors with no problem, correct?

**Comment by Errolyn** [comment]
The colors of the accent color for checkboxes, dropdowns, radio buttons etc are stylistically based on the OS, Browser and what accent the user has chosen for their OS. I have Purple as my accent color, blue is the default color so if you haven't changed your accent color it would be blue. Currently Firefox only only picks up the accent color on launch, safari picks up the color on change, and Chrome changes on launch. I don't have access to a different OS to add screenshot of how the inputs look different that way, but they look different again on both Windows 10 and between the different linux distros.

The entire style of the those element is also based on the browser +OS you can see how the page looks in Chrome:

<img width="1103" alt="Screen Shot 2019-12-04 at 9 26 30 AM" src="https://user-images.githubusercontent.com/1214589/70165782-579cc580-1678-11ea-8dbc-39ab759a520c.png">

If I switch to orange as my accent color Firefox:
<img width="1014" alt="Screen Shot 2019-12-04 at 9 31 42 AM" src="https://user-images.githubusercontent.com/1214589/70166104-f6292680-1678-11ea-9304-e0ed2f54d7c0.png">

We can definitely change other colors on the page like normal. So links and buttons etc its really just certain inputs that have limitations.

**Comment by cgonz0** [comment]
@Errolyn thanks for the clarification. cool, as long as we change the button and link colors, we should be good to go. thanks!

**Comment by Errolyn** [comment]
@cgonz0 for our checkboxes they should have a label for accessibility, should it be visible? here is what it looks like with is visible: 
<img width="656" alt="Screen Shot 2019-12-04 at 10 09 12 AM" src="https://user-images.githubusercontent.com/1214589/70168738-4787e480-167e-11ea-8531-a53a3a06a9ff.png">
This is un-styled, but we could make the text smaller or lighter etc, or I can hide the text altogether.

**Comment by Errolyn** [comment]
This would be my recommendation:
<img width="667" alt="Screen Shot 2019-12-04 at 10 29 23 AM" src="https://user-images.githubusercontent.com/1214589/70170165-ffb68c80-1680-11ea-85ca-43fb7ea36af8.png">

We remove the subscribe at the top, and leave the label using the same styling as the original subscribe.

**Comment by cgonz0** [comment]
@Errolyn thanks for exploring those options. visually works better without the labels, so if we can hide those that'd be preferable

**Comment by Errolyn** [comment]
This is what is looks like with all the changes:

![Screenshot_2019-12-04 Newsletter Subscriptions](https://user-images.githubusercontent.com/1214589/70175544-c5062180-168b-11ea-83f8-735c1931ad16.png)

**Comment by cgonz0** [comment]
looks good to me
