### ISSUE TITLE
Replace generic FxA flows with sync-optional flow

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8201]
## Description

After https://github.com/mozilla/bedrock/issues/8198 lands, we should replace any generic FxA registration flows with the sync-optional flow. This includes:

* /firefox/accounts/
* global nav
* others?

The specifications are:

In "account generic" flows like the top nav (but not in service-specific flows like sync or monitor)...
* For Fx71+, leave off the service parameter
* For Fx70 and below, keep the service parameter
* For non-Fx, leave off service and context parameters

([There is no perfect set of params](https://mozilla.slack.com/archives/C4D36CAJW/p1576098368247200) to cover the last two bullet points.)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Generic FxA registration CTAs go to sync-optional flow

#### Tasks
- [x] Determine a design that includes all user agents
- [x] Change the params on all the buttons
- [x] Ensure test coverage for the change

**Comment by alexgibson** [comment]
There may be an opportunity to pay off some additional technical debt here.

Currently, all our FxA link macros default to including `service` and `context` params. This has historically been because FxA started off life as a Firefox only service. But since then, we have started showing FxA links to all browsers. This means those linke break (the sign up form throws errors), unless we remove the aforementioned params based on user agent. We currently do that in this hacked together piece of JS: https://github.com/mozilla/bedrock/blob/master/media/js/base/mozilla-fxa-sign-in-link.js

Now, fast forward to today. Only legacy (FF < 71) desktop browsers require the `service` param. Only newer Firefox (>= 71) desktop browsers require the `context` param.

It may be simpler, overall - just to omit these parameters by default. Then all we need is a single piece of JS, used to detect Firefox browsers, which adds the appropriate params only when needed. Basically, update the JS linked above to do the reverse.

**Comment by alexgibson** [comment]
There's not much in the way of existing unit tests for this code, so I'm bumping this up to an 8 and also tackling https://github.com/mozilla/bedrock/issues/8212
