### ISSUE TITLE
Update copy for country selector in newsletter sign up form

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8223]
## Description

Per direction in https://wiki.mozilla.org/Lists_of_Countries_and_Regions, we need to update the copy on mozilla.org "Country or Region" instead of only 'Country' where on its own or coupled with 'select' where used in conjunction with the [product details region selection list ](https://product-details.mozilla.org/1.0/regions/en-US.json )

Example:  The newsletter sign up form is used across multiple pages. In the drop down, visible to non- en locale visitors (e.g. - https://www.mozilla.org/de/newsletter/), is the string 'Select country' in its various localized forms.

***Tasks***
To cover this, two strings need to be updated in the /newsletters.lang file:

- [ ] "Select country" needs to be changed to "Select Country or Region"
- [ ] "Country" needs to be changed to "Country or Region"
- [ ] Extract the new strings, make available to localizers
