### ISSUE TITLE
Update /exp/firefox/new/ with skyline branding.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8290]
## Description

We need to find a window between experiments running in order to update the page at [/exp/firefox/new/](https://www.mozilla.org/en-US/exp/firefox/new/) with the more recent [skyline branding](https://www.mozilla.org/en-US/firefox/new/).

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Experimental page is updated to match the main /new/ page.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] There's a chance that changing this mid-way through an experiment could skew results.

#### Tasks
- [ ] Update the /exp/ page for both English and German hard -coded templates.

**Comment by alexgibson** [comment]
Blocked by https://github.com/mozilla/bedrock/issues/8037
