### ISSUE TITLE
Landing pages for Browsers and Products

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#8298]
## Description

Add two landing pages, one for our browsers and one for our products.

The plan is to open all for localization. My thoughts on how to launch it is to put the pages into production for a few weeks for translation (this might take a while with the upcoming holidays) and then add the links to the navigation and other appropriate places.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] New page at firefox/browsers/ which showcases all the browsers we have
- [x] New page at firefox/products/ which showcases all the products we have
- [x] Links in header and footer added where appropriate
- [x] Other links around the site updated where appropriate

#### Tasks
- [x] Browsers page
- [x] Product page
- [x] String extraction
- [x] Nav updated (EN)
- [x] Links updated (EN)
- [x] Update Nav and links (non EN)

**Comment by amychurchwell** [comment]
String extraction PR for firefox/browsers - https://github.com/mozilla-l10n/www.mozilla.org/pull/366

**Comment by amychurchwell** [comment]
String extraction PR for firefox/products - https://github.com/mozilla-l10n/www.mozilla.org/pull/367

**Comment by rraue** [comment]
Now that the two pages are online, when do we plan to add links in the nav and footer to them?

**Comment by stephaniehobson** [comment]
They are already there in English. (the feature cards in the header, and the "browsers" link in the footer) I was going to check translations status for the other locales on Mar 6 (one month after translation was enabled).
