### ISSUE TITLE
WNP 72 - the 72 rapid release on 2020/01/07

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8299]
## Description

WNP 72 - the 72 rapid release on 2020/01/07 - we intended to reuse existing content, wholly, for this page (no new strings).

We will re-use the existing Welcome 4 page, verbatim (the .lang file)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is live by 12/27

#### Tasks
- [x] File [bug w. releng](https://bugzilla.mozilla.org/show_bug.cgi?id=1604358)
- [x] Determine content intended for the page (Welcome 4)
- [x] Remove the 'why am I seeing this' copy and link
- [x] Confirm available locales w. l10n Drivers to update releng

**Comment by ejregithub** [comment]
Closing as invalid - see #8331
