### ISSUE TITLE
Welcome 4 page updates

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8308]
## Description

We need to make some speedy updates to ensure meaningful data can be gathered with the welcome 4 page launch

SMS countries - US, DE, FR

# Locales that should display the 'Send to Device' widget
SEND_TO_DEVICE_LOCALES = ['de', 'en-GB', 'en-US',
                          'es-AR', 'es-CL', 'es-ES', 'es-MX',
                          'fr', 'id', 'pl', 'pt-BR', 'ru', 'zh-TW']

Email locales - en, de, fr, es-ES, ID, pt-BR, RU, PL, zh-TW

The campaign is going to be "Moments Page 4", creative "mobiledownload" and creative will distinguish between QR, SMS, Email links:

email: https://app.adjust.com/2uo1qc?campaign=Moments-page-4&adgroup=mobiledownload&creative=email&fallback=http%3A%2F%2Fmozilla.org%2Ffirefox%2Fmobile%2F

QR: https://app.adjust.com/2uo1qc?campaign=Moments-page-4&adgroup=mobiledownload&creative=QR&fallback=http%3A%2F%2Fmozilla.org%2Ffirefox%2Fmobile%2F

SMS: https://app.adjust.com/2uo1qc?campaign=Moments-page-4&adgroup=mobiledownload&creative=SMS&fallback=http%3A%2F%2Fmozilla.org%2Ffirefox%2Fmobile%2F

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Is live Dec 12

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Timing

#### Tasks
- [x] New Adjust links (3) for  Email, SMS, QR code
- [x] Shortened (mzl.la) URL for SMS Adjust link above - https://mzl.la/2PCKmdH
- [x] new qr code w. Adjust link from above (@amychurchwell - can you create this?)
- [ ] new S2D message set
- [ ] basket changes - @pmac can review changes made by LCM folks

**Comment by pmac** [comment]
basket changes should actually be done by the email team since they'll have to setup the new email message IDs in SFMC and Basket. I'm happy to review things though.

**Comment by hoosteeno** [comment]
The slug for this new email is `firefox-mobile-welcome`.

**Comment by hoosteeno** [comment]
@ejregithub I know we determined that the page wasn't localized in es-MX, but I think we should continue to include es-MX in the list of locales someone could send a link in, because the page will probably be localized there someday. And meanwhile, if nobody sends a link there, no problem, right? 

Does it belong on both SMS and email lists?

**Comment by hoosteeno** [comment]
The dev task here is

a) Update the message sets in https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L1248-L1322 to include the new message and related config. The slug is above.
b) Update the code on the page to include QR codes for the new adjust URLs.
c) Update the code on the page to call the send to device widget with a message set (ref: https://github.com/mozilla/bedrock/blob/60974d4425d5c4cb51c6c763c2fd1dc640ae777f/bedrock/base/templates/macros.html#L96)

**Comment by amychurchwell** [comment]
![qr-code](https://user-images.githubusercontent.com/30483988/70734409-0c5e6480-1cc1-11ea-80b3-e2d72b797c13.png)
qr code from https://mzl.la/2PCKmdH
