### ISSUE TITLE
Define a localization config for Fluent /whatsnew page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8326]
## Description

In https://github.com/mozilla/bedrock/issues/8196 we built a /whatsnew page using Fluent for L10n. Right now, it's being shown for en-US only, until we get the L10n pipeline up and running.

What's still needed for this page in the interim, is a well defined L10n configuration. The original issue cited the page being needed for English. German, and French only. Based on discussion in last weeks meeting, it sounds like that's still tbd.

We need to implement a configuration for the page, using one of the three buckets being defined in https://github.com/mozilla/bedrock/pull/8092.

This basically equates to a choice of:

- Staff
- Staff + vendor
- Staff + vendor + community

Note: we can no longer say "staff + community for everything else". Choosing staff + community would leave a vendor sized hole.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] A configuration exists for `firefox/whatsnew/whatsnew-account.ftl` and `firefox/whatsnew/whatsnew.ftl`.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [x] `firefox/whatsnew/whatsnew.ftl` contains generic strings that may be shared and reused among different /whatsnew releases. We may want to consider a broad strategy for this particular file.

#### Tasks
- [x] Implement a config for both fluent files.

**Comment by hoosteeno** [comment]
I assert the most important thing right now is to kick all the tires. Secondly, we should strive to have as few versions of WNP as possible, and so should aim to have a single fallback someday. I suggest staff+vendor+community for this page.
