### ISSUE TITLE
Show the WNP 71 content in the WNP 72 page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8331]
## Description

Show the WNP 71 content in the WNP 72 page at the Firefox 72 rapid release launch on 1/7/2020

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Attribution is updated to reflect the WNP 72 page, release

#### Tasks
- [x] Create new template w. the same content as WNP 71
- [x] Update for attribution
- [ ] Check and update locales list at 100% (@ejregithub )
- [ ] update [releng bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1604358) with new plan, list of locales if that has changed. (@ejregithub )

)
