### ISSUE TITLE
Make configuring analytics parameters in /whatsnew pages easier

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8333]
## Description

For issues such as https://github.com/mozilla/bedrock/issues/8331, where we're repurposing an existing /whatsnew template from a previous release, we need to make sure we update analytics parameters in order to track conversions.

For example:

```
{% set _entrypoint = 'mozilla.org-whatsnew71' %}
{% set _utm_campaign = 'whatsnew71' %}
```
would become:

```
{% set _entrypoint = 'mozilla.org-whatsnew72' %}
{% set _utm_campaign = 'whatsnew72' %}
```

Right now, we're hard-coding these values, which means the whole template needs to be copy / pasted in order to update the parameters. Either that, or we start defining blocks and extending templates. It's arguable which one creates less tech debt.

What might be simpler is if we start automating these parameters. We already know the version number from the URL, which gets passed in as a context variable to the template. 

Something like this may work:

```
{% set v = version.split('.', 1)[0] %}
{% set _entrypoint = 'mozilla.org-whatsnew' ~ v %}
{% set _utm_campaign = 'whatsnew' ~ v %}
```
We could make things a bit tidier by moving the logic here into the view, and expose a `{{ major_version }}` param as a context variable. We'd also need to conver edge cases such as beta, dev edition etc. 

If we set something like this up for all /whatsnew pages, it could save us a fair amount of duplication and some time for developers. When we move toward an ever green /whatsnew page, this could also be helpful in segmenting performance for each release.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] All /whatsnew pages have a context variable exposed via the view for analytics purposes.

#### Tasks
- [ ] Implement context variable.
- [ ] Write tests.
- [ ] Update /whatsnew pages to use variable where applicable.

**Comment by alexgibson** [comment]
Thoughts @hoosteeno ?

**Comment by hoosteeno** [comment]
This is good and I definitely agree.

The design should anticipate that some pages will have a different set of instrumentation. For example, the send-to-device pages have more and different instruments (qr codes, message sets, etc). It's not the case that all pages have an entrypoint. But all could be driven by `major_version`.

**Comment by alexgibson** [comment]
To solve this issue I ended up creating a set of context variables, shared automatically to all /whatsnew templates. For example:

```python
ctx['analytics_version'] = '70.0'
ctx['entrypoint'] = 'mozilla.org-whatsnew70'
ctx['campaign'] = 'whatsnew70'
ctx['utm_params'] = 'utm_source={0}&utm_medium=referral&utm_campaign={1}&entrypoint={2}'.format(entrypoint, campaign, entrypoint)
```

This means we no longer have to keep rewriting this logic in each template, and if we show a template at multiple URLs then attribution for each release should not require any further work. It should also help keep us more consistent.

When this merges there may be some slight changes to params in older /whatsnew templates, where we weren't yet conforming to our newer standards.
