### ISSUE TITLE
Moments page - Welcome/7/

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8353]
## Description

The request is to create a 'NASCAR' content page featuring all the things in the Firefox brand umbrella.

Similar to: https://www.mozilla.org/en-US/firefox/71.0/whatsnew/all/
and https://www.mozilla.org/en-US/firefox/

Project method will be Team Swarm

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### Tasks
- [ ] Determine users to receive the page and when (launch date)
- [ ] This is an example of a task.

**Comment by Deathrow77** [comment]
@ejregithub I would like to work on this subproject. Can you please elaborate on the required page a bit more?

**Comment by ejregithub** [comment]
@Deathrow77 - this in an internal project, though we definitely appreciated the offer to help.  I would suggest watching for bugs tagged with the '[Good First Bug](https://github.com/mozilla/bedrock/labels/Good%20First%20Bug)' label.  These tend to be less complex (as this issue is) tasks that a developer can work on independently.

**Comment by Deathrow77** [comment]
Thanks!!

**Comment by hoosteeno** [comment]
I reached out to Shep to understand relative priority of this work. Keeping in research.

**Comment by hoosteeno** [comment]
The NASCAR page is no longer Moments 6.

**Comment by hoosteeno** [comment]
Archiving this; it's not clear this is the direction for Moments program.
