### ISSUE TITLE
Remove legacy /firefox/mobile/ page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8371]
## Description

The new /firefox/mobile/ page is now translated by [40 locales](https://l10n.mozilla-community.org/langchecker/?locale=all&website=0&file=firefox/mobile-2019.lang), representing ~95% of our l10n user base. I think we're probably ok to remove the old page.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Legacy template is removed.
- [ ] Legacy l10n file is removed from L10n repo.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Some locales have not yet caught up. Removing the old page may hopefully encourage some to catch up.

#### Tasks
- [x] Remove old template and assets.
