### ISSUE TITLE
Remove legacy /firefox/new/ page.

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8372]
## Description

We don't yet have enough coverage to remove the old Quantum /firefox/new/ page, however I'm filing this issue now as there are several dependencies that may still block this from happening. It may make sense to tackle the below items first:

Dependencies:

- [Update platform /new URLs to trailhead design](https://github.com/mozilla/bedrock/issues/7345)
- [Simplify the /ru/firefox/new/ Yandex page](https://github.com/mozilla/bedrock/issues/7117)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Legacy /firefox/new/ template is removed.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] There are SEO implications if we lose some locales.

#### Tasks
- [ ] Remove legacy template and assets.
- [ ] Update tests.

**Comment by stephaniehobson** [comment]
Looking at this in relation to  https://github.com/mozilla/bedrock/issues/7345. I might be able to remove this template as part of that work.

I'm going to assume it's okay to remove the `scene1.de.html` and `scene1.en-BG.html` templates since we haven't been displaying them since trailhead.

**Comment by alexgibson** [comment]
Once #9202 merges we're going to have 3 /new templates and 3 /thanks templates in the repo, which from both a marketing and maintainability point of view isn't too great.

I put together a quick delta of the current and old (quantum) templates: https://jsbin.com/lutuqariko/edit?html,js,output

The results I got were:

Current template active locales: 50
Old template active locales: 69

Delta (missing locales): an, ar, ast, az, bg, bs, ca, et, gl, gu-IN, he, hi-IN, ja, ko, lo, ml, ms, rm, ta, th

@peiying2 are these locales likely to catch up ever? I'm not sure what the impact may be to lose some of these locales for such a key page, but the current template has been available for some time now.

**Comment by peiying2** [comment]
@alexgibson Please go ahead and switch to the new template whenever you are ready.

**Comment by alexgibson** [comment]
> Please go ahead and switch to the new template whenever you are ready.

@peiying2 does this mean some of the communities listed in the delta above are going to, or have caught up?

**Comment by peiying2** [comment]
> > Please go ahead and switch to the new template whenever you are ready.
> 
> @peiying2 does this mean some of the communities listed in the delta above are going to, or have caught up?

`ca`, `ja`, `ko`, `th` were added to the activated list since sending out an email remainder, bringing the total to 54 locales. In comparison:
- `firefox/new/trailhead.lang` has 47 activated locales with 44 completed updates.
- `firefox/new/quantum.lang` has 71 activated locales with 51 completed updates.

**Comment by alexgibson** [comment]
Ok, thanks you!

@hoosteeno I'm going to pick this one up, as eliminating the oldest template will make https://github.com/mozilla/bedrock/issues/9102 more straight forward.
