### ISSUE TITLE
(1/6/2020) - Update Leadership page

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8376]
## Description

Remove C. Beard from https://www.mozilla.org/en-US/about/leadership/

Update Mitchell's title to read "Chairwoman and Interim Chief Executive Officer" 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Updates are live by EOD Monday January 6th

#### Tasks
- [ ] Remove C Beard from the leadership section of mozilla.org
- [ ] Update Mitchell's title  to read "Chairwoman and Interim Chief Executive Officer"

**Comment by justinokelly** [comment]
Is it possible to complete this by end of today today please?

**Comment by amychurchwell** [comment]
@justinokelly yes, it is in our next production push. :+1:
