### ISSUE TITLE
Update branding on SEO variants of /new

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#8377]
## Description

There are three variations of the firefox desktop download page that are still using the old design:

https://www.mozilla.org/en-US/firefox/windows/
https://www.mozilla.org/en-US/firefox/mac/
https://www.mozilla.org/en-US/firefox/linux/

We should update them to use the current branding.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] New branding displays
- [ ] SEO benifits are preserved

#### ❗️Risks ❗️ 
- [ ] are there any other pages still using the blue design?

#### Tasks
- [ ] windows
- [ ] linux
- [ ] mac
- [ ] look at current structure for /new template and see if system can be simplified with retirement of blue design
- [ ] delete old assets for blue version of design if possible (yandex page?)

**Comment by stephaniehobson** [comment]
See also: #6798

**Comment by alexgibson** [comment]
Is this a duplicate of https://github.com/mozilla/bedrock/issues/7345 ?

**Comment by stephaniehobson** [comment]
Yup. 

Closing in favour of #7345.
