### ISSUE TITLE
Create new webpage on mozilla.org for the community participation hotline content

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8393]
## Description

We need to create new webpage on mozilla.org for the community participation hotline to replace https://events.mozilla.org/communityparticipationhotline, which is going away on Feb 30, 2020, and host the same content from it on the new webpage

New URL:
https://www.mozilla.org/about/governance/policies/participation/reporting/community-hotline

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] The page is live on or before February 29th, 2020

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Splash, the hosting site for the current page, is being EOLed on February 30th, 2020

#### Tasks
- [ ] Set up URL as https://www.mozilla.org/about/governance/policies/participation/reporting/community-hotline
- [ ] Assign content (all the content and links are the same, verbatim, to that of the current page) 
- [ ] Layout should be similar but need not be exact (can conform to an existing template & Protocol components)

**Comment by hoosteeno** [comment]
@craigcook does this look ready for you? If so, we can drag into ready/progress.
