### ISSUE TITLE
Migrate shared .lang files to Fluent

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8401]
## Description

Once the Fluent pipeline is active, we should migrate common shared .lang files to .ftl. This covers things that are shared among multiple pages such as the nav, footer, download button, widgets etc.

- main.lang
- footer.lang
- navigation.lang
- download_button.lang
- firefox/send-to.lang

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] All global components source their strings from Fluent.

#### Tasks
- [ ] Convert .lang files to .ftl
- [ ] Migrate templates to Fluent syntax.
- [ ] Migrate existing translations.

**Comment by hoosteeno** [comment]
Let's add to this list...
* newsletters
* send-to-device
* fxa email forms

**Comment by alexgibson** [comment]
All dependencies here are done, closing.
