### ISSUE TITLE
Remove events data from the DB

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8402]
## Description

Once https://github.com/mozilla/bedrock/issues/6461 is complete, we can then remove event data from the DB and clean up the backend code: https://github.com/mozilla/bedrock/tree/master/bedrock/events

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Event data is removed from the DB

#### Tasks
- [ ] Add table removal migration.
- [ ] Once that's in prod, remove the remaining backend code.

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/6461

**Comment by alexgibson** [comment]
@pmac fyi - the events page has been removed, so I think we should be fine to remove event data from the DB.
