### ISSUE TITLE
Default Browser Campaign Epic

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8428]
## Description

We're building a set of pages to support a default browser campaign. The pages will work together to help people understand and change their default browser setting. This epic ties all the related work together. See below for specific deliverables.

[Master project doc (WNP 73, Landing, Thanks pages)](https://docs.google.com/document/d/1CfAN9CbtwAEAR2MYKhbcXxRYjUGvdm9XDosZPKQMnTg/edit#)

[Copy for Landing Page](https://docs.google.com/document/d/12WIabDAL1iE0z2suTS9fEpA_mMgl5geVlzy8KihcA94/edit?usp=sharing)
[Copy for Thanks page](https://docs.google.com/document/d/1fbxpgFpFfPbo-E1tueXeh7z24zPplUIjGjr2anQRIfI/edit?usp=sharing)
[Copy for WNP73](https://docs.google.com/document/d/1LzZfDKW-UK-QcD3qaY59jXiwiNZTmr2adcr2-2VejV0/edit?usp=sharing) (since it's related)

Timeline:
**Monday January 13** - swarming kickoff, storyboarding the user journey
**Tuesday January 14**
- [x] First [draft copy](url) landing page - @rantley (NLinden)
- [x] First draft copy thanks page - @rantley (NLinden)
- [x] First design iteration landing page - @cgonz0 
- [x] First design iteration thanks page - @cgonz0 
- [x] Code - stubbed out landing page - @Errolyn 
- [x] Code - stubbed out thanks page - @alexgibson 
**Wednesday January 15**
- [x] Swarm during Team Time, finalize content to promote to stakeholders for review
- [x] In person review with stakeholders
**Thursday January 16**
- [x] Team QA of WIP, in person meeting morning
**Friday January 17**
- [x] PR for both pages submitted for code review - TBD Developer
Monday January 20 (US holiday)
 - [x] Code review - @alexgibson (TBD)
Tuesday Jan 21
- [x] Final changes to PR - TBD Developer
Wednesday January 22 
- [ ] go live of landing and thanks pages
