### ISSUE TITLE
Epic: Replace/Augment UA detection with Client Hints

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8440]
## Description

The user agent string will stop being an effective way to determine a user's browser sometime in 2020[0]. 

In 2021, we will likely need to use the Client Hints API[1,2] to get information about user agents. 

Much of our user agent detection is intended to answer a couple key questions: 
* Is the user agent Firefox, or not?
* Is the user agent on a mobile device, or not?

There may be a few more to add.

The answers to these questions appear to be obtainable from Client Hints.

We should be prepared for user agents to stop sending useful UA strings in 2020. One idea would be to use Client Hints where possible, and UA string where missing.

[0] https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/-2JIRNMWJ7s/yHe4tQNLCgAJ
[1] https://developer.mozilla.org/en-US/docs/Glossary/Client_hints
[2] https://wicg.github.io/ua-client-hints/

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Estimate the impact that freezing the UA string will have on www.mozilla.org
- [x] Prototype a solution that migrates bedrock to use Client Hints, falling back to UA detection when not available.
- [x] Migrate bedrock to use Client Hints _after_ Google ships the API, but _before_ the UA string freeze.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] We are unprepared for a browser that is sending Client Hints and therefore misidentify it.
- [ ] We do not know when Google will roll out these changes, or what might change in the meantime.

**Comment by alexgibson** [comment]
It's not yet clear what the implications are for mozorg on Blink's intended change. Mostly we rely on basic OS detection (Windows, Mac, Linux, Android, iOS) to serve up the correct link on download buttons. There's a chance that this information may not be effected (only OS/browser versions and more detailed date), but we should still keep a close eye on this.

Supporting Client Hints is the proposed solution to getting more fine grained data, although I'm not yet clear how that might work for bedrock, and what the implications would be.

I would also welcome us looking at where else we currently rely UA data and trying to reduce our overall reliance on it.

**Comment by alexgibson** [comment]
I've done a bit of investigating here, and it looks like there's a JS API that can provide user agent type data. This may give us enough of what we need, without requiring any server side config:

1. Download Chrome Canary
2. Open `about:flags` and enable "Experimental Web Platform features"
3. Relaunch Chrome Canary.
4. Visit https://www.mozilla.org/
5. Open the web console and paste the following:

```
navigator.getUserAgent().then(function(hints) {
    console.log(hints);
});
```

Gives the output:

```
{architecture: "Intel", brand: "Google Chrome", model: "", platform: "Mac OS X", version: "81.0.4028.0"}
```

**Comment by alexgibson** [comment]
The schedule for Google's planned freezing / deprecation of the US string has been delayed until at least 2021. This is partly due to the global situation right now, but also to give more time for the eco-system to test and give feedback. The initial implementation of Client Hints will be in Chrome 84 for testing. As such this may be put back on the roadmap, but we should still spend some time investigating and testing changes.

https://groups.google.com/a/chromium.org/forum/m/#!msg/blink-dev/-2JIRNMWJ7s/yHe4tQNLCgAJ

**Comment by alexgibson** [comment]
In the latest Chrome it looks like this has changed to

```javascript
navigator.userAgentData
```

```
NavigatorUAData {brands: Array(3), mobile: false}
brands: Array(3)
0: {brand: "Chromium", version: "86"}
1: {brand: ""Not\A;Brand", version: "99"}
2: {brand: "Google Chrome", version: "86"}
```

**Comment by alexgibson** [comment]
I tried setting the `#freeze-user-agent` flag in Chrome Canary to test the impact of these changes in Chrome:

https://web.dev/user-agent-client-hints/#what-happens-to-the-user-agent-string

When trying to download Firefox on macOS, I was presented with an .exe file for Windows. Stub attribution also happened on the download URL.

When checking my useragent I see:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.0.0 Safari/537.36`

And `navigator.platform` gives `Win32`

**Comment by alexgibson** [comment]
@hoosteeno @pmac - the impact of these changes won't be seen until some time in 2021, but we should pay close attention to this. From my testing it will very much impact our current logic in bedrock for serving downloads, unless Chrome roll back on their approach in the coming months.

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/9555

**Comment by alexgibson** [comment]
Timeline for updates: https://www.chromium.org/updates/ua-ch

Scratchpad for client side API: https://user-agent-client-hints.glitch.me/javascript.html

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/issues/9628

**Comment by alexgibson** [comment]
Ok, I've done the research detailed in #9555 and #9628.

Based on those issues I recommend the following:

- We keep an eye on Google's progress in https://www.chromium.org/updates/ua-ch, with an aim to migrating bedrock to use Client Hints some time in 2021 (assuming Google continue to move forward with the change).
- Unless Chrome's frozen UA string definitions change between now and rollout, we **will** see some pretty severe breakage of mozorg's download funnel, unless we take proactive action. We should be ready to move forward with the prototype I started in #9628.
- The LOE in terms of coding is probably a few days work (prototype needs tidying up and lacks tests), however we should also undertake a high level of QA review, which may take considerably more time.
- There's a chance we may lose some degree of information when moving to Client Hints (such 64bit / ARM architecture detection), so we should be prepared to mitigate by providing options to users downloading Firefox.

/cc @hoosteeno

**Comment by hoosteeno** [comment]
Client Hints has an intent to ship: https://groups.google.com/a/chromium.org/g/blink-dev/c/A4wxFpvqUfA/m/g7iccl9ICgAJ

Legacy UA strings have an intent to freeze: https://groups.google.com/a/chromium.org/g/blink-dev/c/-2JIRNMWJ7s/m/yHe4tQNLCgAJ

I haven't yet read the entire threads to understand if they change our approach or urgency here.

**Comment by alexgibson** [comment]
Both of these links are the original intent notifications from 2020. Looking at the latest comments in the UA string freeze thread (which is the one that is most potentially impactful to bedrock), the latest comment s provide a little further information:

> A key change is to separate the disruption of the existing technical standard and practices from the roll out of UACH. Not only is it not appropriate for one technical standard to alter another, there is a need to ensure an extensive period of parallel running to enable orderly migration.

I suggest we keep an eye on the launch timeline here also: https://www.chromium.org/updates/ua-ch

For now, I think we best hold tight and keep an ear to the ground.

**Comment by alexgibson** [comment]
Latest update here: **March 3, 2021: UA-CH is rolling out to 100% of stable population in tandem with version 89**

Checking in the latest stable Chrome, the following snippet now appears to be supported:

```javascript
navigator.userAgentData.getHighEntropyValues(["platform", "platformVersion"]).then(ua => {
    console.log(ua) 
});
```

Now we have to work out what's happening with the user agent strings, so we know a timeline for what exactly needs to be done.

**Comment by alexgibson** [comment]
> Now we have to work out what's happening with the user agent strings, so we know a timeline for what exactly needs to be done.

I asked someone on Google's Dev Rel team on the status of this, and they said that "platform" is being re-classified as low-entropy. So that _might_ mean we're not impacted by the string freeze in such a huge way any longer.

That said, this is just speculation right now and not confirmed, so we should keep a close eye on this.

**Comment by alexgibson** [comment]
Updates to high/low entropy values coming in https://groups.google.com/a/chromium.org/g/blink-dev/c/dafizBGwWMw/m/72l-1zm6AAAJ

**Comment by alexgibson** [comment]
We finally have an update on UA string freezes https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html

**Comment by alexgibson** [comment]
Proposed rollout plan for UA reduction (with example UA strings): https://www.chromium.org/updates/ua-reduction

I still need to find time to read through this properly, but at first glance it looks like it may not be as destructive as first feared (a unified platform name will still be preserved, which is the main thing we rely on). Things related to CPU and architecture are still effected though.

**Comment by alexgibson** [comment]
I spent a little time reading up on the changes, and it looks like the impact of the UA string freeze will be lessened for bedrock, although not mitigated entirely. The new changes boil down to:

- Platform (e.g. `Windows`, `Mac OSX`, `Linux`) is no longer considered a high entropy value. The correct platform will still be preserved in the UA string. This means that bedrock should still detect the right platform for downloading Firefox without any changes.
- Platform _version_ is being frozen for across all UA strings for each platfrom. This means we would need to use the new Client Hints JS API to detect things like Windows 10 accurately. In some places (such as `/download/thanks/`) we try to detect the version of Windows in order to display additional information to help users install.
- Things like CPU / Architecture are also being frozen, and will require the new API. This might effect things such as Linux download, where we try to detect 32/64bit architecture.

There is currently ongoing discussion on whether all this information should be accessible by default using the new JS API, or if it should be a permission based feature policy.

**Comment by alexgibson** [comment]
See also: https://github.com/mozilla/bedrock/issues/11799

**Comment by alexgibson** [comment]
I've been talking a bit on this with Chris Peterson, who is a module peer for Firefox's User-Agent string. It sounds like Firefox is going to implement the Client Hints JS API in addition to Chrome, although that might not be before Chrome's UA string freezes take place. He agrees that a sensible approach here will be to:

1. Feature detect Client Hints and use that if available, for areas where we need (e.g. CPU arch).
2. For browsers where Client Hints is not supported, fall back to the existing UA string methods.
3. For information that is still currently reliable via UA string cross-browser (e.g. platform name), continue to use existing UA string methods.

This will need to happen in Q3, ahead of Chrome 107 which launches Oct 25.
