### ISSUE TITLE
Implement client side error reporting

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8444]
## Description

Bedrock doesn't currently have any form of client side error reporting, so we have no idea when or where JavaScript errors are occuring, unless they are lucky enough to be caught by functional tests.

We should do an evaluation of client side error reporting tools and look at what might be applicable to bedrock. For example, we already use [Sentry](https://sentry.io/welcome/) on the backend, but don't have the client side reporting tool enabled. If third-party tools aren't an option (e.g. due to our websites privacy policy), then we could also look to implement a (crude) first-party reporting mechanism.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Choose and implement an appropriate client side reporting tool.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Chosen will need to comply with our websites privacy policy.

#### Tasks
- [ ] Evaluate the options available.
- [ ] Implement a solution.

**Comment by alexgibson** [comment]
@pmac I'd like to investigate the possibility of enabling client side error reporting in a tool that we use today (i.e. Sentry).

I've had a look back through git history, and I can't see any code or issues to suggest that we've ever enabled this in the past. Do you know of any reasons why we don't use it? Was it because of a prior security review perhaps?

I did find issues relating to using the New Relic JS client at one point, but that got removed later: https://github.com/mozilla/bedrock/pull/3631

**Comment by pmac** [comment]
I think we might have to discuss that with the team that runs our Sentry instance. If we were to introduce a JS error on a popular page we could DDOS the service if it's not prepared for that much traffic. We'd probably also have to request changes to the websites privacy policy if Sentry isn't already in there. It does seem worth investigation though.

**Comment by pmac** [comment]
Seems like we could get started testing it though. The [docs for client-side integration](https://docs.sentry.io/platforms/javascript/) seem pretty straight forward.

**Comment by pmac** [comment]
And this would be all 1st party, so no need for the DNT wrapper.

**Comment by alexgibson** [comment]
Thanks. It's definitely not part of our websites privacy policy currently, but it would be great to better understand if using the JS client is an option for us. 

If using a third-party tool may be an issue, the other option is for us to catch errors in a GA event. Whiulst this would certainly be easy enough to implement, the built-in reporting that Sentry offers is what I think would be most useful.

**Comment by alexgibson** [comment]
@pmac given the unknowns on if Sentry might now be able to withstand our traffic load, I'm tempted to press on with a simpler implementation to catch errors in GA. Do you think that might be the better (low cost) solution here?

**Comment by pmac** [comment]
I'm pretty sure it would handle the load, but you could ask that team. I don't know what a GA solution would look like. Would it even be that useful?

**Comment by alexgibson** [comment]
> but you could ask that team 

Which team do we need to speak to?

> I don't know what a GA solution would look like. Would it even be that useful?

Certainly better than the alternative, which right now is like a black box :)

**Comment by alexgibson** [comment]
Talking in infraeng it sounds like the Sentry instance has a rate limit of 108K per hour, and anything above that is dropped. There's a potential that www.mozilla.org could hit that limit (for example an error on a /whatsnew page), but the risk to the Sentry service itself should be mitigated.

If we do go with Sentry, we should put it behind a feature switch so we can toggle off quickly if needed. We should also alert `wezhou` (Slack handle) if and when we plan to enable it in production.

**Comment by hoosteeno** [comment]
[RRA bug filed.](https://bugzilla.mozilla.org/show_bug.cgi?id=1655162)

**Comment by hoosteeno** [comment]
@bensternthal  suggests we might want to use papertrail instead of sentry, which we also already use. He invited questions/conversation on this. 

https://www.papertrail.com/

**Comment by pmac** [comment]
I've never looked into what else papertrail can do I guess, but we use it for our logs, not errors. I don't understand how logging can help us here.

**Comment by alexgibson** [comment]
I think there's also value in having a unified interface (and reporting mechanism) for both front and back-end errors. Sentry is something the devs are familiar with (for example discovering template related errors), so also using it for JS seems like one less place to check / system to learn.
