### ISSUE TITLE
Port /about/leadership/ page to Protocol

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8503]
## Description

The leadership page is built using Pebbles. We need to port it to Protocol whilst stil retaining the same basic functionality.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is updated in production to use Protocol

#### Tasks
- [ ] Update template, scss.
- [ ] Remove any stray assets.
- [ ] Update functional tests.
