### ISSUE TITLE
Port manifesto pages to Protocol

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8504]
## Description

The /about/manifesto/ and /about/manifesto/details/ pages are still using Pebbles and need porting to Protocol.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Both pages are updated in production to use Protocol.

#### Tasks
- [x] Update templates and scss.
- [x] Remove any stray assets.
- [ ] Update tests?
