### ISSUE TITLE
Port /moss/ pages to Protocol

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8505]
## Description

The /moss/ pages are still using Pebbles and need porting to Protocol.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Pages are updated in production to use Protocol.

#### Tasks
- [x] Update templates and scss.
- [ ] ~Remove any stray assets.~
- [ ] ~Update tests?~
