### ISSUE TITLE
Port /contact/ pages to Protocol

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8506]
## Description

The /contact/ pages are still using Pebbles and need porting to Protocol.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Pages are updated in production to use Protocol.

#### Tasks
- [x] Update templates and scss.
- [x] Remove any stray assets.
- [x] Update tests?
