### ISSUE TITLE
Migrate /firefox/all/ to Fluent

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8511]
## Description

Once the legacy .lang L10n system is frozen, we need to prioritize migrating /firefox/all/ to Fluent, so that we can add locales to support new Firefox builds.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] The main /firefox/all/ page is updated in production using Fluent.
- [x] All existing translations are migrated from .lang to .ftl

#### Tasks
- [x] Convert .lang file to .ftl.
- [x] Convert Jinja template to use Fluent syntax.
- [x] Migrate translations to .ftl.

**Comment by alexgibson** [comment]
Blocked by https://github.com/mozilla/bedrock/issues/8401

**Comment by alexgibson** [comment]
@hoosteeno we're ready to go here code-wise. Any opinions on when we should merge this? Once we do, no new strings could be added to the page until Fluent is activated in Pontoon (really we should be resisting adding new strings anyway seeing as we're so close).

**Comment by hoosteeno** [comment]
The "switch" to Fluent will happen 2020-05-22. I don't think we have many likely string changes on most of the pages in our first migration, so we could theoretically merge any time. But what if the "switch" isn't flipped for some reason -- what happens to content we've migrated?

If reverting to .lang is not hard, then we can merge at our leisure. But it seems safer to me to merge on/around 5/22. Do you agree?

**Comment by alexgibson** [comment]
> If reverting to .lang is not hard, then we can merge at our leisure. But it seems safer to me to merge on/around 5/22. Do you agree?

Ok, let's merge this 5/22 👍
