### ISSUE TITLE
Build an /ru-RU/ homepage

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8512]
## Description

In https://github.com/mozilla/bedrock/issues/7117 we have settled on building an `/ru-RU/firefox/new/` download page to support promoting Yandex. In order for crawlers to find that content, we also need to:

- [ ] Enable `/ru-RU/` as a supported locale in bedrock.
- [ ] Build an `/ru-RU/` homepage (this can be identical to https://www.mozilla.org/ru/).
- [ ] Add `/ru-RU/` to the locales page for crawlers: https://www.mozilla.org/locales/

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] `/ru-RU/` homepage is enabled in production.
- [ ] `/locales/` page is updated to link to the new homepage.

#### Tasks
- [ ] Enable locale and activate homepage translation.
- [ ] Update `/locales/` page.

**Comment by rraue** [comment]
One addition to the homepage /ru-RU/: in the nav the link to /new/ needs to be /ru-RU/firefox/new/ not /ru/firefox new, all other links can go to the /ru/ fallback. Is that possible?

**Comment by alexgibson** [comment]
If a page is localised for /ru-RU/ then a link will navigate to that same locale. If not, we respect a user’s accept language header, and they will be redirected to the next best match in their locale list. That means it will not necessarily go to /ru/ for other pages, but it is likely that Russian language users will have /ru/ in their language preference list.

**Comment by rraue** [comment]
@alexgibson Great, thats how we should keep it then.

**Comment by alexgibson** [comment]
Closing as wontfix, as per #7117
