### ISSUE TITLE
Scale Structured data to tier 1 locales

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#8522]
## Description

We want to scale our structured product data to all locales (currently only on en-US). To integrate this on our locales, we need to automate some changes to the json files the data is based on, the urls are locales specific. To be precise some data is only language specific, not locale specific and some are locale specific:

I will try to catch all changes here and we need to discuss what's in scope so we can ship V1. IDs, URLs and sameAs: wikipedia MUST be localized, all other references should be but the system will (partly) work incomplete as well.

## IDs
All ids need to be specific to the locale. 

For example ` "@id": "https://www.mozilla.org/#firefoxlockwise",` stays like it is on en-US, but en-CA will get ` "@id": "https://www.mozilla.org/#firefoxlockwise-en-ca",`

For de it would be `"@id": "https://www.mozilla.org/#firefoxlockwise-de",`

For pt-PT it will be `"@id": "https://www.mozilla.org/#firefoxlockwise-pt-pt",` and for pt-BR it will be `"@id": "https://www.mozilla.org/#firefoxlockwise-pt-br",`. As pt only is part of our hreflang but does not resolve in a status code 200 itself it will not have any id. 

## URLs

URLs point always to the locale specific url

For example ` "url": "https://www.mozilla.org/en-US/firefox/lockwise/",` stays like it is on en-US, but en-CA will get ` "url": "https://www.mozilla.org/en-CA/firefox/lockwise/",`

For de it would be `"url": "https://www.mozilla.org/de/firefox/lockwise/",`

## sameAs

Not all urls in the sameAs need to be altered. Only wikipedia, amazon and playstore/appstore links need to be language (not locale) specific):

For wikipedia we just alter the subdomain to fit the language part of our locales:

for en-US, en-CA and en-GB it will be all `"sameAs": [
      "https://en.wikipedia.org/wiki/Firefox_Lockwise",`

for de it will be `"sameAs": [
      "https://de.wikipedia.org/wiki/Firefox_Lockwise",`

For pt-PT and pt-BR it will be`"sameAs": [
      "https://pt.wikipedia.org/wiki/Firefox_Lockwise",`

I know that some of these links will not work, as the wikipedia pages do not exist, but right now I cant think of any workaround which would complicate everything by far and I am sure that not resolving links will be just ignored.

For the playstore links we have to just add &hl=language at the url:

for en-US, en-CA and en-GB it will be all `"sameAs": [
      "https://play.google.com/store/apps/details?id=mozilla.lockbox&hl=en",`

for de it will be `"sameAs": [
      "https://play.google.com/store/apps/details?id=mozilla.lockbox&hl=de",`

For pt-PT and pt-BR it will be`"sameAs": [
      "https://play.google.com/store/apps/details?id=mozilla.lockbox&hl=pt",`

Appstore: TBD as their hreflang setup is a bit weird and I need to map it to ours.
Amazon: TBD as their hreflang setup is a bit weird and I need to map it to ours.

## Pages we need to localize structured data on:

- Homepage
- /new
- /mobile
- /mac
- /linux
- /windows
- /developer
- /channel/desktop
- /enterprise
- /lockwise

But the "system" we build should work on all pages, whenever we include structured data in a new /en-US/ (planned is /firefox and any "new" product pages on bedrock)

## Example include on /moz.org/de/

File: [moz_org_de_structured_data.txt](https://github.com/mozilla/bedrock/files/4199498/moz_org_de_structured_data.txt)

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

#### Tasks
- [ ] Check all existing structured data and make sure all urls are locale based (currently some are for testing purpose pointing to the redirect without a locale)

- [ ] Define how we will technically scale and automate this so we do not need json files for every single locale if possible

**Comment by alexgibson** [comment]
@rraue are there any English strings in this data that aren't just product names? If so, we need to think about how we'd manage that. Or alternatively try and minimize English copy where possible.

**Comment by rraue** [comment]
@alexgibson Right now not and as Focus/klar isnt in as well, I think we can think about this sometiems in the future if we want to add descriptions but for now there is only the product/Brand/organisation names and they are as far as I know global.

**Comment by rraue** [comment]
I am still thinking about how to handle sumo, amazon, appstore links but if we get IDs, selfreference urls and wikipedia right, that would be a good start. Imo we cant break anything, as "wrong" data will be just ignored.

**Comment by alexgibson** [comment]
I do see examples of english copy in the JSON:

- https://github.com/mozilla/bedrock/blob/master/bedrock/base/templates/includes/structured-data/organizations/mozilla-corporation-organisation.json#L8
- https://github.com/mozilla/bedrock/blob/master/bedrock/base/templates/includes/structured-data/software/firefox-enterprise-software.json#L9-L10

For the product names, we could potentially remove "for" and just have "Firefox Enterprise" for example. For the Mozilla related copy, this is going to be harder to simplify.

**Comment by alexgibson** [comment]
> I am still thinking about how to handle sumo, amazon, appstore links but if we get IDs, selfreference urls and wikipedia right, that would be a good start. Imo we cant break anything, as "wrong" data will be just ignored.

For sites like SUMO and wikipedia, could we just omit the locale altogether, and allow their own language detection to handle things? This is the same for how we link to sites from within mozorg pages.

**Comment by rraue** [comment]
> For the product names, we could potentially remove "for" and just have "Firefox Enterprise" for example. For the Mozilla related copy, this is going to be harder to simplify.

These are just alternate names and we can ignore this, its just an additional reference more important in English than in German, as there are more names flowing around.

> For sites like SUMO and wikipedia, could we just omit the locale altogether, and allow their own language detection to handle things? This is the same for how we link to sites from within mozorg pages.

Unfortunately not, as these are references and not links. So if it doesn't match, data will be just ignored. But wikipedia and sumo are "easy" as wikipedia is just using language, so we link to the language of our locales and sumo has sort of the same system like us and always a fallback if the locale is not available.

**Comment by hoosteeno** [comment]
This looks ready to me. I'm moving to ready column. Please holler if you disagree.

**Comment by alexgibson** [comment]
I've updated the title  to reflect that we agreed on targeting tier 1 locales for this work as our KR.

**Comment by alexgibson** [comment]
@rraue this is still a rough proof of concept for now, but can you please review the data on the homepage for these locales:

- [ ] https://www-demo2.allizom.org/en-US/
- [ ] https://www-demo2.allizom.org/en-GB/
- [ ] https://www-demo2.allizom.org/en-CA/
- [ ] https://www-demo2.allizom.org/de/
- [ ] https://www-demo2.allizom.org/fr/

If things look good, then I'll look to expand this out to other pages.

Some things to take note on:
- [ ] Do all the mozorg URLs contain the correct locales?
- [ ] Are the ID's all well formed?
- [ ] Are all SUMO links correct?
- [ ] Are all Wikipedia linke correct?
- [ ] Are app store links correct?

**Comment by rraue** [comment]
Yes everything looks fine for this scope.

**Comment by alexgibson** [comment]
After some discussion with @rraue, we think it is likely safe to open this to all locales, given some caveats:

- Locales for bedrock don't necessarily map 1:1 with other sites. This means that for some external URLs, such as Wikipedia and SUMO, there's a chance the destination might return a 404. Given that this data is for crawlers only, this risk is probably ok. Some data is better than no data at all for a locale.
- For app store and play store links, they should fall back to English should a country or translation not be supported.
- There is some English copy in the data, [such as here](https://github.com/mozilla/bedrock/blob/master/bedrock/base/templates/includes/structured-data/organizations/mozilla-corporation-organisation.json#L8). This shouldn't pose too much of an issue for crawlers however, and should not be a blocker to moving forward.

**Comment by alexgibson** [comment]
@rraue some of this might be beyond the scope of this issue, but I have some questions on the current data:

1. The following json files are not used anywhere:
  - firefox-fire-tv-software.json
  - firefox-lite-software.json
  - firefox-lockwise-software.json
  - firefox-monitor-software.json
  - firefox-send-software.json

Should they be included somehere, if they are still needed? I'm guessing the data missing at `/firefox/lockwise/` could be considered a bug.

2. There's no data at all at `/firefox/`. Is that expected?

3. We have data at `/firefox/products/` but it seems somewhat unrelated to the content of the page:

- firefox-browser-software.json
- firefox-beta-software.json
- firefox-developer-software.json
- firefox-enterprise-software.json

**Comment by alexgibson** [comment]
@rraue this is now deployed on demo2 for all locales. Can you please help test?

https://www-demo2.allizom.org/

**Comment by rraue** [comment]
@alexgibson  On non-Tier 1 locale-homepages structured data is missing. Besides that it looks exactly as expected.

**Comment by rraue** [comment]
> The following json files are not used anywhere. Should they be included somehere, if they are still needed? I'm guessing the data missing at /firefox/lockwise/ could be considered a bug

We decided for simplicity to not nest them together but include them all in the organisation schema as right now they are used just on the homepage. But yes lockwise should be on the lockwise page, it was moving when we included the data. I will file an separate issue about this. The other files we should keep as we will need them at some point (for example on the new products page you ask about in 3.)

> There's no data at all at /firefox/. Is that expected?

That page changed as well exactly when we included the data. I will file an issue.

> We have data at /firefox/products/ but it seems somewhat unrelated to the content of the page:

You are right, I will file an issue to include only data shown on the page. /browsers/ is online as well and should have structured data as well.

We shouldnt include these fixes in this issue, as I think it solves the locale problem, so if we later add or delete one piece of structured data it will be automatically added or deleted from all other locales as well, am I right @alexgibson?

**Comment by rraue** [comment]
@alexgibson and I talked offline and we need to update /firefox, /lockwise and /products in order to test the changes in this issue:

- [ ] Include firefox-lockwise-software.json on /lockwise 

- [ ] Include on /products the following:

- firefox-monitor-software.json
- firefox-browser-software.json (is already included, if I see this right)
- firefox-lockwise-software.json
- firefox-send-software.json

- [ ] Delete on /products & /browsers the following (as they are already in browser-software included:

- firefox-beta-software.json
- firefox-developer-software.json
- firefox-enterprise-software.json

- [ ] Include on /firefox the following:

- firefox-monitor-software.json
- firefox-browser-software.json
- firefox-lockwise-software.json
- firefox-send-software.json

**Comment by alexgibson** [comment]
@rraue demo is now updated with the changes listed above. Can you please verify if this looks ok?

https://www-demo2.allizom.org/

Thanks for all your help!

**Comment by rraue** [comment]
@alexgibson Looks all great!
