### ISSUE TITLE
Add Edge browser to automation functional test runs

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8526]
## Description

MS Edge browser is now [supported in Saucelabs](https://saucelabs.com/platform/supported-browsers-devices) on Windows 10. We should include it in our functional test runs, with a longer term aim to relegating IE to sanity tests.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Pipelines include passing MS Edge test runs.

#### Tasks
- [ ] Update pipeline config.
- [ ] Update tests where necessary.

**Comment by alexgibson** [comment]
PR to add edge to `run-integration-tests` https://github.com/mozmeao/www-config/pull/266

Once we're happy / confident we can looks to add edge to dev/stage/prod pipelines.

**Comment by alexgibson** [comment]
Successful test run for Edge: https://gitlab.com/mozmeao/www-config/-/jobs/575269549

**Comment by alexgibson** [comment]
I've added Edge to our test runs for Dev. Over the next few days I'll keep an eye on stability and run times. When things seem good I'll add this to the config for stage / prod.

https://github.com/mozmeao/www-config/compare/701e7fd8b364...73d3f093d239
