### ISSUE TITLE
Epic: Fix broken funnels on Enterprise page

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8529]
## Description

This is an epic.

The page at www.mozilla.org/firefox/enterprise serves a variety of download intents with a lot of links. Several of those links need to be improved. This issue describes a list of problems to solve. We can solve these with quick fixes to links, but before doing so, let's have a designer review the page for more elegant (but still efficient) improvements.

This page must:

* Attract and handle organic traffic looking for variations on "esr", "enterprise" and (sometimes) "msi"
* Help people download Firefox Desktop (any platform), Firefox ESR (any platform), Firefox MSI (windows platform), and Firefox PKG (mac platform) installers
* Make those downloads *measurable* if possible
* Link people to lots of platform-specific install instructions

We need to accomplish the following:

Design:
* A light design for [the "Download" section](https://www.mozilla.org/en-US/firefox/enterprise/#download) that distinguishes download _actions_ from content link clicks
* Note: MSI, PKG, and ESR downloads are actually links to e.g. /firefox/all page. Should they be buttons here, or links? 

Development:
* Implementation of designs provided above
* Links to things that can be downloaded from our site should go to the place on our site where you can download them (e.g. all MSI links, ESR links should go to /all)
* Links to actual downloads should be instrumented to be measurable -- this may mean simply using the standard download button macros on release download links.
* UTM parameters on all referrals other *.mozilla.org sites (e.g. SUMO, ftp) which appear all over the page: `utm_source=mozilla.org-enterprise&utm_medium=referral&utm_campaign=enterprise`
* .lang strings extracted (or, possibly, Fluent configuration) so this page is localizable by community
* Food for thought: Should we augment [/all page logic to allow pre-population of MSI downloads from links on /enterprise](https://github.com/mozilla/bedrock/blob/9a309cacbc5bf9494003313b5845aca3663f8db0/bedrock/firefox/templatetags/helpers.py#L258-L269)?

Cards attached to this epic will track work corresponding to the above.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Enterprise page distinguishes between actions and links in the download section
- [ ] Enterprise page includes appropriate links to downloads, on www wherever possible
- [ ] Enterprise page links to owned external sites include UTM parameters
- [ ] All actual downloads occurring on Enterprise page are measured
- [ ] Strings are localizable
