### ISSUE TITLE
Remove legacy /whatsnew templates

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8538]
## Description

The following /whatsnew templates are now pretty old and can likely be removed:

- https://www.mozilla.org/en-US/firefox/67.0/whatsnew/all/
- https://www.mozilla.org/en-US/firefox/67.0.5/whatsnew/all/
- https://www.mozilla.org/en-US/firefox/68.0/whatsnew/all/
- https://www.mozilla.org/en-US/firefox/69.0/whatsnew/all/

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Templates are removed in production, falling back to the default /whatsnew template.

#### Tasks
- [x] Remove old templates and assets.
- [x] Update tests.
- [ ] Remove .lang files from L10n repo.
