### ISSUE TITLE
Migrate 404 and 500 pages to Fluent

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8591]
## Description

Once https://github.com/mozilla/bedrock/issues/8407 is completed, the L10n team would like to test their new pipeline by migrating the pages to Fluent.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Pages are updated in production to use Fluent for translation.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] There may be a delay in getting translations back whilst they test the system.

#### Tasks
- [ ] Migrate .lang files to .ftl
- [ ] Migrate templates.
- [ ] Expose strings.

**Comment by alexgibson** [comment]
This page isn't suitable as we need to test the vendor pipeline, closing.
