### ISSUE TITLE
Browser comparison for Brave

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8617]
## Description

- Include Brave in the main comparison page
- Create a 1:1 browser comparison page for Brave

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Main comparison page is updated w. Brave information
- [ ] New 1:1 browser comparison page for Brave is live

#### Approvers
- [x] PMM - Tyler Ahn
- [x] @rraue 
- [ ] @hoosteeno 
- [ ] Eddie I (Accountable/Approver)

**Comment by alexgibson** [comment]
Page is live: https://www.mozilla.org/en-US/firefox/browsers/compare/brave/
