### ISSUE TITLE
Migrate /features to Protocol

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8686]
## Description

- [ ] Design: Produce comps for migrating /features to Protocol
- [ ] Copy: Rewrite copy as required to match/fit in new design
- [ ] Code it

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Pages are migrated and live

#### Approvers
- [ ] Team Lead
- [ ] Brand (Copy/Design)
- [ ] UX ?

**Comment by ejregithub** [comment]
@Errolyn -are all the tasks child to this epic complete, can we close this out?
