### ISSUE TITLE
WNP 76 Epic

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8709]
## Description

The content is TBD

WNP 76 Release is May 5th

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Swarming is kicked off on April 13th
- [ ] The page is live by April 25th

#### Approvers
- [ ] Accountable - MWarther
- [ ] Brand - Clio/Natalie
- [ ] Team Lead - Hoosteeno

**Comment by alexgibson** [comment]
Looks like all dependent issues are closed here
