### ISSUE TITLE
Port old /features pages to Protocol

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8712]
## Description

Port old /features pages to Protocol so we can kill off Pebbles

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### Tasks
- [ ] This is an example of a task. Use a checklist!
- [ ] This is an example of a task.

**Comment by hoosteeno** [comment]
Duplicate: https://github.com/mozilla/bedrock/issues/8685
