### ISSUE TITLE
Create a banner for MOSS Covid-19 grants

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8728]
## Description

In https://github.com/mozilla/bedrock/issues/7185 we made the Foundation fundraising banner more reusable. Let's reuse it to enable a banner on the MOSS page and subpages at www.mozilla.org/moss/*. The banner...

* Is in en-US only.
* Contains some text: 

> Mozilla has announced the creation of a COVID-19 Solutions Fund as part of the Mozilla Open Source Support Program (MOSS). Through this fund, we will provide awards of up to $50,000 USD each to open source technology projects which are responding to the COVID-19 pandemic in some way. For more information, [see this blog post](https://blog.mozilla.org/blog/2020/03/31/moss-launches-covid-19-solutions-fund/).

* Links to a blog post. 
* Needs light design, no copy.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Banner is designed, design is approved by devs and attached to design issue
- [x] Banner is launched in en-US ASAP after 4/1

#### Issues
- [x] MOSS-Covid: Light design
- [ ] MOSS-Covid: Code

**Comment by mehan** [comment]
Thanks for this, @hoosteeno! If it's not too late, I'd like to request a small edit to the copy that you included above: it would be great for it to read "awards of up to $50,000 USD each". There was some confusion around that line in the blog post and just want to make sure we're being clear. Thanks!

**Comment by hoosteeno** [comment]
Updated specs with that text change and with the link to blog post.

**Comment by mehan** [comment]
Hi @hoosteeno--any updates or an ETA on when this might land? Thanks!

**Comment by hoosteeno** [comment]
The design issue is underway, and code can probably happen next week.

**Comment by hoosteeno** [comment]
This is live in production:

https://www.mozilla.org/en-US/moss/

**Comment by craigcook** [comment]
The banner is live now: https://www.mozilla.org/moss/

**Comment by craigcook** [comment]
Jinx!

**Comment by mehan** [comment]
Looks great--thanks, all!

**Comment by mehan** [comment]
Hi @hoosteeno--it looks like we are going to announce the closing of this fund on Monday. Could we please remove this banner from the site as well? Thanks!
