### ISSUE TITLE
Epic: Monitor landing page

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8799]
## Description

We should write copy for, code, and launch a Monitor landing page on www.mozilla.org/firefox/monitor. 

The page should be built using a layout of components that we can reuse for future product pages. If it is derived from the future state of /new, all the better. 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is designed and approved by brand, dev, PM, product marketing 
- [ ] Page is instrumented to allow comparison with existing Monitor page
- [ ] Page includes a CTA that works exactly as CTA on monitor.firefox.com
- [ ] Page is built and opened for localization
