### ISSUE TITLE
Update and relaunch Browser Comparison Pages

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8811]
## Description

We need to update the browser comparison pages to the current release of each competitor and reflect the latest features in them.

We should update the copy in each page as specified in copy docs. 

Here is the latest [comparison table](https://docs.google.com/spreadsheets/d/1dyxx-M27jpit4RKStXxR54kkBN1sa9Tbca2a8MionKc/edit#gid=1512926430) vetted by PMM (Tyler Ahn)

Here is a[ listing of links](https://docs.google.com/spreadsheets/d/1UrSn0qR24sI6cdhNVF2fri3aAQr5YdNC2l6DvvSUeIQ/edit#gid=0) to all the things germane to this work

We should go in this order:

* Update all the browser-specific pages
* Update the main page 
* Relaunch the content
* (Migrate to Fluent)
* Build additional pages (e.g. Brave)

Link to [decisions document](https://docs.google.com/document/d/1bOQV23eZDI7AFaRISv9w-fEH3ZPG8KDKk10dLN-QTiI/edit)

---

#### Success Criteria
- [ ] Content is updated & browser versions are prominent

#### Approvals
- [ ] (C) Product: Arthur Edelstein for PrivSec sections
- [ ] (C) Product: Rachel Tublitz & Romain Testard for utility & portability sections
- [ ] (C) - Brand Design: Clio
- [ ] (C) - Brand Copy: Natalie
- [ ] (C) - PMM: TBD
- [ ] (R) - Websites Team Lead: Hoosteeno
- [ ] (A) - TBD

**Comment by hoosteeno** [comment]
@ejregithub Can you add a link to the doc where we captured our copy suggestions?

@rantley Can you update with status on this? How long until we have copy to code? We need to understand timing because our Fluent l10n system is coming online in 2 weeks.

**Comment by ejregithub** [comment]
@hoosteeno - here's that doc (added in the description to this card as well)
https://docs.google.com/document/d/1bOQV23eZDI7AFaRISv9w-fEH3ZPG8KDKk10dLN-QTiI/edit

**Comment by craigcook** [comment]
The pages are live as of 26 June 2020
