### ISSUE TITLE
Epic: Mobile banner takeover

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8821]
## Description

The CRO team ran [an experiment](https://airtable.com/tblO5zD4uNk7ISyG0/viw0HBtxscjMUuaCt/rec6HIbXwsahK8OI9?blocks=hide) that put a large, highly visible banner at the top of /new for all mobile visitors. This experiment showed a notable improvement in on-page conversions (i.e. clicks to app stores) for the treatment. We should write **copy** for, **design**, and **code** an on-page banner for the /new page to show to mobile visitors. The initial designs are available for inspiration.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Banner is designed using systems (such as banner system and protocol design system)
- [x] Approved by copy, devs, brand, and PM
- [x] Coded, launched, available for l10n
