### ISSUE TITLE
Epic: Social Proof Blocks

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8822]
## Description

The CRO team added a social proof block to release notes pages and the pages that included social proofs saw more downloads. We should figure out how to make "Social Proof Blocks" a permanent part of the website, for inclusion in pages like Release Notes and elsewhere. 

The first steps of this epic relate to specifying a system and program that will support this work. Building will come later. 

Questions:
* How do we keep these fresh?
* Where might we display them?
* How do we make them reusable, if desired?

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Key questions about the feature are resolved
- [ ] Feature is designed, including program/system work necessary to maintain it
- [ ] Feature is built in code
- [ ] Feature is populated with initial content
- [ ] Feature is released

**Comment by justinkropp** [comment]
Pulling from our conversation in Slack, I do think it'd be great to have a canonical source of social proof points that we could pull into various places throughout the site: create once, publish everywhere. 

This social proof block should be made into a component in protocol, which would give us the ability to quickly pull both the quote and the block together.

If the collection of social proof points is public, we could include a link back to this collection in the social proof block itself.
