### ISSUE TITLE
(Epic) Experiment : Test upstream CTR on www.firefox.com URLs

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#8843]
## Description

This experiment proposes to test whether a page on www.firefox.com has more pull than a page on www.mozilla.org among upstream audiences (e.g. search engine users and social users).

In order to test that, we'll stand up two identical campaign pages, both of which can be straight copies of /new. One of the pages will live at a campaign URL on www.mozilla.org (e.g. www.mozilla.org/campaign/download-firefox). The other page will live at a temporary URL on *.firefox.com (e.g. www.firefox.com/download-firefox). We'll buy ads on platforms where the URL of the destination is apparent (e.g. search engines, Reddit) and measure whether the click through ratio (CTR) on those upstream sources is different depending on the URL.

https://docs.google.com/document/d/1WoJbs4vZvKO1sdO7P_A9rs_hPlJS6OuUw_QAQ9VWTVk/edit#

---

#### Test Plan

TKTKTK

#### Tasks
- [ ] Build experiment plan https://github.com/mozilla/bedrock/issues/8844
- [ ] Figure out how to build content on *.firefox.com
- [ ] Build/deploy content
- [ ] Front-end QA of deployed page at firefox.com (browser & performance testing).
  - [ ] Is the firefox.com page serving downloads correctly to the browsers we support.
  - [ ] Do both pages perform equally enough for an experiment (using WebPageTest).
- [ ] Make ad buy plan
- [ ] Buy ads 
- [ ] Analyze
- [ ] Clean up/redirect content (to /new)

**Comment by hoosteeno** [comment]
@pmac Could you give this issue a look and let us know the best way to accomplish the *.firefox.com work proposed? Thanks!

**Comment by pmac** [comment]
IT currently hosts www.firefox.com. We're discussing options with them now. I'll get back to you next week when we have a chance to figure some things out.

**Comment by ziegeer** [comment]
@hoosteeno we're looking at hosting options for this. What requirements would you have aside from hosting a single static page on www.firefox.com and also serving the existing www.firefox.com redirects?  Would you also want the page on firefox.com?  Do you need webserver logs or other types of analytics?

**Comment by ejregithub** [comment]
@alexgibson to add info about how this will be tested

**Comment by metadave** [comment]
just a quick note: MozMEAO is in the process of migrating www.firefox.com to our own infra: https://github.com/mozmeao/infra/milestone/46

**Comment by hoosteeno** [comment]
@metadave is there any update on https://github.com/mozmeao/infra/milestone/46 timing?

**Comment by metadave** [comment]
@hoosteeno "soon", we're working on scheduling + security with IT this week. I will let you know when we have a firm date.

**Comment by pmac** [comment]
@hoosteeno in the mean time I can be working on getting the test page setup on our infra we have for www.firefox.com (even though it's not at that domain yet). Do you have exact requirements for which page and at what URL you want it? I can get it up there and we can tweak from there.

**Comment by pmac** [comment]
@hoosteeno I went ahead and got the download page up on our infra. It's live on the staging instance of what will be our firefox.com redirector:

https://fxc-stage.oregon-b.moz.works/en-US/download-firefox/

**Comment by pmac** [comment]
Let us know what else we need to change to get this 100% ready for the test campaign, apart from getting it at the right domain.

**Comment by pmac** [comment]
One question is what to do with the language switcher in the footer? I could either:

1. Remove it for the experiment page since it really is only available in en-US
2. Update the JS so that it will take them to their chosen translation at www.m.o/firefox/new/

**Comment by hoosteeno** [comment]
> Let us know what else we need to change to get this 100% ready for the test campaign, apart from getting it at the right domain.

@rraue can you work with Saptarshi to get an experiment report written for this? That will help answer the above question.

> One question is what to do with the language switcher in the footer? 

@rraue I think this will be a single-locale test (en-US?) and therefore a missing switcher is probably a small impact. Agree?

**Comment by pmac** [comment]
I think the hreflang and canonical tags are still right on this, but we should double check those as well.

**Comment by rraue** [comment]
@hoosteeno Yes I think one locale is enough to inform us about any possible difference in ctr.

**Comment by pmac** [comment]
I'll remove the switcher.

**Comment by pmac** [comment]
@hoosteeno I'm pretty sure we've discussed this, but just to be clear www.firefox.com is now under our control and we can finalize this experiment setup whenever you're ready. This may well be on a back-burner at this point after all of the recent organizational change, but we're ready when you are.

**Comment by hoosteeno** [comment]
I really appreciate the work involved in getting www.firefox.com closer to us. We will use that someday soon (e.g. with an upcoming campaign). That said, building a new product site at www.firefox.com is not as high a priority as it used to be, and we can probably close this bug for the time being. It's a sweet experiment idea so I hope we can run it someday.

**Comment by rraue** [comment]
I gave this experiment another thought and I think I came up with a slightly imperfect but way easier experiment setup:

- /en-US/firefox/mac/ has a very stable no. 1 ranking and ctr from search because it is so specific. 
- The session volume from search for the super specific keyword "firefox for mac" is high enough to run this test in 8 weeks to catch even a 1% change in ctr

Test setup:
- We redirect via 302 www.mozilla.org/en-US/firefox/mac/ to www.firefox.com/browsers/mac/
- If rankings remain stable (I guess so) and the new url is displayed ins earch results we compare the ctr in search to the ctr with the old url
- The experiment would need to run around 47 days to get us significant data for the ctr on the keyword "firefox for mac"
- So all in all the experiment would need to run around two month, as it will take a couple of days for the serps to update

The imperfection:
- As all SEO tests it will be a historical comparison, not an A/B-test
- The test will teach us only something if successful. Failure will have too much possible influences to draw any conclusion but a success could tell us something about the influence of the url
- It might be that rankings will drop because of the 302 (unlikely) and then we need to abort the test and redirect back
- We need to redirect 301 from f.c/browsers/mac back to www once the test is done

- It might be that we have to redirect the whole locale set of the /mac page or we need to adjust hreflang so its not broken by the redirect (could be too much work)

Success criteria:
- Ranking for "firefox for mac" need to stay stable for the whole period we compare
- There must not be any spike in impressions for whatever reason (if that happens we need to get this spike out the data and run the test longer)

Any thought on this @pmac & @hoosteeno? If we think this could be feasible and doable with max a week of work (data analysis excluded) I would pitch that at some point.

**Comment by slightlyoffbeat** [comment]
closing right now. We can re-open if there is renewed interest in this.
