### ISSUE TITLE
Remove pebbles base templates and assets

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8868]
## Description

Once the following issues are resolved, we should be unblocked on removing the Pebbles framework dependencies and related assets:

- https://github.com/mozilla/bedrock/issues/8375
- https://github.com/mozilla/bedrock/issues/8686

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] All Pebbles related code is removed from bedrock.

#### Tasks
- [ ] Remove Pebbles scss library and related files.
- [ ] Remove / rename Pebbles base template(s).

**Comment by alexgibson** [comment]
I think this one is finally ready 🎉
