### ISSUE TITLE
New Feature page for PIP

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8874]
## Description

A feature page for the PIP feature available in Fx starting in the 71 release.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] This is an example of a success criteria. Use a checklist!
- [ ] This is an example of a success criteria.

#### :Approver
- [ ] This is an example of a risk. Use a checklist!
- [ ] This is an example of a risk.

**Comment by alexgibson** [comment]
https://www.mozilla.org/en-US/firefox/features/picture-in-picture/
