### ISSUE TITLE
Update Protocol to implement brand themes

### ISSUE THREAD

**Issue by craigcook** [mozilla/bedrock#8876]
## Description
Theming in Protocol should finally be arriving soonish (https://github.com/mozilla/protocol/issues/447). Once that feature has landed upstream in Protocol there will be some custom follow-up work to implement themes in Bedrock.

Mozilla.org is an atypical (possibly unique) consumer of Protocol in that it's one website with a common codebase that displays pages in both brand themes; some pages are Mozilla branded and other pages are Firefox branded.

Theming on the Protocol side is handled by variables and mixins that output different styles for different brands, which requires compiling the SCSS. In order to display two brands in Bedrock we'll need to compile Protocol twice and make two separate CSS bundles. I believe we can do this with a custom Gulp task. Then we'll have two base templates to choose from, each with its own brand theme, and any given page will inherit its theme from one of those bases.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Both brand themes are compiled separately.
- [ ] All pages are using the appropriate brand theme.

#### Risks
- [ ] I'm assuming this is possible with Gulp but I haven't actually tried it yet, so it may prove impossible and we'll have to do something else.

#### Tasks
- [ ] Update bedrock to use the new version of Protocol (once it's published).
- [ ] Write a custom Gulp task to copy and compile both Protocol themes.
- [ ] Establish two CSS bundles, one for each theme.
- [ ] Establish two base templates, one for each theme.
- [ ] Update every page to use the appropriate template.

**Comment by craigcook** [comment]
Currently blocked by theming shipping in Protocol: https://github.com/mozilla/protocol/issues/447
