### ISSUE TITLE
[26 May] Port new installer-help template to Fluent

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8916]
## Description

The new installer-help page added in https://github.com/mozilla/bedrock/pull/8791 has not yet been exposed for string translation in .lang. 

As such, we'd like to graduate this to be translated using Fluent instead - with an aim to have a PR ready to merge on 26th May (shortly after the new system goes live). This will be a good real world test before we tackle WNP78.

This is a good candidate for another front-end dev other than myself to try.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] New installer help page is live in production using Fluent.
- [ ] Strings are exposed via automation on merge to master.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] There's a risk there may be some bugs in the system still, but that's the job of this test to identify.

#### Tasks
- [x] Create en .ftl file.
- [x] Convert template to use fluent IDs.
