### ISSUE TITLE
Research: switching to Webpack

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8956]
## Description

In https://github.com/mozilla/bedrock/pull/8391 @Errolyn made a great first pass at porting bedrock to Webpack, but given the size of the project and the number of changing files, this proved difficult to bring to fruition in the available time they had to spend on it. Even though this didn't get merged, I still think it was a great exploration and worth trying.

Looking at the more modern front-end features Webpack may open up a path for, I think doing a bit more research may be a good next approach. Because Webpack is a very different type of bundler to how Gulp operates, there are some questions that may be worth exploring before figuring out an easier path for migration. We should do some time-limited research that tries to answer:

- What are the current pain points and limitations of Gulp? What does Webpack do better? Are there still any things that Gulp is still better suited for in terms of bedrock?
- Webpack is aimed at modern web applications and bundles files in a different way to how we currently do things in Gulp. What is the impact of that on our current file system? Would we need to change how we currently handle JS dependencies? How would we handle common dependencies between bundles?
- Webpack does [not support](https://webpack.js.org/concepts/#browser-compatibility) old IE browsers, so the bundles it produces may not run as expected there (or not at all). Would we need to figure out another solution to continue serving the legacy JS bundle? What would that look like? What kind of experience would users on other older browsers see?
- Webpack offers some great [optimization tools](https://webpack.js.org/plugins/split-chunks-plugin/) for reducing bundle sizes. How would this interplay with the way Django and `collectstatic` works? Would we be limited in making full use of these types of features?
- Are there any performance impacts (costs or savings) of switching to the bundles Webpack produces (bundle size, polyfills etc?).

In order to answer the above, I propose we build a rough proof-of-concept:

1. Port a single page to use Webpack (all base bundles + images, + one page bundle).
2. Get it to deploy sucessfully on demo.
3. Test the page for performance and cross browser compatibility.

Once we can do the following then we can start to build a picture of what a Webpack configuration may look like for bedrock, and then figure out a path for migration.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Bundle a single page using Webpack and get it to deploy to demo.

#### Tasks
- [x] Build an MVP Webpack config.
- [x] Port all the bundles / images for a single page using Webpack.
- [x] Build & deploy to demo.
- [x] Test.
- [x] Figure out a path for migration.

**Comment by alexgibson** [comment]
Note for future: something like https://www.npmjs.com/package/webpack-merge-and-include-globally might be a viable solution for serving bundles to old IE.

**Comment by alexgibson** [comment]
Ok, based upon @Errolyn's initial config, I've managed to get a full site webpack build deploying to demo: https://www-demo2.allizom.org/en-US/

There are still some locale dev / performance related issues that are needed to figure out, plus some browser testing.

Working branch is here: https://github.com/alexgibson/bedrock/tree/webpack

**Comment by alexgibson** [comment]
Some other findings from testing:

- By default, webpack's require() bundling method doesn't run in IE8 or below, which breaks legacy bundles served to old browsers.
- Variables like `Mozilla.Mzp` and `jQuery` are undefined by default, since they are no longer in global scope due to the way they are published.

The above can be fixed by using the `webpack-merge-and-include-globally` plugin I referenced above. This should allow us to migrate to webpack without needing to significantly alter our file system of dependencies. Longer term, it would be nice to transition to Webpack's regular bundling method, provided we have an alternate kind of fallback solution for legacy browsers in place.

**Comment by alexgibson** [comment]
Another roadblock I encountered is related to build performance running in local dev. Because we track so many files in bedrock, Webpack was taking a **very** long time to build and rebuild bundles. This wasn't so much of an issue running locally, but inside docker it was taking over a minute and consuming a lot of system resources. Enough to make my system struggle.

The recommendation for this type of problem in the webpack world seems to be use multiple configs and only watch the files you really need. So I split out a separate config for static assets (images, fonts etc), which only runs once on start up. The second config watches only JS and CSS files, and the result is magnitudes faster. It also seems to be much lighter on system resources.

**Comment by alexgibson** [comment]
Ok, based on the above I think we've figured out a path that would enable us to switch bedrock to Webpack in a slightly easier way. The next steps I propose would be:

- Move JS linting and testing to NPM scripts (https://github.com/mozilla/bedrock/issues/8479).
- Implement an MVP webpack config that enables us to ship concatenated / minified bundles in production, in the exact same format we do today. 
  - This means no changes or impacts on page performance, browser support, or JS dependency management.
  - We can also ensure there is no change to front-end dev workflows. Devs would still use `static-bundles.json` like they do today, and the same `make run` / `npm start` commands.
- Once we have an initial webpack config running and we're happy with it, we could then start to work toward takiong advantage of some other new features such as Webpack's default bundling, Babel compilation etc.

Before we do this, I think the team (mainly the front-end devs) should be in some form of agreement that this change is benefitial tand makes some sense for bedrock.

My own opinions (based on my findings so far):

Pros:
- Webpack is more of a common standard today, and offers a very rich ecosystem of plugins compared to Gulp. As a tool, it could open up some interesting opportunities for bedrock. Not just for local development, but also performance related tooling, libraries and tooling etc.
- There seem to be many more developers in the market today who are familiar with how Webpack works compared to Gulp. Offering familiar tooling and workflows is something that increase productivity, and can also make a project more appealing to work on.

Cons:
- Webpack is no more/less complicated than Gulp. This is especially true for a larger site with many dependencies. Both systems are relatively complex.
- Webpack is mainly geared toward SPA (single page application) type projects. It can still cater for traditional multi page projects like bedrock that have many different dependencies, but it introduces a few more hoops to jump through to get there.
- Webpack is still fairly process hungry when running locally in watch mode, much the same as Gulp is today. This is true more so when running in Docker, vs a native install of bedrock.

I'd be interested in thoughts from others here.

/cc @Errolyn @stephaniehobson @craigcook @amychurchwell

**Comment by alexgibson** [comment]
I'm going to close out this research as complete:

TL:DR - yes we can switch to webpack, and there's a proof of concept branch here: https://github.com/alexgibson/bedrock/tree/webpack

We can decide if this is something we want to do or not at a time when things aren't quite as up in the air.
