### ISSUE TITLE
implement a 410 Gone page

### ISSUE THREAD

**Issue by lonnen** [mozilla/bedrock#8964]
## Description

When we decommission mozilla projects we sometimes want to retain the domain name for some time to prevent squatting or malicious syphoning. It would be useful to have a single HTTP 410 Gone error page to point these towards, like our 404 and 500 error pages. This would be less confusing for users than a 404, and provide an opportunity to engage with them in a moment of possible surprise or frustration.

Existing 410 pages like (https://www.mozilla.org/projects/user-docs/local/) partially implement this, but has no explanatory text that the resource is gone.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] an official looking page is returned explaining the page you were seeking is gone
- [ ] the server http response code is 410 so that caching can appropriately handle future requests

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] having a generic page may not provide enough context to a surprised user

#### Tasks
- [ ] note from reporter: I don't know enough to break this down into useful subtasks

**Comment by lonnen** [comment]
my example use cases are all microsites we made for demos or initiatives that have passed their moment, like https://inhumanads.com/ or https://games.mozilla.org/

**Comment by localjo** [comment]
Taking a look at this. I'm noticing that https://www.mozilla.org/projects/user-docs/local/ returns a 410 response but no response body at all, so I don't think a 410 page was implemented there, just the status code.

For https://inhumanads.com/ and https://games.mozilla.org/ they are returning a 302 and 301 redirect, respectively. I think that *may* be an acceptable solution in many cases, though it doesn't give the user any information about what may have happened to the resource.

I can clone the 404 page design to use as a starting point for a 410 page:

<img width="793" height="576" alt="Image" src="https://github.com/user-attachments/assets/96202aee-58d9-423e-8a0f-44f6592675d9" />

I think we just need to decide what the 410 page should say. I can propose the following:

```md
# Sorry, that page is gone

You may be able to find more information about what you were looking for by searching on [The Mozilla Blog](https://blog.mozilla.org/en/)
```

Thoughts? @stephaniehobson @janbrasna

**Comment by stevejalim** [comment]
@localjo Go for it, yeah - sounds sensible. I'm not 100% sure that pointing to the Mozilla blog will help for most things, but we can tweak that based on feedback from @stephaniehobson and @slightlyoffbeat

**Comment by stephaniehobson** [comment]
I think searching the blog is the best option we can offer. They can't search WMO and the blog actually has a better historical record of campaigns, initiatives, and products.

**Comment by janbrasna** [comment]
The original ticket had STR that no longer point to bedrock, but definitely one example still in place would be e.g.: https://www.mozilla.org/help-wanted.html

The current [gone_view](https://github.com/mozilla/bedrock/blob/c589157211ed2bb0648afd3cbf2132dbc5b00532/bedrock/redirects/util.py#L317) used does not offer good end-user experience.

The issue with empty response body is the UX most browsers employ and display own UI for that, implying something's broken with the site, instead of it being a deliberate choice:

> <img width="1376" height="1076" alt="410:Gone" src="https://github.com/user-attachments/assets/33d06f6b-0634-4e31-96cc-c79c8d2e0c6c" />

The reason for the empty gone view historically was that it was returned mostly for hosted project stuff, think *.js files too etc. — but that utility is long gone (got the pun?) these days, so this can be user–focused now.

The 4xx/5xx error template layout is definitely a good starting point. Just needs a good micro–UX in terms of a copy describing the situation, why is it expected, why that happens, and where to go next. For most 410 Gones you probably just want folks to continue to home–products/features—about/download etc.

(Linking to Wayback Machine would be normally pretty cool, but here the removed content is usually something we don't want to show folks anymore, so getting any news elsewhere is probably better.)

Copy/comm style that I imagine for this (thinking out loud, please design appropriately, this is just a drive-by dabbling): ‹hX› "We used to have this page here before." ‹/hX›‹p› "Features change, products evolve, and this content was no longer used here, so it got removed. […/insert any blog mention for archaeology here?/…] Please use the links below to start your journey and explore our products, vision and values:" [1. … 2. … 3. … links]
