### ISSUE TITLE
WNP 78

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#8972]
## Description

Build and launch the Whatsnew page for the Firefox 78 release.

Content: Mobile

[Releng bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1644222)

---

####  Success Criteria 
- [ ] Is live in production on or before June 26th

#### Approvals
- [x] Accountable - LNiolet
- [x] Mobile PMM - LAustin
- [x] Brand (Design) - Clio
- [x] Brand (Copy) - Natalie
- [x] Team Lead - Hoosteeno
- [x] Legal - MFeldman
