### ISSUE TITLE
WNP 79 EPIC

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#9063]
## Description

WNP for the Firefox 79 release on 7/28

[Principal project doc](https://docs.google.com/document/d/1DW2-pohjlRxmtSf7l4vhsVUCkhLQuXh6VdkOyopWPDk/edit)

Standard swarming schedule:

- Kickoff - Mon July 6
- First content review/swarming session - Tues July 7
- Websites Team checkin/swarming - During Team Time, Wed July 8
- Second content review/swarming session - during OMN/Websites weekly checkin - Wed July 8
- Final Stakeholder review - Thurs July 8
   - Includes Legal, as available and if required
- Closure - string extraction, final design elements, code review, go live, QA testing (required the Monday prior to the product release)
- Page go live - on or before Fri July 17
- QA (Softvision) week of July 20
- Product release - Tues July 28

---

#### Success Criteria
- [ ] The new content is live in the WNP 79 page no later than 7/17 (to allow for l10n and QA testing)

#### Approvals
- [ ] The Accountable - MWarther
- [ ] Brand - Clio
- [ ] Brand - Natalie
- [ ] Team Lead - Hoosteeno
- [ ] Legal - MFeldman or ELitka
