### ISSUE TITLE
WNP 80 Epic

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#9159]
## Description

The WNP for Firefox 80 release on 2020-08-25, promoting content as part of the Sept campaign.

---

#### Success Criteria
- [ ] Is live in production on or before 2020-08-14

#### Approvals
- [ ] The Accountable- MWarther
- [ ] Brand design - Clio
- [ ] Brand copy - Natalie
- [ ] Team Lead - Hoosteeno
- [ ] PMM - TBD
