### ISSUE TITLE
Epic: Automated testing evaluation & pipeline improvements

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9171]
## Description

Conduct an evaluation of Selenium-based automated testing solutions.

Pitch deck: https://docs.google.com/presentation/d/1Wy_b0m-DrGhIm4TZFAiIVqKhxrwT7tAbwzQTmyY2MgI/edit?usp=sharing

---

#### Success Criteria
- [x] Implement pipeline improvements & cost savings
- [x] Evaluate service providers & make a recommendation.

#### Approvals
- [ ] The Accountable
- [ ] Team Lead
- [ ] Mozmeao team
- [ ] Front end devs

**Comment by alexgibson** [comment]
Depends on:

- https://github.com/mozilla/bedrock/issues/9444
- https://github.com/mozilla/bedrock/issues/9453
- https://github.com/mozilla/bedrock/issues/9443
