### ISSUE TITLE
Understand the number of users blocking GA when visiting WMO

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#9219]
## Description

KR - By 2020-09-30, understand the percentage of www.mozilla.org visitors who are blocking Google Analytics. Make possible segmentation by user agent and locale and/or geography.

Google Analytics (GA) is commonly blocked by security- and privacy-conscious users. A recent study found 13% of users on average visiting a small sample of sites -- including nearly 60% of Firefox users -- were blocking GA. If either number holds on www.mozilla.org, then our cross-sell and download rate calculations are wildly off. We should know what those numbers are.

---

#### Success Criteria
- [ ] An element contributing to the definition of done for the card
- [ ] Tasks should be represented here as something like "the new design is done and approved, live on the page"

#### Approvals
- [ ] Team Lead
- [ ] Others, validation by Saptarshi/Data Science?

**Comment by stephaniehobson** [comment]
I believe this was addressed by the [Glean Experiment](https://docs.google.com/presentation/d/1nA6v1iO8QEnyG-I9S2vaPfTTo87gqOgvd1jRqW-hd6Q/edit#slide=id.g82761e80df_0_1948) (Mozilla only).
