### ISSUE TITLE
Epic: Global Navigation Review

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9220]
## Description

The VPN highlights some UX issues with our current global navigation scheme. We need to review whether present global nav is working for users and serving the business. The output of this work should be a recommendation for changing the global navigation that makes the VPN easily discoverable on all pages of the site. 

---

#### Success Criteria
- [x] Recommendation/specs/design delivered
- [x] VPN is included in the nav by the end of August
- [ ] Code implemented & launched

#### epic issues
- [x] Design https://github.com/mozilla/bedrock/issues/9286
- [ ] Code https://github.com/mozilla/bedrock/issues/9466
- [ ] Iterate #9594

**Comment by ejregithub** [comment]
Justins to check in this week

**Comment by chrismore** [comment]
@hoosteeno let me know when you have a proposal you want to discuss further. Thanks!

**Comment by hoosteeno** [comment]
#8937 #9286 #9206

**Comment by hoosteeno** [comment]
This has been completed. Hooray!
