### ISSUE TITLE
Epic: Design & build evergreen download user flow

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9224]
## Description

In https://github.com/mozilla/bedrock/issues/8372, Alex highlights the debt we incur with every overhaul of the download page: It is likely that some locales will not localize the new page ever, and other locales will not localize it for a year or more. 

In locales where the new content is not localized, we have to serve something. Firefox is downloadable in those locales; they need a download button with localized copy on it. We should not serve them an unlocalized page (e.g. a page with the fallback language in place), and we should not redirect them to a different locale (e.g. to en-US). 

Our practice to date has been to retain legacy versions of the download page. But this creates maintenance and brand debt. For example, see https://www.mozilla.org/eu/firefox/new/: Many of the visuals are up to date, but subcontent and copy are from Firefox Quantum. 

We have an evergreen solution for Whats New pages: When a user visits from a locale that has not localized the newest Whats New page, they get a fallback that we maintain, which is basic and functional.

We should design an evergreen experience of the download page that is easy to localize, easy to integrate with new brand assets, and evergreen in terms of content. 

---

#### Success Criteria
- [x] Designs for the user journey and UI are attached to a design issue
- [ ] Code implementing the new user journey and UI is launched
- [ ] Legacy code replaced by new journey is removed

#### Issues
- [x] #9398
- [x] #9399

**Comment by justinkropp** [comment]
I'm proposing two solutions to this problem: one which is a significantly truncated version of the `/new` page, and second is a more significant reduction in page content.

----

### Option One: Diet `/new`

<img width="2164" alt="Evergreen with content" src="https://user-images.githubusercontent.com/1461798/89340446-c306bf00-d66d-11ea-869a-da74b9506c14.png">

This option would reduce the content on the `/new` significantly. We'd maintain the hero section copy as well as three high-value features that we'd show below the hero section. This would still need to be localized, but it would be a much smaller ask than the Regular `/new` page. 

----

### Option One: Minimal `/new`

<img width="2164" alt="Evergreen sans content" src="https://user-images.githubusercontent.com/1461798/89340721-2db7fa80-d66e-11ea-8642-c0c1003a96f2.png">

This option would ostensibly remove all content from the page except for a primary headline, supporting value prop sub-headline, and a download button. This approach would be the least-complex to maintain from a localization and brand evolution standpoint.

**Note**: _This solution is very similar to the CRO test that examined the performance of a viewport-wide background image with limited copy._

**Comment by hoosteeno** [comment]
Really great work, @justinkropp . Thanks. 

The options force us to choose between the following benefits:

a) Minimize technical/localization debt incurred by changes to marketing content
vs.
b) Maximize SEO value of evergreen page

Do you agree?

**Comment by justinkropp** [comment]
Yes, the proposed solution represent these two options. 👍

**Comment by rraue** [comment]
Of course for SEO reasons the diet option would be better, but top three features will change over time and are in every locale a bit different, as Firefox is used different all over the globe.

The second option might have been the winner in a cro experiment, but wouldn't in that stage be optimal for SEO, even tho, it would most likely preserve 80% of traffic.

I propose a third option combining the two and the learnings from the cro experiment:

1. Head like in Minimal
2. Below that a different approach to the Diet: the full feature list from /new:

![Screenshot 2020-08-06 at 19 18 41](https://user-images.githubusercontent.com/36700618/89562478-4c5af480-d81a-11ea-86eb-d210cb258f36.png)

That's not a lot of content and basically everything you need to know about Firefox. Even if no other page is available in this locale, with that list you get a very good impression, what Firefox can do for you. We just need to maintain this list and we need no "branded" and soon outdated images, just plain what Firefox does.

How does that sound? I am sure we would preserve all SEO traffic, might even get some more.

**Comment by hoosteeno** [comment]
@rraue That's an intriguing suggestion. Question: If a page with the features section was live in a locale, but the features section itself was not localized, would that have any negative SEO impacts? I am wondering if we could make this serve our immediate need if the top section was localized, but the bottom section was sometimes not localized.

**Comment by rraue** [comment]
A lot here depends. Just having the minimal one is better than nothing. Minmal plus all features in the localized language is the optimum for not having the whole /new translated. 

So our priority should be:
1. /new completely translated
2. Minimal with the feature list translated
3. Minimal with at least three features in the list translated (we should check regularly if some more are translated and need then a design where they can be automatically added if translated.

I am torn apart on the decision about just minimal as 4. or minmal with feature list in english. Would it be a t lot of work to test this (Seo testing for minimum 4 weeks on half of the untranslated locales with just minimal and half with english feature list)?

**Comment by ejregithub** [comment]
How much copy are we talking about here such that the cost for localization (of evergreen content, not ephemeral, so the cost really could be viewed as an investment given it is the download page) might be deemed prohibitive? 

I think if we have a word count, ball park, then we could run some projections based on those and the number of locales that are consistent vs. not in keeping up with l10n on the mozilla.org project to suss out a reasonably accurate cost estimate to translate the 'high risk' languages by an agency.

**Comment by ejregithub** [comment]
The first proposed version is most similar to the last version of the page, as seen here - https://www.mozilla.org/es-ES/firefox/new/ .  This has but 107 words in it.  Let's say we bump that to 250 just to be safe.

That version of the page currently has 54 locales at a high enough % to be activated.  If we assume that will be that max done by the community going forward, that's 54 out of the 101 locales available.

If we pay for localization of 250 words in all 47 remaining locales at .3999 cents per word, that's a total of $4700 to have our evengreen page in every locale the site offers. There's the overhead to adding all those strings, but a shared, concerted effort by internal staff could do that within days with a relatively low time commitment for the cut and paste tasks.

**Comment by hoosteeno** [comment]
If we can achieve our present list of locales on an evergreen template, then this change still represents a net win. We can separately address the question of whether (and how) to invest in all the rest of the locales. I suggest we go with the features section, and hide it unless completely localized, and watch these 2 things for a month before deciding what to do next:

1) Are we moving toward equivalent locale coverage for this new template? If not, we may wish to invest.
2) Do we see SERP improvements in covered locales where we have not had this kind of content before? If so, we may wish to invest.

Does this sound reasonable?

**Comment by alexgibson** [comment]
My 2 pence to throw in here:

- If these pages are truly to act like an evergreen page, they should be low maintenance in terms of copy requirements that needs to change over time. A list of core features might be perfectly well suited, but a long and evolving list of features can become an L10n burden - something we should pay close attention to if these pages are "never" to retire. It could evolve into a long and complicated mix of l10n fallbacks and inaccurate information for some locales.
- In order for these pages to take precedence over existing/older templates and start to see any real traffic, we need to get that broad locale coverage. This is something that may not be easy to get, at least quickly, or perhaps not at all depending on community activity. If there are vendor options that can be considered here, it may be worth it.
- Lastly, we should consider https://github.com/mozilla/bedrock/issues/9266 being part of this, as those pages are continually dropping out of date each time /new gets a redesign.

**Comment by rraue** [comment]
I think I am good with just two states for the evergreen: above the fold and list only when translated. 

We just have to make sure then that h1 and description is really functional so we do not lose the main keywords. I will work on a proposal, it might be best if the headline is the title or a truncated version of it and the sentence under it will be the meta description, then its less to translate and definitely functional covering the most important keywords.

**Comment by justinkropp** [comment]
Thanks for all the thoughtful discussion on this. Just my 2 pence from a UX perspective: I was looking for a long term solution for this page that would reduce the amount of maintenance to almost zero while also balancing including the minimum amount of valuable information to a user. I like approach that @hoosteeno proposed:

> I suggest we go with the features section, and hide it unless completely localized, and watch these 2 things for a month before deciding what to do next...

**Comment by stephaniehobson** [comment]
At the moment these pages have the download button on them that swaps out for android, ios, etc if the user is on mobile. I'm going to change that to be just the desktop download link, unless anyone objects.

I'd also suggest adding /ios and /android versions of the platform templates. These can display at /mobile/ios and /mobile/android and serve as evergreen fallbacks for whatever we end up building out there eventually. @rraue Thoughts on adding these pages?

**Comment by stephaniehobson** [comment]
Suggested title, description, and page heading for the new platform pages: https://docs.google.com/document/d/125FFxytmY_FUlAxiyLHp1-FqR0Jy0KCls_8kl9KEb38/edit (Mozilla only link)

@rraue I'd like your take on this before I talk to Tyler and legal.

**Comment by stephaniehobson** [comment]
We can't touch these pages without also also creating a new /thanks template.

Suggested text for that:

> Your download should begin automatically. 
> Didn’t work? _Try downloading again_.

My impulse was to include the help links from the current /thanks page but as far as I can tell no one has ever clicked them. 🤦‍♀️

**Comment by stephaniehobson** [comment]
Current thinking:

1) Update Yandex to use the most recent /new template (Issue: #9883 PR: #9896).
2) Create a new "basic" template for the simple /new and platform page to share
3) Populate the basic template with existing strings from the download.ftl file. (Remove unused strings from this file).
    - use the old strings as fallbacks in places where we would like to update the copy.
4) Switch the platform pages to the basic template.
5) Investigate using the FTL file from the long form download page to populate the "features" section of the basic page. (Or vice versa?) (I noticed some communities have partially translated this section already, is there any easy way to capitalize on this work?)

**Comment by slightlyoffbeat** [comment]
@alexgibson @stephaniehobson How much time is needed to complete this? Could you reconnect on this and recommend next steps?

https://github.com/mozilla/bedrock/pull/9934

**Comment by alexgibson** [comment]
> How much time is needed to complete this? Could you reconnect on this and recommend next steps?

There's a [pull request](https://github.com/mozilla/bedrock/pull/9934) open for this that @stephaniehobson has been working on, although I'm not 100% sure where it's at currently. We should circle back on this as soon as time allows.
