### ISSUE TITLE
[8/27] Banner promo for Fenix release

### ISSUE THREAD

**Issue by ejregithub** [mozilla/bedrock#9302]
Description: The new release, Fenix, for Firefox mobile on Android is currently planned for global availability on the 27th. Promoting that on www.mozilla.org can be achieved by using the banner component on the site and placing that on high trafficked pages.

[Principal Project Doc](https://docs.google.com/document/d/1cmqftlLoUphUD7eGblUyAiapksP6fpy-PFGU-fORAyM/edit)

#### Success Criteria
- [ ] Banner is live on 2020-8-27 on the homepage, /firefox/, and /firefox/mobile/

#### Tasks
- [ ] Copy - Rob
- [ ] Design - Cristina
- [ ] Code - Craig

#### Approvals
- [ ] Accountable - Mei
- [ ] TL - Hoosteeno
- [ ] Brand copy - Natalie
- [ ] Brand design - Clio
- [ ] NA Brand TL - Eddie

**Comment by hoosteeno** [comment]
@justinkropp can you attach designs to this when done?

**Comment by justinkropp** [comment]
This is the most recent version of the Fenix banner as it'll show up on desktop.

![Fenix Desktop Banner 1312](https://user-images.githubusercontent.com/1461798/91354759-30b09180-e7bb-11ea-8c64-116fa1820cab.png)

I'm going to check with Mei to double-check that the copy is final and approved.

**Comment by hoosteeno** [comment]
@justinkropp Looks nice to me. Can you specify the interaction on this, too? Is it dismissable (and for how long)? What should happen on click?

So far we've planned to land it on the homepage, the /firefox/ page, and the /firefox/mobile/ page. Do you think we should consider anywhere else?

**Comment by justinkropp** [comment]
@hoosteeno Yes. 

- This should be dismissable.
- If the user is on desktop they should see the CTA above ("Get it on your phone"), which should trigger the current send to device modal
- If the user is on mobile, I'd like to show the respective app store buttons  (App Store and Google Play), both of which would open the appropriate app store experience
- Can we also land this on /firefox/products/ ?

> Is it dismissable (and for how long)?
Do you mean how long until the user sees the banner again after dismissing it?

----

By the way, copy is approved.

**Comment by hoosteeno** [comment]
> Do you mean how long until the user sees the banner again after dismissing it?

We set a cookie that can expire. Should it expire? 

> If the user is on desktop they should see the CTA above ("Get it on your phone"), which should trigger the current send to device modal

We agreed in Slack that we can send to the get-app page (https://www.mozilla.org/en-US/firefox/mobile/get-app/) instead.

**Comment by hoosteeno** [comment]
@craigcook here are some initial specs for the CTA button instrumentation that we should *test* before launching. LMK if I can help with that.

Data Attribute | Value
-- | --
data-cta-type | button
data-cta-text | Get It Now
data-cta-position | banner

**Comment by craigcook** [comment]
The Play Store badge is shown in place of the button on Android and links to `https://app.adjust.com/2uo1qc?redirect=https://play.google.com/store/apps/details?id=org.mozilla.firefox&campaign=www.mozilla.org&adgroup=firefox-daylight-launch-banner`
