### ISSUE TITLE
Epic: Simplify WNP production process

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9384]
## Description

We want to eliminate our _community_ l10n and release management dependence in cyclical WNP production. We propose to do this by:

* Building an evergreen WNP that serves almost all locales and all release versions and is updated semi-annually outside the release calendar
* Focusing our regular WNP updates on locales with staff/vendor localizers (en/de)

The issues are described below, and will be attached soon.

---

#### Issues
- [ ] #issue: specify the routing we expect & remove unnecessary view code and write functional tests to validate  cases: 
  * 60 or above, release channel, release-specific WNP for locale exists (e.g. en-US): should get release-specific WNP (https://www.mozilla.org/en-US/firefox/81.0/whatsnew/all/)
  * 60 or above, release channel, NO release-specific WNP for locale exists, modern evergreen exists: should get modern evergreen (https://www.mozilla.org/en-US/firefox/100.0/whatsnew/all/)
  * 60 or above, release channel, NO release-specific WNP for locale exists (e.g. en-US), modern evergreen NOT exists: should get baseline evergreen (https://www.mozilla.org/ar/firefox/81.0/whatsnew/all/)
  * 59 or below: should baseline evergreen
- [ ] #issue: write a new l10n config that makes the release-specific WNP only available in en-US/de
- [ ] #issue: in the next release (82?), do en-US and German
- [ ] #issue: document the new cyclical dev process
  * create a new template for release-specific WNPs
  * create a new fluent file for release-specific WNPs
  * update view to point to new template
  * associate template with new fluent file
  * eliminate old template -- and figure out if we can eliminate old fluent file

--- 

#### Follow up epics
- [ ] Make WNP more flexible for different content (using Protocol & some demo pages)?
- [ ] Port a more modern, evergreen WNP to the modern evergreen template and maybe(?) to baseline evergreen template.

**Comment by hoosteeno** [comment]
This issue is pending a conversation with marketing execs.

**Comment by hoosteeno** [comment]
@peiying2 This issue seems tied up with conversations around community vs. vendor localization. Do you think you can help clarify that in a comment here?

My understanding is that, by about Fx83, we'll have a vendor-supported localization path for a set of locales, and we can push all WNPs through that localization path. If we did so, in the context of the goals of this bug...
* We'd have an SLA for vendor localization of a fixed set of locales that might be ~5 days that would increase our breadth of locales, for a price
* We could still eliminate community l10n from the process by constraining our l10n expectations to the vendor-supported locales
* We could still eliminate release management from the process by having an evergreen fallback that serves anyone who does not see the most recent WNP

Am I understanding all this right?

**Comment by gueroJeff** [comment]
> @peiying2 This issue seems tied up with conversations around community vs. vendor localization. Do you think you can help clarify that in a comment here?
> 
Are there other elements to the community/vendor localization conversation that need to be revisited? To my knowledge, the main question is finalizing the list of languages that Marketing needs vendors involved in. The list of available languages and the policy we created around community/vendor/staff localization is here: https://mana.mozilla.org/wiki/display/FIREFOX/Sourcing+translation+for+mozorg+marketing+content

> My understanding is that, by about Fx83, we'll have a vendor-supported localization path for a set of locales, and we can push all WNPs through that localization path. If we did so, in the context of the goals of this bug...
> 
>     * We'd have an SLA for vendor localization of a fixed set of locales that might be ~5 days that would increase our breadth of locales, for a price
> 
This SLA is more based on guaranteed turnaround than breadth of locale coverage. I believe that's the correct turnaround expectation. Thoughts @peiying2 ?
>     * We could still eliminate community l10n from the process by constraining our l10n expectations to the vendor-supported locales
> 
We could, but that would set marketing localization significantly behind product localization in terms of breadth of coverage. My understanding was that the evergreen WNP would be localized by community for locales not listed in the Mana page above.
>     * We could still eliminate release management from the process by having an evergreen fallback that serves anyone who does not see the most recent WNP
> 
> 
> Am I understanding all this right?

**Comment by peiying2** [comment]
After WNP#82 and now prepping for WNP#83, there are a few questions we can answer:
- One fallback page: The fallback page when WNP# has no localization need. After talking to Craig, he thought one fallback page is sufficient. Anything older may not have the right content to state what our products do now. This Evergreen page should be this one: https://github.com/mozmeao/www-l10n/blob/master/metadata/firefox/whatsnew/whatsnew-account.json which came from https://www.mozilla.org/en-US/firefox/70.0/whatsnew/all/.  If we can all agree that this is the great Evergreen page for extended period of time, I will ask the communities to focus on this page so we have higher completion rate than we have now. Right now we have 54 locales (including en-* but non-US). 
- Inform Releng automatically on completed locale list when WNP# is localized and due, new or evergreen. We did discuss this with pmac and Alex. All the WNP related locale activation info can be found here: https://github.com/mozmeao/www-l10n/tree/master/metadata/firefox/whatsnew.

**Comment by hoosteeno** [comment]
@alexgibson do you think there is a way we could collapse the functionality of the 2 fallback pages into a single page? I think that would make localizers' lives easier, but might add an add'l conditional to the page. 

E.g. could we take the "modern fallback" and, for Fx<60, show one kind of content, and for >=60, show a different kind of content?

**Comment by alexgibson** [comment]
@hoosteeno yes, the modern fallback already has two states (sync / send-to-device), so we could add some logic to say:

- If FF < 60, always show send-to-device
- If FF >= 60, show sync, else show send-to-device if already signed in

**Comment by maureenlholland** [comment]
Closing as this is marked as Done in Websites Team Committed Work
