### ISSUE TITLE
Epic: Evergreen Content for SEO 

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9490]
## Description

What is the overall outcome we aim to achieve? 
We will create 20 evergreen pages for SEO growth. This issue track progress.

Principle:
existing designs, most preferred protocol components only

Link to pitch, brief, or background documents.

---

#### Issues
- [ ] Translate Page https://github.com/mozilla/bedrock/issues/9759
- [ ] Fingerprinting page https://github.com/mozilla/bedrock/issues/9761
- [ ] Password Page https://github.com/mozilla/bedrock/issues/9760
- [x] Pillar Page https://github.com/mozilla/bedrock/issues/9503
- [x] Quantum page https://github.com/mozilla/bedrock/issues/9499
- [x] FAQ page #9491
- [x] Chromebook Page https://github.com/mozilla/bedrock/issues/9512
- [x] Sync Page https://github.com/mozilla/bedrock/issues/9516
- [x] Little Book of Privacy Page https://github.com/mozilla/bedrock/issues/9520
