### ISSUE TITLE
Epic: Chromebook page

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9512]
## Description

We want to build a page for chromebook

url: /firefox/browsers/chromebook/

Pitch: https://docs.google.com/document/d/17aL69fIIUhftGhFnx87OcfYcWoecs-xno1a1rT6_Nc4
Gdrive: https://drive.google.com/drive/folders/1VFoA7IJlj_jUYWkGIp4kYhMGHRjzJ-k_

---

#### Issues
- [x] Content https://github.com/mozilla/bedrock/issues/9513
- [x] Design  https://github.com/mozilla/bedrock/issues/9514
- [ ] Coding https://github.com/mozilla/bedrock/issues/9515
