### ISSUE TITLE
Epic: Firefox Sync Page

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9516]
## Description

We want to build a page for Firefox Sync

url: /firefox/sync/

Pitch: https://docs.google.com/document/d/17aL69fIIUhftGhFnx87OcfYcWoecs-xno1a1rT6_Nc4
Brief: https://docs.google.com/document/d/1Jk5sHZYxj8wwNp_lwSuCOzHaSPtkLJsH7U9cUqp2quk/edit?usp=sharing
Gdrive: https://drive.google.com/drive/folders/1CRZckII0qtg0Vp5zqi6kajQQvGYp8LvR

---

#### Issues
- [x] Content https://github.com/mozilla/bedrock/issues/9517
- [x] Design  https://github.com/mozilla/bedrock/issues/9518
- [ ] Coding https://github.com/mozilla/bedrock/issues/9519
