### ISSUE TITLE
Epic: Little Book of Privacy Page

### ISSUE THREAD

**Issue by rraue** [mozilla/bedrock#9520]
## Description

We want to build a page for the little book of privacy
url: /firefox/privacy/book/

Pitch: https://docs.google.com/document/d/17aL69fIIUhftGhFnx87OcfYcWoecs-xno1a1rT6_Nc4
Brief: https://docs.google.com/document/d/1GxaA7BXQhuV4BseXXGOKFUxCtmKyUIrrCR-ILZ5UiaU/edit?usp=sharing
Gdrive: https://drive.google.com/drive/folders/1EPL0Z_AlRpK6Teq5SQQk5kgEIpD0nFbU?usp=sharing

---

#### Issues
- [x] Content https://github.com/mozilla/bedrock/issues/9521
- [x] Design  https://github.com/mozilla/bedrock/issues/9522
- [x] Coding https://github.com/mozilla/bedrock/issues/9523
