### ISSUE TITLE
WNP 83 Epic: Pocket

### ISSUE THREAD

**Issue by skrelnick23** [mozilla/bedrock#9573]
## Description
The WNP for Firefox 83 release on 2020-11-17, promoting Pocket.

What is the overall outcome we aim to achieve? Drive Fx users to get Pocket.
[Principal Project Doc](https://docs.google.com/document/d/19H1s7NEqmwbEfDnkzsCpCwq7w6P0Mfa_xb72DSTEy5g/edit#
) 

Approvals

- [ ] The Accountable- 
- [ ] Brand design - Michael H
- [ ] Brand copy - Meg 
- [ ] Team Lead - Hoosteeno
- [ ] PMM - Tyler A

Epic Issues: 

- [x] Copy
- [x] Design
- [x] [Coding](https://github.com/mozilla/bedrock/issues/9585)

**Comment by maxxcrawford** [comment]
Bugzilla release bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1672277

**Comment by skrelnick23** [comment]
PR has merged! Site is here: https://www-dev.allizom.org/en-US/firefox/83.0/whatsnew/all/
