### ISSUE TITLE
Epic: Implement floating promo box

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9612]
## Description

When https://github.com/mozilla/protocol/issues/603 lands, we will have the possibility of building floating promotional boxes on content on www.mozilla.org. This card is about operationalizing it. In order to do that, we'll have to:

1. Get the latest Protocol into Bedrock
2. Identify the pages where a promo would work (hint: most of them, except 2 classes of page -- really short pages, or pages where a promo would be incredibly dissonant like the manifesto). We could start with e.g. 20-30 of our most important pages.
3. Identify the kind of promo that would go on each page.
4. Standardize those promos, so we don't have to hand code them on each page. E.g. we have a promo for downloading the browser, and a promo for our entire product suite, and we know which pages get which promo.
5. Copy/Art
6. Code

---

#### Issues
- [x] Add latest Protocol https://github.com/mozilla/bedrock/issues/9608
- [x] 20 quick wins for promoting desktop downloads: https://github.com/mozilla/bedrock/issues/9767
- [x] Refine UX Behavior #9717

**Comment by hoosteeno** [comment]
This issue is the epic/pitch that addresses the comment at https://github.com/mozilla/bedrock/issues/9406#issuecomment-692959396.

**Comment by stephaniehobson** [comment]
https://github.com/mozilla/bedrock/pull/9441 will add a promo to firefox, firefox/new and firefox/browsers. It shows products to exiting Firefox users and a download prompt to non-Firefox users.

**Comment by stephaniehobson** [comment]
Here is a spreadsheet (Mozilla staff only) of options for places to add promos and what to promote: https://docs.google.com/spreadsheets/d/1zTqVida6kc7vbu9Uujb09v9QGMBvHRQtFsL_GZD7LDU/edit#gid=0

**Comment by hoosteeno** [comment]
This is such a good start, @stephaniehobson . Thanks!

When you look at the list of places we could put a promo box, and the variety of things that could be in the box, do you see ways we could enable it via some system, rather than with on-page code? And, if so, do you think we need 1+ issues about that system as part of this epic?

**Comment by stephaniehobson** [comment]
I think that we can systematize adding the promo. But, since each page needs different content we can't configure that globally. (But, we can do that in a reusable way with a macro).

We could also move quickly to add a Non-Fx Desktop only promo to any page where that's appropriate and then follow behind more slowly adding the custom content for the current users. (or... just... not add things for existing users, not where when the juice stopps being worth the squeeze.)

**Comment by stephaniehobson** [comment]
[Here's a pitch](https://docs.google.com/presentation/d/1zvJ-02NoXdmqCgw77TnP8GVdONYyUWITmyWfAd-3UP8/edit#slide=id.ga2fdac9f2d_0_0) to do the quick work. (Mozilla only)

**Comment by stephaniehobson** [comment]
The pitch to add a simple promo to pages promoting Firefox Desktop has been approved and I created this card for it: https://github.com/mozilla/bedrock/issues/9767

**Comment by alexgibson** [comment]
All the success criteria items here are done, so I think we can close this one out.
