### ISSUE TITLE
WNP84: Use WNP82 for WNP84 users. 84 lands 2020-12-15.

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9719]
## Description

We want to reuse WNP82 for WNP84 users. **84 lands 2020-12-15.**

This is a straightforward effort:

#### Tasks
- [ ] Activate WNP82 template for WNP84 requests
- [ ] Coordinate with l10n team (no l10n should be needed)
- [ ] Coordinate with QA team to validate...
* Target market experience
* Out-of-market experience
* Chinese IP experience

82 Bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1668938
82 QA issue here: https://jira.mozilla.com/browse/PI-821

---

#### Success Criteria
- [ ] Page is live and available for QA/l10n
- [ ] l10n knows what they need to do (nothing??)
- [ ] QA knows what they need to do
