### ISSUE TITLE
Epic: Workflow for editing, saving drafts, reviewing, approving,and publishing. 

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#9731]
## Description

We have access to contentful enterprise for a few weeks, which means we have a limited window to test their user roles and permissions that are limited to enterprise users. Lets make sure that the capabilities offered will meet our needs.

---

### Success

- [ ] A role that allows user to create, edit and author content, but not publish
- [ ] A role that allows a user to review and approve changes, but not publish.
- [ ] A role that allows users to 
- [ ] Ability to schedule content for a later date
- [ ] Ability to to validate and publish multiple pieces of content at once
- [ ] Ability to set roll back individual pieces of content.
- [ ] Documented approval workflow that has 'thumbs up' from external stakeholder (TBD or MJ)
- [ ] Set roles that include or exclude access within a single space
- [ ] Set roles that include or exclude access between spaces

---

### Tasks (can be converted to an issue)
- [ ] Interview a stakeholder (MJ, unless told otherwise) to find an optimal process before diving into contentful capabilities
- [ ] Create user roles, using existing homepage
- [ ] document and run stakeholders through the process.
- [ ] (if necessary) Iterate and repeat last two steps

---

### Issues

---

### Relevant Links
- [Custom Roles](https://www.contentful.com/help/creating-a-custom-role/)

**Comment by slightlyoffbeat** [comment]
I think I can run with most or all of this epic. 

@pmac this epic touches on backups and environments, but it may be a separate epic with its own set of tasks/success criteria. Thoughts?

**Comment by slightlyoffbeat** [comment]
Never mind, we already have a card around deploying content model changes and that should be completely separate from this Epic. I'll update to reflect.

**Comment by slightlyoffbeat** [comment]
The purpose of this card was to evaluate capabilities before signing on with Contentful. We were able to validate that Contentful has the necessary capabilities around roles. This card will be closed and new cards can be created around more specific tasks if needed.
