### ISSUE TITLE
Epic: Validate that a we can use conditional logic and validation with contentful

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#9732]
## Description

This epic will allow us to validate if conditional logic and validation is possible, while also kicking the tires on the custom UI and custom app feature of Contentful

---

### Success

- [ ] Created and hosted a custom app
- [ ] Fields are shown based on what is chosen in a previous field
- [ ] Validation is available for shown fields
- [ ] Ability to localize content when using custom UI
- [ ] Validation works for fields with only English
- [ ] Validation works for fields with English and German
- [ ] Validation works when there is only German
- [ ] A documented workflow that can is repeatable and scalable
- [ ] A "thumbs up" from a non-technical contributor after walking them through the proposed process.

---

### Tasks (can be converted to an issue)
- [ ] Set up a host for custom apps
- [ ] Recreate layout cards with a custom app/element

---

### Issues

---

### Relevant Links
- [App Locations](https://www.contentful.com/developers/docs/extensibility/app-framework/locations/)
- [Create Contentful App](https://www.contentful.com/developers/docs/extensibility/app-framework/create-contentful-app/)
- [Getting started with entry extensions](https://www.contentful.com/developers/docs/tutorials/general/uiextensions-entry/)
- [Sample entry extension on Github](https://github.com/contentful/extensions/tree/master/samples/entry-editor-extension/)

**Comment by slightlyoffbeat** [comment]
@pmac @hoosteeno  We need a solid test project for this. I'll get it rolling with ideas, but please feel free to add. I can update tasks and success criteria when we agree on a test project:

- a custom entry field that is specific to images. We could use conditional fields to solve for some of the complexities we've hit in the past. For example, we could have a user select where the image will be used, and then surface the necessary fields they need to fill in (with validation).

- Create an omni-content type for card layouts. We could allow users to select the card layout and then surface necessary fields to fill out.

- We could have optional content appear on a card, if an editor indicates that the card will be used in specific places. For example, an editor could indicate that the card will be "featured" or "xl", which will then surface new fields for high res images that include validation.

**Comment by slightlyoffbeat** [comment]
notes from my conversation with pmac:

We are going to create a card for card layouts that will present options depending on what is chosen (6 card, 5 card, 3 card, etc).

The first step/deliverable will be from me. I need to define the MVP of what this card will be. It's a blocker until I deliver that, so I'll get on it ASAP.

**Comment by slightlyoffbeat** [comment]
@pmac 

OK, Here is a draft for how to approach building this card. I think it covers enough cases to really kick the tires on this: https://docs.google.com/document/d/1WzSYFl0Uzyva0gvMz4FDdx3IHAwep3pOFZKYIP2lEpM/edit?usp=sharing
