### ISSUE TITLE
Epic: Test l10n capabilities

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#9736]
## Description

In our previous test project, we tested having two separate homepages with two separate sets of content. We should fully test the l10n capabilities to make sure that contentful will fit our workflow for pages that have localized content, unique content by locale, and a mixture of localized and unique content.

---

### Success

- [ ] display localized content on a page for FR, DE, EN, ES
- [ ] display unique content on a page for EN, DE,
- [ ] localized and unique content are displayed at the same time for EN and DE
- [ ] System for falling back to default language when no content is available.
- [ ] Can integrate with existing localization workflows and tools in use at Mozilla
- [ ] Thumbs up on documented process by l10n stakeholder (TBD)
- [ ] Can change media shown based on locale

---

### Tasks (can be converted to an issue)
- [ ] Expand on homepage content type to include localized content for FR, DE, EN, ES
- [ ] Create fallback language when locale is not available 

---

### Issues
- #9459
---

### Relevant Links
- [Locale documentation](https://www.contentful.com/developers/docs/concepts/locales/?utm_source=webapp&utm_medium=locales-sidebar&utm_campaign=in-app-help)

**Comment by slightlyoffbeat** [comment]
@hoosteeno @pmac I'm proposing that we continue with the homepage as a project for this Epic. it would allow us to test mixed content (unique and localized). There could be a case for doing a completely different page since there isn't a lot of content on the homepage outside of cards. Let me know if you see any issues or would like to propose a different page to test on.

**Comment by pmac** [comment]
by "localized content" do you mean cards that are direct translations of English cards, or content outside of Contentful's control? If it's the latter I think we already have that, or at least the plan and the way of getting that content localized is with the existing l10n system.

**Comment by pmac** [comment]
Either way I'm +1 on using the Home page. I think it's a good mix of things and a good place to start.

**Comment by slightlyoffbeat** [comment]
Yes. To clarify:

localized content = content that is a direct translation of English
unique content = content that is unique to a locale (such as the cards we created in the last test)

**Comment by pmac** [comment]
My question then is, will there be localized content in Contenftul? I'm guessing there will eventually be, so do we need to test that before finalizing our decision? This content will be translated outside of our current process, so we'll have to figure that out (i.e. is it going to be manual and editors will enter translations or will we have this automated with a vendor?).

**Comment by slightlyoffbeat** [comment]
Notes from my conversation with pmac:

- Our system with smartling isn't fully figured out yet, so it wouldn't be very productive to test contentful integration right now.

- we agreed that it would be good to do a simple localization test and make sure there are no red flags. We landed on doing /firefox (targeting the various h1 & h2 elements, not everything). I'm going to set up the content models and then hand off to @pmac for further implementation.

**Comment by slightlyoffbeat** [comment]
@pmac Content models are set up. It is a content type called "www page /firefox".

It is set up with several headlines that are localized to DE, FR, and ES.

DE and FR are set up to include validation across the entire space. This means that any time a field can be localized, the content cannot be published until FR and DE is also provided. 

ES is has a setting that allows its fields to be blank and skip validation. This means that ES does not need to be provided in order for a content piece to be published (if localization is an option). I only filled out 1-2 fields for ES.

All three languages are set to fall back to EN if nothing is provided.

Every field is a short text field, except for the final CTA headline. The final CTA headline is a rich text field that has everything disabled except for "bold". This way we can provide which word should have the Firefox zap. You can see the content at the link below. I've also included an illustration that shows what is included, and what its field name is:

![Screenshot_2020-12-08 Firefox - Protect your life online with privacy-first products](https://user-images.githubusercontent.com/2030656/101545858-bc11f500-395c-11eb-9da2-e3f611352afe.png)

**Comment by pmac** [comment]
I informed people directly but it seems I forgot to mention it here. The demo for the above is up and running:

https://www-demo5.allizom.org/en-US/firefox-home-preview/3esZ0muUd3oPdflfqZWoKS/
