### ISSUE TITLE
Epic: Validate image capabilities and workflow.

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#9737]
## Description

During our first research and demo sprint, images came up several times as one of the trickiest parts to get right. Lets make sure that we are confident that the image capabilities provided by Contentful will be sufficient.

---

### Success

- [x] Images can be easily uploaded
- [x] Images can be made available in 1:1, 3:2, and 16:9 (either through GUI or separate process)
- [x] Images are optimized for delivery
- [ ] Ability to provide standard and high res options to accommodate all necessary image sizes.
- [ ] Ability to mitigate any issues from unintentionally cropping faces or important content out of photo during process
---

### Tasks (can be converted to an isssue)
- [ ] research and evaluate third party solutions (see relevant links)
- [ ] recreate card content type with [Cloudinary App](https://www.contentful.com/marketplace/app/cloudinary/)

---

### Issues

---

### Relevant Links
- [Contentful apps for image management](https://www.contentful.com/marketplace/category/digital-asset-management/)
- [Cloudinary app](https://www.contentful.com/marketplace/app/cloudinary/)

**Comment by slightlyoffbeat** [comment]
Notes from my meeting with pmac:

Right now, we feel comfortable with the image capabilities. We will likely hold on tests with Cloudinary for now (it can be something we experiment with in the future if we choose to move forward with contentful).

Most of our discussions around images were really rooted in validation and content modeling, and not the image capabilities themselves. For now, we won't be doing any additional tests for this card.

**Comment by Ayushsunny** [comment]
I wanna work on this issue
