### ISSUE TITLE
Epic: Versioning & content model changes

### ISSUE THREAD

**Issue by slightlyoffbeat** [mozilla/bedrock#9741]

**Comment by slightlyoffbeat** [comment]
## Description

Lets make sure that the versioning, backup, restore etc capabilities of Contentful will meet our needs

---

### Success

- [ ] Create backup points for everything
- [ ] Restore from backup point
- [ ] Deploy content model changes in a way that doesn't disrupt editors/authors
- [ ] Ensure that a process exists that allows for content model changes without breaking everything
- [ ] We are able to back everything up to a repository outside of contentful
- [ ] We are able to restore everything from a repository outside of contentful
---

### Tasks (can be converted to an issue)
- [ ] Document a process for backups
- [ ] Document a process for content model changes


---

### Issues
- #9470 
---

### Relevant Links
- [Managing multiple Environments](https://www.contentful.com/developers/docs/concepts/multiple-environments/)
- [Environment Alias](https://www.contentful.com/developers/docs/concepts/environment-aliases/)
- [Custom Roles](https://www.contentful.com/help/creating-a-custom-role/)

**Comment by slightlyoffbeat** [comment]
@pmac Setting tasks and success criteria are a bit outside of my wheelhouse. Would you mind taking a look and adding/removing/editing whatever you think is needed?

**Comment by pmac** [comment]
I think this looks pretty good actually. Does Contentful have some backup/restore system or are you suggesting we'll need to build something using their API to do that?

**Comment by pmac** [comment]
Something like https://www.contentful.com/blog/2019/05/15/configuring-automatic-backups-for-contentful/ ?

**Comment by slightlyoffbeat** [comment]
I'm not certain. There seems to be importing/exporting, backups, and environments for content model updates. Perhaps that may be 3 separate things? I'm just looking to capture everything we'd like to test and accomplish. 

@pmac I know we talked about import/export/backups a while back. Is there anything we should kick the tires on now that we have some more time and resources?

**Comment by pmac** [comment]
Yeah, probably so. I can see what I can do with the export commands in the CLI. If that works well then we should easily (for some definition of easy) be able to automate it.

**Comment by slightlyoffbeat** [comment]
Notes from the meeting pmac and I had today:

@pmac is going to take the lead on this one, and will be focusing on seeing if he can find a method for backing up content models to a place outside of contentful and restoring from that backup as well.

**Comment by pmac** [comment]
I have successfully tested the `contentful space export` and `import` functions using a new environment I made in our space. I manually deleted all of the content, assets, and some content models from the environment. Then restored using the CLI tool and it all came back 👍

**Comment by slightlyoffbeat** [comment]
@pmac  awesome. It looks like that would cover a majority of the success criteria. Is there anything else to test here (keeping in mind that the success criteria are really up to you since you have the most knowledge on this).

Since you are working with spaces/importing/exporting do you think that this could be used to bring content model changes over from a different environment in order to avoid losing content that may have been created while working on a forked environment?

**Comment by pmac** [comment]
> Since you are working with spaces/importing/exporting do you think that this could be used to bring content model changes over from a different environment in order to avoid losing content that may have been created while working on a forked environment?

That is the next bit to test. I'd like to try scripting schema changes so that we could use a process like this:

1. Create a tmp environment for schema changes
2. Create and run a script for updating the schema in the new env
3. Verify that everything worked as expected and make changes (back to step 2 as needed)
4. Once it is verified that the script is working delete the previous tmp env and create a new one
5. Simultaneous with step 4, tell all editorial staff to stop changes for a bit (or lock changes via the UI if possible)
6. Run the script on the new env
7. Update the main alias to point to the new env
8. Open editing back up

**Comment by pmac** [comment]
Found a good video explaining some core data model migration scripting concepts and practices:

https://contentful.wistia.com/medias/889yeie6ti

As well as a repo of example migration scripts:

https://github.com/contentful/ls-content-as-code

They also have a migration client for NodeJS:

https://github.com/contentful/contentful-migration

**Comment by slightlyoffbeat** [comment]
I've captured our question around how to bring content model changes in from a different environment and I'm closing this card.
