### ISSUE TITLE
Redesign/rebuild S2D widget

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/bedrock#9864]
## Description

The Send-to-device (S2D) widget on www.mozilla.org includes SMS capabilities. As we transition to a new email and contacts provider, we'll EOL SMS as a delivery mechanism for these messages. This epic includes short term and long term work to make that true. We can build task cards for individual activities below as needed.

---

#### Issues
- [x] SHORT TERM: Remove SMS from widget -- eliminate language advertising SMS, and remove features providing it.
LONG TERM:
- [ ] Design a new widget -- it should include email, QR code, and app-store badges
- [ ] Automate QR codes, so Bedrock serves them rather than manually creating
- [ ] Implement & launch the new widget
- [ ] Replace all widgets (in every locale) with new widget, since geography is no longer a constraint

**Comment by maxxcrawford** [comment]
Note - I removed myself from this epic issue and assigned myself to the task #9875 as part of the epic.

**Comment by alexgibson** [comment]
Closing old / stale issues. Feel free to re-open if still relevant
