### ISSUE TITLE
Epic: VPN Landing page

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#9949]
## Description

Creating this epic to track all the related issues for launching and updating the VPN landing page. I'll continue to add dependencies here as I create.

---

#### Issues
- [x] ~https://github.com/mozilla/bedrock/issues/9855 (landing page migration)~
- [x] ~https://github.com/mozilla/bedrock/issues/9922 (experiment referrals)~
- [x] ~https://github.com/mozilla/bedrock/issues/9942 (internal link updates)~
- [x] ~https://github.com/mozilla/bedrock/issues/9948 (location based pricing)~
- [x] ~https://github.com/mozilla/bedrock/issues/9938 (GA goal setting)~
- [x] ~https://github.com/mozilla/bedrock/issues/9950 (design updates & localization)~
- [x] ~https://github.com/mozilla/bedrock/issues/9952 (VPN staging instances)~
- [x] ~https://github.com/mozilla/bedrock/issues/9969 (Waitlist language selection)~
- [x] ~https://github.com/mozilla/bedrock/issues/10003 (Update VPN goals for new pricing)~
- [x] ~https://github.com/mozilla/bedrock/issues/10025 (Add VPN logo to privacy notice)~
- [x] ~https://github.com/mozilla/bedrock/issues/10002 (Sign-in fail state messaging)~
- [x] ~https://github.com/mozilla/bedrock/issues/10040 (append query string to subscription links)~
- [x] ~https://github.com/mozilla/bedrock/issues/10039 (pricing anchor)~
- [x] ~https://github.com/mozilla/bedrock/issues/10053 (WNP attribution)~
- [x] ~https://github.com/mozilla/bedrock/issues/10069 (update winning headline)~
- [x] ~https://github.com/mozilla/bedrock/issues/10070 (hide price in non-available countries)~
- [x] ~https://github.com/mozilla/bedrock/issues/10097 (update subscription plan IDs for production)~
- [x] ~https://github.com/mozilla/bedrock/issues/10106 (Add sub-navigation to VPN landing page)~
- [x] ~https://github.com/mozilla/bedrock/issues/10114 (Update press logos)~
- [x] ~https://github.com/mozilla/bedrock/issues/10126 (Switch to new subscription URL format)~
- [x] ~https://github.com/mozilla/bedrock/issues/10128 (Update VPN system requirements)~
- [ ] https://github.com/mozilla/bedrock/issues/10159 (Enable VPN for DE/FR)
- [ ] https://github.com/mozilla/bedrock/issues/10171 (Functional tets for variable pricing)
